### ISSUE TITLE
使用socketio时协议一直都是轮询，没有自动升级

### ISSUE THREAD

**Issue by caiya** [thinkjs/thinkjs#1000]
## DESC
使用socketio时协议一直都是轮询，没有自动升级
### ENV

OS Platform:
win10_64
Node.js Version:
6.11.2
ThinkJS Version:
3.2.4
think-websocket Version:
1.0.6
think-websocket-socket.io Version:
1.0.5

### 问题描述
我配置了socketio之后，浏览器端ws没有升级到websocket，还是一直在轮询，使用的google浏览器，我的配置如下（config.js已开启stickyCluster: true）：

#### 1、adapter配置：
```js
exports.websocket = {
    type: 'socketio',
    common: {
    },
    socketio: {
        handle: socketio,
        path: '/socket.io',             // 默认 '/socket.io'
        adapter: null,                  // 默认无 adapter
        messages: [{
            open: 'api/websocket/alarm/open',     // 建立连接触发
            close: 'api/websocket/alarm/close',    // 关闭连接触发
            message: 'api/websocket/alarm/msg'
        }]
    }
}
```
#### 2、extend配置：
```js
module.exports = [
  view, // make application support view
  model(think.app),
  cache,
  session,
  websocket(think.app),
  fetch   // http请求
];
```

#### 3、action配置：
```js
module.exports = class extends think.Controller {
    // 建立连接action
    openAction(){
        think.logger.info('websocket连接建立了.........', this.websocket.handshake.query.uid)
        userWsConns.bind(this.websocket.handshake.query.uid, this.websocket)
        this.emit('connected', 'success connected!')
        return this.success()
    }

    // 连接关闭action
    closeAction(){
        think.logger.info('websocket连接断开了.........', this.websocket.handshake.query.uid)
        userWsConns.del(this.websocket.handshake.query.uid, this.websocket)
        return this.success()
    }

    msgAction(){
        think.logger.info('来消息了.........', this.wsData)
        return this.success()
    }
}
```

### 浏览器截图

![image](https://user-images.githubusercontent.com/12036572/33750086-7be31078-dc0c-11e7-93b4-328ad00eeef5.png)

### 补充说明

如果我把think-websocket-socket.io Version:
1.0.5
切换到1.0.3的话，浏览器端websocket连接如下：

![image](https://user-images.githubusercontent.com/12036572/33750168-09a84b6c-dc0d-11e7-989a-fc4198031c7b.png)

**Comment by lushijie** [comment]
请升级到 think-websocket-socket.io@1.0.6， 刚修复了一个bug

**Comment by lushijie** [comment]
1.0.6 我在 chrome 下都是 ws 的，有问题麻烦再反馈

**Comment by caiya** [comment]
@lushijie 试了下1.0.6，貌似并没有改好：

![image](https://user-images.githubusercontent.com/12036572/33753334-b141e52c-dc21-11e7-89a0-2dd5d18c4b93.png)

![image](https://user-images.githubusercontent.com/12036572/33753362-cea8741e-dc21-11e7-922f-3cc5bb10f562.png)

**Comment by lushijie** [comment]
顺便发一下你的浏览器端的代码吧，我看看能复现这个问题不

**Comment by caiya** [comment]
前端代码是vue写的，涉及到socket这块代码比较简单，如下：

socket.io-client Version：1.7.4

```js
import io from 'socket.io-client'
io(window.location.host, {
    path: '/socket.io',
    query: {
      uid: 'admin'
    }
  })
```

**Comment by lushijie** [comment]
socket.io-client 你升级到2 试试，socket.io 我们使用的版本 >2.0.1 的

**Comment by caiya** [comment]
@lushijie 不行，试了吧前后台socket.io-client全部换到2.0.4版本，还是不行的，你发发下你的测试的代码吗，包括前后台的

**Comment by caiya** [comment]
@lushijie 但是1.0.3是可以正常切换到ws协议的，有出现101状态码的

**Comment by lushijie** [comment]
你先更新到**1.0.7**，然后把node_modules/think-websocket-socket.io/index.js 
```js
    if(config.adapter || config.allowOrigin || config.path) {
      this.io.listen(server);
    }
```
这段代码注释掉看看可以不？ 我现在还没复现问题

**Comment by caiya** [comment]
@lushijie 注释掉的话和1.0.3就一致了
![image](https://user-images.githubusercontent.com/12036572/33813204-5ad2a5bc-de5d-11e7-850d-cdab4d34e7aa.png)

**Comment by lushijie** [comment]
好的我看一下

**Comment by lushijie** [comment]
更新到 think-websocket-socket.io@1.0.9吧, 修复了 server.path(*) 的问题，感谢反馈

**Comment by caiya** [comment]
@lushijie 阔以了

**Comment by lushijie** [comment]
👌
