### ISSUE TITLE
设置enableDefaultRouter为false，没有被定义的路由访问时报500 error信息ctx.module required in multi module，而并不是404

### ISSUE THREAD

**Issue by WayneLiang** [thinkjs/thinkjs#1001]
没被定义的路由，到达logic时this.ctx.module、 this.ctx.controller、this.ctx.action出现undefined导致出现ctx.module required in multi module   500 error，而并非期望的404 not found

**Comment by lushijie** [comment]
你是多模块下连模块名都没有匹配到导致了一个 assert 报错，think-controller 有个 emptyModule 配置，看看能解决你的问题不

**Comment by WayneLiang** [comment]
现在是所请求的路由不存在理应报404不应该报500，在think-logic就已经assert报错，还没到think-controller，我觉得应该在think-router 最后next()前做404处理。我这边现在的处理是把think-controller和think-logic的assert直接next(),原来的error msg直接console.log出来
![Alt text](http://cdn.otpath.com/404.png)

**Comment by lushijie** [comment]
think-logic@1.1.0
think-controller@1.0.4

请升级这两个包到上述版本

**Comment by WayneLiang** [comment]
ok

**Comment by lushijie** [comment]
@WayneLiang 更新之后如何？

**Comment by WayneLiang** [comment]
更新后可以正常报404 @lushijie
