### ISSUE TITLE
think-view 增加 controller外调用

### ISSUE THREAD

**Issue by callmez** [thinkjs/thinkjs#1002]
目前think-view只做了controller的绑定

可不可以增加到think或ctx对象上

比如我的一个应用场景是:

think-email的html想用think-view来做模板.

**Comment by lushijie** [comment]
think-view 相关的模板都有 render template to string 方法可以返回字符串，然后你把返回的字符串当做think-email 的模板内容不就行了？

**Comment by lushijie** [comment]
其实 think-view 在某些情况都是不存在的，例如只提供接口的系统。
我们并没有打算把 think-view 耦合到其他 extend 中。
如果你真想使用可以自己拓展 think 方法，系统提供了拓展的方法。

**Comment by callmez** [comment]
扩展是没问题... 仅仅是看到think-view有缓存instance.   我仅是出于对实例复用的一个考虑,

既然有view使用.  mail模板只需要借用view的渲染  成 string就可以了 . 功能无伤大局  

仅是一个设计模式上的问题.

**Comment by welefen** [comment]
@callmez 恩，可以添加扩展到 ctx 上。是否愿意改下帮忙发个 pr 呢

**Comment by callmez** [comment]
可以尝试下.. 因为赶项目....不保证哦
