### ISSUE TITLE
thinkjs 怎么通过 ssh 的方式连接数据库，服务器没有开放3306的端口让我们直接连接数据库

### ISSUE THREAD

**Issue by billLiao** [thinkjs/thinkjs#1003]
thinkjs 怎么通过 ssh 的方式连接数据库，服务器没有开放3306的端口让我们直接连接数据库

**Comment by xb594328980** [comment]
看一下是否是在别的端口。

**Comment by welefen** [comment]
@billLiao  可以通过 ssh 代理来弄，具体见：https://stackoverflow.com/questions/24687932/node-js-connecting-through-ssh
