### ISSUE TITLE
安装think-cli时报错(CoffeeScript on NPM has moved to "coffeescript" (no hyphen))

### ISSUE THREAD

**Issue by fenglinzeng** [thinkjs/thinkjs#1005]
## DESC
执行`npm i -g think-cli`时报错`npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)`
### ENV

OS Platform:
macOS10.12.6
Node.js Version:
8.8.1
ThinkJS Version:

### code

```js
npm i -g think-cli
```

### error message

```
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/think-cli
npm ERR! path /usr/local/lib/node_modules/think-cli
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/usr/local/lib/node_modules/think-cli'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by makeco** [comment]
@fenglinzeng 

> npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

提示你 `CoffeeScript` 包名换成了 `coffee script`，重点是：

> npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/think-cli

你没有写权限，加个sudo试试。

**Comment by fenglinzeng** [comment]
@makeco 问题依旧，而且全局装别的包也没问题。应该是我电脑的问题，我再试试，感谢。

**Comment by ruanfumin** [comment]
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/usr/local/bin/vue -> /usr/local/lib/node_modules/vue-cli/bin/vue
/usr/local/bin/vue-init -> /usr/local/lib/node_modules/vue-cli/bin/vue-init
/usr/local/bin/vue-list -> /usr/local/lib/node_modules/vue-cli/bin/vue-list
+ vue-cli@2.9.6
updated 1 package in 4.96s

**Comment by ruanfumin** [comment]
`npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/usr/local/bin/vue -> /usr/local/lib/node_modules/vue-cli/bin/vue
/usr/local/bin/vue-init -> /usr/local/lib/node_modules/vue-cli/bin/vue-init
/usr/local/bin/vue-list -> /usr/local/lib/node_modules/vue-cli/bin/vue-list
+ vue-cli@2.9.6
updated 1 package in 4.96s`

**Comment by ruanfumin** [comment]
> npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/usr/local/bin/vue -> /usr/local/lib/node_modules/vue-cli/bin/vue
/usr/local/bin/vue-init -> /usr/local/lib/node_modules/vue-cli/bin/vue-init
/usr/local/bin/vue-list -> /usr/local/lib/node_modules/vue-cli/bin/vue-list
> + vue-cli@2.9.6
> updated 1 package in 4.96s
