### ISSUE TITLE
并发下think.messenger.map偶发报错，返回结果集不正确

### ISSUE THREAD

**Issue by Srma** [thinkjs/thinkjs#1006]
### ENV

OS Platform:
WIN10
Node.js Version:
V8.1.2
ThinkJS Version:
3.2.4
### code

```js
// controller file
  async testAction() {
       let device_id = 1;
       let channel_list = await think.messenger.map('getStream', device_id);
       return this.success(channel_list);
  }
// work.js
think.messenger.on('getStream', (device_id) => {
    for (var item of fms_helper.stream_channels) {
        if (item.device_info.id == device_id) {
            return item.stream_info.stream_path;
        }
    }
    return null;
});


```

### error message
E:\Projects\xh\flink_v2\source\node_modules\think-cluster\lib\messenger.js:48
            map.get(worker).resolve(message.data);
               ^

TypeError: Cannot read property 'get' of undefined
    at EventEmitter.cluster.on (E:\Projects\xh\flink_v2\source\node_modules\think-cluster\lib\messenger.js:48:16)
    at emitThree (events.js:140:20)
    at EventEmitter.emit (events.js:216:7)
    at Worker.<anonymous> (internal/cluster/master.js:162:13)
    at emitTwo (events.js:130:20)
    at Worker.emit (events.js:213:7)
    at ChildProcess.Worker.process.on (internal/cluster/worker.js:42:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at handleMessage (internal/child_process.js:753:14)
    at Pipe.channel.onread (internal/child_process.js:472:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! thinkjs-application@1.0.0 start: `node development.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the thinkjs-application@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Srma\AppData\Roaming\npm-cache\_logs\2017-12-12T03_23_45_777Z-debug.log
```

```

### debug log

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle thinkjs-application@1.0.0~prestart: thinkjs-application@1.0.0
6 silly lifecycle thinkjs-application@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle thinkjs-application@1.0.0~start: thinkjs-application@1.0.0
8 verbose lifecycle thinkjs-application@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle thinkjs-application@1.0.0~start: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\Projects\xh\flink_v2\source\node_modules\.bin;C:\Programs\Python27\;C:\Programs\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Program Files\TortoiseSVN\bin;D:\Program Files\Git\cmd;D:\Program Files\TortoiseGit\bin;C:\Program Files\Java\jdk1.8.0_112\bin;C:\Program Files\Java\jdk1.8.0_112\jre\bin;C:\Programs\apache-maven-3.3.9\bin;D:\Server\phpStudy\php\php-5.6.27-nts;C:\ProgramData\ComposerSetup\bin;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;D:\Program Files\nodejs\;C:\Programs\gradle-4.0.1\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;D:\Program Files (x86)\QuickTime\QTSystem\;D:\Program Files (x86)\Bitvise SSH Client;D:\Program Files\ffmpeg\bin;C:\Users\Srma\AppData\Local\Microsoft\WindowsApps;C:\Users\Srma\AppData\Roaming\Composer\vendor\bin;C:\Users\Srma\AppData\Roaming\npm;;C:\Users\Srma\AppData\Local\Programs\Fiddler;D:\Program Files\Microsoft VS Code\bin;C:\Users\Srma\AppData\Local\Microsoft\WindowsApps
10 verbose lifecycle thinkjs-application@1.0.0~start: CWD: E:\Projects\xh\flink_v2\source
11 silly lifecycle thinkjs-application@1.0.0~start: Args: [ '/d /s /c', 'node development.js' ]
12 silly lifecycle thinkjs-application@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle thinkjs-application@1.0.0~start: Failed to exec start script
14 verbose stack Error: thinkjs-application@1.0.0 start: `node development.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid thinkjs-application@1.0.0
16 verbose cwd E:\Projects\xh\flink_v2\source
17 verbose Windows_NT 10.0.16299
18 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 verbose node v8.1.2
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error thinkjs-application@1.0.0 start: `node development.js`
23 error Exit status 1
24 error Failed at the thinkjs-application@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by makeco** [comment]
@Srma 感谢反馈，问题已经修复，请升级think-cluster@1.5.3。

**Comment by Srma** [comment]
@makeco 非常感谢及时修复。 还有一个问题，并发下结果返回不一致的问题，开启一个worker，当前有任务没有结束时，又有新任务到达，返回结果不一致，请看我的调试日志：

// controller file
``` 
async testAction() {
    let device_id = this.getParam('device_id');
    let channel_list = await think.messenger.map('getStram', device_id);
    console.log('参数为'+device_id+'执行结果', channel_list);
  }
```

// work.js
```
think.messenger.on('getStram', (device_id) => {
    console.log('params device_id:', device_id);
    for (var item of fms_helper.stream_channels) {
        if (item.device_info.id == device_id) {
            console.log('参数为',device_id,'的返回结果为：', item.stream_info.stream_path);
            return item.stream_info.stream_path;
            break;
        }
    }
    return null;
});
```

// 正常时输出
```
params device_id: 19486
参数为 19486 的返回结果为： /live/MV8xOTQ4Ng==
参数为19486执行结果 [ '/live/MV8xOTQ4Ng==' ]
params device_id: 19487
参数为 19487 的返回结果为： /live/MV8xOTQ4Nw==
参数为19487执行结果 [ '/live/MV8xOTQ4Nw==' ]
```

// 异常输出
```
params device_id: 19487
参数为 19487 的返回结果为： /live/MV8xOTQ4Nw==
params device_id: 19486
参数为 19486 的返回结果为： /live/MV8xOTQ4Ng==
参数为19487执行结果 [ '/live/MV8xOTQ4Nw==' ]
参数为19486执行结果 [ '/live/MV8xOTQ4Nw==' ]
```

**Comment by makeco** [comment]
@Srma 今天我会跟进这个问题

**Comment by makeco** [comment]
@Srma 模拟了一下并发，代码如下：

```js
// worker.js
const channels = [
  {
    device: {
      id: 1
    },
    stream: {
      path: 11
    }
  },
  {
    device: {
      id: 2
    },
    stream: {
      path: 22
    }
  }
];

think.messenger.on('getStream', deviceId => {
  const [channel] = channels.filter(channel => channel.device.id === deviceId);
  return channel.stream.path;
});
```

```js
// conotroller/index.js
async testAction() {
    const max = this.get('max') || 100;
    let count = 0;
    while (count < max) {
      const deviceId = count % 2 + 1;
      think.messenger.map('getStream', deviceId).then(streamList => {
        if (streamList[0] !== deviceId * 10 + deviceId) {
          console.error(`deviceId ${deviceId} -> streamList ${streamList}`);
        }
      });
      count++;
    }
    return this.success();
  }
```
经过调试发现是这样问题：
子进程里通过`messenger.map()`派发了`stream`事件并监听`stream_ret`，然后messenger收集子进程返回的数据触发`stream_ret`事件，处理`stream_ret`事件时发生竞争，导致数据返回异常。

解决方法：
给每个任务加上唯一的`taskId`，由任务计数器和pid组成。

so，请升级think-cluster@1.5.4，感谢反馈~

**Comment by jc5337207** [comment]
@makeco 这里我更新了think-cluster@1.5.4，thinkjs升级到3.2.5后，crontab里的配置需要改动吗？例如：

**Comment by jc5337207** [comment]
@makeco 这里我升级了thinkjs3.2.5，think-cluster@1.5.4，执行以往的crontab定时任务时报错，
`{
        interval: '30s',
        immediate: true,
        handle: 'api/test/doContact',
        type: 'one',
        enable:true
    },`
报错如下：
![wechatimg1245](https://user-images.githubusercontent.com/23159732/33978304-04ac5e92-e0da-11e7-948b-03e6d831cb25.jpeg)
请问是map那里对process.pid的处理有问题吗？对应的crontab配置需要修改么？

**Comment by makeco** [comment]
@jc5337207 不需要，稍等我改一下重新发版。

**Comment by makeco** [comment]
@jc5337207 @Srma 请升级think-cluster@1.5.5，感谢及时反馈。
