### ISSUE TITLE
无法获取全局的websocket对象

### ISSUE THREAD

**Issue by thinkido** [thinkjs/thinkjs#1008]
## DESC
需要实现类似私聊功能，通过socket.id找到好友的socket发送信息
thinkjs 是没有全局的websocket 对象呢，在rest接口的action中无法通过 this.websocket 和 ctx.req.io 获取到socket对象

### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by cuitianze** [comment]
```
socket 对象
Action 里可以通过 this.http.socket 拿到当前的 socket 对象。
```
> https://thinkjs.org/zh-cn/doc/2.2/adapter_websocket.html

thinkjs@2.2不是有socket 对象吗？ @lushijie

**Comment by lushijie** [comment]
action 可以通过 this.websocket 可以拿到当前socket；可以通过 this.ctx.req.io 拿到 io 实例
    


From ShijieLu


原始邮件
发件人:cuitianzenotifications@github.com
收件人:thinkjs/thinkjsthinkjs@noreply.github.com
抄送:Shijie Lulushijie1218@126.com; Mentionmention@noreply.github.com
发送时间:2017年12月18日(周一) 00:22
主题:Re: [thinkjs/thinkjs] 无法获取全局的websocket对象 (#1008)


socket 对象 Action 里可以通过 this.http.socket 拿到当前的 socket 对象。
https://thinkjs.org/zh-cn/doc/2.2/adapter_websocket.html
thinkjs@2.2不是有socket 对象吗？ @lushijie

**Comment by lushijie** [comment]
ping @thinkido

**Comment by lushijie** [comment]
无反馈，关闭issue

**Comment by yi-ge** [comment]
@lushijie 在rest的action无法通过 this.websocket 拿到当前socket，也无法通过 this.ctx.req.io 拿到 io 实例。

**Comment by lushijie** [comment]
@yi-ge 上代码吧，包括路由配置和rest controller

**Comment by yi-ge** [comment]
@lushijie 
```
module.exports = [
  [/\/api\/(\w+)\/(\w+)(?:\/(\d+))?/, 'api/:1/:2?id=:3', 'rest'],
  [/\/api\/(\w+)(?:\/(\d+))?/, 'api/:1?id=:2', 'rest']
];

```

```
  async getAction () {
    try {
      // action 可以通过 this.websocket 可以拿到当前socket；可以通过 this.ctx.req.io 拿到 io 实例
      console.log(this.websocket)
      console.log(this.ctx.req.io)
    } catch (err) {
      console.log(err)
    }

    const data = 'abc'
    return this.success(data)
  }
```

**Comment by yi-ge** [comment]
@lushijie 我通过这样的方法临时解决了问题
```
think.socket = null
export default class extends think.Controller {
  openAction () {
    this.emit('opend', `This client ${this.websocket.id} opened successfully!`)
    this.broadcast('joined', 'There is a new client joined successfully!')
    if (!think.sockets) {
      think.socket = this.ctx.req.io
    }
  }
```
我无法理解的是，websocket的实例既不在请求上下文中，为什么绑定到请求上下文中呢？

**Comment by lushijie** [comment]
针对 rest 确实要稍作 base.js 调整才能适应websocket。所以建议websocket 不用rest，websocket使用一个普通的controller，涉及的接口使用rest。
因为websocket 事件映射到了action，所以绑定到请求上下文

**Comment by yi-ge** [comment]
@lushijie 非常感谢您的回复。希望thinkjs原来越好！
