### ISSUE TITLE
Typescript [ts] 类型Think上不存在config

### ISSUE THREAD

**Issue by charmtiger** [thinkjs/thinkjs#1009]
### ENV

OS Platform:
mac
Node.js Version:
8.9.0
ThinkJS Version:
3.2.5
### code

```js
import { think } from 'thinkjs'
import Base from './base.js'
export default class extends Base {
  async testAction() {
    think.logger.debug(think.config('model'))
    return this.ctx.body = 'success'
  }
}
```
![default](https://user-images.githubusercontent.com/8412626/33928823-31594972-e022-11e7-8c93-65905281bd9d.png)

### more description

// your detail description

**Comment by wurining** [comment]
```
import { think } from 'thinkjs'
import Base from './base.js'
export default class extends Base {
  async testAction() {
    think.logger.debug(this.config('model'))
    return this.ctx.body = 'success'
  }
}
```

**Comment by charmtiger** [comment]
@wurining 在service  中不能通过this.config 获取配置，只有通过 think.config() 才可以。

**Comment by wurining** [comment]
@charmtiger 应该是types文件没加这个，我测试了一下，是可以获取到的。

**Comment by charmtiger** [comment]
@wurining  获取是可以的，但是npm run compile 是会报错的

**Comment by wurining** [comment]
@charmtiger 你试试提一个pr给thinkjs加上吧。或者你在controller中获取config用参数的形式传给service临时解决一下。

**Comment by charmtiger** [comment]
目前就是通过controller 传参解决的 😃

**Comment by wurining** [comment]
@charmtiger 你真棒

**Comment by SijieCai** [comment]
我加一下，关注一下后面版本发布

**Comment by SijieCai** [comment]
@charmtiger @wurining  problem has been fixed, please update to ThinkJS version 3.2.6, cheers.

**Comment by SijieCai** [comment]
set [commit](https://github.com/thinkjs/thinkjs/commit/1e55da25b6b5ea48b2a1d926492761516907f92e)
