### ISSUE TITLE
socket.io-redis如何引入?是否与think-websocket-socket.io冲突

### ISSUE THREAD

**Issue by maxcheers86** [thinkjs/thinkjs#1010]
## DESC
在adapter.js中require('socket.io-redis')，产生错误Maximum call stack size exceeded
是不是与think-websocket-socket.io冲突了
### ENV

OS Platform:
windows
Node.js Version:
6.11
ThinkJS Version:
3
### code

adapter.js

const socketio = require('think-websocket-socket.io');
const redis = require('socket.io-redis')

exports.websocket = {
  type: 'socketio',
  common: {
    // common config
  },
  socketio: {
    handle: socketio,
    allowOrigin: '',  // 默认所有的域名都允许访问
    path: '/socket.io',             // 默认 '/socket.io'
    adapter:redis,
    messages: [{
      open: '/websocket/open',       // 建立连接时处理对应到 websocket Controller 下的 open Action
      close: '/websocket/close',     // 关闭连接时处理的 Action
     ...
    }]
  }
}

### error message
Maximum call stack size exceeded

### more description
能否给一个加入socket.io-redis完整的配置

**Comment by lushijie** [comment]
文档错误，已修正
```js
const redis = require('socket.io-redis');
exports.websocket = {
  // ...
  socketio: {
    // ...
    adapter: redis({ host: 'localhost', port: 6379 }),
  }
}
```

关于如何使用 socket.io 的adapter可以查看其官网
