### ISSUE TITLE
Logic层校验返回的错误信息为Object

### ISSUE THREAD

**Issue by wurining** [thinkjs/thinkjs#1011]
https://github.com/thinkjs/thinkjs/blob/dc2e33ae0ecdcf8109c21f2de70fd26810e0f2c2/index.d.ts#L306

errmsg的类型可以改为object | string。
在Logic层进行校验时返回错误信息有可能为object
```
  indexAction(){
    let rules = {
      email: {
        required: true
      },
      email2: {
        required: true
      },
    }

    // 自定义 app_id 的错误信息
    let msgs = {
      app_id: '{name} 不能为空(自定义错误)',
    }

    if(!this.validate(rules, msgs)) {
      return this.fail(this.validateErrors);
    }
  }
```

**Comment by lushijie** [comment]
```js
{
  email: "email need an email under your options",
  email2: "email2不能为空"
}
```
this.validateErrors返回的就是一个object呀？有什么问题？？？

**Comment by wurining** [comment]
@lushijie return this.fail(88000,this.validateErrors);这句this.fail会报类型不符的错误，可以运行但是会报错。

**Comment by lushijie** [comment]
这个问题是 index.d.ts 写 type 的时候指定错了，将 node_modules/thinkjs/index.d.ts

```fail(errno: any, errmsg?: string, data?: string): any;```
改为 
```fail(errno: any, errmsg?: object | string, data?: string): any;```

ThinkJS 下个版本发布的时候会修复这个问题。
