### ISSUE TITLE
关于多进程的socket问题

### ISSUE THREAD

**Issue by zsj975516** [thinkjs/thinkjs#1012]
## 关于多进程的socket问题

原本的想法是在登陆成功后，将socket对象存到global中
现在需要开启多进程，而多进程中，global对象也会有多个，现在将socket对象存入global中，显然是不太现实，是否有更好的解决方案？

### 目前拥有单是未实现的思路
就是将socketid存到redis中，然后根据需要点对点发送信息的时候，根据socketid取到需要的socket对象，然后进行发送

```
  let socketObj = io.sockets.connected['xxx']; // xxx socket.id 在redis存储
  if (socketObj) {
    socketObj.emit(eventName, msg);
  }
```
目前未解决的问题，便是这个io问题，因为不知道怎么取得这个io

**Comment by zsj975516** [comment]
已经解决

**Comment by zuoyanart** [comment]
请问您的解决思路是什么？
