### ISSUE TITLE
利用 fs.writeFile写入txt文件或者创建txt文件

### ISSUE THREAD

**Issue by shangguanyang** [thinkjs/thinkjs#1013]
在写入文件的时候，直接打开txt文件看不到写入的内容，在console.log()可以打出所写入的内容；
或者创建文件，提示创建成功，但是在项目中看不到创建的文件，写入的内容也可以用console.log()打出来

**Comment by lushijie** [comment]
上代码吧

**Comment by shangguanyang** [comment]
![image](https://user-images.githubusercontent.com/29453053/34033265-78398580-e1b4-11e7-8b02-f0ed82e3faf4.png)

**Comment by lushijie** [comment]
请以代码格式粘贴代码，另writeFile这里不建议使用./相对目录， thinkjs 下面有 think.ROOT_PATH 建议基于这个路径写

**Comment by shangguanyang** [comment]
let writedata = '追加的数据？';
    fs.writeFile('./house_order_delegation.txt',writedata,{flag:'w',encoding:'utf-8',mode:'0666'},function(err){
      if(err){
        console.log("文件写入失败")
      }else{
        console.log("文件追加成功");
      }
    });

**Comment by shangguanyang** [comment]
是我存放的路径错了，谢谢了

**Comment by lushijie** [comment]
ok
