### ISSUE TITLE
logic中的this.fail返回的错误信息结构建议支持自定义

### ISSUE THREAD

**Issue by sailengsi** [thinkjs/thinkjs#1015]
### dev

OS Platform:mac

Node.js Version:8.xxx

ThinkJS Version:3.xx

### code
例如这个返回错误信息
```js
return this.fail('错误信息啊**', '错误数据啊**', this.validateErrors);
```

### error message

```
{
    "errno":1000,
    "errmsg":"错误信息啊**",
    "data":"错误数据啊**"
}
```

### more description
建议可以自定义上面的属性以及值。
正常情况，每家公司都会有自己的写接口的风格，比如我的风格如下：
### 成功
```
{
    status:200,
    data: {
    }
}
```
### 错误
```
{
    status:1,//或者 其他错误码
    msg: '错误信息'
}
```
所以，每一个系统，接口的风格都不一样，且每一个系统内的风格都应该保持一致，如果按照this.fail的固定结构来说，将会让前端多写一点代码，个人感觉不太优雅，希望这方面可以提供一个配置让开发者自定义，或者提供一个接口，让开发者重写fail。

**Comment by lushijie** [comment]
```js
// src/config/config.js
{
   errnoField: 'errno', 
   errmsgField: 'errmsg'
   // ...
}
```
有这两个配置，不知能否满足需求？

**Comment by sailengsi** [comment]
@lushijie 您好，感谢，基本能满足需求，不知状态码是否可以自定义呢？

**Comment by sailengsi** [comment]
@lushijie 文档中可以配置默认，但是没有找到自定义的地方，这个并不是很强制，如果不支持，也没关系。

**Comment by lushijie** [comment]
第一个参数是number的话就是errno

发自我的 iPhone

**Comment by sailengsi** [comment]
@lushijie 我曹，我想知道你是怎么知道的？文档中有地方说明么？是我看的不仔细？我再看看，草了。

**Comment by lushijie** [comment]
好好看代码呦(●◡●)

**Comment by sailengsi** [comment]
@lushijie 看源码啊？

**Comment by lushijie** [comment]
https://thinkjs.org/zh-cn/doc/3.0/controller.html#toc-ff1 
其实文档中有写的啦，好好看看文档呦
