### ISSUE TITLE
建议：计划任务能单独启动一个进程来处理

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#1016]
目前有这样一种情景，我做的一个商城系统，每隔一段时间需要执行结算大量数据的计划任务，而且一些是属于CPU密集型任务（比如生成、解析xls表格），遇到极端情况，直接把某个worker“忙死了”，造成部分用户请求响应很慢。
能不能单独开个进程来处理计划任务？这样减少对响应用户请求的影响。

**Comment by lizheming** [comment]
可以直接用系统的 crontab 代替，内部的 crontab 适合一些需要共用 ThinkJS 实例的情况。

**Comment by welefen** [comment]
耗 CPU 的任务建议用命令行执行，https://thinkjs.org/zh-cn/doc/3.0/crontab.html#toc-173
这是一个独立的进程执行的，不会影响用户的请求。

**Comment by KuoKongQingYun** [comment]
主要是和运行时数据有耦合，如果单独用命令行执行的话，可以用think.messenger发送数据么？

**Comment by welefen** [comment]
@KuoKongQingYun 单独的是完全隔离的，可以把数据写到一个缓存文件中，然后计划任务的进程里读取然后执行。

**Comment by KuoKongQingYun** [comment]
好的 ，暂时只能这样了
