### ISSUE TITLE
service层调用mongoose插入数据时，mongoose无法获取到传入参数，仅插入只有_id的数据

### ISSUE THREAD

**Issue by WayneLiang** [thinkjs/thinkjs#1017]
![5f1b69e6-eee8-459f-86f9-59427174763f](https://user-images.githubusercontent.com/13344145/34139224-8313809e-e4ae-11e7-95ce-ad776ebea429.png)
![0e23da8f-9208-4d83-b403-2f67c9637e70](https://user-images.githubusercontent.com/13344145/34139240-9400eb58-e4ae-11e7-805b-fc38ea48bf1a.png)

如果controller层有调用mongoose，那service层就正常
如果controller层没有调用，service层mongoose就获取不了传进去的数据

**Comment by welefen** [comment]
你是单模块项目还是多模块项目？

**Comment by WayneLiang** [comment]
@welefen 多模块

**Comment by WayneLiang** [comment]
我现在这个是service,model，controller是同个模块下的

**Comment by WayneLiang** [comment]
找到解决方法了，多谢提醒是多模块，看了下think-mongoose源码多模块应该这么调用才对think.mongoose('SmsCode',undefined,'api').create

**Comment by welefen** [comment]
@WayneLiang 恩，多模块要指定模块名，另外除非必须，不建议项目用多模块，会带来很多开发上的麻烦。
