### ISSUE TITLE
一个服务能同时连接 mysql 和 mongodb 吗?

### ISSUE THREAD

**Issue by fansenze** [thinkjs/thinkjs#1021]
## DESC
一个服务里能同时连接 mysql 和 mongodb 吗?
### ENV

OS Platform:  OSX

Node.js Version: 8.9.1

ThinkJS Version: 3.0

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lushijie** [comment]
可以




| |
卢士杰
|
|
邮箱：lushijie1218@126.com
|

签名由 网易邮箱大师 定制

在2017年12月22日 17:54，senze.fan 写道：
DESC

一个服务里能同时连接 mysql 和 mongodb 吗?

ENV

OS Platform: OSX

Node.js Version: 8.9.1

ThinkJS Version: 3.0

code
// your code here
error message
// your error message here

more description

// your detail description

**Comment by fansenze** [comment]
有demo吗，我用官网文档里的两个demo代码，mongodb对应export暴露的名称改了一下，发现mongodb连接报错

**Comment by lushijie** [comment]
例如 model 的adaper指定type为mysql，如下可以读取mongoose的配置，连接mongodb:

```js
  let Employee = this.mongoose('mongoose/employee', 'mongoose');
```

**Comment by fansenze** [comment]
this上没有mongoose的属性

**Comment by lushijie** [comment]
1. adapter配置
```js
// src/config/adapter.js
module.exports = {
  type: 'mysql',
  common: {
    logSql: isDev,
    logger: msg => console.log(msg)
  },
  mysql: {
    handle: mysql,
    // ...
  },
  mongoose: {
    // ...
  }
};
```
2. extend配置
```js
const model = require('think-model');
const mongoose = require('think-mongoose');
module.exports = [
  // ...
  model(think.app),
  mongoose(think.app)
];
```
3. controller
现在controller可以使用用 think.model() 和 this.mongoose('', 'mongoose'); // 非默认adpater要指定类型
各自的model分别继承think.Model 和 think.Mongoose；

think-mongo 同理 

另：[文档中多数据库的使用说明](https://thinkjs.org/zh-cn/doc/3.0/relation_model.html)

**Comment by fansenze** [comment]
谢谢
你提供的demo和我之前写的是一样的
我昨天才发现我的问题其实是没有查对应表。。。就 think 里提供的 `model.table` 方法
