### ISSUE TITLE
thinkjs 3如何实现类似thinkjs2的配置错误号和错误信息？

### ISSUE THREAD

**Issue by haodalong** [thinkjs/thinkjs#1022]
## DESC
请问thinkjs 3如何实现类似thinkjs2的配置错误号和错误信息？
### ENV

OS Platform: win7_64

Node.js Version: 8.9.3

ThinkJS Version: 3+

### more description
在thinkjs 2中可以通过config文件夹下的locale/en.js配置错误号和错误信息，从而直接this.fail()调用配置的变量名就行了，具体如下图所示
https://thinkjs.org/zh-cn/doc/2.2/controller.html#toc-6a8
![image](https://user-images.githubusercontent.com/13931187/34317910-c1c095b8-e7f4-11e7-85eb-d8e223dc5cc4.png)

而在thinkjs 3中如何实现？

**Comment by lushijie** [comment]
```js
// src/config/validator.js
module.exports = {
  messages: {
    ERR_TEST: [1001, '这里是错误信息']
  }
}

// 调用
this.fail('ERR_TEST'); // 'ERR_TEST'起名字需要满足/^[A-Z_]+$/ 
```

**Comment by lushijie** [comment]
长时间无应答，关闭issue

**Comment by haodalong** [comment]
这样配置是可以的，谢谢
