### ISSUE TITLE
有没有基于NodeJs实现的工作流引擎，基于bpmn2.0规范，并且支持国际化的更好

### ISSUE THREAD

**Issue by souljessi** [thinkjs/thinkjs#1023]
## DESC
之前看过一些诸如状态机这样的模块，感觉复用性不强，前端的流程设计器，国际化做的不友好
### ENV

OS Platform:

Node.js Version:8.9.0

ThinkJS Version:3.0

**Comment by SijieCai** [comment]
这种问题不是 issue 里面。关闭了。

关于工作流引擎这个话题比较大。还是去翻翻技术论坛吧，也可以参考一些java和.net的方案。
