### ISSUE TITLE
thinkjs 3的500页面无法出现堆栈信息

### ISSUE THREAD

**Issue by macurial** [thinkjs/thinkjs#1025]
## DESC
如题
### ENV

OS Platform: windows 7

Node.js Version: v8.9.3

ThinkJS Version:v3.2.5

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description 
如图所示
![20171225150044268](https://user-images.githubusercontent.com/10878381/34334847-1430eeba-e985-11e7-9d7b-357ccbe01a44.png)

![20171225150050814](https://user-images.githubusercontent.com/10878381/34334848-1655da8e-e985-11e7-9614-7535d9715048.png)
我在模拟一个错误信息的时候。500页面并没有出现堆栈信息。经检查发现是页面中js代码中多了&quot;导致。已提交pr  [think-trace](https://github.com/thinkjs/think-trace/pull/5)

**Comment by welefen** [comment]
think-trace 已发新版
