### ISSUE TITLE
typescript: model.join({ table }) tslint 提示错误

### ISSUE THREAD

**Issue by charmtiger** [thinkjs/thinkjs#1029]
### ENV
![image](https://user-images.githubusercontent.com/8412626/34371957-2d0f6d0c-eb0c-11e7-9e0d-720241573e5d.png)

OS Platform:
mac
Node.js Version:
8.9.0
ThinkJS Version:
3.2.6
### code

```js
let techerModel = this.model('techer') as techerModelClass
    return techerModel.alias('t').join({
      table: 'user',
      as: 'u',
      on: ['user_id', 'id']
    }).page(currentPage, pageSize).countSelect()
```

**Comment by SijieCai** [comment]
ts 定义有点问题，join 支持三种类型，我看看改一下

**Comment by SijieCai** [comment]
已修复 think-model@1.1.7    [commit](https://github.com/thinkjs/think-model/commit/a45ba4948737ac6aaabc8ee8977055bf376ee616)，@charmtiger 请确认后关闭issue

**Comment by charmtiger** [comment]
已确认
