### ISSUE TITLE
d.ts可能未在think.Model加入think.model.MANY_TO_MANY等常量

### ISSUE THREAD

**Issue by wurining** [thinkjs/thinkjs#1030]
<img width="598" alt="2017-12-27 4 05 23" src="https://user-images.githubusercontent.com/26198634/34375103-c7d50d3e-eb1f-11e7-9336-4249ffbad06b.png">

**Comment by SijieCai** [comment]
是的，这个有些实现难度，Model 是 interface，没有特别好的方法给 interface 添加 static 变量，如果有好的方案欢迎提供。

**Comment by SijieCai** [comment]
Translate this issue:
think-model, enum like think.model.MANY_TO_MANY is not added into the d.ts
Yes, this is somewhat difficult to achieve, think.model is an interface, there is no particularly good way to add static variable interface, if you have a good solutions PR is welcome.
Of cause, if we implement this again we would export the enum in some other way, such as import  {ModelRelation} from 'think-model'....

workaround:   To create the ts enum in your project and use it, it is just four lines of code.

**Comment by wurining** [comment]
@SijieCai 
是否考虑使用枚举呢？
[https://www.tslang.cn/docs/handbook/enums.html](https://www.tslang.cn/docs/handbook/enums.html)

**Comment by lizheming** [comment]
@SijieCai Why don't use `class` instead `interface`?

**Comment by SijieCai** [comment]
不能用 class，应为实现是未定义的。后面应该修改成，这些 enum 常量需要显示 import 进来

**Comment by SijieCai** [comment]
https://github.com/thinkjs/think-mongoose/pull/4
