### ISSUE TITLE
使用websocket时无法保存session的问题

### ISSUE THREAD

**Issue by yichinzhu** [thinkjs/thinkjs#1033]
## DESC
thinkjs的session是在请求结束后更新的，但是在websocket的情景下并没有请求结束这个概念，导致session无法更新。
### ENV

OS Platform:
Linux

Node.js Version:

ThinkJS Version:
2.2.20

### code

```js
'use strict';
import Base from './base.js'

var foobar = 1;

export default class extends Base{
    async setAction(self) {
        let username = self.http.data;
        await this.session("username", username);
    }

    async getAction() {
        let username = await this.session("username");
        this.emit("user", username);
    }
}
```

### more description

运行结果如图
![20171229180103912](https://user-images.githubusercontent.com/7543516/34434634-518b1d4a-ecc2-11e7-9a9a-aa5238f2fa31.jpg)

**Comment by lushijie** [comment]
可以在 openAction 的时候把 session 绑定到那个 socket 上，让 session 跟着 socket

**Comment by lushijie** [comment]
无响应关闭issue

**Comment by chenyuncai** [comment]
连接socket时不要写127.0.0.1的host，需要写localhost,线上时候就是域名。浏览器出于安全角度，对ip地址的socket连接请求不发送cookie
