### ISSUE TITLE
开启事务后，有时数据库会阻塞

### ISSUE THREAD

**Issue by hankexu** [thinkjs/thinkjs#1038]
## DESC
在很多地方启用了事务，有时会整个数据库都会阻塞，只能重启服务器

有可能是我在某些地方使用`this.db()`没有指定正确的连接，这种情况应该怎么定位错误呢，访问量比较大，看日志找不到，有没有自动重启的方法，或者有没有其他引起这种情况的可能
### ENV

OS Platform:Ubuntu 16.04.2 LTS

Node.js Version:8.9.3

ThinkJS Version:3.2.4

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by KuoKongQingYun** [comment]
要么是db()没设置好，要么是有死锁，看看数据库的锁的状态，大致推测是什么地方导致

**Comment by t04041143** [comment]
我也遇到这个问题了，启动一段时间后，所有访问数据的接口都超时，无数据操作的接口正常。docker-log也没有错误，数据库也没有死锁日志，何解？

**Comment by luckyscript** [comment]
1.2.4还是有这个问题。
