### ISSUE TITLE
think-sequelize记录Sequelize变量

### ISSUE THREAD

**Issue by callmez** [thinkjs/thinkjs#1040]
目前并没看到公开获取Sequelize实例的方法或变量

只看到 think-sequelize 通过 Socket获取 sequelizeConn, 但是并没有放出来

因为有些方法需要通过Sequelize是来调用
```
const conn = new Sequleize(...)
conn.query(sql...)
```

可以不可以提供变量来获取Sequelize实例
比如
```js
const conn = think.Sequel.connection // 当前Sequelize实例

const conn = think.sequle('user').connection // 获取model的关联Sequlize实例
```

**Comment by lushijie** [comment]
think-sequelize@1.3.0 对model 增加了this.getConnection([modelName=this.modelName])的方法，
获取当前conn可以 this.getConnection() 获取其他可以 this.getConnection(modelName)

**Comment by callmez** [comment]
@lushijie this.conn需要预定义下吧?

我这里报错了 `Cannot set property 'user' of undefined`

**Comment by callmez** [comment]
请及时修复下....

**Comment by lushijie** [comment]
think-sequelize@1.3.1 已修复

**Comment by callmez** [comment]
可以用  谢谢!
