### ISSUE TITLE
think-session-redis 连接池没有释放？

### ISSUE THREAD

**Issue by lizhiyang1** [thinkjs/thinkjs#1041]
## DESC
用的 think-session-redis , 当访问数多的时候，redis连接数会持续增长，没有释放，导致连接数超限。

### ENV

OS Platform: centOs

Node.js Version: 6.9.1

ThinkJS Version: 3.1.2

### code

```js
const redisSession = require('think-session-redis');
const redisConfig = {
  port: 6379,
  host: xxx,
  password: xxx
};
/**
 * session adapter config
 * @type {Object}
 */
exports.session = {
  type: 'redis',
  common: {
    cookie: {
      name: 'auth'
    },
    ...redisConfig
  },
  redis: {
    handle: redisSession,
    maxAge: 15 * 60 * 1000, //15min
    autoUpdate: true
  }
};
```

### error message

```
# REDIS INFO Clients
connected_clients:1281 // 一直增加
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0
```

### more description

// your detail description

**Comment by lushijie** [comment]
redis 有个 tcp-keepalive 参数， 你看看你有配置这个参数么？

**Comment by lizhiyang1** [comment]
# TCP keepalive.
#
# If non-zero, use SO_KEEPALIVE to send TCP ACKs to clients in absence
# of communication. This is useful for two reasons:
#
# 1) Detect dead peers.
# 2) Take the connection alive from the point of view of network
#    equipment in the middle.
#
# On Linux, the specified value (in seconds) is the period used to send ACKs.
# Note that to close the connection the double of the time is needed.
# On other kernels the period depends on the kernel configuration.
#
# A reasonable value for this option is 300 seconds, which is the new
# Redis default starting with Redis 3.2.1.

tcp-keepalive 0

**Comment by lushijie** [comment]
请更新 think-redis@1.1.0

**Comment by lizhiyang1** [comment]
已升级，还是不行。是否需要我提供测试数据？

**Comment by lushijie** [comment]
恩，你提供一下代码吧。升级之后我用ab并发测试没有问题。

**Comment by lushijie** [comment]
```js
  /**
   * getConnection by config
   * @param  {Object} config [description]
   * @return {Object}        [description]
   */
  [_getConnection](config) {
    delete config.cookie;
    const md5 = helper.md5(JSON.stringify(config));
    if (!cacheConn[md5] || !cacheConn[md5].connector.connecting) {
      cacheConn[md5] = new IOredis(config);
    }
    return cacheConn[md5];
  }
```
think-redis index.js 有一段这样的代码，你可以打一下 log 看看这个connection 是否能复用？

**Comment by lizhiyang1** [comment]
可以复用，😊测试用例发你邮箱了~

**Comment by lushijie** [comment]
我远程连接了你的redis，client list 发现 10.122.234.68 你的这个机器创建了太多了连接，我本地连接你的redis 是能够正常复用redis 连接的， 你更新了think-redis 之后有重新启动么？我邮件回你了，你加我微信吧

**Comment by lizhiyang1** [comment]
更新了think-redis 之后重启了，现在还是很多连接，难道跟 think-cache-redis 也有关系？微信：18612189178

**Comment by lushijie** [comment]
经过排查是think-cache-redis package.json 中使用了 ~, 导致 think-redis 未升级到最新版，已修复。 think-cache-redis@1.2.0

**Comment by chenzeZzz** [comment]
"think-cache-redis": "^1.2.0",
 "think-redis": "^1.1.1",

连接没有释放

**Comment by lushijie** [comment]
@chenzeZzz  https://github.com/thinkjs/think-redis/blob/master/index.js#L35 调试一下，看看这里复用出啥问题了

**Comment by chenzeZzz** [comment]
@lushijie think-session-redis@1.0.4 里面引用了 "think-redis": "^1.0.5" 会不会有问题

**Comment by chenzeZzz** [comment]
@lushijie think-session-redis 引用 think-redis 的版本更新就ok了，你那边确认一下

**Comment by lushijie** [comment]
think-session-redis 依赖 ^think-redis 没有问题。
可以强制升级一下 think-session-redis，而不是直接升级 think-redis。
