### ISSUE TITLE
ts 下自定义model提示方式

### ISSUE THREAD

**Issue by chigco** [thinkjs/thinkjs#1043]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description 
typescript生成的项目，创建自定义的model，并实现方法。
正确的步骤该怎么操作，才能在controller中，this.model("xxx").自动提示出自定义的方法？

**Comment by wurining** [comment]
https://github.com/thinkjs/thinkjs/issues/976
