### ISSUE TITLE
关于业务逻辑封装在那一层？

### ISSUE THREAD

**Issue by zuoyanart** [thinkjs/thinkjs#1052]
## DESC
看了3.x的文档，没有弄清楚业务逻辑封装到那个地方。 logic是做数据校验的，model是处理数据逻辑的，service到是可以通过扩展调用model来做业务逻辑封装层，但是看文档貌似service层的设计初衷也是不是这个。 业务逻辑总不能写到controller里吧？没法复用了， 请帮忙解惑
### ENV

OS Platform:

Node.js Version:

ThinkJS Version: 3.x

**Comment by lizheming** [comment]
就是写到 controller 里额，所以你认为 controller 是用来干什么的呢？

**Comment by zuoyanart** [comment]
写不了复杂应用啊，而且MVC，C层就不是写复杂业务逻辑的地方  @lizheming

**Comment by lizheming** [comment]
复杂业务逻辑是可以拆分出来的，其实在 controller 里面的逻辑并没有想象的那么重。如果 MVC 三个你都不想写复杂业务逻辑，你觉得复杂业务逻辑写哪里合适呢？

**Comment by zuoyanart** [comment]
通常情况下会添加logic或service层（当然这个和thinkjs的定义不一样，thinkjs的logic准确说是validate层）， 在这个层里封装方法，做逻辑复用和方法拆分。我很奇怪为什么thinkjs的结构没有做这个考虑，我刚翻了tp5和eggjs的文档，也是有考虑的。
建个issues讨论一下想法。 @lizheming

**Comment by lizheming** [comment]
logic 层不仅仅是 validate，基本上用户请求参数处理的逻辑都可以放到 logic 中处理，除了校验之外还能格式化复写参数，controller 层无需做校验参数的事情。另外除了数据校验和处理，甚至于权限校验等和业务逻辑无关的操作也可以前置到 logic 中，例如 https://github.com/thinkjs/pharos 项目中，就将大量的权限验证放在了 logic 中，controller 只需要去处理真正的业务逻辑就好。除了用户数据处理，还有入库数据处理，这部分可以抽离到 Model 中做，这块大家都明白就不多说了。而 service 就是为了脱离 controller 将（业务）逻辑代码封装方便多处调用的，这个也正如你内容里说的，比较契合你的想法。

**Comment by zuoyanart** [comment]
service里写逻辑封装？看文档是可以实现。但是为啥看文档总感觉thinkjs没有考虑这块呢

**Comment by lizheming** [comment]
logic, controller, service, model 等的划分就是为了给大家解耦业务代码的，具体怎么用全看大家怎么写:smile:，没有说明可能是文档考虑不周，欢迎你给文档补充你的最佳实践。

**Comment by zuoyanart** [comment]
ok! @lizheming

**Comment by muunnw** [comment]
能否把validator抽离出来，可以在任意位置用呢？比如在多模块下controller之间调用，也需要进行数据校验，这时候就不会经过logic层了。

**Comment by lizheming** [comment]
A 调用 B 的 controller 的话，对应的在  A 的 logic 里调用 B 的 logic 做校验就好了。
