### ISSUE TITLE
think-mongo里update忘加where条件会把整个表都刷成最后一条

### ISSUE THREAD

**Issue by aov2005** [thinkjs/thinkjs#1053]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

不知道这是个 bug 还是 feature....

**Comment by lushijie** [comment]
https://github.com/thinkjs/think-mongo/blob/master/src/model.js#L353-L369
mongodb 的feature

**Comment by aov2005** [comment]
= =好吧

还有个问题，mongo的order解析解析不了DESC和ASC，看源码只有判断1和-1的，切数据库的时候挺蛋疼的

**Comment by lushijie** [comment]
think-mongo@1.0.7, 支持了 `await modelInst.where({name: 'thinkjs'}).order({id: 'DESC'}).select(); ` 写法
