### ISSUE TITLE
init()模板渲染问题

### ISSUE THREAD

**Issue by wangsenyan** [thinkjs/thinkjs#1055]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
 async init(http){
	var self = this;
        super.init(http);
        self.assign({
            loginStatus:0,
            globalFid:0,
            userInfo:userInfo
        })
        let userInfo = await self.session('userInfo');
 }
```

### error message

```

```

### more description

当 let userInfo = await self.session(‘userInfo’); 在self.assign()前传不到模板数据，在后面就可以，问大佬怎回事呢？用的是2.2

**Comment by welefen** [comment]
要先通过 session 获取到数据才能 assign 模板里的

**Comment by lizheming** [comment]
`init()` 方法是不支持使用 `async` 来异步的，你这么写是无法严格保证最终的 `display` 和 `session` 两者的异步关系的。如果有这个需求还请使用 `__before()` 方法，它是支持 async 异步的。

```js
async __before() {
        let userInfo = await this.session('userInfo');
        this.assign({
            loginStatus:0,
            globalFid:0,
            userInfo:userInfo
        })
}
```

**Comment by wangsenyan** [comment]
@welefen @lizheming 十分感谢
