### ISSUE TITLE
[think-model]使用Model-Relation的HAS_MANY进行联查的小问题。

### ISSUE THREAD

**Issue by wurining** [thinkjs/thinkjs#1057]
## DESC
使用Model-Relation的HAS_MANY进行联查时，必须在关系中的查询字段包含fKey，否则无法显示联查结果。例如：
```
    get relation () {
        return {
            user: {
                type    : ModelRelation.HAS_MANY,
                key     : 'id',
                fKey    : 'role_id',
                field   : 'id,role_id,type,user_status,time_login,ip_login,login_name,login_nickname',
                relation: false,
            },
        }
    }
```

* 上段代码中，`field`字段必须包含`fKey`，否则查不出结果。
* 初步断定是联查过程中，是先对子集查询`field`字段中的列，然后在使用子集结果筛选包含`fKey`的结果。这样就导致如果不在`field`中添加`fKey`就查不出结果。
* 本意是想使用`field`字段限制结果中的列，不是查询过程中的列。

### ENV

OS Platform: Lastest

Node.js Version: Lastest

ThinkJS Version: Lastest

**Comment by welefen** [comment]
@wurining 恩，必须要有关联的字段，不然查询出来的数据无法关联上。
