### ISSUE TITLE
think-mongo 使用where 加$ne无效果

### ISSUE THREAD

**Issue by grapewheel** [thinkjs/thinkjs#1062]
## DESC
在model中使用where时加$ne等修饰符，查找无效

### ENV

OS Platform: deepin 15.5

Node.js Version: nodejs 8.5.0

ThinkJS Version: thinkjs 3.0.0

### code

```js
// 以下两个mongo查询$ne都无效
const hasUser = await this.where({phone: data.phone}).where({[this.pk]: {$ne: id}}).find() // 或者
const hasUser = await this.where({phone: data.phone, [this.pk]: {$ne: id}}).find()
```

### more description
id 为字符串，看过官方的parse.js 源代码，理应会将id转换为ObjectId，并调用查询的，但实际上无效，在mongodb的GUI管理软件测试有效

**Comment by lushijie** [comment]
```js
// just like this
return this.where({'_id': {$eq: think.Mongo.ObjectID('59eff824d455d5b177292751')}}).select();
```

**Comment by grapewheel** [comment]
@lushijie thx！buddy, 但很是奇怪，我看官方parse.js 源代码应该是会自动转换的
