### ISSUE TITLE
麻烦更正一下pageSize大小写导致的设置返回分页数无效问题

### ISSUE THREAD

**Issue by newcomein** [thinkjs/thinkjs#1063]
### ENV

OS Platform:

Node.js Version:9.4.0

ThinkJS Version:3.2.6

### code

```js
// your code here

    mysql: {
        handle: mysql,
        port: 3306,
        host: 'localhost',
        database: 'testnode',
        user: 'root',
        password: 'root',
        charset: 'utf8mb4_bin',
        encoding: 'utf8',
        dateStrings: true,
        supportBigNumbers: true,
        bigNumberStrings: true,
        pageSize: 20, // 设置默认每页为 20 条
        connectionLimit: 20, // 连接池的连接个数，默认为 1
    }

{
  pagesize: 10, //每页显示的条数
  currentPage: 1, //当前页
  count: 100, //总条数
  totalPages: 10, //总页数
  data: [{ //当前页下的数据列表
    name: "thinkjs",
    email: "admin@thinkjs.org"
  }, ...]
}
```

### error message

```
// your error message here
```

### more description

// your detail description 
https://thinkjs.org/doc/3.0/relation_model.html#toc-a39
https://thinkjs.org/doc/3.0/relation_model.html#toc-a43

其中返回的pagesize,这个跟mysql配置项里的pageSize大小写不一致,虽然可以在配置项里统一改成pagesize使配置项生肖,但是返回pagesize跟其他字段长得不一样,会有点别扭....问题虽然不大,但是还是希望官方能够更正,维护一下强迫症患者内心的秩序,谢谢(≧∇≦)ﾉ

**Comment by lushijie** [comment]
同为强迫症的我修改了，think-model@1.1.8 之后此字段修改为pageSize, 请更新。

**Comment by newcomein** [comment]
@lushijie 感谢~~

**Comment by lushijie** [comment]
1.1.8 漏掉一个地方出现了一个bug，升级一下1.1.9 吧 @newcomein

**Comment by newcomein** [comment]
@lushijie thanks
