### ISSUE TITLE
定时任务重复执行

### ISSUE THREAD

**Issue by hhxx1994** [thinkjs/thinkjs#1065]
### ENV

OS Platform: window 7 64bit

Node.js Version:v8.9.3

ThinkJS Version:v2.2.24

### code

```js
//path src/common/bootstrap/crontab.js
let CronJob = require('cron').CronJob
new CronJob('*/5 * * * * *', async () => {

        console.log("cronjob")
        
    }, () => {

    },
    true
);
```

### more description
上面文件改动时，babel转译时定时任务被注册，启动时定时任务再次被注册

**Comment by welefen** [comment]
@hhxx1994 开发环境下会是这样，线上环境没有这个问题
