### ISSUE TITLE
线上环境如何实现 src 文件有改动就自动编译

### ISSUE THREAD

**Issue by tumobi** [thinkjs/thinkjs#1067]
### 关于环境
+ 本地开发环境： Windows 10、WebStorm
+ 线上测试服务器：CentOS、pm2、nginx

### 问题
本地使用 WebStorm 开发好后使用 WebStorm 的 Deployment 上传到线上服务器，此时我希望服务器能监听到 src 的文件有改动，自动调用 `npm run compile` 和 `pm2 restart pm2.json` 实现自动化更新线上的代码。请问有什么方式可以实现吗？

**Comment by makeco** [comment]
写个脚本平滑重启服务的脚本一起扔到服务器上。装依赖，编译，然后 `kill -s USR2 $nodepid` 让node 进程平滑重启。

**Comment by songguangyu** [comment]
@tumobi 改错了 线上直接故障了？你这个太不靠谱了吧

**Comment by tumobi** [comment]
@songguangyu 是 线上测试服务器
