### ISSUE TITLE
logic下的rules中 关于 mobile 的验证要升级啦

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#1068]
现在国内又出了 199 和 166 开头的手机号码段, 如果不升级, 下列规则验证会失败

```
let rules = {
            mobile: {
                required: true,
                mobile: 'zh-CN',
                trim: true,
                aliasName: '手机号'
            }
        };
```

**Comment by lushijie** [comment]
```js
'zh-CN': /^(\+?0?86\-?)?1[345789]\d{9}$/,
```
这个正则199开头的可以通过，166的确实不能，我看看去给依赖库提个pr

**Comment by lushijie** [comment]
[Hi，isMobilePhone need support 166 section with locale of 'zh-CN'](https://github.com/chriso/validator.js/pull/768) 

哦 已经有人提pr了，但是还没有被接受

**Comment by lushijie** [comment]
刚刚被 accept 了，validator 发新版之后就ok了

**Comment by junmaqiang** [comment]
@lushijie  点赞 for you
