### ISSUE TITLE
自定义ts声明文件报错

### ISSUE THREAD

**Issue by cyyjs** [thinkjs/thinkjs#1074]
## DESC
再src目录下自定义了ts描述文件(在其他目录下不生效)，启动项目会报错
![image](https://user-images.githubusercontent.com/2883079/35547920-03335730-05b7-11e8-874a-f5bfacd0202a.png)

### ENV

OS Platform: macOS 10.13.3

Node.js Version: 8.9.4

ThinkJS Version: 3.2.6

**Comment by chigco** [comment]
我也想知道添加自定义的数据类型的ts声明文件，应该放哪里好。

controller/index.ts

`
import { MyData  } from 'src/MyData';
const data= {} as MyData;
`

MyData.d.ts
`interface MyData {
    a:string;
    b:string;
}`

启动项目是报错

**Comment by isLishude** [comment]
不可以在src目录使用 `*.d.ts`，去掉 `.d` 即可。

**Comment by isLishude** [comment]
不可以在src目录使用 `*.d.ts`，去掉 `.d` 即可。

可以在其它目录建立一个 defined 目录，里面加入 `*.d.ts` 然后在 tsconfig.json 内 include 即可

**Comment by SijieCai** [comment]
或者直接把 d.ts 改成 ts， 然后 export 出去。
