### ISSUE TITLE
分页的时候默认用id统计总条数，但我的主键名不是id，分页时就报错了

### ISSUE THREAD

**Issue by super-ax** [thinkjs/thinkjs#1075]
Node.js Version:5.6.0

ThinkJS Version:3.0
let result=await this.model('a_menu').page(getData.pageNumber,getData.pageSize).countSelect();
分页的时候默认用id统计总条数，但我的主键名不是id，分页时就报错了
![image](https://user-images.githubusercontent.com/31919734/35552937-b61c075c-05d0-11e8-90de-0bcb0c0bafb0.png)

**Comment by super-ax** [comment]
如何自定义id?

**Comment by welefen** [comment]
配置 pk, https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#toc-c88

**Comment by super-ax** [comment]
@welefen  好的，谢谢！
