### ISSUE TITLE
无法动态更改数据库配置

### ISSUE THREAD

**Issue by Srma** [thinkjs/thinkjs#1076]
## DESC
项目接入统一配置中心，启动时（beforeStartServer）从配置中心获取数据库配置，然后动态配置数据库信息，使用think.config查看，配置已经改变，但是数据库连接时没有改变。
### ENV

OS Platform:
win10
ThinkJS Version:
3.2.4

**Comment by welefen** [comment]
@Srma 项目是单模块还是多模块？

**Comment by Srma** [comment]
@welefen 我用的是多模块，单模块没测试

**Comment by welefen** [comment]
@Srma 多模块项目下写入配置默认只是写入到 common 模块下，如果要写入所有模块，需要增加额外参数：

```js
think.config('www', 'sss', true); // true 表示写入所有模块
```

**Comment by Srma** [comment]
@welefen 可以了，非常感谢

**Comment by wujie0919** [comment]
> @welefen 可以了，非常感谢

兄弟 你这个动态配置数据库 怎么设置的？我的一直报错
