### ISSUE TITLE
thinkjs 中增加 node-acl 权限管理如何获取 mongoose 连接？

### ISSUE THREAD

**Issue by ErikJiang** [thinkjs/thinkjs#1081]
### ENV

* thinkjs3.0
* think-mongoose
* node-acl

## DESC
项目中要增加权限控制功能，看到`node-acl`可以满足要求，想将其引入到thinkjs中，
但是要创建一个`acl`实例，需要`mongodb`的`dbConnection`，具体方式如下：
```
let mongoose = require('mongoose'),
    acl = require('acl');

let aclInst = new acl(new acl.mongodbBackend(mongoose.connection.db, 'acl_'));

```
但是只知道`thinkjs`中`mongoose`是通过`adapter`适配器引入数据库连接配置，但具体的这个`dbConnection`在thinkjs中如何获取就不知道了，尝试`think.mongoose.connection.db`也拿不到这个连接，哈哈，请问该如何获取这个mongo连接呢？

另外还想请教一下，在thinkjs中有没有更好的实现RBAC的方式？

**Comment by welefen** [comment]
think-mongoose 里包装的时候只有执行对应方法的时候才会建立连接，并且也是内部使用，外部无法调用。

你这里直接使用 mongoose 模块吧。

官方目前还没有提供对应的 RBAC 模块

**Comment by JiangInk** [comment]
好的，谢谢　^_^
