### ISSUE TITLE
thinkjs conntrolle层r为什么不支持多重继承，如A继承B，B继承C

### ISSUE THREAD

**Issue by souljessi** [thinkjs/thinkjs#1082]
## DESC
我想在B和C两个基类conntroller,挂载到think对象上，然后在业务conntroller继承B，B继承C。启动报错：TypeError: Class extends value undefined is not a constructor or null
### ENV
dev

OS Platform:

Node.js Version:8.9.3

ThinkJS Version:3.2

### code
```js
// extend/think.js
import BaseController from '../framework/common/controller/BaseController';
import BaseSocket from '../controller/websocket/BaseSocket';
export default {
    Redis: new RedisInit(),
    BaseController: BaseController,
    BaseSocket: BaseSocket,
}
// 业务conntroller.js
export default class extends think.BaseSocket {}

//  controller/BaseSocket .js
export default class extends think.BaseController {}

// controller/BaseController.js

export default class extends think.Controller{}
```

### error message
TypeError: Class extends value undefined is not a constructor or null

### more description
有的方法在在基类B，有的方法在基类C，通过A继承B继承C，A获得B C的方法，这是ES6的一种特性，本质上就是原型链的扩展，但是为什么在think用这种方式不能多重继承，是运行时的加载顺序问题，还是别的什么原因

**Comment by welefen** [comment]
export 的时候还没挂载上去呢，后面直接 extends think.BaseSocket 当然报错了

**Comment by welefen** [comment]
@souljessi ping
