### ISSUE TITLE
thinkjs 全局变量正确使用方式（ts）

### ISSUE THREAD

**Issue by chigco** [thinkjs/thinkjs#1083]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description 

thinkjs(ts)如何使用全局变量呢？
我是这样实现全局变量的，
在一个ts中做定义。
declare global { namespace NodeJS { export interface Global { socketServer: any; onlineUser: any; } } }
然后在a.ts
global.onlineUser = onlineUser;
在b.ts中输出global.onlineUser 的话，没有问题。
但是我发代码到生产之后，b.ts 输出报 global.onlineUser 为 underfine

**Comment by xioxin** [comment]
worker进程之间内存是不共享的
最好改用其他方式存储 比如redis
或者也可以修改设置 将workers 设置为1

**Comment by SijieCai** [comment]
你说的应该是全局共享的常量。
说来话长，TS 的类型规定，即使定义了全局变量，也需要import 一下，TS 在编译的时候才知道定义了什么，所以不推荐使用 global，具体为什么可以多看看网上的文章。
建议： 使用正常的模块定义，需要用到的时候 import 一下。多一行 import 很正常的。
