### ISSUE TITLE
TypeScript构建的项目 在调用model自定义方法时提示有误

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#1084]
## DESC
我检查了下,发现只要是think官方手册出现的方法都不提示,只有自定义的方法才提示. 之前没用tpyeScript构建的项目 这样写是可行的!

### ENV

OS Platform: macOS High Sierra 10.13.4

Node.js Version: v8.9.2

ThinkJS Version: 3.2.3

### code

我首先在src/model/sms.ts 下面定义了一个方法
```js
/*
 * 生产4位短信码数字
 * @return {string}
 */
setCodeNumber() {
    return String(Math.random()).substr(6,4)
}
```
然后在src/controller/v1/sms.ts 下实例化model,并且调用 setCodeNumber 这个方法

``` js
/**
 * 前置操作
 * @returns {boolean}
 */ 
async __before(){
  // 定义模型
  this.modelInstance = this.model('sms')
}

data['code'] = await this.modelInstance.setCodeNumber();
```
### error message

```
调用的地方提示: [ts] 类型“Model”上不存在属性“setCodeNumber”。
```
如下图
![33](https://user-images.githubusercontent.com/1819457/36056414-4d37c998-0e3f-11e8-8f05-3f47a78fc1e3.png)

### more description
朋友们帮我看看,我要如何写 才能解决这个报错问题!

**Comment by junmaqiang** [comment]
我用的是 rest 控制器

**Comment by junmaqiang** [comment]
我也试过了issues 上其他人的方法 还是不行,例如下面写法
```
import BaseRest from '../rest';
import Sms from "../../model/sms";
export default class extends BaseRest {

/**
 * 前置操作
 * @returns {boolean}
 */ 
async __before(){
  // 定义模型
  this.modelInstance = this.model('sms') as Sms
}
```

**Comment by wurining** [comment]
https://github.com/thinkjs/thinkjs/issues/976

**Comment by Louis-LiuQi** [comment]
哥们找到解决办法了吗，我也是用typescript构建项目，在这个问题卡住了，想把控制器里面的数据操作业务写在model里面，上面的方法都试过，要么提示不存在属性，要么可以找到此属性了，但是调用的时候确报错，提示 is not a function

**Comment by SijieCai** [comment]
#976

**Comment by Louis-LiuQi** [comment]
提了太久忘记了，我最终的解决方法是
**model 文件**
![](https://user-images.githubusercontent.com/26320931/50954013-1e071d00-14f0-11e9-9752-b23b3e0f091e.png)

![](https://user-images.githubusercontent.com/26320931/50954386-2744b980-14f1-11e9-94b1-a48e02e0fd03.png)


**controller中使用**
![](https://user-images.githubusercontent.com/26320931/50954224-ba312400-14f0-11e9-89d6-b6d522136229.png)
