### ISSUE TITLE
用TypeScript后Logic下面的 fail() 报错有误

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#1085]
## DESC
在TypeScript构建的项目中 fail 参数需要如何调整才不报错,请教下朋友们

### ENV

OS Platform: macOS High Sierra 10.13.4

Node.js Version: v8.9.2

ThinkJS Version: 3.2.3

### code

```js
      // 校验规则
      let flag = this.validate(rules);
      // 判断规则
      if (!flag) {
          // 通过 this.fail 把错误信息以 JSON 格式输出
          return this.fail('参数有误', this.validateErrors);
      }
```

### error message
![44](https://user-images.githubusercontent.com/1819457/36057049-c9ae50c8-0e44-11e8-8d40-e2941a0e5c6a.png)

**Comment by junmaqiang** [comment]
用下面写法就不报错
```js
      // 判断规则
      if (!flag) {
          // 通过 this.fail 把错误信息以 JSON 格式输出
          return this.fail(this.validateErrors);
      }
```

**Comment by wurining** [comment]
https://github.com/thinkjs/thinkjs/issues/1011

**Comment by junmaqiang** [comment]
谢谢, @wurining
