### ISSUE TITLE
thenAdd() 改进意见

### ISSUE THREAD

**Issue by yi-ge** [thinkjs/thinkjs#1086]
### ENV

OS Platform:MAC

Node.js Version:9.5

ThinkJS Version:3

### more description

// your detail description 
 thenAdd方法，只返回id和type，这就没意思了，如果type是'exist'，还得再次请求一次其他内容。但是this.fieldReverse().thenAdd()的用法却是可以的。

**Comment by welefen** [comment]
你的具体需求是什么呢？

**Comment by yi-ge** [comment]
@welefen 如果存在则返回所有内容，除非参数限定只返回id和type。个人认为这样更适用于大部分应用场景。

**Comment by lizheming** [comment]
@yi-ge 主要是默认 INSERT SQL 就是不返回数据只返回 insertid 的，如果要返回数据就要再写一个 SELECT 方法，这对大部分用户可能又不需要用到。你可以自己写一个 base 基类复写掉 thenAdd 方法：

```js
//base.js
module.exports = class extends think.Model {
  async thenAdd(...args) {
    const insert = super.thenAdd(...args);
    return this.where({[this.pk]: insert[this.pk]}).find();
  }
}
```

**Comment by yi-ge** [comment]
@lizheming 明白您的设计意图了，这是很高明的用法。也非常感谢您提供的方案！谢谢！

**Comment by lizheming** [comment]
@yi-ge 不客气，有问题欢迎继续反馈呀~
