### ISSUE TITLE
请教TypeScript下用this.post()数据转换问题

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#1088]
## DESC
请问伙伴们,如何处理typeScript下面object类型数据赋值给string变量操作的?
### ENV

OS Platform: macOS High Sierra 10.13.4

Node.js Version: v8.9.2

ThinkJS Version: 3.2.3

### error message

![55](https://user-images.githubusercontent.com/1819457/36085452-ddc6409e-1000-11e8-9e82-0dd5dc60edf9.png)

**Comment by wurining** [comment]
const smsCode:string=this.post('smsCode').toString();

**Comment by junmaqiang** [comment]
谢谢 @wurining
