### ISSUE TITLE
pm2 reload时候服务还是不能访问

### ISSUE THREAD

**Issue by feeloc** [thinkjs/thinkjs#1089]
### ENV

OS Platform: centos

Node.js Version: v8.4.x
 
ThinkJS Version: 最新

### code

```js
pm2 reload xxx
```

### error message

```
服务502
```

### more description

reload不是应该实现平滑过渡的吗，为什么还是出问题了

**Comment by welefen** [comment]
pm2 reload 并不会平滑过度，具体见：https://thinkjs.org/zh-cn/doc/3.0/deploy.html#toc-465

**Comment by feeloc** [comment]
哦哦，感谢，没注意看文档
