### ISSUE TITLE
请教如何实现像PHP Ob_flush效果？

### ISSUE THREAD

**Issue by yuanzhij** [thinkjs/thinkjs#1097]
for($j = 1; $j <= 5; $j++) { 
    echo str_repeat($i,1); 
    ob_flush(); 
    flush();
    sleep(1); 
}

谢谢。

**Comment by lizheming** [comment]
https://imququ.com/post/reduce-ttfb-on-thinkjs3-website.html

**Comment by yuanzhij** [comment]
3Q
