### ISSUE TITLE
thinkjs 3.0 如何部署SPA（前端有路由）?

### ISSUE THREAD

**Issue by KidLau** [thinkjs/thinkjs#1100]
## DESC

如何部署 SPA（前端有路由）?
2.2 的时候我也问过同样的问题，那时候是通过处理404的逻辑解决的，但3.0的项目里面没有找到关于404的逻辑代码，一时没有任何思路了

### ENV

OS Platform: windows10

Node.js Version: nodejs8

ThinkJS Version: 3.0

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
https://github.com/thinkjs/pharos/blob/master/src/config/middleware.js#L66
https://github.com/thinkjs/pharos/blob/master/src/controller/base.js#L19-L21

使用 `emptyContrller` 搭配 `__call` 魔术方法即可解决。

**Comment by KidLau** [comment]
谢谢指教！！！
