### ISSUE TITLE
adapter和extend的dts文件缺失

### ISSUE THREAD

**Issue by cca313** [thinkjs/thinkjs#1101]
## DESC
adapter和extend都有dts文件才称得上支持ts吧
### ENV
dev,prod
OS Platform:
windows
Node.js Version:
latest
ThinkJS Version:
latest
### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description 
我在用各位大神的框架准备用ts重构一个项目，发现很多adapater和extend都木有dts文件，也没有详细的API，而且还得看源码一个个去写，各位既然口号都写了支持ts,麻烦把最后一步走完吧。

**Comment by cca313** [comment]
@welefen @lushijie

**Comment by SijieCai** [comment]
@cca313  所有的Extend 都会有dts描述，但不是默认引入，用到哪个需要配置一下。请看https://thinkjs.org/zh-cn/doc/3.0/typescript.html 。Adapter 一般是不需要dts，如果有遗漏清具体描述一下问题。

**Comment by cca313** [comment]
@SijieCai  引入了extend-websocket和adapter-websocket.io 在controller中无法通过this对象访问emit方法
![image](https://user-images.githubusercontent.com/6041493/37279580-30449c68-2626-11e8-9352-82bd6d603fdc.png)

**我的配置：**
extend:
![image](https://user-images.githubusercontent.com/6041493/37279627-4f74676c-2626-11e8-8165-c85957a83b39.png)
adapter:
![image](https://user-images.githubusercontent.com/6041493/37279661-607b726c-2626-11e8-839f-d4e344630740.png)
config:
![image](https://user-images.githubusercontent.com/6041493/37279672-680c051e-2626-11e8-9e5c-03f18b298437.png)

**Comment by cca313** [comment]
@lushijie this.ctx.socket里面有个emit方法 不知道是不是这个？希望文档再健全些,加入typescript在adapter、extend、controller里的用法

**Comment by SijieCai** [comment]
@lushijie 这个现在什么情况了

**Comment by SijieCai** [comment]
@cca313 让我看看你的 src/index.ts 文件
这里面应该有一句   import 'think-websocket';

**Comment by wurining** [comment]
@cca313 
我的解决办法是把
`this.emit()`换成`this.ctx.emit()`
