### ISSUE TITLE
thinkjs的程序怎么打包

### ISSUE THREAD

**Issue by houxiaozhao** [thinkjs/thinkjs#1102]
### ENV

OS Platform: win10

Node.js Version: 9.5.0

ThinkJS Version: 3.2.4

### description

因为项目要部署到客户的服务器上，不希望客户可以看到源代码，有没有办法可以打包项目再运行。

**Comment by lizheming** [comment]
可以使用 docker 打包一个镜像出来？

**Comment by lushijie** [comment]
如果编译的话只提供 app 目录下的代码，不过仍然可以读懂

**Comment by houxiaozhao** [comment]
目前采用压缩代码的方式
安装`babel-minify`
`npm install babel-minify --save-dev`
把package.json的script/compile 
改成
`babel --no-babelrc src/ --presets think-node,minify  --out-dir app/`
