### ISSUE TITLE
think-model 一对多模型下当关联模型有新增数据的时候会获取不到值

### ISSUE THREAD

**Issue by biao166** [thinkjs/thinkjs#1107]
在更新主表的时候 https://github.com/thinkjs/think-model/blob/debc587f54954a911db5688bf2a35de09ebf5f33/src/model.js#L520

在更新关联表的时候  https://github.com/thinkjs/think-model/blob/debc587f54954a911db5688bf2a35de09ebf5f33/src/relation/has_many.js#L41

前一个更新将PK已经删除导致更新关联表取不到值 （this.data[this.options.key];）

**Comment by lizheming** [comment]
https://github.com/thinkjs/think-model/blob/debc587f54954a911db5688bf2a35de09ebf5f33/src/model.js#L535

好像 535 行又会加回来？

**Comment by biao166** [comment]
debug了一下
```
  async putAction() {
    if (!this.id) {
      return this.fail('params error')
    }
    const pk = this.modelInstance.pk
    const data = this.post()
    delete data[pk]
    if (think.isEmpty(data)) {
      return this.fail('data is empty')
    }
    const rows = await this.modelInstance.where({
      [pk]: this.id
    }).update(data)
    return this.success({
      affectedRows: rows
    })
  }
```
从putAction 就已经 delete data[pk]， 后面追加并没有将this.id 追加进来

**Comment by lizheming** [comment]
针对这个问题，我们商量了一下，这个主键值是一定要有的，要不然没办法将添加的关联数据和主表联系起来。所以我们在 think-model 上增加了主键值是否存在的判断，没有的话就不添加，同时我们修改了 `putAction` 里面的写法，将 `delete data[pk]` 替换为 `data[pk] = this.id`，避免 RESTful 中主键不存在的情况。如果是已创建的项目可参考一下如下链接的修改：https://github.com/think-template/standard/blob/master/template/src/controller/rest.js#L80
