### ISSUE TITLE
thinkjs redis 连接数超过最大数量。

### ISSUE THREAD

**Issue by Shidou** [thinkjs/thinkjs#1110]
### ENV

OS Platform: cents os 7.9 64位

Node.js Version: v8.7.0

ThinkJS Version:3.2.6

think-cache@1.1.0

think-cache-redis@1.2.0

### error message

```
ERR max number of clients reached
```

### more description
redis服务器连接数超过最大数， 现在每天定时重启服务器。
下面是正常情况下：
# Clients
connected_clients:850
client_longest_output_list:0
client_biggest_input_buf:0
blocked_clients:0

**Comment by welefen** [comment]
@Shidou 提供下 think-redis 的版本，如果不是 1.1.0，升级到这个版本看下。

**Comment by Shidou** [comment]
老大，是这个版本think-redis@1.1.0

**Comment by Shidou** [comment]
@welefen 老大，是这个版本think-redis@1.1.0

**Comment by welefen** [comment]
@Shidou 把相关代码和 cache 的配置提供下

**Comment by lushijie** [comment]
think-model cache 方法向 config 增加了 key 字段，但是在复用连接的时候未去除 key 导致，问题已修复请更新到think-redis@1.1.1
