### ISSUE TITLE
如何通过 logic 进行复杂参数验证

### ISSUE THREAD

**Issue by pz25925** [thinkjs/thinkjs#1111]
当有如下传入参数时:
![image](https://user-images.githubusercontent.com/12759499/37579664-7b6df636-2b7a-11e8-95dc-6f9cb2f607ed.png)

如何对 [data] 通过如下形式校验:
![image](https://user-images.githubusercontent.com/12759499/37579682-907bd71e-2b7a-11e8-8c16-250edccac48c.png)

**Comment by lushijie** [comment]
对于数组、对象的验证，logic 本身目前只支持一级嵌套的简单验证，对于复杂的验证建议通过自定义校验方法实现，如下：


```
// logic
let rules = {
      data: {
        array: true,
        children: {
         checkArrayItem: true
        }
      }
}
```

```
// src/config/validator.js
module.exports = {
    checkArrayItem: function(value, {ctx, currentQuery, parsedValidValue, rule, rules, validName, validValue }) {
     return [true | false]
    }
  },
  messages: {
    checkArrayItem: '{name}校验失败',
    // ASD_DS: [1001, 'EFF']
  }
}
// 关于自定义校验方法的更多信息请查看文档
```

**Comment by lushijie** [comment]
>think-validator@1.6.0 对复杂数据支持了 json-schema，如果熟悉可以使用 json-schema [查看文档](https://thinkjs.org/zh-cn/doc/3.0/logic.html#toc-ee8)

**Comment by pz25925** [comment]
谢谢, thinkjs 越来越强大了.

**Comment by xbup** [comment]
@lushijie 我使用了新版本的think-validator 但是json-schema失效了

**Comment by lushijie** [comment]
@xbup 你这样说我这没法定位问题，请详细描述下问题，谢谢

**Comment by xbup** [comment]
@lushijie 在think-validato@1.6.1的情况下 使用 官网上给的示例 
在valid错误的情况下
返回 ajv.errorsText(validate.errors)
然后flag拿到的仍为true

**Comment by lushijie** [comment]
@xbup 
```
    let rules = {
      data: {
        required: true, //必填，否则data不填写的情况下可以验证通过
        jsonSchema: {
          "properties": {
            "foo": { "type": "string" },
            "bar": { "type": "number", "maximum": 3 }
          }
        }
      },
    }
```

`required: true, //必填，否则data不填写的情况下可以验证通过`, 是不是你发的数据不对？

[postman demo](https://p5.ssl.qhimg.com/t01e2629d4c6253e93f.png)

如果不是这个意思，show me your code !

**Comment by lushijie** [comment]
顺便发一下你的数据请求吧，我想看下请求头




| |
卢士杰
前端工程师
|
|
奇虎360奇舞团
邮箱：lushijie1218@126.com
|

签名由 网易邮箱大师 定制

在2018年04月12日 20:23，白晓寒 写道：

"think-validator": "^1.6.1", 版本

**Comment by xbup** [comment]
@lushijie postman测试  
发送数据
`{
	"good":{
		"good_uuid":"aaaaaaaaaaaaaaaaaaaaaaaaaaa",
		"good_title":"aaaaaaaaa"
	},
	"member":{
		"member_uuid":"dasdasdd",
		"id":"dasdasdasd"
	}
}`
请求头：
`Connection →keep-alive
Content-Length →2
Content-Type →text/plain; charset=utf-8
Date →Thu, 12 Apr 2018 12:32:12 GMT
X-Powered-By →thinkjs-3.2.7
X-Response-Time →553ms`
结果是：
```
valid= false ajv.errorsText(validate.errors)= data should have required property 'good_by_member_uuid'
flag= true
```

**Comment by lushijie** [comment]
明天早上我看一下回复你，电脑不在身边




| |
卢士杰
前端工程师
|
|
奇虎360奇舞团
邮箱：lushijie1218@126.com
|

签名由 网易邮箱大师 定制

在2018年04月12日 20:33，白晓寒 写道：

@lushijie postman测试
发送数据
{ "good":{ "good_uuid":"aaaaaaaaaaaaaaaaaaaaaaaaaaa", "good_title":"aaaaaaaaa" }, "member":{ "member_uuid":"dasdasdd", "id":"dasdasdasd" } }
请求头：
Connection →keep-alive Content-Length →2 Content-Type →text/plain; charset=utf-8 Date →Thu, 12 Apr 2018 12:32:12 GMT X-Powered-By →thinkjs-3.2.7 X-Response-Time →553ms
结果是：

valid= false ajv.errorsText(validate.errors)= data should have required property 'good_by_member_uuid'
flag= true

**Comment by xbup** [comment]
好的 谢谢您

**Comment by lushijie** [comment]
@xbup 你的Content-Type 不对，你这样拿不到json data（你在logic/相应的action中可以打印 this.ctx.post()看看你获取到了什么东西）, 而

```
 let rules = {
            good: {
                required: true, // 看这里
                // 版本问题 需要think-validator @ 1.6.0 以上
                jsonSchema: { // jsonSchema 为自定义的校验方法具体使用参照ajv
                    type:'object',
                    required:['good_uuid','good_by_member_uuid','good_title']
                },
            },
            member:{
                required:true,
                object:true
            }
        };
```

`good`没有required: true。 导致的最终结果是 good 没有传值，而且非必填，验证通过。

thinkjs 验证会先对字段是否required进行验证，之后再进行其他规则的验证。

**Comment by xbup** [comment]
这是我刚刚进行的测试
![default](https://user-images.githubusercontent.com/26322213/38713116-28df8312-3f02-11e8-83a3-863a45d68e39.PNG)

**Comment by xbup** [comment]
@lushijie 这是think-validator的版本号
![1](https://user-images.githubusercontent.com/26322213/38713230-c34dee7a-3f02-11e8-9ac1-709657dc6514.PNG)

**Comment by lushijie** [comment]
Amazing，加我QQ吧，我拿你的测试也没有问题。。。 1036534499

**Comment by lushijie** [comment]
```
module.exports = {
  rules: {
    jsonSchema: function(value, {argName, validName, validValue, parsedValidValue, rule, rules, currentQuery, ctx}) {
      let validate = ajv.compile(validValue);
      let valid = validate(value);
      if (valid) return true;
      return {
        data: ajv.errorsText(validate.errors); // jsonSchema校验失败必须以对象的形式返回，一般形式为 字段名: 错误信息
      };
    }
  }
}
```
