### ISSUE TITLE
使用field后关联表不返回数据

### ISSUE THREAD

**Issue by yuanzhij** [thinkjs/thinkjs#1113]
模型名为 user，关联表的模型名为 info，
结果为
```js
[
  {
    id: 1,
    name: '111',
    info: { //关联表里的数据信息
      user_id: 1,
      desc: 'info'
    }
  }, ...]
```

如果模型 user使用了field字段，info就不返回了。

**Comment by welefen** [comment]
field 里必须含有关联表里对应的字段，不然的话无法把数据关联起来

**Comment by welefen** [comment]
比如： A 表里的 c 字段是和 B 表里的 d 字段进行关联的，如果查询 A 表指定 field() 里没有包含 c 字段，那么把 B 表里的数据查询出来后怎么关联起来呢？

**Comment by yuanzhij** [comment]
@welefen 万分感谢谢，明白你的意思，已经搞定了。
