### ISSUE TITLE
配置thinkjs-session-redis如何让浏览器关闭session不失效

### ISSUE THREAD

**Issue by shihuojian** [thinkjs/thinkjs#1117]
今天在配置thinkjs-session-redis的时候，发现浏览器关闭后再重新打开，session就失效了，但是redis数据还在。设置了expires，跟maxAge也还是那样，求下具体配置

**Comment by lushijie** [comment]
请发一下 config/adaper/session.js

**Comment by welefen** [comment]
@shihuojian 配置 session 对应的 cookie 失效时间，默认是浏览器进程

**Comment by lizheming** [comment]
关闭这个问题。配置一下 cookie 的 timeout 字段即可，可参考 https://github.com/firekylin/firekylin/blob/master/src/common/config/adapter/session.js#L11
