### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by cnn007** [thinkjs/thinkjs#1118]
### ENV mac

OS Platform: mac

Node.js Version: v8.2.1

ThinkJS Version:think-cli@1.0.16
"tenpay": "^2.1.2",
    "think-cache": "^1.0.0",
    "think-cache-file": "^1.0.8",
    "think-logger3": "^1.0.0",
    "think-model": "^1.0.0",
    "think-model-mysql": "^1.0.0",
    "think-session": "^1.0.0",
    "think-session-file": "^1.0.5",
    "think-view": "^1.0.0",
    "think-view-nunjucks": "^1.0.1",
    "thinkjs": "^3.0.0",
    "urllib": "^2.25.0"
### code
    "tenpay": "^2.1.2",
     ./node_modules/_tenpay@2.1.2@tenpay/lib/index.js:215
      ...params,
      ^^^
       

```js
// tenpay@2.1.2@tenpay/lib/index.js:215
getNativeUrl(params) {
    let pkg = {
      ...params,
      appid: this.appid,
      mch_id: this.mchid,
      time_stamp: '' + (Date.now() / 1000 |0),
      nonce_str: util.generate()
    };

    let url = 'weixin://wxpay/bizpayurl'
            + '?sign=' + this._getSign(pkg)
            + '&appid=' + pkg.appid
            + '&mch_id=' + pkg.mch_id
            + '&product_id=' + pkg.product_id
            + '&time_stamp=' + pkg.time_stamp
            + '&nonce_str=' + pkg.nonce_str;
    return url;
  }
```

### error message

```
 SyntaxError: Unexpected token ...
```
   
### more description

安装使用tenpay后，启动定时任务，node production.js XXX/XXX 
报错，SyntaxError: Unexpected token ...

**Comment by lizheming** [comment]
https://www.npmjs.com/package/tenpay tenpay 模块需要 node >= 8.3.0
