### ISSUE TITLE
请问是否有朋友用docker的node镜像部署过thinkjs

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#1127]
## DESC
1, 我这个Dockerfile文件是利用网易的node作为基础,
2, 然后build一个镜像日后专门用于启动thinkjs项目
3, 编译命令是: docker build -t="node/thinkjs" ./
4, 编译成功了 ID: 54a8c9795bba
5, 启动容器命令是: docker run -p 127.0.0.1:8006:8360 -v /thinkjs-ts-api:/usr/src/app --name api -d 54a8c9795bba

![wx20180412-155136](https://user-images.githubusercontent.com/1819457/38663485-7d3c4722-3e69-11e8-8860-b36e4765bdf8.png)

**问题: 容器也启动成功,只是挂起状态,似乎我的端口没暴露,-d也没起到效果;**

我在本地写了一个Dockerfile文件,内容如下:
```md
# 基础镜像信息
FROM hub.c.163.com/library/node:8.4.0
# 维护者信息
MAINTAINER jun <junma@gmail.com>
# 创建服务目录
RUN mkdir -p /usr/src/app
# 设置工作目录
WORKDIR /usr/src/app
# 设置权限
# RUN chmod a+w $WORKDIR/package.json
# 安装NPM依赖
RUN npm install
# 开放端口
EXPOSE 8360
# 启动-thinkjs
CMD ["npm", "start"]
```

### ENV

OS Platform: macOS High Sierra 10.13.4

Node.js Version: v8.9.2

ThinkJS Version: 3.2.3

**Comment by lizheming** [comment]
先不 `-d` 直接运行看看有报什么错么？粗看了下 Dockerfile 应该没啥问题。

**Comment by isLishude** [comment]
Docker 需要使用前台任务来运行，如果你的npm start 是后台任务就会有错误。

如果你用了 pm2 需要设置`--no-daemon`

具体可以参考我的文章：https://github.com/isLishude/blog/issues/143

**Comment by lizheming** [comment]
最近正好有用 Docker 做 ThinkJS 的启动环境，可以参考下[lizheming/animaris](https://github.com/lizheming/animaris) (基于 ThinkJS + MongoDB 开发的项目）的 [Dockerfile](https://github.com/lizheming/animaris/blob/master/Dockerfile) 和 [docker-compose.yml](https://github.com/lizheming/animaris/blob/master/docker-compose.yml) 文件。

**Comment by lizheming** [comment]
暂时先关闭这个问题，有相关需求的可参考文章 https://zhuanlan.zhihu.com/p/37082611
