### ISSUE TITLE
建议：thinkjs package.json 定义的模板路径优化

### ISSUE THREAD

**Issue by isLishude** [thinkjs/thinkjs#1131]
## DESC

使用 thinkjs new，会在 package.json 中定义了一段 thinkjs 的配置信息，这里有个字段是 `cacheTemplatePath` 使用的当前的用户家目录的路径下的一个地址，但是如果其它协作的伙伴也使用 `thinkjs controller ... ` 生成这种模板的话，就有些混乱。

Nodejs 里面还不能识别 `path.resolve("~")` 这样的定义家目录的方式，我想应该在 think-cli 下载模板的时候使用 `path.resolve(process.env.HOME, "默认模板路径")` ，而不需要显示定义具体的用户家目录。

或者默认不要直接定义在用户家目录，而是 /tmp 什么的目录。。

```json
{
"thinkjs": {
    "metadata": {
      "name": "...",
      "description": "application created by thinkjs",
      "author": "..."
    },
    "projectName":  "...",
    "templateName": "typescript",
     // 这里如果不定义的话，还会报错
     // 我认为这里应该指定模板的不包含用户家路径的路径
     // 下载的时候再使用 path.resolve() 加上当前用户家目录
    "cacheTemplatePath": "/Users/name/.think-templates/typescript",
    "clone": false,
    "isMultiModule": false
  }
}
```
### ENV

OS Platform: mac

Node.js Version: 8.x lts

ThinkJS Version: 3.x latest

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by berwin** [comment]
@isLishude 嗯嗯嗯，感谢提出问题，前几天我们已经讨论了这个问题，目前正在修复中。。

**Comment by xbears** [comment]
至少是否可以将这两个配置独立出来，不放在 package.json，  然后这两个配置就可以不加入版本控制了。

**Comment by berwin** [comment]
@xbears 你好，请问下你说的是哪两个配置？？😂😂

**Comment by xbears** [comment]
```
"templateName": "/Users/xxx/.nvm/versions/node/v8.9.4/lib/node_modules/think-cli/default_template",

"cacheTemplatePath": "/Users/xxx/.think-templates/-Users-xxx-.nvm-versions-node-v8.9.4-lib-node_modules-think-cli-default_template",
```

**Comment by isLishude** [comment]
需要考虑一些兼容性，直接移除不好。

**Comment by isLishude** [comment]
新版本是移除了，这条关闭了。

**Comment by berwin** [comment]
@isLishude 对，新版本将cacheTemplatePath移除了，每次使用到cacheTemplatePath时通过固定的规则重新拼一个路径~ 这样可以避免每个人的家目录不同的问题~
