### ISSUE TITLE
cron 定时任务不执行

### ISSUE THREAD

**Issue by cnn007** [thinkjs/thinkjs#1134]
### 使用定时任务，0/5 * * * * 这种表达式不能执行，0 2 * * * 但是这种却可以正确执行。

OS Platform: MACOS, centos

Node.js Version: v8.10.0

ThinkJS Version: 
 "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-preset-think-node": "^1.0.0",
    "node-notifier": "^5.0.2",
    "think-watcher": "^3.0.0",
    "think-inspect": "0.0.2",
    "think-babel": "^1.0.3",
    "eslint": "^4.2.0",
    "eslint-config-think": "^1.0.0"
  },

### code

```js
{//
  cron: '0 2 * * *',    // 每天凌晨2点执行 可以正确执行
  handle: 'order/refund',
  immediate: false,
  type: 'one',
  enable: true
}, {
  cron: '0/5 * * * *',    // 每5秒执行
  handle: 'activity/staticTersure',
  immediate: true,
  type: 'one',
  enable: true
}
```

### error message

``` 
// 第二种不会执行，
```

### more description

// 需要间隔执行的定时任务，例如没1一小一次，每5秒一次，
是表达式写的不正确，还是哪里配置的问题，请楼主帮忙看下。
参考资料：https://blog.csdn.net/yansong_8686/article/details/46991189
https://thinkjs.org/zh-cn/doc/3.0/crontab.html

**Comment by welefen** [comment]
cron: '0/5 * * * *',    这个格式不正确啊。 5 秒的用 interval 来做 https://thinkjs.org/zh-cn/doc/3.0/crontab.html#toc-224

**Comment by lizheming** [comment]
think-crontab 支持设置秒，不过格式是这样的

```js
cron: '0/5 * * * * *'
```
你少了一位，interval 暂时不支持设置开始时间，如果要设置开始时间的话可以这么写：

```js
cron: {
  start: new Date('2014-04-23 10:00:00'),
  rule: '0/5 * * * * *'
}
```
表示4月23日10点之后每隔5秒执行

**Comment by junmaqiang** [comment]
我有点懵逼了, 到底是几个 * 位?
https://thinkjs.org/zh-cn/doc/3.0/crontab.html    这里的 cron 是 5个 * 位
你这里的例子是 6个 * 位
http://crontab.org  官方推荐参考的 也是 5个 * 位

@lizheming 大哥过来瞧瞧;

**Comment by lizheming** [comment]
@junmaqiang Linux 的 crontab 是不支持设置秒的，因为它的最低频率是一分钟，所以默认 crontab 的格式是5位。但是 ThinkJS 内部使用的 node-schedule 是通过 node 去模拟 crontab 服务的，能支持秒级别，所以对 crontab 格式做了扩展，增加了一位设置秒。

其实这些东西都很简单，懂的搜索看一下 node-schedule 的 README 就全清楚了 https://github.com/node-schedule/node-schedule

**Comment by junmaqiang** [comment]
@lizheming  大哥 小弟受教啦!  
还有个疑问请教下:
我希望当天的早上9:00开始到第二天凌晨3:00期间每隔20分钟执行下定时任务,下面这样写,对否?
```
    {
        cron: '*/20 9-3 * * *', 
        handle: 'v1/crontab/autoDown',
        type: 'one',
        enable: true,
    },
```

**Comment by lizheming** [comment]
写不来 cron 命令的推荐你一个网站 https://crontab.guru/#*/20_9-3_*_*_* 自己去校验下就知道了

**Comment by junmaqiang** [comment]
迅速收藏,  感谢大哥厚爱和分享   @lizheming
