### ISSUE TITLE
关于beforeUpdate的问题

### ISSUE THREAD

**Issue by xbup** [thinkjs/thinkjs#1135]
在使用beforeUpdate的时候是先where按照id查询到相应的数据然后update
可是在beforeUpdate里接收到的data是where查询到的而不是我要更新的数据

**Comment by lizheming** [comment]
第一个参数是传入的待更新的数据，第二个是参数是 model 相关的配置项，其中有一个 `options.where` 可以用来获取 where 条件。
https://github.com/thinkjs/think-model/blob/master/src/model.js#L525

**Comment by xbup** [comment]
@lizheming 可是我拿到的是数据库的旧数据 。。。

**Comment by lizheming** [comment]
那就是你哪里操作过啦，代码里没有这种逻辑，你再仔细debug一下，你看看源码，默认 beforeUpdate() 之前都没有处理数据啦。

**Comment by xbup** [comment]
![image](https://user-images.githubusercontent.com/26322213/39118444-08a548da-471c-11e8-802e-5458e343c37a.png)

这是我的操作，我无法看为什么test没有传入

**Comment by xbup** [comment]
![image](https://user-images.githubusercontent.com/26322213/39118444-08a548da-471c-11e8-802e-5458e343c37a.png)

这是我的操作，我无法看出为什么test没有传入

**Comment by xbup** [comment]
![image](https://user-images.githubusercontent.com/26322213/39118796-ccac9c06-471c-11e8-89d9-3dd65cfa2b5f.png)

这是调用的controller

**Comment by lizheming** [comment]
你的表里有 test 这个字段没

**Comment by xbup** [comment]
数据库没有test字段

**Comment by xbup** [comment]
看来传入的确实是我要更新的数据，有问题的是boolean类型变了

**Comment by xbup** [comment]
我知道原因了  因为 数据库是tinyint类型的  而我传入的true  所以字段改变字段值了 谢谢您的回答
