### ISSUE TITLE
mysql分页查询缓慢

### ISSUE THREAD

**Issue by Shidou** [thinkjs/thinkjs#1137]
## 由于mysql模块提不了问题，把问题提在了这里，关于mysql分页需要优化问题。
      thinkjs提供的数据库处理模块，分页在查询到page=几千几万的时候会很慢，因为用了原生的limit 1000，10。 希望可以优化。

### 正式环境

OS Platform:  linux

Node.js Version:  v8.9.4

ThinkJS Version:3.2.7

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by songguangyu** [comment]
如果数据量非常庞大的情况下 建议使用上一页 下一页 通过索引查找。不建议使用常规分页，因为limit 几百万的时候 就是很慢。
