### ISSUE TITLE
请问下thinkjs可同时支持链接操作mongodb和mysql数据库嘛？

### ISSUE THREAD

**Issue by huoyufei** [thinkjs/thinkjs#1138]
请问下thinkjs可同时支持链接操作mongodb和mysql数据库嘛？，现在新开一个工程需要链接之前业务的数据库

**Comment by lushijie** [comment]
ThinkJS 支持配置多种数据库共存，不过默认的数据库配置只有一种，如果要使用默认之外的数据库配置，需要在操作语句上修改数据库类型。

**Comment by huoyufei** [comment]
好的，万分感谢！
