### ISSUE TITLE
如何在其他模块中调用controller模块中的方法？

### ISSUE THREAD

**Issue by Shidou** [thinkjs/thinkjs#1142]
## 自己用了一个简单的消息队列，消息队列随着thinkjs项目启动而启动。
在消费者队列中，想要调用对应的某个controller来解决业务，但是这个queue没有依赖继承thinkjs.controller。
所以我我只能调用think这个对象。这个think对象中就看到了 think.app.controllers下面各个controller，不知道具体怎么调用controller下面的方法。

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/controller.html#toc-7d3

**Comment by Shidou** [comment]
@lizheming 按了return键，莫名其妙的写了标题就发送出来了。

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/crontab.html#toc-173

**Comment by Shidou** [comment]
@lizheming 老哥，文档不对呀，现在我的消费者队列里面只有think这个对象可以调用。

**Comment by lizheming** [comment]
![image](https://user-images.githubusercontent.com/424491/39252541-7b73a4a2-48d8-11e8-870f-a33c5ab5ba3a.png)

**Comment by Shidou** [comment]
@lizheming 老哥，除了这个方法，还是其他代码直接调用的不？

**Comment by lizheming** [comment]
没有哦，而且你一个异步队列完全没必要随着 ThinkJS 启动诶

**Comment by Shidou** [comment]
@lizheming 那老哥的思路是？

**Comment by lizheming** [comment]
单独起个进程开队列，需要调 ThinkJS 的时候直接使用命令行的形式调用把参数传过去 `node production.js "a/b?test=1&q=2"。

**Comment by lushijie** [comment]
new think.app.controllers.pad2().indexAction() 
问题确认得到解决，关闭issue
