### ISSUE TITLE
缓存cache的针对不同类型adapter配置timeout

### ISSUE THREAD

**Issue by UtillYou** [thinkjs/thinkjs#1144]
## DESC
在thinkjs2的时候配置cache过期很简单。thinkjs3.的配置变成了针对adapter的配置。比如说我开发时要用到

```javascript
await this.cache(cacheKey, cacheValue, {file: {timeout: 10 * 60 * 1000}});
```

但是在部署到服务器上要使用redis，难道要把代码都改一遍成：

```javascript
await this.cache(cacheKey, cacheValue, {redis: {timeout: 10 * 60 * 1000}});
```

像这样的代码程序里很多，一个一个去改太麻烦了。
### ENV

OS Platform:
windows
Node.js Version:
8
ThinkJS Version:
3
### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lushijie** [comment]
如果你程序中只用一个cache 
```

module.exports = {
  type: 'file',
  common: {
    timeout: 30 * 1000,
  },
  file: {
    handle: fileCache,
    cachePath: path.join(think.ROOT_PATH, 'runtime/cache'),  // absoulte path is necessarily required
    pathDepth: 1,
    gcInterval: 24 * 60 * 60 * 1000 // gc interval
  },
  redis: {
    handle: redisCache,
    port: 6379,
    host: '127.0.0.1',
    password: ''
  },
  memcache: {
    handle: memcacheCache,
    hosts: ['127.0.0.1:11211'],
    maxValueSize: 1048576,
    netTimeout: 5000,
    reconnect: true
  }
}
```

修改type 不就可以了？ 例如 isDev ? 'file' :  'redis'。 为什么要一个个的改？？？

**Comment by KuoKongQingYun** [comment]
@lushijie 我想楼主的意思是，他可能要为不同的缓存设置不同的超时时间，而设置超时时间的时候就得指定type，所以不能在配置文件里设置一个统一的配置。

**Comment by lizheming** [comment]
那就直接给每个 adapter 配 timeout 呗，虽然文档的示例里是放到 common 上的，但是 common 意为所有 adapter 的共同配置，这些配置显然也是能单独在 adapter 上配的。

```js
const fileCache = require('think-cache-file');

exports.cache = {
  type: 'file',
  file: {
    handle: fileCache,
    timeout: 24 * 60 * 60 * 1000
  },
  longtimtoutFile: {
    handle: fileCache,
    tiemout: 24 * 60 * 60 * 1000 * 365
  }
}
```

**Comment by UtillYou** [comment]
要是只有这样的几个缓存当然不成问题，问题是在实际的系统中，有很多缓存，每个缓存的过期时间不一样。就像我们的电商系统。用户的access_token 过期时间为两小时，session 过期时间一天。注册验证码十分钟。激活邮件链接半小时，订单未支付超时一小时。。。更为复杂的是过期时间需要程序计算得出的那种。像这种的只能写在代码里，通过统一的配置实在很难。
现在的版本的过期非要指定adapter类型，但实际上我根本不关心adapter类型啊。我们一般在开发的时候使用 file 类型，在服务器上用 redis 。理想的情况就是像 thinks2 那样。之前我们就用得很好，在代码里可以自由的写一个缓存项需要多久过期，至于用得什么类型的adapter，根本就不需要关心，反正由配置文件切换就好。

**Comment by lizheming** [comment]
感觉语文要多学学了，说了这么多才明白你要干嘛。。。
如果你仅仅是因为要切 adapter 而已。。。adapter 的配置之自由，怕你是想不到的。。。

```js
const fileCache = require('think-cache-file');
const redisCache = require('think-cache-redis');

exports.cache = {
  type: 'fileRedis',
  fileRedis: {
    handle: isDev ? fileCache : redisCache,
    tiemout: 24 * 60 * 60 * 1000 * 365
  }
}
```

开发环境中直接 

```js
await this.cache(cacheKey, cacheValue, {fileRedis: {timeout: 10 * 60 * 1000}});
```

需要改 adapter 名字么，不需要呀~

**Comment by UtillYou** [comment]
哈哈，是我语文能力不行，表达得不好，你说的这个方案的确是可行，我没有想到还可以这样配置，谢谢了！
