### ISSUE TITLE
how to find data in bot.on('message', (msg)

### ISSUE THREAD

**Issue by ijry** [thinkjs/thinkjs#1147]
![b6d5f472a9e74c9f648f2e0d8e9a8aef](https://user-images.githubusercontent.com/3102798/39413395-31995138-4c5c-11e8-95fd-b79893d9b001.jpg)

![7fb5672cb88b1e696b7422d2ced19934](https://user-images.githubusercontent.com/3102798/39413396-34f7409c-4c5c-11e8-9a02-5d362bd2ab65.jpg)

**Comment by lizheming** [comment]
```js 
bot.on('message', async msg => {
  const tel = this.model('tel');
  const exist = await tel.where({chat_id: msg.chat.id}).find();
});
```
