### ISSUE TITLE
Column 'user_id' in where clause is ambiguous 跨表join添加where条件

### ISSUE THREAD

**Issue by newcomein** [thinkjs/thinkjs#1148]
### ENV

OS Platform:

Node.js Version:10.0

ThinkJS Version:3.2.7

### code

```


    async checkUserToken() {
        return this.alias('table_a').where({user_id:'80381d8ce4f5af478f92cb89ceb3597e'}).join({
            user: {
                on: {
                    user_id: 'user_id',
                }
            },
            token: {
                on: {
                    token_id: 'token_id'
                }
            },
        }).find();
    }


```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by newcomein** [comment]
单独拼写sql的话
`
SELECT * FROM `user` AS table_a LEFT JOIN `user` ON (`table_a`.`user_id`=`user`.`user_id`) LEFT JOIN `token` ON (`table_a`.`token_id`=`token`.`token_id`) WHERE ( table_a.`user_id` = '80381d8ce4f5af478f92cb89ceb3597e' )

`

给where加上表的查询别名就可以查询数据,this.alias('table_a')这个设置别名似乎不影响到where里查询的表?

**Comment by lizheming** [comment]
别名肯定没办法影响到 `where()` 字段啊，你 JOIN 之后万一查询的字段是 JOIN 表里面的呢？所以肯定不能程序给你加别名的。这种你自己直接写 `where(where({'table_a.user_id':'80381d8ce4f5af478f92cb89ceb3597e'})` 应该就可以了。

**Comment by newcomein** [comment]
![image](https://user-images.githubusercontent.com/13670360/39422291-56e22d82-4c9f-11e8-8fbc-60dad4fad207.png)
还有另外一个问题,就是join的时候  返回重复的数据 

![image](https://user-images.githubusercontent.com/13670360/39422362-995be8ba-4c9f-11e8-93cc-aebaec0170df.png)
以及count数量不准确

![image](https://user-images.githubusercontent.com/13670360/39422388-b56f2e72-4c9f-11e8-98a9-70479ead9063.png)
video_comment这张表一共7条数据

这段的代码是这样的:

`


        const data2 = {
            orderByKey: 'table_a.createTime',
            orderByType: 'ASC',
        };

        const page = data.page;

        delete data.page;

        const result = await this.alias('table_a').field('table_c.userName,comment_id,content,createTime,user_id').join({
            user: {
                as: 'table_c',
                on: {
                    user_id: 'user_id',
                }
            },
            video_comment: {
                as: 'table_b',
                on: {
                    user_id: 'user_id'
                }
            },
        }).where({'table_b.video_id': data.video_id}).order(`${data2.orderByKey} ${data2.orderByType}`).page(page, 84).countSelect();


`

@lizheming

**Comment by lizheming** [comment]
别限制 SELECT 字段，放开了看看所有的数据，这种问题基本上是你写的连表查询语句有问题。

**Comment by newcomein** [comment]
@lizheming 改为没有限制字段之后也一样

**Comment by lizheming** [comment]
我是让你放开看所有的数据自己查一下你的 JOIN 哪有问题啦，不是说放开数据就能解决问题，你的 JOIN 表太复杂没环境肉眼不好给你debug~

**Comment by newcomein** [comment]
@lizheming 

![image](https://user-images.githubusercontent.com/13670360/39422968-662fb69e-4ca2-11e8-8617-f30b4aa21376.png)

user表:
![image](https://user-images.githubusercontent.com/13670360/39423008-8b733cf0-4ca2-11e8-8d4c-4efe6f8e2c1e.png)

video_comment表
![image](https://user-images.githubusercontent.com/13670360/39423044-a939922a-4ca2-11e8-82cd-4608ea4484eb.png)



也没觉得有多复杂,就是在user和video_comment中找到指定的video_id的所有评论数据,并返回用户和评论的信息

精简了一下代码

`return this.join({
            user: {
                as: 'table_user',
                on: {
                    user_id: 'user_id',
                }
            },
            video_comment: {
                as: 'table_video_comment',
                on: {
                    user_id: 'user_id'
                }
            }
        }).select();
`

这个问题依然存在

@lizheming

**Comment by lizheming** [comment]
id 一样能证明什么呢，连表一对多的时候本来就有可能会多生成同样的数据呀。控制台确认输出的 sql 是不是你写的那个意思，如果是那就不是 thinkjs 的问题，那就证明你的 sql 语句本来就有问题。从你前文给出的 sql 语句和你这句给出的 node 语句来对比，sql 语句的输出是正常的。这个连表反正我是有点晕😓 你自己再好好看看吧，别掉到左连的坑里了。鉴于这个 issue 和程序本身无关，我先关闭了，代码bug你自己再查查吧。

**Comment by newcomein** [comment]
@lizheming😂  我大概找到原因了  我这是跨了三张表所以导致返回的数据有问题  在model层 this本身就是指向了一张表,我再次声明的时候将原本已经指向的表重复写了一次,所以出问题了

**Comment by lizheming** [comment]
优秀了~给你点赞哦~

**Comment by newcomein** [comment]
@lizheming 哦 冷漠
