### ISSUE TITLE
支不支持原生sql语句

### ISSUE THREAD

**Issue by chenzeZzz** [thinkjs/thinkjs#1150]
使用 model.sum 的时候：
 _this5.model(...).setRelation(...).group(...).field(...).sum(...).select is not a function
我的操作是，分组并求和一个字段，取100条数据，提示生成的sql是：
SELECT SUM(`cost_award`) AS think_sum FROM `group_transaction` GROUP BY `user_id` LIMIT 1
我该怎么结合sum和其他功能，或者支不支持原生sql

**Comment by KuoKongQingYun** [comment]
https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#toc-bf5

**Comment by lizheming** [comment]
另外直接 `sum()` 就可以得到结果了，不需要 `select()`。https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#toc-c11

**Comment by chenzeZzz** [comment]
@lizheming 后来解决的方法是，this.field（[‘id'， 'sum(price)’]）

**Comment by lizheming** [comment]
也可以的
