### ISSUE TITLE
thinkjs的运行流程到底是怎么样的？

### ISSUE THREAD

**Issue by zluo001** [thinkjs/thinkjs#1153]
新手，看不懂官方文档里的运行流程说明，因为从文档来看，运行都应该是读取的src目录下的代码，跟app目录没啥关系，app只是转义后的代码，个人理解是，即使是上线，用app里的代码，也是把app里的代码拷贝到src目录下，不知道这个理解是否有错误？但是在开发测试的时候发现，用node development.js启动，运行读取的是app目录下代码。这是为什么呢？新手，望见谅。谢谢。

**Comment by lizheming** [comment]
https://github.com/think-template/standard/blob/master/template/development.js#L9
读取的是 `APP_PATH` 上定义的目录，babel 编译的话就读 `app`，不编译的话就读 `src`，当然也可以自己配。上线还要自己把 `app` 改成 `src` 这种不智能的事情肯定不会发生的啦~

**Comment by zluo001** [comment]
谢谢，瞬间明白了，一目了然，非常感谢。
