### ISSUE TITLE
获取当前路径错误

### ISSUE THREAD

**Issue by yoder** [thinkjs/thinkjs#1155]
## DESC
ctx.href以及ctx.origin在https状态下获取到的都是http://的地址
### ENV

OS Platform:
centos7
Node.js Version:
v8.9.1
ThinkJS Version:
3.1.0
### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
1. https://github.com/think-template/standard/blob/master/template/production.js#L7 确认一下是否是 `node production.js` 启动的
2. 如果是，确认下 `proxy:true` 这个属性是否设置上
3. 如果以上都 OK，最后再确认下 Nginx `proxy_pass` 到 ThinkJS 的时候有没有 `add header  X-Forwarded-Proto`。

**Comment by yoder** [comment]
好的

**Comment by jhyvictory** [comment]
@lizheming 直接npm start调试的话就是没法获得真实ip了？
