### ISSUE TITLE
如何在service中调用session获取redis中的值

### ISSUE THREAD

**Issue by Tauleos** [thinkjs/thinkjs#1157]
## DESC
如题所示。
### ENV

OS Platform:windows7

Node.js Version:v8

ThinkJS Version:v3

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description 

我在项目中自己扩展了request-promise的一个方法用于发http请求给java端。在用户登录之后，java端会给node端一个特征值。后续接口发送请求的时候需要在header中增加该字段。该特征值当前是存储在redis中。如何在service中通过think.session获取该特征值？

**Comment by welefen** [comment]
@Tauleos  Session 跟用户相关，Service 是脱离用户关联的。如果 Service 里需要该值，可以在 Controller 里获取到 Session 然后作为参数传递进去

**Comment by Birjemin** [comment]
了解
