### ISSUE TITLE
think-watcher 如何watch view层文件

### ISSUE THREAD

**Issue by liuxingsheng** [thinkjs/thinkjs#1158]
## DESC
如何watch view层文件
### ENV

OS Platform:maxOS

Node.js Version:v9

ThinkJS Version:v2

### code
think-watcher 如何watch view层文件
```js
// think-watcher

**Comment by lushijie** [comment]
view 默认开启了模板缓存，所以开发模式下，你会发现页面刷一下但是内容没有变化，可以把缓存关掉。

如果你已经了解到上述问题，只是想做到修改页面就更新的效果，可以借助简单的浏览器插件。

**Comment by liuxingsheng** [comment]
// exports.cache = {
//     type: 'file',
//     common: {
//         timeout: 24 * 60 * 60 * 1000 // millisecond
//     },
//     file: {
//         handle: fileCache,
//         cachePath: path.join(think.ROOT_PATH, 'runtime/cache'), // absoulte path is necessarily required
//         pathDepth: 1,
//         gcInterval: 24 * 60 * 60 * 1000 // gc interval
//     }
// };
还是没有效果啊

**Comment by lushijie** [comment]
是view自身的cache。。。




| |
卢士杰
前端工程师
|
|
奇虎360奇舞团
邮箱：lushijie1218@126.com
|

签名由 网易邮箱大师 定制

在2018年05月11日 20:34，liuxingsheng 写道：

// exports.cache = {
// type: 'file',
// common: {
// timeout: 24 * 60 * 60 * 1000 // millisecond
// },
// file: {
// handle: fileCache,
// cachePath: path.join(think.ROOT_PATH, 'runtime/cache'), // absoulte path is necessarily required
// pathDepth: 1,
// gcInterval: 24 * 60 * 60 * 1000 // gc interval
// }
// };
还是没有效果啊

**Comment by liuxingsheng** [comment]
请问view层的缓存如何关闭？

**Comment by lushijie** [comment]
有个option里面有cache配置




| |
卢士杰
前端工程师
|
|
奇虎360奇舞团
邮箱：lushijie1218@126.com
|

签名由 网易邮箱大师 定制

在2018年05月11日 20:43，liuxingsheng 写道：

请问view层的缓存如何关闭？

**Comment by liuxingsheng** [comment]
具体是哪个配置？你给我说下目录，我去找找

**Comment by liuxingsheng** [comment]
<img width="195" alt="wx20180511-205043 2x" src="https://user-images.githubusercontent.com/11531863/39925316-b8a7ee78-555d-11e8-81f7-d478a348cd02.png">

这是config目录

**Comment by lushijie** [comment]
如果使用nunjucks 模板的话：
```
nunjucks: {
    handle: nunjucks,
    options: {
      noCache: true,
    }
}
```

**Comment by liuxingsheng** [comment]
我用的是ejs，按你说的加上noCache，还是没有预期效果
<img width="436" alt="wx20180511-210633 2x" src="https://user-images.githubusercontent.com/11531863/39925796-a5c9d4fe-555f-11e8-8e7c-e9ab27afc995.png">

**Comment by lushijie** [comment]
ejs 当初没有统一，很遗憾配置稍有不同：

```
ejs: {
   ..
   options: {
     cache: false
   }
}
```
https://github.com/thinkjs/think-view-ejs/blob/master/index.js#L24

**Comment by liuxingsheng** [comment]
可以了，万分感谢

**Comment by lushijie** [comment]
不客气，有机会可以尝试读一下源码

**Comment by liuxingsheng** [comment]
好的

**Comment by zqw** [comment]
**赞，谢谢Lxxsss，解决了我的问题**

**Comment by zqw** [comment]
ejs: {
   ..
   options: {
     cache: false
   }
}
