### ISSUE TITLE
【typescript】单例使用

### ISSUE THREAD

**Issue by chigco** [thinkjs/thinkjs#1159]
在typescript中如何使用单例模式呢？

写了一个类，然后在controller中使用就报错了。
```typescript
class Singleton {
    public static GetInstance(): Singleton {
        if (Singleton._instance == null) {
            Singleton._instance = new Singleton();
        }
        return Singleton._instance;
    }
    // tslint:disable-next-line:variable-name
    private static _instance: Singleton = null;
}

const Singleton = require("../service/Singleton");


private singleton = Singleton.GetInstance();

//TypeError: Singleton.GetInstance is not a function

```

因为我看到框架中的redis提供的方法有限。
想引入ioredis，写个redis的链接管理需要在整个项目中只存在一个单实例。
typescript中具体应该怎么写？
如果是写个service类，export default class extends think.Service 貌似也不对吧？每次require就都会去创建链接。

**Comment by lizheming** [comment]
思路以及Singleton 这部分写的没什么问题，检查一下是不是 require 的路径不对，亦或是文件没有将 Singleton export 出来，逐步调试一下。

**Comment by SijieCai** [comment]
如果是写个service类，export default class extends think.Service 貌似也不对吧？每次require就都会去创建链接。
关于这个：每次 require 不会重新创建。
需要注意的事这种写法，只是每个进场上是单例，不是整个项目上的单例。
