### ISSUE TITLE
addMany时，如果第一个数据中，包含null的值，会导致sql ER_WRONG_VALUE_COUNT_ON_ROW错误

### ISSUE THREAD

**Issue by tinder1024** [thinkjs/thinkjs#1164]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
let arr = [{a:10,b:null,c:'xxx'},{a:20,b:30,c:'yyy'}];
think.model('xxx').addMany(arr);
生成的sql如下
INSERT INTO `xxx` (`a`,`c`) VALUES (10,'xxx'),(20,30,'yyy');
导致sql执行报错
```

### error message

```
ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 2
```

### more description

如果addMany时，第一个数据包含null项，生成的sql中，columns字段中，就不会包含null项。但是后续的其他数据中，这一项并不是null，values中，就会无法匹配columns

**Comment by lizheming** [comment]
https://github.com/thinkjs/think-model-abstract/blob/master/lib/query.js#L75 是的，因为根据第一个数据做了 key 的格式化，这个目前看来只能算是 feature 了，不太好改。

**Comment by lizheming** [comment]
Hello, we have decided to won't fix it, you can validate your data before `addMany` to avoid this error.
