### ISSUE TITLE
怎么调用存储过程？

### ISSUE THREAD

**Issue by zluo001** [thinkjs/thinkjs#1165]
麻烦请教下，thinkjs怎么调用mysql存储过程？并且存储过程带参数，有结果集返回。另外不是很清楚，如果存储过程返回的结果集跟任何model，或者说表都没关系（不知道这么描述是否正确），只是自定义的一个结果集（比如返回几列，每一列都来自于不同的表，或者甚至是有计算列），这时候我应该建一个什么样的model.js文件呢？新手，不是很明白，谢谢。
另外也参考了这个issues https://github.com/thinkjs/thinkjs/issues/352
但是愚钝，还是没看明白，到底怎么给sp传参，并且返回结果集？文档中也没找到。
谢谢。

**Comment by Messilimeng** [comment]
let sql =`set @totalpage = 0;call sp_pager('${params.tablename}','${params.fields}','${params.orderfield}','${params.sqlwhere}','${params.groupfield}','${pagesize}','${params.pageindex}','${params.sqlcounttable}',${params.paging},@totalpage);select @totalpage;`;
sp_pager 是存储过程名字 然后直接写参数 最后返回 
就是你把mysql 里面执行储存过程的语句贴出来就可以了 然后 this.model('mysql').query(sql)

**Comment by tommymsw** [comment]
补充一下：sp_pager 是存储过程名字 然后直接写参数 最后返回
      就是你把mysql 里面执行储存过程的语句贴出来就可以了 然后 this.model('mysql').query(sql)

let sql = call my_sp( params1,params2, @incr);

我调用了带out 参数的存储过程 举例： let result = await this.model('my_sp').query(sql);
但是 返回的结果如下：
 [ OkPacket {
    fieldCount: 0,
    affectedRows: 0,
    insertId: 0,
    serverStatus: 10,
    warningCount: 3,
    message: '',
    protocol41: true,
    changedRows: 0 },
  [ RowDataPacket { '@incr': 0 } ] ]

我希望的结果是取到 返回回来的 out 参数的值， 请问该如何获取到 返回回来的out 值

**Comment by Messilimeng** [comment]
这个在存储过程里面定义一下就行了
