### ISSUE TITLE
请问如何返回文本，不需要json，就是文本

### ISSUE THREAD

**Issue by UtillYou** [thinkjs/thinkjs#1166]
## DESC
在thinks2的版本中我们还可以用this.end 来返回，3就完全没有了，返回的头信息里总有application/json。请问有直接返回一段文本的方法吗？
### ENV

OS Platform:windows

Node.js Version:8.11.0

ThinkJS Version:3

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
```
this.ctx.body = 'hello world';
```

**Comment by UtillYou** [comment]
设置了body的值然后怎么返回呢？用this.succes,this.json都不行

**Comment by lizheming** [comment]
这个设置完了就返回了

**Comment by UtillYou** [comment]
测了一下，的确是这样，但是和原来相比太不优雅了，需要写一个空return，希望能像原来那样添加一个方法，这样程序看起来明确一些

**Comment by lizheming** [comment]
可以自行添加 extend 方法https://thinkjs.org/zh-cn/doc/3.0/extend.html

**Comment by UtillYou** [comment]
好的
