### ISSUE TITLE
请问join操作后，对于相同的列名，field里面如何写？

### ISSUE THREAD

**Issue by liuxingsheng** [thinkjs/thinkjs#1167]
### code

```js

this.model('a').join('b on a.id=b.id).field('a.id,b.id').select();

```

### more description

请问join操作后，对于相同的列名，field里面如何写？

**Comment by lizheming** [comment]
就你这么写呀，或者用 AS 给一下别名

**Comment by liuxingsheng** [comment]
Error: ER_NON_UNIQ_ERROR: Column 'id' in order clause is ambiguous

**Comment by liuxingsheng** [comment]
对对对，as可以重命名，没事了，谢谢
