### ISSUE TITLE
通过post('xml')取值时，结果是数组

### ISSUE THREAD

**Issue by netfere** [thinkjs/thinkjs#1168]
## DESC
在做微信开发中，微信推送xml数据，程序中用this.post('xml')获取数据，结果如下：
{ ToUserName: [ 'ww8d4d086dd677c346' ],
 Encrypt:[ 'vttZIENo9h2Nfiz9y6r....' ],
AgentID: [ '' ] }
但根据微信文档来看，推送的xml本身不是数组，但post('xml')读出的结果是还数组的。
查看了一下payload代码，用的是xml2js来解析，而xml2js默认是以数组方式输出的，需要加explicitArray:false参数才不用数组。现在不知道使用post('xml')时，如何设置成不用数组输出。
### ENV

OS Platform:linux

Node.js Version:9.2.1

ThinkJS Version:3.2.7

**Comment by berwin** [comment]
您好，这个问题已经修复，think-payload模块现已更新、
解析XML支持参数啦~
直接在参数中设置`explicitArray: false`即可。

**Comment by netfere** [comment]
this.post('xml',{explicitArray:false})是这样读取么？

**Comment by berwin** [comment]
@netfere 额，，，不是的，，config目录下有一个middleware.js这个文件。这个文件里有配置项目使用都的中间件和参数，例如：

```javascript
{
  handle: 'payload',
  options: {
    explicitArray: false
  }
}
```
