### ISSUE TITLE
redis 配置信息无效

### ISSUE THREAD

**Issue by Messilimeng** [thinkjs/thinkjs#1169]
### ENV

OS Platform:

Node.js Version:
8.+
ThinkJS Version:
3.X
### code

```js
// your code here
```

### error message
thinkredis 配置信息无效
设置了密码连不上 
reids 取消了密码 就能连接上
```
// your error message here
```

### more description

// your detail description

**Comment by welefen** [comment]
@Messilimeng Redis 设置密码后通过其他途径看能不能连接上，看是不是有什么限制

**Comment by Messilimeng** [comment]
@welefen 我试试 那天试了 很多次  log打印都是默认配置配置信息 不知道怎么回事 现在项目都在运行 不好测

**Comment by Messilimeng** [comment]
![image](https://user-images.githubusercontent.com/12272166/41276466-e378b954-6e56-11e8-92c5-823787497437.png)
我改掉 think-redis 的默认配置就可以连接了 请尽快修复bug 我们要用 谢谢啊 老大

**Comment by Messilimeng** [comment]
![h xjnxiiieh7w e6ftp0](https://user-images.githubusercontent.com/12272166/41279815-092e5a4c-6e60-11e8-84de-7ab33e49efc3.png)
打印配置信息没有redis 配置 但是吧 think-reids 默认配置换了就可以了连接 ，所以配置获取不到

**Comment by lushijie** [comment]
session redis 配置位置错误，已解答
