### ISSUE TITLE
this.controller怎么调用controller下面文件夹的action

### ISSUE THREAD

**Issue by liuxingsheng** [thinkjs/thinkjs#1170]
```js
this.controller('mb/login', 'test');
```

### more description
this.controller怎么调用controller下面文件夹的action

**Comment by liuxingsheng** [comment]
![image](https://user-images.githubusercontent.com/11531863/40401670-0c3c9104-5e7a-11e8-85b0-53cab9e2b15b.png)

**Comment by liuxingsheng** [comment]
<img width="1017" alt="wx20180523-111522 2x" src="https://user-images.githubusercontent.com/11531863/40401768-a019079a-5e7a-11e8-99f7-89ec7daa38fa.png">

**Comment by lizheming** [comment]
调 action 是 `this.action` https://thinkjs.org/zh-cn/doc/3.0/controller.html#toc-7d3

**Comment by liuxingsheng** [comment]
调用其他action的时候不能传参数吗？

**Comment by lizheming** [comment]
Action 不支持传参

**Comment by liuxingsheng** [comment]
除了action，有没有其他可以传参的调用方式呢？
