### ISSUE TITLE
未开启babel转译的项目在报错后文件src内的文件莫名被删除

### ISSUE THREAD

**Issue by qq1073830130** [thinkjs/thinkjs#1173]
### ENV

OS Platform:

Node.js Version: 10

ThinkJS Version:  3.x

### code

```js
// your code here
```

### error message

// your error message here

### more description

// your detail description 
**触发了这个错误**

```[2018-05-24T14:39:20.675] [7892] [INFO] - SQL: UPDATE `user`
SET `name`='ice3' WHERE ( `id` = '6' ), Time: 4ms
{ Error: ER_DUP_ENTRY: Duplicate entry 'ice3' for key 'name```

然后对应的控制器文件user.js就自动被删除了,昨天晚上也出现过似的情况，不过是配置文件adapter.js被删除

**Comment by lizheming** [comment]
`DEBUG=think-watcher npm start` debug 模式启动后看看 `think-watcher` 的日志是否有什么异常，贴出来看看。
