### ISSUE TITLE
关于新版thinkjsBUG问题

### ISSUE THREAD

**Issue by smallage** [thinkjs/thinkjs#1179]
## DESC
创建多模块报错
### ENV

OS Platform:
win10
Node.js Version:
v8.9.3
ThinkJS Version:
 v2.2.24

### code

```js
 thinkjs new cms --module
```

### error message

```
 error: unknown option `--module'

```

### more description

// your detail description

**Comment by lizheming** [comment]
```js
npm install think-cli -g
```

请安装 `think-cli` 模块，`--module` 是 ThinkJS3 才有的参数，老版本 ThinkJS 2 中对应的是 `--mode=module`。
