### ISSUE TITLE
自定义配置目录

### ISSUE THREAD

**Issue by wuliupo** [thinkjs/thinkjs#1182]
## DESC
按照官方文档（https://thinkjs.org/zh-cn/doc/3.0/config.html），所有的配置都统一管理，文件都放在 src/config/ 目录下。
可否通过 new Application 时指定 config 目录的位置？

### ENV

OS Platform: Any

Node.js Version: 8.11.1

ThinkJS Version: 3.2.7

**Comment by welefen** [comment]
@wuliupo 不可以，为啥想要自定义呢

**Comment by BaffinLee** [comment]
实在要这样的话，可以曲线救国，在 `src/config` 文件夹下的配置文件里面 require 或 import 别的位置的配置信息。

**Comment by wuliupo** [comment]
@welefen 我们生产环境只约定了两个目录：
app 是 node 端代码
dist 是 ui 端代码

**Comment by welefen** [comment]
@wuliupo 项目都部署在 app 目录下不就好了么？

**Comment by lizheming** [comment]
我们在启动脚本里，是支持配置  `APP_PATH` 属性来定义项目目录的，默认是 `src` 你也可以直接定义成 `app` 的。
