### ISSUE TITLE
多进程， 多机器在work.js 里设置定时器 

### ISSUE THREAD

**Issue by chenzeZzz** [thinkjs/thinkjs#1186]
多进程的时候定时器会执行多次

多进程可以用think-crontab或者work id，多台机器有什么好的解决办法

**Comment by lushijie** [comment]
https://thinkjs.org/zh-cn/doc/3.0/multi_process.html

**Comment by chenzeZzz** [comment]
@lushijie 是这样的，我进程问题可以解决， 但是项目部署在多台机器上，在work.js 里有定时器，如果有机器执行了更新数据库，怎么让其他机器跳过这个步骤

**Comment by lushijie** [comment]
多机器，得自己共享操作结果，存数据库，或者其他类似方案

**Comment by chenzeZzz** [comment]
是的，非常感谢
