### ISSUE TITLE
文档'Logic' 中一个写法的疑惑

### ISSUE THREAD

**Issue by flight9** [thinkjs/thinkjs#1187]
## DESC
> https://thinkjs.org/zh-cn/doc/3.0/logic.html
文档'Logic' 中的 '多action复用校验规则'小节中, 示例代码:
```
module.exports = class extends think.Logic {
  get scope() {
    return {
      app_id: {
        required: true
      }
    }
  }
....
}
```
请问 
get scope() {...} 是什么用法, 一下看不明白, 查了下 Baidu 等没有找到类似, 请明白人解释一下,谢谢。

**Comment by lushijie** [comment]
就是下面 n 个 logic 校验中都存在这个app_id 字段。

**Comment by flight9** [comment]
@lushijie 这个是什么语法？ 是标准 js 语法还是 thinkjs 特有的, 有介绍吗？

**Comment by qgy18** [comment]
es5 中的 getter：

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

**Comment by flight9** [comment]
@qgy18 谢谢
