### ISSUE TITLE
d.ts缺少ctx.req.io的定义 

### ISSUE THREAD

**Issue by cca313** [thinkjs/thinkjs#1189]
### ENV

OS Platform: debian

Node.js Version:  10.3.0

ThinkJS Version: latest (typescript)

### code

```js
// your code here
```

### error message
[ts] Property 'io' does not exist on type 'IncomingMessage'.
```
// your error message here
```

### more description

// your detail description 
typescript也不知道是配错什么了还是漏了什么 ctx对象是可以访问到的,但是io对象在d.ts中都没有定义？
![_ _20180611180802](https://user-images.githubusercontent.com/6041493/41226285-9d3c8b54-6da3-11e8-816b-f81d3479bc16.png)
![_ _20180611181713](https://user-images.githubusercontent.com/6041493/41226303-ad1f6e42-6da3-11e8-8af1-bfe3c4c94ed4.png)

以下是我的配置
**adapter:**
![_ _20180611180725](https://user-images.githubusercontent.com/6041493/41226368-e0a9708c-6da3-11e8-8a19-e8c138f3e4ed.png)
**extend:**
![_ _20180611181916](https://user-images.githubusercontent.com/6041493/41226410-f57a0314-6da3-11e8-9186-6c24c0cbc44c.png)
**middleware:**
![_ _20180611181932](https://user-images.githubusercontent.com/6041493/41226430-06da9254-6da4-11e8-9492-ba85e8cf94ac.png)
**index.ts**
![_ _20180611182034](https://user-images.githubusercontent.com/6041493/41226474-295b58fe-6da4-11e8-8759-0d2f3ff17f36.png)

**Comment by cca313** [comment]
@SijieCai  @welefen 麻烦大佬抽两分钟看下是我配置的问题还是d.ts文件的问题

**Comment by BaffinLee** [comment]
用 `this.ctx.app.websocket` 或者 `think.app.websocket`。

文档里写了 `ctx` 有 `io` 属性，是 `websocket` `handler` 的实例：[文档](https://thinkjs.org/zh-cn/doc/3.0/websocket.html#toc-112)

但是代码里没有把 `instance` 挂在 `ctx` 下面，[代码](https://github.com/thinkjs/think-websocket/blob/master/index.js#L13)

index.d.ts 文件里也没 `io` 属性的定义，[代码](https://github.com/thinkjs/think-websocket/blob/master/index.d.ts#L3)

可能是 `bug` 或者文档未更新。

**Comment by cca313** [comment]
@BaffinLee  感谢~ 下次我也得学着去看看代码

**Comment by lizheming** [comment]
https://github.com/thinkjs/cn.thinkjs.org/blob/master/3.0/websocket.md#io-%E5%AF%B9%E8%B1%A1 感谢各位，文档已更新。
