### ISSUE TITLE
官方文档网址无法嵌入到iframe中显示

### ISSUE THREAD

**Issue by hyingreborn** [thinkjs/thinkjs#1195]
内部网页中需要显示thinkjs官方文档，嵌入到iframe中报错如下：
Refused to display 'https://thinkjs.org/doc/index.html' in a frame because it set 'X-Frame-Options' to 'deny'.

**Comment by lushijie** [comment]
禁止了 iframe 嵌入，请到官方网站查看文档，谢谢

**Comment by hyingreborn** [comment]
@lushijie 只是想嵌入到网页里，便于浏览，不能解除禁止吗？

**Comment by lizheming** [comment]
已经去除了，感谢建议。
