### ISSUE TITLE
thinkjs-cli创建的项目，app目录和src目录的区别是什么？

### ISSUE THREAD

**Issue by zhenwoo** [thinkjs/thinkjs#1196]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/babel.html
开启编译的话`src`是编译前 `app`是编译后文件位置。
