### ISSUE TITLE
如何为不同用户的session设置不同的过期时间？

### ISSUE THREAD

**Issue by hyingreborn** [thinkjs/thinkjs#1197]
登录时想做“3天内保持登录状态”功能
但是session目前只能全局设置，现在希望登录时如果传了过期时间，则为这个用户单独设置一个session过期时间，没传则使用全局的过期时间

**Comment by BaffinLee** [comment]
```javascript
await this.session('name', 'value', {
  maxAge: 3 * 24 * 3600 * 1000
});
```

前提是 `cookie` 的 `maxAge` 要大于等于 3 天，要不然 `cookie` 比 `session` 先过期了。

**Comment by hyingreborn** [comment]
@BaffinLee 感谢！官方文档里没找到有options，去翻think-session源码找到了

**Comment by hyingreborn** [comment]
@BaffinLee 试了好像不可以啊，看session里还是使用了全局的过期时间
