### ISSUE TITLE
希望cache支持清空方法

### ISSUE THREAD

**Issue by hyingreborn** [thinkjs/thinkjs#1198]
有时候使用缓存的时候，为了兼顾性能和数据及时更新，需要做一个手动清空缓存的功能，发现redis缓存不能方便的清空，折中直接使用IOredis来清空：

![image](https://user-images.githubusercontent.com/1283261/42018794-c32c1628-7ae5-11e8-821c-99d0389d3887.png)

think-redis是否可以提供清空方法，以避免手工再次连接一次redis服务器？

**Comment by lushijie** [comment]
redis有可能别的存储也在使用不太可能全量清掉，目前只能逐个清除。
