### ISSUE TITLE
logic's __after method is deprecated, it will be discarded in the next version  <anonymous>:null:null

### ISSUE THREAD

**Issue by xiaomiwujiecao** [thinkjs/thinkjs#1200]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
It's doesn't matter, you can ignore this message. It's an warning tips for remove `__after` magic method in logic.
