### ISSUE TITLE
where complex query(where  复合查询)

### ISSUE THREAD

**Issue by wzlhappy** [thinkjs/thinkjs#1201]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code
![image](https://user-images.githubusercontent.com/30285548/42151463-adacb6d6-7e0f-11e8-8463-151974a51c2d.png)

```js
// your code here
```

### error message

```
// your error message here
```

### more description
使用 where 里的复合查询，如果同时使用两个复合查询，只按最后一个运行。怎样使两个复合查询同时生效？
// your detail description

**Comment by lizheming** [comment]
对象的属性是不重复的，同一个属性后面的赋值会覆盖前面的。我看了一下目前应该是不支持多符合查询的，如果有这个需求可以使用 `query()` 方法写原生 SQL 搞定。

**Comment by wzlhappy** [comment]
谢谢谢谢，我直接where（），里面用sql写的查询条件，非常感谢

在 2018-07-14 09:58:23，"公子" <notifications@github.com> 写道：


对象的属性是不重复的，同一个属性后面的赋值会覆盖前面的。我看了一下目前应该是不支持多符合查询的，如果有这个需求可以使用 query() 方法写原生 SQL 搞定。

**Comment by lizheming** [comment]
`_complex` now support Array data type, please upgrade to `think-model-abstract@1.2.4`. You can write code like this:

```js
this.model('user').where({
  _complex: [
    {'a.c_print': ['IN', [0,3]], 'o.print_status': 3, _logic: 'or'},
    {'o.path': ['LIKE', '%'+bms+'%'], 'o.bumen_id':42, _logic: 'or'}
}).select();
```
