### ISSUE TITLE
ThinkJS是否还在维护？

### ISSUE THREAD

**Issue by hyingreborn** [thinkjs/thinkjs#1203]
近半年多都没什么大的升级，QQ群里维护人员也不怎么活跃，作为小白感觉ThinkJS用的比eggjs顺手很多，不知道官方是否还有继续维护升级的计划？有4.0的计划吗？

**Comment by lizheming** [comment]
有问题就问问题，我们都有在回 issue 啊。4.0 还在计划，没那么快。
