### ISSUE TITLE
关于xml请求的解析

### ISSUE THREAD

**Issue by grapewheel** [thinkjs/thinkjs#1206]
## DESC
thinkjs自带了text/xml的请求解析xml转换为json，但如何设置xml的转换格式？默认转换格式字段带了数组，又要自己做多次转换
### ENV

OS Platform: linux

Node.js Version: 10.0

ThinkJS Version: 3.2.7

**Comment by lizheming** [comment]
same as https://github.com/thinkjs/thinkjs/issues/1168, close this issue.

**Comment by grapewheel** [comment]
OK，thx
