### ISSUE TITLE
Tue, 10 Jul 2018 13:10:10 GMT logic deprecated logic's __after method is deprecated, it will be discarded in the next version  at <anonymous>:null:null

### ISSUE THREAD

**Issue by shihuojian** [thinkjs/thinkjs#1207]
ThinkJS version: 3.2.8  一直提示
Tue, 10 Jul 2018 13:10:10 GMT logic deprecated logic's __after method is deprecated, it will be discarded in the next version  at <anonymous>:null:null

**Comment by lushijie** [comment]
后续大版本 logic 的 __after 方法可能会去掉，这是一个提示，不是bug~

**Comment by lizheming** [comment]
same as #1200 close this issue
