### ISSUE TITLE
Promise.map跟thinkjs的版本有关

### ISSUE THREAD

**Issue by feeloc** [thinkjs/thinkjs#1208]
### ENV 

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
    await Promise.map(images, async img => {
      xxx
    })
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
由于自带的 Promise 的性能已经足够好，所以 3.2.8 已经移除了 Bluebird 的 Promise Polyfill 支持。而 `Promise.map` 是 Bluebird 提供的一个非标准方法，如果已使用的话可以在 `production.js` 自己引入

```js
global.Promise = require('bluebird');
```
