### ISSUE TITLE
关于mongod的aggregate查询$lookup无效

### ISSUE THREAD

**Issue by shihuojian** [thinkjs/thinkjs#1209]
关于mongod的aggregate查询$lookup无效，例如我设置以下查询方法，两个集合的数据库是有关联的，但是inventory_docs映射的数据始终为空
```js
{
          $lookup:{
            from:'orders',
            localField:"_id",
            foreignField:"pid",
            as:'inventory_docs'
          }
        }
```
@lushijie @welefen

**Comment by lizheming** [comment]
我看 `$lookup` 比较新，应该是目前 `think-mongo` 使用的 `mongodb@2` 的版本不支持。由于已经有一个升级 mongo 的 issue 存在了 https://github.com/thinkjs/thinkjs/issues/1210 ，暂时先关闭这个 issue，相关同学可关注 #1210
