### ISSUE TITLE
创建typescript项目出错

### ISSUE THREAD

**Issue by chigco** [thinkjs/thinkjs#1212]
think-cli@2.2.4
 think-cli · Cannot read property 'some' of undefined

**Comment by chigco** [comment]
$ thinkjs new ts typescript

? Project name ts
? Project description ThinkJS 3.0 typescript
? Author

   think-cli · Cannot read property 'some' of undefined

**Comment by berwin** [comment]
@chigco OK，我在windows系统下看看，我之前是在Mac上看的，可能与系统环境有关系

**Comment by berwin** [comment]
@chigco 经排查，应该是模板缓存的问题，把本地模板清除就可以了，执行以下命令：

```shell
# 1. 清除本地缓存模板
$ thinkjs clean

# 2. 重新创建项目
$ thinkjs new ts typescript
```

这个问题与 #1014 是相同的问题~
