### ISSUE TITLE
thinkjs 在cluster模式下如何在内存中共享一个对象？

### ISSUE THREAD

**Issue by scofieldfan** [thinkjs/thinkjs#1214]
## DESC

某些场景下，想在内存中声明一个对象，不同进程来访问和修改，   请问thinkjs 在cluster模式下如何在内存中共享一个对象？并且共享的时候是否像其他语言一样加锁？
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by welefen** [comment]
@scofieldfan 借用外部的存储介质吧，如：Redis、Memcache

**Comment by scofieldfan** [comment]
redis，和memcache 会更好一些，但是cluster模式下 是因为要进程间通讯？发消息来实现么？thinkjs 框架没做封装是么？

**Comment by scofieldfan** [comment]
谢谢，看一下。

**Comment by welefen** [comment]
@scofieldfan Master 和 Worker 之间可以通过 IPC 通道通信，传递数据（通过 JSON 序列化数据）。

至于进程之间共享数据，不建议把数据放在 Master 进程中。因为 Master 进程会接收请求，然后转发给 Worker 进程处理，所以要保持  Master 足够稳定（Master 挂了会导致服务直接挂了）。

至于把内容放在一个 Worker 保存，然后共享给其他 Worker 是否可行呢？理论上是可行的。
Worker 之间是没有接口直接相互通信的，如果要通信的话有二种办法：1）通过 Master 进程中转 2）Worker 进程自己启动一个 TCP 服务，其他 Worker 进程直连这个 TCP 服务。

第一种方案要中转一次，会比较慢，同时也会给 Master 增加压力，可能会造成 Master 不稳定。第二种方式需要自己处理这个策略。

所以实际情况中还不如直接借用外部的一个服务来存储，这样 Node 服务重启后数据也还在。
