### ISSUE TITLE
上传文件获取获取不到文件

### ISSUE THREAD

**Issue by ApolloRoad** [thinkjs/thinkjs#1215]
think-payload，文件上传之后返回了文件地址，却没有实际写入文件到文件系统，你也拿不到this.ctx.request.body.file 的实际对象，只给你一个空json，下一步什么都取不到。

**Comment by welefen** [comment]
@ApolloRoad 你上传接口的 Content-Type 是对的么？另外：文件上传后会保存在一个临时目录，请求结束后会删除，如果需要保存下来，需要手工移动到其他地方，具体请参考：https://thinkjs.org/doc/3.0/context.html#toc-322

至于为什么在请求结束后删除，是因为：如果不删除，那么攻击者会利用该接口一直上传，把机器磁盘撑爆。

**Comment by ApolloRoad** [comment]
@welefen Content-Type是对的，在Action中通过this.ctx.request.body.file，能取到file的信息（下图2，我把file直接返回），但是官网文档的this.file('image')是取不到的，this.ctx.request.body.file下一步取file.path或者file.name之类的，也什么都取不到了。
官网的文档虽然默认返回了OK但是也没有实际写入文件，网上的例子也无效，会报错取不到（下图3,图4）直接500

![qq 20180717104716](https://user-images.githubusercontent.com/5633780/42793886-cbca0cc2-89ae-11e8-9116-32564807611b.png)
![qq 20180717104928](https://user-images.githubusercontent.com/5633780/42793958-1c8c8ebe-89af-11e8-995e-d754bb783a1a.png)

**Comment by ApolloRoad** [comment]
![qq 20180717105632](https://user-images.githubusercontent.com/5633780/42794467-843a0b70-89b1-11e8-9322-8d99eab2d0c9.png)
![777](https://user-images.githubusercontent.com/5633780/42794479-930b17e8-89b1-11e8-87b5-433ffc89a239.png)

**Comment by ApolloRoad** [comment]
![qq 20180717111001](https://user-images.githubusercontent.com/5633780/42794553-f8f91b9a-89b1-11e8-9bcf-7a9f1ef2e5de.png)
![777](https://user-images.githubusercontent.com/5633780/42794557-fc175e7c-89b1-11e8-99a4-c5b3701ef11b.png)

### **我是windows上弄的，是不是和系统有关系？？？**

**Comment by ApolloRoad** [comment]
至于临时目录，也不会写入实际文件，配置了payload的options，也没用

**Comment by welefen** [comment]
@ApolloRoad  你表单上传的时候表单名称是 "file"，所以取的时候要通过 `this.file("file")`

**Comment by ApolloRoad** [comment]
@welefen
我回去了试试，那通过request.body.file取到的是什么？？？

**Comment by lizheming** [comment]
如果有不明白的可以多看看代码，其实很简单的。

https://github.com/thinkjs/think-payload/blob/master/lib/multipart.js#L38-L41 `think-payload` 文件上传解析出来是一个 `{post, file}` 的对象会赋值给 `ctx.request.body` https://github.com/thinkjs/think-payload/blob/master/index.js#L46

最后 `ctx.file('file')` 获取文件的逻辑在 https://github.com/thinkjs/thinkjs/blob/master/lib/extend/context.js#L236-L250

**Comment by ApolloRoad** [comment]
搞定了，谢谢
