### ISSUE TITLE
关于连接mysql数据库的疑问

### ISSUE THREAD

**Issue by Birjemin** [thinkjs/thinkjs#1216]
## 关于连接mysql数据库的疑问

线上的业务出现了一个诡异的情况，就是每过一段时间（大约40min maybe）,连接myql数据库特别慢，约10s的样子才会返回结果。

### ENV

OS Platform:Centos 7

Node.js Version: 10.6.0

ThinkJS Version:3.2.8

### code

```js
// 数据库配置（adapater.production.js）
/**
 * model adapter config
 * @type {Object}
 */
exports.model = {
  type: 'mysql',
  common: {
    logConnect: isDev,
    logSql: isDev,
    logger: msg => think.logger.info(msg)
  },
  mysql: {
    handle: mysql,
    database: 'xxxx',
    prefix: '',
    encoding: 'utf8',
    host: 'xxx.xxx.xxx.xxx',
    port: '3306',
    user: 'xxx',
    password: 'xxx',
    connectionLimit: 10,
    dateStrings: true
  }
};

```

### error message

```
无
```

### more description

正常的请求时会在100ms左右，可是每隔一段时间（大约40min，maybe更长一点），就会卡一下（请求时长会达到10s一下），通过日志打点（在取数据前打印出时间，读取数据之后打印出时间），发现耗时10s，初步猜测thinkjs连接数据库的逻辑是不是:数据库操作，获取连接句柄A->尝试连接->连接失败->重新创建句柄B->尝试连接。
有人遇到这种情况么？或者给予一些排查的思路~~
万分感谢~~~   ღ( ´･ᴗ･` )比心，❤️❤️都给你！！！

**Comment by lizheming** [comment]
日志里会打印每一句 SQL 的执行时间的，你看看慢的地方是那块，执行时间是多少。

**Comment by lizheming** [comment]
有很大的可能是 MySQL 查询请求并发数过多，当执行这句的时候所有的现成都被占用了，导致后面的请求在等待线程池释放线程，所以会造成这么慢的情况。看看你的 MySQL 请求并发是不是很高，如果是的话加大一下 `connectionLimit` 的值试试。

**Comment by Birjemin** [comment]
已经知道啥原因了，和代码无关，应该是网路的问题，我的代码和mysql并不是在同一台服务器，之间应该有啥配置导致了这种情况，我将代码和mysql放在同一台服务器，此情况就不会出现，跑题了跑题了，还是万分感谢！

**Comment by lizheming** [comment]
好的，此问题暂时关闭。有后续进展可以继续回复~感谢反馈~
