### ISSUE TITLE
Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value:

### ISSUE THREAD

**Issue by aidenZou** [thinkjs/thinkjs#1225]
## DESC
nickName: '🙈子凡 คิดถึงคุณ'
Error: ER_TRUNCATED_WRONG_VALUE_FOR_FIELD: Incorrect string value: '\xF0\x9F\x99\x88\xE5\xAD...' for column 'nickName' at row 1

手动执行 SQL可以保持数据到数据库。thenUpdate() 方法报错

### ENV
Mysql 字符集用的  utf8mb4

OS Platform:

Node.js Version:
node: v8.11.4

ThinkJS Version:
"@koa/cors": "^2.2.2",
"think-cache": "^1.1.0",
"think-cache-file": "^1.1.0",
"think-logger3": "^1.1.1",
"think-model": "^1.2.2",
"think-model-mysql": "^1.0.6",
"think-session": "^1.0.3",
"think-session-file": "^1.0.6",
"think-view": "^1.0.11",
"think-view-nunjucks": "^1.0.7",
"thinkjs": "^3.2.8"

**Comment by welefen** [comment]
开启下 logSql，看下控制台下打印的 SQL 语句跟你手工执行的有什么区别

**Comment by aidenZou** [comment]
谢谢，添加 charset: 'utf8mb4' 配置好使了
