### ISSUE TITLE
关于成功之后的返回三个参数

### ISSUE THREAD

**Issue by gaoyangy** [thinkjs/thinkjs#1226]
### ENV

OS Platform:

Node.js Version:
8.11.3
ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description 

我想知道this.success()能不能自定义默认errcode不是空字符串，或者可以改写this.success()方法吗？

**Comment by gaoyangy** [comment]
不好意思，可能是我描述的不够准确，我主要想在成功的是时候也返回一个默认的状态吗，而不是'',因为在调用this.success的时候只有两个参数是data,message,用时候我需要一个默认的errorno

**Comment by lizheming** [comment]
https://github.com/thinkjs/thinkjs/blob/master/lib/extend/context.js#L103 默认 success 的时候会返回 0 的错误码，不是 `''`。如果你要复写这个逻辑的话建议直接使用 Extend 直接复写 `this.success()` 方法即可。具体可参考文档 https://thinkjs.org/zh-cn/doc/3.0/extend.html

```javascript
//src/extend/controller.js
module.exports = {
  success(data, message, errno) {
    const obj = {
      [this.config('errnoField')]: errno,
      [this.config('errmsgField')]: message,
      data
    };
    this.type = this.config('jsonContentType');
    this.body = obj;
    return false;
  }
```

**Comment by lizheming** [comment]
ping @gaoyangy
