### ISSUE TITLE
关于 用接口调用 websocket 的消息通道

### ISSUE THREAD

**Issue by gaoyangy** [thinkjs/thinkjs#1227]
### ENV

OS Platform:

Node.js Version:
8.11.3
ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description 

![image](https://user-images.githubusercontent.com/23468113/44318887-43c15600-a46b-11e8-83c8-8413273b5398.png)
在上图中 如果我使用api接口调用这个action里面的websocket这个对象是错的

**Comment by lizheming** [comment]
和正常的请求不一样，websocket 进入 Action 的话是一个模拟的 http 请求，在请求中会注入 websocket 对象进入，具体可查看代码 https://github.com/thinkjs/think-websocket-socket.io/blob/master/index.js#L39-L47 了解相关逻辑

**Comment by lizheming** [comment]
ping @gaoyanggy

**Comment by peisheng** [comment]
> 和正常的请求不一样，websocket 进入 Action 的话是一个模拟的 http 请求，在请求中会注入 websocket 对象进入，具体可查看代码 https://github.com/thinkjs/think-websocket-socket.io/blob/master/index.js#L39-L47 了解相关逻辑
@lizheming I also hit this problem,can you make a solution demo
