### ISSUE TITLE
logic中，数组array参数为非必须时，并没有传该参数的情况下，解析为数组[null]

### ISSUE THREAD

**Issue by jhyvictory** [thinkjs/thinkjs#1228]
## DESC
logic中，数组array参数为非必须时，并没有传该参数的情况下，解析为数组[null]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version: 3.2.8

### logic code
```js
editAction() {
    this.allowMethods = 'post';
    let rules = {
      user_id: { string: true, required: true },
      remark: { string: true, length: { max: 32, min: 1 } },
      tags: { array: true },
      see: { int: true, in: [0, 1] },
    };
    let flag = this.validate(rules);
    if (!flag) {
      return this.fail('参数错误', this.validateErrors);
    }
  }
```
### controller代码
```js
let param = this.post();
```
### 传递的参数
{
	"user_id": "oxOWG1k1PjMDT4KC9q_aJ1rAYIlM",
	"see": 0
}
### 解析得到的参数
{ 
  user_id: 'oxOWG1k1PjMDT4KC9q_aJ1rAYIlM',
  see: 0,
  tags: [ null ] 
}
```
// your error message here
```

### more description

// your detail description

**Comment by jhyvictory** [comment]
为啥没人来解决下？ @welefen @leeight

**Comment by lushijie** [comment]
array存在一个强制类型转化，如果声明为array，最终拿到的一定是一个数组，如果数组没有值就会拿到[null]的情况

**Comment by jhyvictory** [comment]
这块能不能改下，不传的话，就不要强转了；如果传空数组[]，也不要转为[null]，而是不变，还是[]

**Comment by lushijie** [comment]
我今天晚些时候看下，现在不太方便，我得验证下空字符串的情况

**Comment by lushijie** [comment]
think-validator@1.6.4 修复。
截止到本版本，
对于 { tags: {array: true}} 规则：
如果不存在tags字段，同时tags非必填，post 内容中不会出现tags的信息；（1.6.4修复）
如果存在tags字段,tags值传了一个 '' ,这时候你会拿到 ['']（这里这样处理是有时候真的传过来空字符串，我没法区分）
