### ISSUE TITLE
两个模型互相关联问题导致死循环问题

### ISSUE THREAD

**Issue by lscho** [thinkjs/thinkjs#1231]
比如在学生表中使用`think.Model.BELONG_TO`关联班级表，然后在班级表中使用`think.Model.HAS_MANY`关联学生表，此时就会陷入无限循环。

这个算是bug还是用法不对？

**Comment by welefen** [comment]
可以设置 `relation: false` 来关闭
```js
this.relation = {
   student: {
       type: think.Model.BELONG_TO,
       relation: false // 关闭该关联模型
   }
}
```

**Comment by welefen** [comment]
更多支持的字段见： https://thinkjs.org/doc/3.0/relation_model.html#toc-548

**Comment by lscho** [comment]
明白了，感谢。。
