### ISSUE TITLE
model下的Pk不支持组合主键

### ISSUE THREAD

**Issue by imunez** [thinkjs/thinkjs#1233]
## DESC
文档上的Pk方法可以设置单个主键，但是希望能增加组合主键
### ENV

OS Platform:
mac
Node.js Version:
8.11
ThinkJS Version:
3.0
### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
是的，不支持，有需要可以换 https://github.com/thinkjs/think-sequelize
