### ISSUE TITLE
_this.mongo is not a function

### ISSUE THREAD

**Issue by l0ca1** [thinkjs/thinkjs#1240]
# DESC
在model里面使用 this.mongo提示错误
### ENV
OS Platform: windows

Node.js Version: 9.4

ThinkJS Version: 3

### code

```js
module.exports = class extends think.Mongo {
    async getList() {
        const user = this.mongo("user");
        const data = await user.select();
        return data;
      }
};
```

### error message

```
TypeError: _this.mongo is not a function
```

### more description

// your detail description

**Comment by lizheming** [comment]
`think-mongo@1.0.9` have add this alias method, please upgrade to this version.

**Comment by l0ca1** [comment]
ok ！ thank you
