### ISSUE TITLE
关于定时任务 crontab 格式配置，在mac配置无效

### ISSUE THREAD

**Issue by basillee** [thinkjs/thinkjs#1243]
## DESC
关于定时任务 crontab 格式配置，在mac配置无效
### ENV

OS Platform:
Mac
Node.js Version:
v8.11.2
ThinkJS Version:
3.0
### code
module.exports = [{
    // interval: '10s',
    cron: '0/1 * * * *  /bin/sh ',
    immediate: true,
    handle: () => {
      //do something
      console.log('crontab handler.');
      
    }
  }, {
    cron: '0/1 * * * *',
    // interval: '3s',
    immediate: true,
    handle: 'http://127.0.0.1:8360',
    type: 'all'
  }]
```js
// your code here
```

### error message
无法执行crontab 格式任务。
```
// your error message here
```

### more description

// your detail description

**Comment by basillee** [comment]
crontab 格式理解不到位，问题已经解决。

测试每分钟执行一次定时任务代码如下：
module.exports = [{
    // interval: '10s',
    cron: '*/1 * * * *',
    immediate: true,
    handle: () => {
      //do something
      console.log('crontab handler.');
      
    }
  }, {
    cron: '*/1 * * * *',
    // interval: '3s',
    immediate: true,
    handle: 'http://127.0.0.1:8360',
    type: 'all'
  }]

注意：
是 */1 不是 0/1.

总结：
crontab格式的定时任务相比较interval  时间间隔配置更加灵活方便。

**Comment by junmaqiang** [comment]
我也是mac系统下,但我这个配置真无效
```
cron: '38 14 * * *'
    {
        cron: '38 14 * * *', // 每日14:38 执行本任务
        handle: 'v1/crontab/init',
        type: 'one',
        enable: true,
    },
```

其实我就是系统每天下午14:38分的时候执行一初始化任务;
伙伴们看看,我这个配置有问题吗?

**Comment by lizheming** [comment]
cron 格式没问题，你的 handle 路径是对的么？直接用 URL 访问能访问到么。如果确认没问题请提供下最小可复现代码。

**Comment by junmaqiang** [comment]
反复尝试多次后发现格式没问题, 问题出在保存后没有重启thinkjs服务
现在可以了!   @lizheming
