### ISSUE TITLE
可否为think-mongoose的types.d.ts文件添加find等接口，在ts下会报错找不到方法。

### ISSUE THREAD

**Issue by wurining** [thinkjs/thinkjs#1247]
## 描述
使用typescript语言开发时，如代码部分，使用think-mongoose包会出现下面问题。
### 环境
OS Platform:
Mac os v10.13.6
Node.js Version:
v8.11.3
ThinkJS Version:
v3.2.3
### 代码

```js
import PortalPostModel, { IPortalPostModel } from '../model/portalpost';

/// ...

 async indexAction () {
        const portalPostModel = this.mongoose('PortalPost') as PortalPostModel;

        const new_post = {
            title  : '测试',
            content: '<p>测试</p>>',
            order  : 1,
            status : 'published',
            more   : {},
        } as  IPortalPostModel;
        const result = await portalPostModel.create(new_post);  //<=====此处create报错

        const data = await portalPostModel.find({  //<=====此处find报错
            order:1
        });
        return this.success(result);
    }
```

### 错误信息
> Error:(22, 46) TS2339: Property 'create' does not exist on type 'default'.
> Error:(26, 44) TS2339: Property 'find' does not exist on type 'default'.

**Comment by lizheming** [comment]
That's because module doesn't import mongoose `d.ts` file yet. We have figured out how to resolve this problem, and @SijieCai will fix it in this weekend. Than you for your reply.

**Comment by SijieCai** [comment]
changes on think-mongoose 1.1.1 @wurining
