### ISSUE TITLE
初学者,新建了一个restful Api的问题

### ISSUE THREAD

**Issue by wenner** [thinkjs/thinkjs#1251]
## DESC
通过官方文档新建了一个 resuful api  

> thinkjs controller test -r

然后我按文档修改了router

> ['/test/:id?', 'rest'], // 第三种方式

然后再次

> npm start

访问对应的url

>   think-router matchedRule: {"match":{"keys":[{"name":"id","prefix":"/","delimiter":"/","optional":true,"repeat":false,"partial":false,"asterisk":false,"pattern":"[^\\/]+?"}]},"path":"test","method":"REST","options":{},"query":{}} +3s
  think-router RouterParser: path=/test, module=, controller=test, action=get, query={} +1ms

这个说明应该是路由生效了...然后后面就出现了错误

> { Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)

这个应该是连接mysql的问题....可是我只是个测试..不需要这些...

我想..是不是吧这个注释掉就可以....然后我又找文档...并不知道去那找...包括 src/config/extend.js , 包括config....
我吧config中的注释掉..报错..吧extend中的注释掉..还是报错

然后发现,默认的index哪里是没有问题的..那么一定这个新建的controller发生的问题...
看rest.js...吧constructor中注释掉

>    //this.modelInstance = this.model(this.resource);

然后再次访问...getAction的错误

> Cannot read property 'select' of undefined

那么,想问一下...我该怎么做?
比如我就像实现一个 到对应的action返回一段json...这种呢:(

### ENV

OS Platform: win10 professinal

Node.js Version: v10.3.0

ThinkJS Version:  2.2.5

**Comment by lizheming** [comment]
RESTful API usually relates with database, so we put database handle in CURD ad default behavior. If you want create RESTful URL without it, just don't extend `rest.js` in your controller.

```js
module.exports = class extends think.Controller {
  getAction() {
    return this.success('getAction');
  }
  postAction() {
    return this.success('postAction');
  }
  putAction() {
    return this.success('putAction');
  }
  deleteAction() {
    return this.success('deleteAction');
  }
}


```

**Comment by wenner** [comment]
好的,了解了...
不过感觉不是很友好,尤其对新手 :(
是不是可以加参数建立空的action

**Comment by lizheming** [comment]
You can use `thinkjs controller test` to create empty crontroller
