### ISSUE TITLE
在服务器上使用生产环境无法访问static目录的问题

### ISSUE THREAD

**Issue by noderex** [thinkjs/thinkjs#1256]
在我本机开发环境下，使用webstorm启用development和production文件都可以。
但是用命令node production.js就无法访问，浏览器一直转圈，服务器好像进入死循环了。
但是在服务器上执行命node production.js，访问127.0.0.1:8360，可以访问到接口，但是访问不了static目录。显示出来的页面，没有加载css、图片、Js，因为static目录无法访问。

### ENV

OS Platform: windows server 2012

Node.js Version:8.12

ThinkJS Version:3

{ NotFoundError: url `/static/js/jquery.scrollLoading.js` not found.
    at Object.throw (C:\nodeapp\picsite\node_modules\koa\lib\context.js:96:11)
    at beforeTrace.then.then (C:\nodeapp\picsite\node_modules\think-trace\lib\in
dex.js:33:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  message: 'url `/static/js/jquery.scrollLoading.js` not found.' } { request:
   { method: 'GET',
     url: '/static/js/jquery.scrollLoading.js',
     header:
      { host: 'localhost:8360',
        connection: 'keep-alive',
        'user-agent': 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.
36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36',
        accept: '*/*',
        'accept-encoding': 'gzip, deflate, br',
        'accept-language': 'zh-CN,zh;q=0.9' } },
  response:
   { status: 404,
     message: 'Not Found',
     header: { 'x-powered-by': 'thinkjs-3.2.8' } },
  app: { subdomainOffset: 2, proxy: true, env: 'production' },
  originalUrl: '/static/js/jquery.scrollLoading.js',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/deploy.html#toc-aaf

**Comment by noderex** [comment]
感谢
