### ISSUE TITLE
think-model-abstract不支持blob数据插入和更新

### ISSUE THREAD

**Issue by wxhuang** [thinkjs/thinkjs#1259]
以前我用mysql或者mysql2库，可以使用buffer类型插入或更新到数据库的blob类型字段中。
不知你们设计model的时候基于什么原因考虑，这个featrue似乎没加上去。
如果需要这个featrue，我可以提个PR。

**Comment by welefen** [comment]
没支持主要考虑到：1、支持 buffer 很多校验的地方要考虑比较麻烦，blob 格式数据使用率很低  2、model 的 cache 功能会有问题。

你是什么场景要用 blob 来存数据呢？

**Comment by wxhuang** [comment]
我们的业务需要保存一些几K大小的二进制数据，业务规模不大所以打算直接把数据存数据库这样子。
你的问题可否详细说明一下？

**Comment by wxhuang** [comment]
[我对这部分的改动](https://github.com/wxhuang/think-model-abstract/commit/a8fdb345791fed345d30549a66b7861caff5e9d6)

**Comment by welefen** [comment]
@wxhuang 你发个 pr 吧，我们先合进去

**Comment by welefen** [comment]
+ think-model-abstract@1.4.0

**Comment by welefen** [comment]
+ think-model-abstract@1.4.0
