### ISSUE TITLE
并发高经常出现Pool is closed问题

### ISSUE THREAD

**Issue by 1349927591** [thinkjs/thinkjs#1262]
![image](https://user-images.githubusercontent.com/44162286/46946455-5c846b80-d0aa-11e8-8c59-44bab8c47733.png)
think-instance模块每个ip访问一个接口就创建一个连接池,如果一个子进程同时接到11个请求，会导致其中一个请求出现Pool is closed错误，希望官方能提出个好的方案

**Comment by welefen** [comment]
@1349927591 传进来的配置有动态变化的值么？可以把配置打出来看看

**Comment by 1349927591** [comment]
有,config参数的的ctx里面的ip和path有变化

**Comment by 1349927591** [comment]
因为是根据参数生成md5的，所以只要同一个子进程同时接到11个不同ip或者同ip不同接口的请求,而且有一个是比较慢的操作,就会触发Pool is closed错误.
而且,我发现他是将对象转为数组,并且将第一个连接池关闭,这很可能会因为当前的连接池生成的md5刚好排在第一个而触发Pool is closed错误,望知悉

**Comment by 1349927591** [comment]
不好意思，真正的原因找到了，是有个同事在config里面写了其他参数进去，抱歉了
