### ISSUE TITLE
为指定路由配置中间件

### ISSUE THREAD

**Issue by csm0912** [thinkjs/thinkjs#1266]
## DESC
脚手架创建的项目，自定义了一个test中间件(/src/middleware/test.js)，src/config/middleware.js配置了：
{
    handle: "test",
    enable: isDev
  }
但是发现在html中引入的/static/css/index.css也执行了该中间件，可以屏蔽静态资源执行中间件吗
另一个问题，如何为指定路由指定中间件。
比如/home和/user，有一个登录拦截中间件，但是只在访问/user的时候才需要该中间件

新手一枚，感谢
### ENV

OS Platform:

Node.js Version: V8.10.0

ThinkJS Version: V3.0.0

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by welefen** [comment]
https://thinkjs.org/zh-cn/doc/3.0/middleware.html#match   可以为中间件配置哪些路由命中

**Comment by csm0912** [comment]
测试了一下，第一种路径匹配，需要路径全匹配才生效？
设置：
module.exports = [
  {
    handle: "test",
    match: "/user"
  }
...
]
当访问http://127.0.0.1:8360/user/test时，中间件test并没有生效，只有访http://127.0.0.1:8360/user时才会生效

**Comment by welefen** [comment]
@csm0912 字符串是全路径匹配，你可以配置正则或者函数

**Comment by csm0912** [comment]
了解了，感谢

**Comment by jameskid007** [comment]
### code

```js
{
    handle: 'csrf',
    options: {},
    match: /^\/admin/
}
```

### error message

#### 使用中间件koa-csrf, 放在最上面，发现所有的路由都回走csrf，无论match填什么. 这是怎么回事?
