### ISSUE TITLE
mysql 查询两个表，两个表都有status， where status=0时，报Column 'status' in where clause is ambiguous

### ISSUE THREAD

**Issue by DengRiGuang** [thinkjs/thinkjs#1267]
### ENV

OS Platform:
window10
Node.js Version:
8.11.3
ThinkJS Version:
3.0.0
### code

```js
async indexAction() {
    const page = this.get('p') || 1;
    const pageSize = this.get('s') || 10;
    const model = this.model('posts').alias('p')
      .field('p.status as s')
      .where({check: 0, access: 0, status: 0})
      .join({
        table: 'user',
        join: 'inner',
        on: ['open_id', 'open_id']
      })
      .page(page, pageSize).countSelect();
    const data = await model;
    return this.success({
      article: data
    });
  }
```

### error message

```
'status' in where clause is ambiguous
```

### more description

// your detail description

**Comment by welefen** [comment]
where 里也用别名或者加上表名

**Comment by DengRiGuang** [comment]
@welefen 我试了，还是报错
const model = this.model('posts').alias('p')
      .field(['u.nickname as name', 'title', 'author', 'content', 'record_url as voice'])
      .join({
        table: 'user',
        as: 'u',
        join: 'inner',
        on: ['open_id', 'open_id']
      }).where({check: 0, access: 0,p.status: 0})
      .page(page, pageSize).countSelect();

**Comment by welefen** [comment]
{check: 0, access: 0,p.status: 0}  这不是合法的语法，得加上引号 {check: 0, access: 0, 'p.status': 0}

**Comment by DengRiGuang** [comment]
成功了，谢谢 @welefen

**Comment by welefen** [comment]
@DengRiGuang  后面这种错误解答得收费才行，哈哈。

**Comment by DengRiGuang** [comment]
@welefen 第一次用不太会，只能一步步试，找不到只能提issue，不过真的很感谢就是了、让我入了node这个坑。^_^^_^
