### ISSUE TITLE
缓存到redis的时候，是否能够指定数据的类型呢，我发现存进去的都是string

### ISSUE THREAD

**Issue by liuhuanhui** [thinkjs/thinkjs#1268]
缓存到redis的时候，是否能够指定数据的类型呢？

**Comment by liuhuanhui** [comment]
会自动识别类型的吗？

**Comment by welefen** [comment]
底层用的是 ioredis，具体的数据类型可以看 https://github.com/luin/ioredis

**Comment by welefen** [comment]
如果你能保证保存的数据格式，redis 都是支持（底层依赖 ioredis），可以自己写个插件来操作。
