### ISSUE TITLE
急-3.0获取如何raw-body，是否需要改写payload 模块

### ISSUE THREAD

**Issue by liuhuanhui** [thinkjs/thinkjs#1271]
请问3.0获取如何raw-body？有部分相关文档嘛

**Comment by liuhuanhui** [comment]
@welefen

**Comment by welefen** [comment]
因为不知道传递过来的数据大小，默认的中间件并不会把传递过来的所有数据都保存了。
可以通过在 payload 中间件之前加个自定义的中间件来获取，如果只是部分 URL 下要获取，可以配置下 match，payload 里配置下 ignore，具体见官网文档
