### ISSUE TITLE
think-cli是不是应该更新一下？

### ISSUE THREAD

**Issue by JakeWoki** [thinkjs/thinkjs#1280]
脚手架创建的是thinkjs3.0.0，ThinkJS 3.2 开始支持了创建 TypeScript 类型的项目，是不是应该更新下？

**Comment by lizheming** [comment]
脚手架模板所有的依赖都是 `^3.x.x` 开头的，中版本依赖会自己更新。创建 ts 项目使用如下命令。
```shell
thinkjs new demo typescript
```
