### ISSUE TITLE
file缓存和redis缓存同时使用，如何设置默认缓存类型

### ISSUE THREAD

**Issue by liuhuanhui** [thinkjs/thinkjs#1281]
file缓存和redis缓存同时使用，缓存的时候默认会使用那个缓存？比如sql查询缓存的时候？

**Comment by liuhuanhui** [comment]
> 文件缓存和Redis的缓存同时使用，缓存的时候默认会使用那个缓存？比如SQL查询缓存的时候？

**Comment by lizheming** [comment]
默认 type 指的是什么就是什么。我理解应该不存在你所谓的两个缓存同时使用，只是你写了两个配置，支持你切换而已。

**Comment by liuhuanhui** [comment]
嗯 我是想能不能不指定type的是时候默认是redis

**Comment by lizheming** [comment]
那你就设置默认的 type 是 redis 就好了。

**Comment by liuhuanhui** [comment]
好 谢谢~
