### ISSUE TITLE
定时任务crontab，可以通过GET方式定时调用restful接口吗？默认是CLI

### ISSUE THREAD

**Issue by songhongjiang** [thinkjs/thinkjs#1283]
定时任务crontab，可以通过GET方式定时调用restful接口吗？crontab默认是CLI类型，可以设置为GET或者POST吗？

**Comment by songhongjiang** [comment]
@lizheming 您好，我按照提示，没成功，路由写得有问题？谢谢
router.js
module.exports = [
    [/\/api\/(\w+)(?:\/(\d+))?/, 'api/:1?id=:2', 'rest']
];

crontab.js
module.exports = [{
    interval: '5s',
    immediate: false,
    enable:true,
    handle: '/api/srv?id=3&_method=get',
    type: 'all'
}]

**Comment by lizheming** [comment]
不需要配自定义路由

**Comment by songhongjiang** [comment]
@lizheming 删了也不行啊，感觉没有起作用

**Comment by lizheming** [comment]
看更新内容
