### ISSUE TITLE
think-cache-redis有提供发布和订阅吗

### ISSUE THREAD

**Issue by liuhuanhui** [thinkjs/thinkjs#1284]
think-cache-redis有提供发布和订阅吗

**Comment by lushijie** [comment]
https://github.com/thinkjs/think-cache-redis/blob/master/index.js

**Comment by liuhuanhui** [comment]
有点绕，think-cache-redis封装think--redis封装ioredis

**Comment by liuhuanhui** [comment]
已经使用ioredis
