### ISSUE TITLE
typescript 官网文档问题

### ISSUE THREAD

**Issue by meltifa** [thinkjs/thinkjs#1295]
对于需要定义参数实例化的service，文档上的示例并不能使定义类型生效（编辑器里看不到参数的类型）
是不是可以考虑下修改示例，直接用new来实例化service？这样语法上也更简洁些

**Comment by lizheming** [comment]
可以呀，ts 对于动态引用的确不太友好，欢迎修改

**Comment by SijieCai** [comment]
Use new to create service will create instance each time, FYI.
