### ISSUE TITLE
mysql问题

### ISSUE THREAD

**Issue by Ailein** [thinkjs/thinkjs#1296]
### ENV

OS Platform: 

Node.js Version: 8.12.4

ThinkJS Version:thinkjs 3.2.9

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description 
作者你好，我想问下如果真正部署到服务器了，mysql 并发上来了，达到了最多连接数，这个时候可以从哪里知道错误，有没什么可以监听到这个错误的地方？

**Comment by welefen** [comment]
如果请求量比较大的话，可以适当调大 connectionLimit 配置

**Comment by Ailein** [comment]
好的，感谢
