### ISSUE TITLE


### ISSUE THREAD

**Issue by chigco** [thinkjs/thinkjs#1297]


**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/extend.html#toc-e4e

**Comment by chenyuncai** [comment]
这个文档的最后的常见问题里，介绍到扩展函数重名的情况，所以你可以直接自己写一个success和fail扩展，覆盖掉系统默认的 @chigco

**Comment by chigco** [comment]
@chenyuncai 


按照文档覆盖success函数，内部直接 return this.ctx.success(data,message);
发现不行，断点看了下，进入了node_modules\thinkjs\lib\extend\context.js 
在this.type = this.config('jsonContentType'); 的时候飞了，是少了什么东西吗？

**Comment by caffreycc** [comment]
尝试一下**middleware** ? 
1、写一个自定义中间件，格式如下：
`module.exports = (options, app) => {
  // 处理response 响应的中间件
  return (ctx, next) => {

  }
}`
2、然后在 _**sr/common/config/middleware.js_**中新增自定义中间件；

**应该著已中间件的顺序！！**

添加一个自定义的中间件，处理/过滤/新增 所有的response 响应。

写惯了django , 这是我觉得可行的最快的方式了，

thinkjs 的中间件思维和python 的 django 框架原理相似。
