### ISSUE TITLE
nunjucks模板里面 怎么直接输出json 或者数组

### ISSUE THREAD

**Issue by Ailein** [thinkjs/thinkjs#1299]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
var data = "{{datas | safe}}";
var data2 = {{datas | safe}};

console.log(data);
console.log(data2);
```

### error message

```
// your error message here
```

### more description

// your detail description 
这两种都不行，有什么办法可以输出吗

**Comment by welefen** [comment]
最简单的办法就是在 controller 中把 JSON.stringify 后的值传递到模板中。如：

```js
this.assign('data', JSON.stringify(data));
```

模板中用下 safe，如：

```
var data = {{data | safe}};
```

**Comment by Ailein** [comment]
谢谢，解决了
