### ISSUE TITLE
关于 think-logger 使用问题

### ISSUE THREAD

**Issue by Shidou** [thinkjs/thinkjs#1304]

**Comment by DickyNet** [comment]
api/src/common/config/adapter.js 配置文件里配置
logger: msg => think.logger.info(msg)这个就是自动记录所有操作数据库的sql语句

/**
 * model adapter config
 * @type {Object}
 */
exports.model = {
  type: 'mysql',
  common: {
    logConnect: true,
    logSql: true,
    **logger: msg => think.logger.info(msg)**
  },
  mysql: {
    handle: mysql,
    database: 'test',
    prefix: 'test',
    encoding: 'utf8',
    host: '10.12.134.21',
    port: '3306',
    user: 'root',
    password: '123',
    dateStrings: true
  }
};
