### ISSUE TITLE
mysql链接数不释放

### ISSUE THREAD

**Issue by Shidou** [thinkjs/thinkjs#1307]
### production

OS Platform: centos7.0(64)

Node.js Version:v8.7.0

ThinkJS Version:v3.2.10

### 

```js
 connectionLimit: 30,
```

### error message

```
// 会导致 小部分sql事务执行不了，接口等待超时。
```

### more description

除此之外，我还想问下connectionLimit这个参数，是限制最大链接数，还是代表什么意思？

**Comment by Shidou** [comment]
@welefen 成银大佬,帮忙看看

**Comment by welefen** [comment]
connectionLimit 是最大链接数，每个进程下最多会有这些连接数

**Comment by welefen** [comment]
总的最大连接数为：机器数量 * node 进程数（配置中 workers 值） * connectionLimit

**Comment by Shidou** [comment]
收到

**Comment by Shidou** [comment]
帮忙关闭下好，已解决
