### ISSUE TITLE
think.model.join主表别名的问题

### ISSUE THREAD

**Issue by noderex** [thinkjs/thinkjs#1309]
```js
this.modelName = 'admin_log';
    const data = await this.where({admin_id: 1}).join({
      table: 'admin',
      join: 'inner', // join 方式，有 left, right, inner 3 种方式
      as: 'c', // 表别名
      on: ['admin_id', 'id'] // ON 条件
    }).field('id,admin_id,c.nickname').find();
```

### more description
请问，在以上示例中，我有admin,admin_log两个表，admin_log是从表。当在做admin_log查询的时候
我希望join admin表里面的nickname字段。现在遇到的问题是，两个表都有ID字段，我想取admin_log的ID字段,框架中没有给别名，因为数据表还有前缀，也不能直接在代表中写死表名。请问该如何指定访问admin_log.id？

**Comment by noderex** [comment]
> `field('admin_log.id as aid,admin_id,c.nickname')`

感谢，如果这样写的话，我准确的表名是 fix_admin_log
但这样写的后果就是：以后我再也不能修改表的前缀了。因为业务代码里干涉了表前缀。
这应该是框架为Join的主表指定一个别名就能解决的问题吧。

**Comment by welefen** [comment]
是的

发自我的 iPhone

**Comment by noderex** [comment]
收到，感谢

> model 实例上有 alias 方法，给当前使用的表设置别名，我会这样写
> 
> ```js
> // 字段多的时候，方便检查
> const fields = [
>     'al.id',
>     'a.admin_id',
>     'a.nickname'
> ]
> const data = await this
>     .alias('al')
>     .where({ admin_id: 1 })
>     .join({
>         table: 'admin',
>         as: 'a', // 表别名
>         join: 'inner', // join 方式，有 left, right, inner 3 种方式
>         on: ['admin_id', 'id'] // ON 条件
>     })
>     .field(fields.join(','))
>     .find();
> ```
