### ISSUE TITLE
关于think-mongo的使用问题

### ISSUE THREAD

**Issue by songhongjiang** [thinkjs/thinkjs#1315]
### ENV

OS Platform:
centos7

Node.js Version:
v8.14.0

ThinkJS Version:
v3.2.10

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description 
目前think-mongo使用的是mongodb2.2.36，请问怎么把think-mongo依赖的mongodb版本换到mongodb3.1.10？

**Comment by welefen** [comment]
你可以把依赖里的 mongodb 升级下试试（估计会有兼容性的问题）。后续我们尽快升级下。

**Comment by songhongjiang** [comment]
嗯，感谢！！！
