### ISSUE TITLE
Typescript Template rest.ts getId() bug

### ISSUE THREAD

**Issue by violetice** [thinkjs/thinkjs#1316]
### ThinkJS Template is Typescript
node v10.12.0
thinkjs v3.2.10
think-router v1.3.1

### Test1
router.ts
```node
module.exports = [
  ['/api/admin_user/:id?', 'rest']
];
```

URL list
```
GET /api/admin_user  // success
GET /api/admin_user.html  // error
GET /api/admin_user/1  // success
GET /api/admin_user/1.html  // success
```

#### think-router debug `GET /api/admin_user.html` console  output
Router Parser and SQL
```
path=/api/admin_user.html, module=api, controller=admin_user, action=get, query={}
SQL: SELECT * FROM `admin_user` WHERE ( `id` = 'admin_user.html' ) LIMIT 1
```
------
### Test2
router.ts
```node
module.exports = [
  ['/api/:id?', '/api/admin_user', 'rest']
];
```

URL list
```
GET /api  // error
GET /api.html  // error
GET /api/1  // success
GET /api/1.html  // success
```

#### think-router debug `GET /api` console  output
Router Parser and SQL
```
path=/api, module=api, controller=admin_user, action=get, query={}
SQL: SELECT * FROM `admin_user` WHERE ( `id` = 'api' ) LIMIT 1
```

#### think-router debug `GET /api.html` console  output
Router Parser and SQL
```
path=/api.html, module=api, controller=admin_user, action=get, query={}
SQL: SELECT * FROM `admin_user` WHERE ( `id` = 'api.html' ) LIMIT 1
```

### Summary
Default rest.ts `getId()` need not `return last`.
No corresponding project was found in GitHub. Hope to correct.
```node
getId() {
  const id = this.get('id');
  if (id && (think.isString(id) || think.isNumber(id))) {
    return id;
  }

  return '';
}
```

**Comment by SijieCai** [comment]
Hi @violetice ，thank you for your feedback. 
Base on your description, the problem should be how to properly handle unexpected input, and it varies from project to project, fell free to modify it.
Template code, on the other hand, should cover more scenarios for easier project startup, for example not all rest id is type number. I'm going to update the logic to be more generic, just like the latest JavaScript version of [rest.js](https://github.com/think-template/standard/blob/master/template/src/controller/rest.js).
