### ISSUE TITLE
如何处理OPTIONS请求呢？

### ISSUE THREAD

**Issue by DengRiGuang** [thinkjs/thinkjs#1319]
### ENV

OS Platform:
window10
Node.js Version:
8.11.3
ThinkJS Version:
3.00
### code

```js
    base.js=>
    __before
    this.header('Access-Control-Allow-Origin', this.header('origin') || '*');
    this.header('Access-Control-Allow-Headers', 'x-requested-with');
    this.header('Access-Control-Request-Method', 'GET,POST,PUT,DELETE');
    this.header('Access-Control-Allow-Credentials', 'true');
```

### error message

```
还是会先进行一次预请求，再请求数据
```

### more description

// your detail description

**Comment by lizheming** [comment]
跨域参考文章 https://zhuanlan.zhihu.com/p/37506089

**Comment by DengRiGuang** [comment]
@lizheming 中间件我是配置了的
middleware.js=>
const kcors = require('kcors');
{
    handle: kcors, // 处理跨域
    options: {
      origin: '*',
      credentials: true,
      allowMethods: 'GET,HEAD,PUT,POST,DELETE,PATCH'
    }
  },
但是还是会先预请求啊
