### ISSUE TITLE
在model中使用think.service可能会报错，能否调整下加载model和service的顺序

### ISSUE THREAD

**Issue by zhangyanzt** [thinkjs/thinkjs#1321]
### ENV

OS Platform:Mac Mojave 10.14.2

Node.js Version:v10.13.0

ThinkJS Version:3.2.10

### code

```js

const aliPay = think.service('pay/alipay')

module.exports =  class extends think.Model {
  async getPayInfo(){
   //…
  }
}

```

### error message

```
TypeError: Cannot read property 'common' of undefined

```

### more description

即在module.exports以外初始化service，会报错，这样如果在model中有多个地方调用service就需要多次实例化，比较麻烦。
参考官方文档运行流程，加载model 文件是在service文件之前的，知道了问题原因之后，我把loader.js中加载model和service的代码调换了一下位置，问题解决了。

**Comment by lushijie** [comment]
```js
/**
 * get service
 */
think.service = (name, m, ...args) => {
  let mcls = think.app.services;
  if (think.app.modules.length) {
    mcls = think.app.services[m || 'common'] || {};
  } else {
    args.unshift(m);
  }
  const Cls = mcls[name];
  assert(Cls, `can not find service: ${name}`);
  if (helper.isFunction(Cls)) return new Cls(...args);
  return Cls;
};
```
module.exports 以外 think.service调用呀，另外你说的多次实例化什么意思，如果是个fuction，返回的时候已经是一个实例了呀。

**Comment by zhangyanzt** [comment]
> ```js
> /**
>  * get service
>  */
> think.service = (name, m, ...args) => {
>   let mcls = think.app.services;
>   if (think.app.modules.length) {
>     mcls = think.app.services[m || 'common'] || {};
>   } else {
>     args.unshift(m);
>   }
>   const Cls = mcls[name];
>   assert(Cls, `can not find service: ${name}`);
>   if (helper.isFunction(Cls)) return new Cls(...args);
>   return Cls;
> };
> ```
> 
> module.exports 以外 think.service调用呀，另外你说的多次实例化什么意思，如果是个fuction，返回的时候已经是一个实例了呀。

比如

> 引入顺序这块已经调整过一次了，但是众口难调，有些人还要在 Service 中初始化 Model，如果调整了也会有问题。所以基本上是不建议大家在 class 外部做引入，如果要在外部引入的话有两种办法，一个是不调用 `think.service` 而是使用 `require()` 的形式导入文件自行初始化。还有一种是外部声明，内部赋值，如：
> 
> ```js
> let aliPay;
> module.exports = class extends think.Model {
>   constructor(...args) {
>     super(...args);
>     aliPay = think.service('pay/alipay');
>   }
> }
> ```



> 引入顺序这块已经调整过一次了，但是众口难调，有些人还要在 Service 中初始化 Model，如果调整了也会有问题。所以基本上是不建议大家在 class 外部做引入，如果要在外部引入的话有两种办法，一个是不调用 `think.service` 而是使用 `require()` 的形式导入文件自行初始化。还有一种是外部声明，内部赋值，如：
> 
> ```js
> let aliPay;
> module.exports = class extends think.Model {
>   constructor(...args) {
>     super(...args);
>     aliPay = think.service('pay/alipay');
>   }
> }
> ```

了解了，谢谢

**Comment by zhangyanzt** [comment]
> ```js
> /**
>  * get service
>  */
> think.service = (name, m, ...args) => {
>   let mcls = think.app.services;
>   if (think.app.modules.length) {
>     mcls = think.app.services[m || 'common'] || {};
>   } else {
>     args.unshift(m);
>   }
>   const Cls = mcls[name];
>   assert(Cls, `can not find service: ${name}`);
>   if (helper.isFunction(Cls)) return new Cls(...args);
>   return Cls;
> };
> ```
> 
> module.exports 以外 think.service调用呀，另外你说的多次实例化什么意思，如果是个fuction，返回的时候已经是一个实例了呀。

比如一个model多个方法里用同一个service，想用实例一次就都能适用，但是
