### ISSUE TITLE
除了indexActtion能调用外，其他Action都报404

### ISSUE THREAD

**Issue by flftfqwxf** [thinkjs/thinkjs#1327]
## DESC
除了indexAction可以匹配到运行到，其他写的Action都报404
### ENV

OS Platform: mac

Node.js Version: 10.15.0

ThinkJS Version:

### code
![image](https://user-images.githubusercontent.com/5468564/51385902-8d69b600-1b5b-11e9-999d-a5c906b30992.png)

```js
// your code here
```

### error message

![image](https://user-images.githubusercontent.com/5468564/51386093-3b756000-1b5c-11e9-8819-01b7162a652d.png)

### more description
如果在代码中加上

 ```
   indexAction() {
        this.body = '4444444sdfsdfsdf';
    }
    loginAction() {
        this.body = '455555555555444444sdfsdfsdf';
    }
```
就始终会去调用indexAction
请问是什么原因，之前用thinkjs2.0比较多，也基于其他thinkjs3.0上开源项目上做过二次开发，这次是从新 thinkjs new xxx，发现有这种情况，看了文档完全按文档的流程做的，但是出现404，未明白什么道
// your detail description

**Comment by lizheming** [comment]
先回滚到 think-router@1.3.1 的版本，最新的 1.3.2 的版本还有点问题在修复。

**Comment by flftfqwxf** [comment]
@lizheming 好的，谢谢

**Comment by lushijie** [comment]
1.3.3 版本已发~ @flftfqwxf
