### ISSUE TITLE
把thinkjs项目打包为docker镜像,然后也启动了,就是访问不到! 

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#1328]
### Dockerfile 配置如下

```js
# 第一部分,基础镜像
FROM mhart/alpine-node:10.15.0

# 第二部分,项目依赖
WORKDIR /www
COPY ./api/package.json ./package.json
RUN npm install --production -d --registry=https://registry.npm.taobao.org

# 第三部分,项目文件拷贝
COPY ./api/src ./src
COPY ./api/production.js ./production.js

# 第四部分,项目启动
ENV DOCKER=true
EXPOSE 8016
CMD [ "node", "production.js" ]
```

### 启动容器的命令如下

```
docker run -d --name api -p 127.0.0.1:8016:8016 e46910171a11
```

下面是我访问的结果
![001](https://user-images.githubusercontent.com/1819457/51441830-d7e06380-1d10-11e9-8edd-087cf0ff2910.jpg)
下面看起来似乎容器是运行着的
![002](https://user-images.githubusercontent.com/1819457/51441840-e3cc2580-1d10-11e9-91bf-d663176731d2.jpg)

### 可宿主机上死活访问不到 这个容器服务
我本地代码开发环境和生产环境都可以访问;
放到了容器里就访问不到了!
我放到容器里面的代码是经过 npm run compile 命令编译过的
也就是 /app下面的代码, 放到容器里面的/src 里面
我尝试过更换端口位8360
也尝试过 启动容器时 不绑定127.0.0.1
也试过不用 -d 后台运行
似乎都访问不到这个容器
但是我本机mysql容器我都可以访问的噻;

**Comment by junmaqiang** [comment]
哇哦, 一大早收到Email提醒 有人回复,经过尝试并且解决问题,对于整天而言可谓是莫大的欣喜;
按照 @lizheming 您说的
配置 config.js host:0.0.0.0 果然就好了!  
感谢 公子小哥 的回复!    解决了我昨晚熬夜到2点都没解开的问题!

**Comment by junmaqiang** [comment]
这个问题是得到解决了, 我想如果可以帮到更多人的话, 再提个文档建议.
建议 把 "config.js 设置一下 host:0.0.0.0 监听任意IP的请求" 写到 https://thinkjs.org/zh-cn/doc/3.0/deploy.html 这个页面的 docker 部分;
想必日后用docker部署项目的越来越多, 他们可能也会因此困扰多时;
@lizheming

**Comment by lizheming** [comment]
OK，文档是大家都可编辑的，非常欢迎 PR。
