### ISSUE TITLE
confi中配置errnoField和errmsgField后think-trace输出404错误的时候还是使用系统默认的errno和errmsg

### ISSUE THREAD

**Issue by tjhyupo505** [thinkjs/thinkjs#1330]
### ENV

OS Platform: centos7.2

Node.js Version: v10.15.0

ThinkJS Version: 3.2.10
think-trace版本：1.0.16 

### code
在config.js中配置如下项目：
```js
errnoField: 'status', // errno field
errmsgField: 'message', // errmsg field
```

think-trace的配置中
```js
contentType 设置的是 json
```

### error message

```
confi中配置errnoField和errmsgField后think-trace输出404错误的时候还是使用系统默认的“errno”和“errmsg”
```

### more description

// your detail description

**Comment by lizheming** [comment]
It's fixed in latest version, please upgrade to think-trace@1.0.17
