### ISSUE TITLE
请教大家,我用RESTful后对请求路径还有需求如何满足

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#1332]
## DESC
我用thinkjs作为api接口中心, 路由统一用 RESTful 方式; 
但是我发现开发过程中对于一些检查,或者获取特定信息的时候需要独立路径来命名方法的时候就有点蒙圈了;

比如:
按照 RESTful 方式 
我获取用户列表用get; 新增用户用post; 修改用户用put; 删除用户用delete;

但是
我也需要获取用户的状态
也需要额外方法获取用户的积分
甚至还希望有专门的方法获取用户和其他表数据的关系

请问
我这些额外需求,需要定义专门的方法?
我得怎么做呀?
要修改路由表?
知道的伙伴给找个参考好不好, 非常感谢

**Comment by lizheming** [comment]
首先你的需求都是可以用 RESTful 路由表示出来的

- 获取用户列表：`GET /users`
- 新增用户：`POST /user/:username`
- 修改用户：`PUT /user/:username`
- 删除用户：`DELETE /user/:username`
- 获取用户的状态：`GET /user/:username/status`
- 获取用户的积分：`GET /user/:username/redeem`

其次如果你不要用 RESTful 路由的话，只要不在自定义路由里配置 rest 类型即可。

**Comment by junmaqiang** [comment]
公子小哥哥你提到关于 获取用户的状态 和 积分 的路径写法确实是我期望的,只是我不晓得要实现这样子 如何定义路由 和 控制器里面的部分!  可否指点一二 @lizheming

**Comment by lizheming** [comment]
只说这么多，剩下的自己去理解吧。

```js
[/\/user/(\w+)/(status|redeem)\??(.*+)$/, '/user/:2?:3&username=:1', 'rest']
```
