### ISSUE TITLE
think-mysql 在事务场景下可能会死锁

### ISSUE THREAD

**Issue by luckyscript** [thinkjs/thinkjs#1334]
## 描述
在日常使用中发现，如果在事务中有多个连接，会引起死锁，导致整个thinkjs应用无法再操作任何数据库。
虽然官方在文档中说明了，事务的使用需要复用连接，但是发现thinkjs2.x无此问题。如果用户未开启debug，也不会发现这个问题，排查会十分痛苦。
示例代码：
```javascript
async indexAction() {
    const model = this.model('person');
    try {
      await model.startTrans();
      const id = await model.add({ name: `liming${Date.now()}` });
      await this.model('project').add({ name: `test Trans${Date.now()}` });
      await model.commit();
      return this.display();
    } catch (e) {
      await model.rollback();
      return this.fail(e.message)
    }
  }
```
### 原因：
在npm的mysql包中发现，默认的`config.connectionLimit`为1，而在`Pool.prototype.getConnection`中，如果发现已有连接数不小于这个限制，会进入`this._enqueueCallback(cb);`
在这个callback中，只会`emit enqueue`。
在thinkjs中，触发`enqueue`也只会debug出一条信息。

### 修复方式：
在事务开启和关闭的时候加入一个变量来记录，在`getConnection`的时候，判断当前是否在事务中，并且是否已经存在连接，并且当前队列已经有连接在排队了。这时候，清除mysql连接，抛出正确的异常。

### 环境

OS Platform: macOS、centOS

Node.js Version: 11

ThinkJS Version: latest

之前试着提了pr到think-mysql包里，但是貌似没大神在关注，就先提到这里了。

**Comment by luckyscript** [comment]
https://github.com/thinkjs/think-mysql/pull/3

**Comment by welefen** [comment]
这样会有问题。如果不是复用同一个连接，中间有多个操作，当其中一个操作出现异常时，最终会执行 rollback，此时并不能把所有的操作都回滚

**Comment by luckyscript** [comment]
所以，如果发现用户没有复用同一个连接的话，应该抛出异常，而不是导致mysql操作都死锁了吧。

**Comment by welefen** [comment]
@luckyscript  + think-mysql@1.4.0 已发布新版本
