### ISSUE TITLE
thinkjs监听消息队列

### ISSUE THREAD

**Issue by songhongjiang** [thinkjs/thinkjs#1335]
想在程序启动时单独启动一个子进程监听消息队列，thinkjs只能在master中调childprocess吗？？thinkjs有实现类似agent进程的方式吗？用来去做一些后台服务，比如长连接，监听消息队列等，望大神们指教！

**Comment by lizheming** [comment]
可以放到 crontab 中做，具体可参考文档 https://thinkjs.org/zh-cn/doc/3.0/crontab.html

**Comment by songhongjiang** [comment]
谢谢
