### ISSUE TITLE
请求并发数过多后，PostgreSQL数据库不释放连接，造成大量的死连接

### ISSUE THREAD

**Issue by yitm** [thinkjs/thinkjs#1338]
有个很小的业务线，并发量一上来后，就会造成大量的死连接，程序本身并不释放，只有重启服务才会释放掉，应用程序服务器和数据库都在阿里云，但不在同一个区，走的外网建立连接，这种情况如何解决？

### ENV

OS Platform: Centos 7
Node.js Version: 8.9.4
ThinkJS Version: 3.2
PostgreSQL: 阿里云单实例1核\1G 云数据库RDS PostgreSQL 版，版本10.0

**Comment by lizheming** [comment]
`idleTimeoutMillis` 调整成 `1000` 试试？

**Comment by yitm** [comment]
> `idleTimeoutMillis` 调整成 `1000` 试试？

没具体理解到这个意思，我理解的是在adapter.production.js配置项里面的postgresql配置项，加这么一个配置，我这么做后好像没什么效果，还是会在一定的并发情况下产生死连接，积累到大量的死连接没被释放后，整个程序就不可用了。我检测到服务器内存\CPU等指标最高也只在百分之几的样子，在访问量在低谷的时候就不会产生死连接。

我还以为是应用程序访问数据库走的是外网原因，后面我切到内网的数据库连接方式也存在相同的现象。

**Comment by lizheming** [comment]
现在默认的配置里线程池最大数量是10个，应该不会有特别多的死链才对。如果找不到死链的原因的话只能从两点入手：减少线程池个数，减小线程存活时间。`idleTimeoutMillis` 是用来修改线程等待存活时间的，不过你这个是 hang 住了可能不会生效。有一个 `poolSize` 是用来修改线程池个数的，也可以试试。

**Comment by shasharoman** [comment]
我也遇到了这个问题，经过排查，发现问题的罪魁祸首是think-model-postgresql，其socket.js中使用think-debounce时未考虑连接release问题，从而出现连接没有释放，SQL执行hung住。

解决方案是在postgresql设置中禁用debounce：

```
{
    type: 'postgresql',
    postgresql: {
        user: '',
        password: '',
        // ...
        debounce: false  // 这一行可以金庸debounce特性，从而连接管理不会出现问题
    }
}
```

**Comment by shasharoman** [comment]
![image](https://user-images.githubusercontent.com/5089251/62341473-210e3d00-b516-11e9-9989-ab7701b63631.png)

上次漏了这个图，反馈到这，便于其他开发者修复问题

**Comment by DickyNet** [comment]
debounce: true 时引起的BUG还没修复么？

**Comment by lizheming** [comment]
> debounce: true 时引起的BUG还没修复么？

稍等，我处理一下，之前看同学解决了我就没关注这块了。

**Comment by lizheming** [comment]
> debounce: true 时引起的BUG还没修复么？
`think-model-postgresql@1.1.6` 发了，你试一下？

**Comment by DickyNet** [comment]
> > debounce: true 时引起的BUG还没修复么？
> 
> `think-model-postgresql@1.1.6` 发了，你试一下？

可以了，非常感谢
