### ISSUE TITLE
mysql的读写分离和事务之间的bug

### ISSUE THREAD

**Issue by luckyscript** [thinkjs/thinkjs#1341]
## DESC
最近发现数据库加了读写分离后，部分接口报错，是mysql的连接出问题了。

研究后发现，这些接口都用到了事务。

分析了一下原因，是因为开启事务的时候(await model.startTrans();)，  
 https://github.com/thinkjs/think-model-abstract/blob/master/lib/query.js#L37 这个地方的sql是undefined，导致parser里面的配置取不出来。所以，在think-mysql那里会采用默认配置。

临时解决方法是：在config外层配上默认的配置。这样至少不会被最默认的配置取代。

OS Platform: ALL

Node.js Version: 11

ThinkJS Version: latest

**Comment by luckyscript** [comment]
https://github.com/thinkjs/think-model-abstract/pull/13
尝试着改了下，调用socket函数的时候，传个字符串过去。

**Comment by lizheming** [comment]
`think-model-abstract@1.4.3` 已发，感谢反馈修复。
