### ISSUE TITLE
where条件中如果使用函数怎么封装参数为对象形式

### ISSUE THREAD

**Issue by junieHF** [thinkjs/thinkjs#1342]
### ENV

OS Platform:WIN

Node.js Version:8.9

ThinkJS Version:3.0

### code

```js
// your code here
```
let filter = {
is_delete:0
}
// 我需要添加个条件，用到函数
// find_in_set(1,tag_id)
// 我需要怎么写
### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#toc-d47 对应 EXP 条件

**Comment by junieHF** [comment]
感谢
