### ISSUE TITLE
Logic返回的错误信息可以自定义为字符串吗

### ISSUE THREAD

**Issue by junieHF** [thinkjs/thinkjs#1343]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```
现在Logic校验返回的数据是这样的
`{
    "errno": 1001,
    "errmsg": {
        "grade_id": "grade_id can not be blank"
    }
}`

但我的业务中有其他返回错误数据比如
`{
    "errno": 1001,
    "errmsg":"id重复"
}`
这就导致客户端需要判断我返回的errmsg的数据类型，然后来获取
不知道框架对logic返回的错误信息有没有自定义修改的地方
### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/logic.html#toc-212 建议多看看文档
