### ISSUE TITLE
怎么在控制台输入调试信息

### ISSUE THREAD

**Issue by aa24615** [thinkjs/thinkjs#1345]
如何在控制器使用 console.log(); 输出在命令行窗口中

**Comment by lizheming** [comment]
唔？直接使用就好了？

**Comment by aa24615** [comment]
> 唔？直接使用就好了？

就是没用啊,我才来问的

**Comment by lizheming** [comment]
具体说下你的场景怎么用的吧，直接 console.log 是可以在终端输出的。

**Comment by aa24615** [comment]
`
const Base = require('./base.js');

module.exports = class extends Base {
  indexAction() {
    console.log(123);
    return this.display();
  }
};
`

在终端看不到123

**Comment by lizheming** [comment]
访问路由了么

**Comment by aa24615** [comment]
访问了

**Comment by aa24615** [comment]
127.0.0.1:xxx/index/index

**Comment by lizheming** [comment]
那就是没访问到正确的路由没执行到这个 Action

**Comment by aa24615** [comment]
执行了,视图都出来了,怎么可能没执行到,

**Comment by luckyscript** [comment]
有没有重写console.log？
或者提供一个可复现仓库吧？

**Comment by lizheming** [comment]
创建个可复现的 demo 出来吧

**Comment by aa24615** [comment]
有了,好奇怪,估计是被刷到上面去了,没发现

**Comment by lizheming** [comment]
OK，那关闭 issue 了。
