### ISSUE TITLE
是否考虑提供单进程模式？

### ISSUE THREAD

**Issue by snadn** [thinkjs/thinkjs#1348]
thinkjs v3 强制启用了多进程模式。然而现在 docker+k8s 流行。在镜像中采用单进程似乎更合理一些。那是否有考虑提供单进程模式呢？

**Comment by lizheming** [comment]
1. 目前的流程采用单进程实现不太可能
2. docker 替代的是之前多机部署的方式，和单机多进程没有太大的冲突。

**Comment by snadn** [comment]
1. 如果要支持，改动似乎确实有点大。之前3出来的时候就咨询过这个问题，个人觉得单进程模式还是很有价值的。最近看到egg有这方面的动向，所以来问问看。
2. 如果是k8s的话，还是有些影响的吧。因为起多个实例的话，并不清楚实例是否落到同一个节点。所以将进程的控制交给部署层面似乎会更可控一些。

**Comment by lizheming** [comment]
1. 修改效果不大，暂时没这个计划
2. https://thinkjs.org/zh-cn/doc/3.0/config.html#toc-f2a 有一个 stickyCluster 的配置，能够确保落到同一个进程。
    ps. 这个问题其实没有特别大的意义，如果你觉得 ThinkJS 管理的进程无法落到同一节点，你又凭什么相信 k8s 的会落到同一个节点呢？

**Comment by snadn** [comment]
我这里说的不是请求落到同一节点。我说的是k8s的pod的分配，可能落到同一台机器。比如多进程模式，进程数同内核，如果我需要两个pod，结果又都落到同一台机器的话，显然不能达到我负载的预期。

**Comment by lizheming** [comment]
没太明白你纠结的点，ThinkJS 多进程默认是用的轮询策略，配置 stickyCluster 之后使用粘性会话策略，具体可以看 https://zhuanlan.zhihu.com/p/37921649。

**Comment by snadn** [comment]
如果我在一台4核机器上起一个服务监听8000端口，现在服务扛不住了，我在同一台机器上再起一个监听8001端口，通过前端的nginx负载。这样能达到我缓解服务压力的预期吗？应该会大打折扣吧，预期肯定是在另外一台机器上面起新的服务。
当然可以通过各种配置避免这样的情况，但是把资源分配的事交给k8s去处理，而不是由业务来关注我觉得更合理一些。即thinkjs可以做到不用关注解决性能负载的事，把这块的任务交给别的服务去做。

**Comment by lizheming** [comment]
ThinkJS 多进程模式是理论上压榨单机最大性能，可以根据你的需求去配置，默认是和内核数一致的，这个和你多机负载不冲突。另外 ThinkJS 多进程不仅仅只是为了解决负载的问题，它主要是解决了单进程时候的重启相关的问题，例如如何自重启以及平滑重启等问题。

**Comment by snadn** [comment]
关键是k8s的负载不一定是多机，可能落到同一台机器。同时thinkjs解决的这些问题，k8s也有自己的一些理念来解决。这样的话，感觉双方做的事有一些重叠。

**Comment by lizheming** [comment]
刚才举例的两个，不用到 k8s，之前 PM2 就有，但是自重启和平滑重启自己做是最优雅的，其它外部工具做因为切入不到进程内部或多或少都有点问题。k8s 的负载不一定多机，那就让它多机？没谁说它实现了你就不能实现了，这些功能都是必要的功能，不做的话就需要和外部工具强绑定了。

**Comment by snadn** [comment]
并没有说thinkjs支持了多进程不好，而是说如果有单进程模式可选，那么当我需要结合k8s使用的时候，可以有更好的选择。

**Comment by lizheming** [comment]
目前我们在线上多进程配合 k8s 使用也没什么问题，你要不喜欢自带的多进程模式可以直接设置 worker 数为 1，这样就不用考虑自带的进程管理了。
