### ISSUE TITLE
关于全局异常

### ISSUE THREAD

**Issue by oneDayGo** [thinkjs/thinkjs#1355]
我想请问一下，自定义抛出的异常如何在全局捕获呢？？

**Comment by luckyscript** [comment]
可以在middleware里捕获并处理。

**Comment by oneDayGo** [comment]
> 可以在middleware里捕获并处理。

trace里我无法得到thinkjs的实例或者this，因此我无法处理错误逻辑，请问如何在trace里得到实例呢？？

**Comment by lizheming** [comment]
> > 可以在middleware里捕获并处理。
> 
> trace里我无法得到thinkjs的实例或者this，因此我无法处理错误逻辑，请问如何在trace里得到实例呢？？

`think.app` 就是全局实例啊...

**Comment by oneDayGo** [comment]
@lizheming  我打印了think出来了，但里面好像没有控制里面的body方法,因为我想在里面组装错误信息，然后返回给客户端

**Comment by oneDayGo** [comment]
已解决了，抱歉了，是我看文档没有看仔细，中间件里面有ctx,ctx里面包含一个jsonp()的方法
