### ISSUE TITLE
thinkjs调用solr的问题

### ISSUE THREAD

**Issue by DickyNet** [thinkjs/thinkjs#1357]
如题，thinkjs中如何调用solr客户端脚本

solr包地址：https://github.com/lbdremy/solr-node-client

var solr = require('solr-client');

// Create a client
var client = solr.createClient();

// Add a new document
client.add({ id : 12, title_t : 'Hello' },function(err,obj){
   if(err){
      console.log(err);
   }else{
      console.log('Solr response:', obj);
   }
});
上面的代码，在thinkjs中如何写？ 要怎么改成await 的方式调用呢，而不是异步回调里处理调用结果？

**Comment by lizheming** [comment]
您需要在哪里使用就在哪里调用就好了，在哪里写都无所谓。我看 `solr-node-client` 似乎是支持 Promise 调用的，您可以试试。如果不支持的话可以使用 `think.promisify()` 方法包装一下，具体见文档：https://thinkjs.org/zh-cn/doc/3.0/think.html#toc-c09

**Comment by DickyNet** [comment]
嗯，可以包装了

        const client = solr.createClient(constants.solr.host, constants.solr.port, constants.solr.core, '/solr');
        client.autoCommit = true;
        const doc = {
          id: 1,
          title: ‘test title’
        };
        const solrAdd = think.promisify(client.add, client);
        const solrResult = await solrAdd(doc);
        log.info('solrResult', solrResult);
