### ISSUE TITLE
这个i18n着实在难用，可以自由选择就好了，有些小型项目未必用得上那么猛的替换

### ISSUE THREAD

**Issue by huangchunwen** [thinkjs/thinkjs#1359]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
相关 issue https://github.com/thinkjs/think-i18n/issues/2
