### ISSUE TITLE
服务端使用think-websocket-socket.io的websocket功能，浏览器总是出现No 'Access-Control-Allow-Origin' header is present on the requested resource错误

### ISSUE THREAD

**Issue by shenjackson** [thinkjs/thinkjs#1360]
## DESC
服务端使用think-websocket-socket.io的websocket功能，浏览器总是出现No 'Access-Control-Allow-Origin' header is present on the requested resource错误
### ENV

OS Platform: centos7

Node.js Version: v11.9.0

ThinkJS Version: v2.2.8

### code

```js
// your code here
```

const socketio = require('think-websocket-socket.io');
// WebSocket配置
exports.websocket = {
  type: 'socketio',
  common: {
    // common config
  },
  socketio: {
    on: true, //是否开启 WebSocket
    type: "socket.io",
    sub_protocal: "",
    handle: socketio,
    allowOrigin: '127.0.0.1:8360',  // 默认所有的域名都允许访问
    path: '/socket.io',             // 默认 '/socket.io'
    adapter: null,                  // 默认无 adapter
    messages: {
      open: 'admin/websocket/open',       // 建立连接时处理对应到 websocket Controller 下的 open Action
      close: 'admin/websocket/close',     // 关闭连接时处理的 Action
      addUser: 'admin/websocket/addUser', // addUser 事件处理的 Action
    }
  }
};
### error message
No 'Access-Control-Allow-Origin' header is present on the requested resource
```
// your error message here
```

### more description

// your detail description 
不知道如何设置头信息，this.header('Access-Control-Allow-Origin', this.header('origin') || '*');不起作用，文件结构如下
![image](https://user-images.githubusercontent.com/38517143/55644004-cc281780-57fe-11e9-813a-7eea3860eff2.png)

WebSocket配置在adapter.js文件下
![image](https://user-images.githubusercontent.com/38517143/55644057-f11c8a80-57fe-11e9-98d3-0bbea50e13c9.png)
extend.js文件配置如下：
![image](https://user-images.githubusercontent.com/38517143/55644082-02659700-57ff-11e9-9907-77cc7512d50b.png)

**Comment by lizheming** [comment]
提示信息这么清楚，不怀疑一下你的 `allowOrigin` 配置的有问题么？另外网上搜搜也能搜到答案。
https://stackoverflow.com/questions/24058157/socket-io-node-js-cross-origin-request-blocked

**Comment by shenjackson** [comment]
我是使用think-websocket-socket.io这个库，头设置不知道怎么设置，网上没有答案，其他答案都是nodejs的，

**Comment by shenjackson** [comment]
我是使用think-websocket-socket.io这个库，头设置不知道怎么设置，网上没有答案，其他答案都是socket.io的，

**Comment by lizheming** [comment]
adataper 的 `allowOrigin` 配置，截图这么大不能看不到吧？

**Comment by shenjackson** [comment]
额额，我现在删了可以了，我是按着官方来的
![image](https://user-images.githubusercontent.com/38517143/55664072-aa588000-5852-11e9-8491-9fef90e6bf2e.png)
