### ISSUE TITLE
关于定时任务的interval问题

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#1362]
这个interval是等待handle执行完以后开始计算，还是开始执行handle的时候计算？
如果是等待handle执行完以后开始计算，那我的handle是一个控制器的action方法，返回的是promise，有什么办法能等待这个promise完成以后再开始计算interval呢？

**Comment by lizheming** [comment]
目前的实现就是 setInterval，你可以设置最小粒度的间隔时间然后在 handle 外部设置一个标记变量实现，每次执行检查下该变量，执行前设置为 false 执行完毕后设置该标记变量为 true。

**Comment by KuoKongQingYun** [comment]
@lizheming 感谢，我现在也是在worker里自己手动控制了，没用那个crontab

**Comment by KuoKongQingYun** [comment]
还有个问题，如何保证只有一个worker执行
