### ISSUE TITLE
vscode 调试

### ISSUE THREAD

**Issue by magdsnail** [thinkjs/thinkjs#1363]
### ENV

OS Platform:

Node.js Version:
10.15.3
ThinkJS Version:
3.2
### code

```js
// your code here
```

### error message
F5 之后不能访问服务
```
// your error message here
```

### more description

// your detail description 

vscode 调试 thinkjs项目 无法访问http://127.0.0.1:8360/

**Comment by magdsnail** [comment]
https://thinkjs.org/zh-cn/doc/2.2/debug.html 无效

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/debug.html 3.0 的断点调试文档是这个。

**Comment by magdsnail** [comment]
> https://thinkjs.org/zh-cn/doc/3.0/debug.html 3.0 的断点调试文档是这个。
已经测试通过，好了，不好意思，是我错了，谢谢
