### ISSUE TITLE
where.update bug

### ISSUE THREAD

**Issue by js0exp** [thinkjs/thinkjs#1365]
await this.model.where({xx: 'xx'}).update(data);
本来是update 操作， 会生成select 语句

**Comment by lizheming** [comment]
请提供最小可复现的项目环境。目前还不清楚您用的是 ThinkJS 版本几。ThinkJS 3 中的代码逻辑是这样的，2 的逻辑也基本一致。

https://github.com/thinkjs/think-model/blob/master/src/model.js#L513-L538

https://github.com/thinkjs/think-model-abstract/blob/master/lib/query.js#L166-L169

https://github.com/thinkjs/think-model-abstract/blob/master/lib/parser.js#L650-L654

如果您确认是 ThinkJS 的 bug 请提供一个最小可复现的仓库给我们我们下下来本地复现一下，谢谢。
