### ISSUE TITLE
promise里面调用this.body this.successthis.json等均没有用。

### ISSUE THREAD

**Issue by wickedcode01** [thinkjs/thinkjs#1368]
rt

**Comment by wickedcode01** [comment]
promise.then()函数里面调用this.success()这些没效果

**Comment by lushijie** [comment]
当然没效果啦。把promise返回去，或者await出结果之后，再this.json返回去




| |
卢士杰
前端工程师
|
|
奇虎360奇舞团
邮箱：lushijie1218@126.com
|

签名由 网易邮箱大师 定制

在2019年04月19日 19:10，JIMMY-YEN 写道：

promise.then()函数里面调用this.success()这些没效果

**Comment by lizheming** [comment]
解决方法是楼上说的，具体原理可以看看这篇文章最后的问题部分：https://zhuanlan.zhihu.com/p/34220232
