### ISSUE TITLE
sql查询时如果.where({Task_num:['IN', list]})如果list为一个空数组会报错

### ISSUE THREAD

**Issue by klwfwdk** [thinkjs/thinkjs#1370]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
this.model('Task').where({
        Task_num:['IN', list2]
      }).select();
```

### error message
 'You have an error in your SQL syntax;│Fast-forward check the manual that corresponds to your MariaDB serv
er version for the right syntax to use near \') )\' at line 1',                                              
sqlState: '42000',                     
 index: 0,                              
sql: 'SELECT * FROM `SP_Task` WHERE ( `Task_num` IN () )' } 
```
// your error message here
```

### more description

// your detail description 
建议增加一个长度判断 如果传入数组为空直接返回空对象

**Comment by lizheming** [comment]
框架本身不太适合封装业务逻辑，尽量的把详细的报错暴露出来比较好，这样用户可以选择自己监听报错亦或是返回空数据。如果是直接返回控球率则无法判断是真的返回空还是因为报错返回的空，报错是何种错误都无法知晓。

这边给您的建议是调用之前自己判断一下比较方便，亦或是复写掉 think.Model 基类的 where 方法增加判断。

**Comment by luckyscript** [comment]
感觉可以判断一下，然后throw一个方便定位问题的error。

**Comment by klwfwdk** [comment]
已经通过判断解决了 我只是以为如果in条件为空的话返回一个空数组时一个很正常的逻辑

**Comment by lizheming** [comment]
@luckyscript 嗯，不过感觉这个报的也还挺清楚的，可以看看之后有没有类似的需求。
