### ISSUE TITLE
关于worker.js中使用异步函数的问题

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#1381]
我需要在子进程工作之前做一些初始化操作，所以需要在worker.js里增加一些初始化相关的代码，比如存取数据库，这肯定用到了异步，这就导致了一个问题，我无法保证那些异步的逻辑能按时执行，比如我重启了一下网站，我预想的是所有初始化操作完成以后，网站才开始服务，但现在的情况是，我worker里的异步代码还没执行，controller或者计划任务就可能先被执行了。

**Comment by KuoKongQingYun** [comment]
我现在想得是在global里加一个变量来表示 初始化是否完成，然后在计划任务或者controller或者中间件里加入对这个标识的判断来决定是否继续，但这样就把简单的问题复杂化了，还额外消耗性能。

**Comment by KuoKongQingYun** [comment]
worker能否设计为一个返回Promise的函数，必须等待这个Promise完成才会进入接下来的流程？

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/bootstrap.html#toc-724

**Comment by KuoKongQingYun** [comment]
@lizheming 不好意思，没看到这个地方
