### ISSUE TITLE
关于thinkjs版本更新问题

### ISSUE THREAD

**Issue by junieHF** [thinkjs/thinkjs#1382]
版本很长时间没有更新了

**Comment by lizheming** [comment]
你需要什么更新

**Comment by junieHF** [comment]
1、thinkjs有没有升级什么模块功能
2、高并发下100并发下偶尔会出现错误
Error: read ECONNRESET
      at _errnoException (util.js:1024:11)
      at TCP.onread (net.js:615:25)
之后服务就处于卡死状态
3、使用事物时如果需要使用 model对象的自定义方法时，就会出现卡死，原因是事物引起的，这个可有什么解决方法

**Comment by lizheming** [comment]
1. 暂时没有
2. 请提供最小可复现的仓库以及可复现步骤另外开 issue 讨论
3. 请升级到最新的 `think-model` 版本

**Comment by welefen** [comment]
@junieHF  现在都是按模块单独来升级的

**Comment by junmaqiang** [comment]
@welefen 大哥你博客貌似有半年没更新; Thinkhs也半年没更新, 给人一种弃婴产品的感觉, 对用户而言就是缺乏安全感.  哈哈哈

**Comment by lizheming** [comment]
@junmaqiang 是否在维护不应该是看用户的反馈是否有及时的处理么？
