### ISSUE TITLE
发送SIGUSR2 信号后，进程多了好几倍

### ISSUE THREAD

**Issue by zuoyanart** [thinkjs/thinkjs#1384]
## DESC
pm2 发送SIGUSR2 信号给thinkjs，然后运行`ps -ef | grep node`，发现进程多了好多倍，而且不会释放掉
### ENV

OS Platform: centos7

Node.js Version:
10.15.3
ThinkJS Version:
3.2.10
### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
请提供最小可复现的仓库以及可复现的步骤我们复现一下。

**Comment by zuoyanart** [comment]
找到原因了，是pm2的`    "instances": 0,`配置导致的，一个pm2任务包含了6个子thinkjs worker。性能要求不高的话配置成1就行了
