### ISSUE TITLE
think-mongoose的模型设计受限太多

### ISSUE THREAD

**Issue by webignorant** [thinkjs/thinkjs#1385]
## DESC
```js
    let schema = this.schema;
    if (!(schema instanceof mongoose.Schema)) {
      schema = new mongoose.Schema(schema);
    }
    const model = connection.model(this.tableName, schema, config.useCollectionPlural ? null : this.tableName);
```
用过mongoose都知道Scheme实例支持两个参数，第二个参数设置模型的一些options。
而演示例子却建议用户返回配置由think-mongoose的Line:3进行实例化。

吐槽原因：
1. think-mongoose不开启issues
2. 演示例子更建议直接返回Schema实例，让mongoose的用户更容易理解插件的功能。
3. 插件不要搞太多无谓的事情，应该做好包装和配置即可。

### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
    let schema = this.schema;
    if (!(schema instanceof mongoose.Schema)) {
      schema = new mongoose.Schema(schema);
    }
    const model = connection.model(this.tableName, schema, config.useCollectionPlural ? null : this.tableName);
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
1. 所有的模块都统一在 `thinkjs/thinkjs` 项目下提 issue 即可
2. 您如果觉得 API 设计的不太合理的话可以帮忙提个 PR 上来我们跟进一下，mongoose 这块我们也用的不太多
3. 这个观点我是统一的

**Comment by webignorant** [comment]
@lizheming 不知道怎么说，感觉用起来没有egg.js那种便捷。
特殊原因要求使用think.js，结果开发中要不断看底层库实现才能继续。
不知道是文档的缺陷，还是混入太多thinkphp的思路搞复杂事情了。

1. 路由分组没有，而且数组配置的方式很难看，应该再包装成调用路由函数来创建路由。
2. logic看起来是validator，搞得有点怪怪的，我原以为logic是控制器逻辑复用模块，结果看文档却是数据验证为主。我只能被迫使用service实现逻辑复用。
3. 一般项目都是三个环境，如果我没猜错，看起来加新环境就得复制多一份production.js，建议用环境变量来区分。

我是thinkjs一天新手，别嫌弃我，我只是说出最真实的使用体验

**Comment by lizheming** [comment]
1. 路由正常是不用做分组配置的，直接使用文件形式不需要配置，你要对路由进行分组就是对文件进行文件夹的整理。只是你有自定义的需求的话需要你写一下映射一下。
2. logic 就是校验层，这个名字是从 ThinkPHP 迁移过来的，用来做参数的校验、权限校验、一些和业务逻辑无关的处理，让 Controller 专心写业务。
3. 不同的环境可以有不同的操作和不同的配置，例如 development 环境会监听文件变化实时更新服务，production 环境可能需要做一些前置操作，简单的 `NODE_ENV` 变量配置可能无法完全满足。如果你的场景环境变量的形式可以满足，其实稍微改写下 production.js 的 `env` 配置为 `process.env.NODE_ENV` 即可满足你的需求。
