### ISSUE TITLE
mongoose如何随机获取指定数量的记录

### ISSUE THREAD

**Issue by hrj904064990** [thinkjs/thinkjs#1386]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lushijie** [comment]
.limit(random num) 不就可以么？？？

**Comment by lizheming** [comment]
https://stackoverflow.com/questions/24806721/mongodb-how-to-find-10-random-document-in-a-collection-of-100
