### ISSUE TITLE
官网文档例子优化

### ISSUE THREAD

**Issue by webignorant** [thinkjs/thinkjs#1387]
## DESC
框架底层已经把think作为全局变量使用，但是不建议这样使用。
建议每个controller|logic|model都明确引入think，这样才能让编辑器(例如VsCode)能自动代码提示。node开发本来就推荐模块化开发...

所有使用think的文件都加上这句引入，有惊喜
```js
const { think } = require('thinkjs');
```

### ENV

OS Platform: all

Node.js Version: all

ThinkJS Version: all

### code

```js
// your code here
// 官方例子都缺少这个
const { think } = require('thinkjs');
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
嗯，在 ts 的写法中我们就是需要每个文件引入 `import think from thinkjs` 来着。
