### ISSUE TITLE
this.session(name, undefined, options),不能通过options切换不同的session

### ISSUE THREAD

**Issue by Haiyang2017** [thinkjs/thinkjs#1388]
## DESC
think-session中
使用file存储session，方法：this.session(name, undefined, options)，设置options为：{cookie:'6e8c865e-7433-4b96-bf1b-c741e5ed91ae'},  不能生效，不能切换session文件。

场景：在非当前session中，希望通过事先存储的cookie的id，查询另外一个session中存储的信息。在session管理中，有好办法吗？要不就只能自己读文件了。

### ENV

OS Platform:Mac Os

Node.js Version:10.15.3

ThinkJS Version:3.2.10

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
session 是指会话任务，顾名思义就是指它的内容应该和当前会话有关的。如果您需要做多会话的一些逻辑的话，这边给您的建议是直接使用 file cache，没有读 cookie 的一些问题，而且后续的逻辑和 session 比较类似。https://thinkjs.org/zh-cn/doc/3.0/cache.html

**Comment by Haiyang2017** [comment]
多谢，cache确实能够解决一些问题，但是我想自己实现一个cas sso的单点登录和单点退出，感觉通过cookie的id找到session并操作它可能时需要的，比如APP1退出之后，sso要通知APP2和APP3清除局部session，有什么好建议吗？
