### ISSUE TITLE
think-redis功能太弱，demo例子真是误导人

### ISSUE THREAD

**Issue by webignorant** [thinkjs/thinkjs#1389]
## DESC
还考虑着要不要使用think-redis插件，一看源码，就写死五个可以操作的方法。
redis功能很强大，不可能只有增删改查的。
后来看一下，还好类有导出ioredis实例.。
我建议插件的readme.md还是补充一下该插件引用了ioredis，
顺道补多一个返回实例的方法，demo里面至少告诉开发者，
更多redis使用方法请参考ioredis。
目前我看来，think-redis根本不算插件，
开发者直接使用ioredis或者node_redis就行了。

### ENV

OS Platform: all

Node.js Version: all

ThinkJS Version: all

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
`think-redis` 的包装之前只是为了 cache 和 session 模块使用 redis 服务做的 adapter，也正是因为怕用户觉得功能不全所以直接导出了 ioredis 的实例。一般有 redis 特殊需求的我都建议直接使用 ioredis，或者您觉得可以的话也可以帮忙把 `think-redis` 完善一下。
