### ISSUE TITLE
能够主动监听session失效吗？

### ISSUE THREAD

**Issue by Haiyang2017** [thinkjs/thinkjs#1391]
## DESC
能够主动监听session失效吗？
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:3.2.10

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
session 失效是指什么意思？

**Comment by Haiyang2017** [comment]
我是想说会话过期，我想自己实现一个cas sso单点登录，想监视全局会话的状态，如果全局会话过期了，就通知各个应用清理局部会话。能主动监听会话的状态吗？有什么建议吗？

**Comment by lizheming** [comment]
想了下 CAS 方案在这种情况下确实是需要手工调用清除，如果是同域的情况还好说，不同域的情况的话二者的 cookie 的确没有关联，需要人工操作。建议可以试试用 redis 的订阅通知让 session 过期之后执行操作调用所有服务的登出操作。

**Comment by Haiyang2017** [comment]
好的，多谢
