### ISSUE TITLE
跪求开发者提供一个CLI调用示例

### ISSUE THREAD

**Issue by webignorant** [thinkjs/thinkjs#1392]
## DESC
看到application提供一个cli运行模式。
cli模式使用还是很有必要的，例如提供一个一次性运行工具(例如数据库迁移等等)
```js
  runInCli(argv) {
    think.app.emit('appReady');
    return mockHttp({
      url: argv.path,
      method: 'CLI',
      exitOnEnd: true
    }, think.app);
  }
```
我看cli默认的method是CLI，跪求如何指定需要调用的业务逻辑？

小弟不才，只想到mock一个url实现调用，
node index.js http://127.0.0.1:8090/v1/admin/test
但是这样肯定是404的...
```bash
$ node index.js http://127.0.0.1:8090/v1/admin/test
[2019-06-24T21:27:18.566] [19988] [INFO] - [WorkerStart]
[reqArgs] { url: 'http://127.0.0.1:8090/v1/admin/test',
  method: 'CLI',
  exitOnEnd: true }
{ NotFoundError: Not Found} { request:
   { method: 'CLI',
     url: 'http://127.0.0.1:8090/v1/admin/test',
     header: {} },
  response:
   { status: 404,
     message: 'Not Found',
     header:
      [Object: null prototype] { 'x-powered-by': 'thinkjs-3.2.10' } },
  app: { subdomainOffset: 2, proxy: false, env: 'development' },
  originalUrl: 'http://127.0.0.1:8090/v1/admin/test',
  req: '<original node req>',
  res: '<original node res>',
  socket: '<original node socket>' }
```

### ENV

OS Platform: all

Node.js Version: all

ThinkJS Version: all

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by webignorant** [comment]
在下输了，原来路由还能指定type为cli。
在下膜拜大神，看了路有源码才知道大神预留神通...

**Comment by lizheming** [comment]
`node development.js "v1/admin/test"` 直接后面跟路径就好了，这个文档都有写吧 https://thinkjs.org/zh-cn/doc/3.0/crontab.html#toc-173

**Comment by webignorant** [comment]
@lizheming 
麻烦老铁你说说，response的body都不给输出，
怎么判定任务正常完成？
```js
  if (reqArgs.exitOnEnd) {
    delete reqArgs.exitOnEnd;
    res.end = msg => {
      process.exit();
    };
  }
```

总不会加文件锁来识别吧？

**Comment by webignorant** [comment]
@lizheming 
1. 参数后面直接录入路径是错误的，直接返回404。因为Mock那里可不会自动拼接host和port，除非项目使用127.0.0.1:80去运行？
2. 建议文档更新一下，把CLI模式放到系统架构设计那里去，否则还真不容易找。
3. 使用CLI主要是为了能复用think的逻辑

**Comment by webignorant** [comment]
@lizheming 还是这样舒服多了，一个入口好管理环境
```js
/**
 * Run
 * @example node run.js development
 */

const path = require('path');
const Application = require('thinkjs');

const cliArgs = process.argv.slice(2);
// env suggest enums [ development, testing, production ]
const env = cliArgs[0] || 'development';
const rootPath = path.join(__dirname, '');

const options = {
  ROOT_PATH: rootPath,
  APP_PATH: path.join(rootPath, 'src'),
  env
};
if (env === 'development') {
  options.watcher = require('think-watcher');
}

const instance = new Application(options);
instance.run();
```

**Comment by lizheming** [comment]
1. 不需要输入 IP 和端口，命令行启动会直接启动个新的服务走后面的路由。如果有问题的话你 `DEBUG=* node development.js xxxx/xxx` 看看具体信息。
2. 众口难调，不善于搜索的话放哪里都有人说不好找，官网文档直接搜 `cli` 就能查到对应信息。
3. 略
4. CLI 相当于直接执行了一次 HTTP 请求（只是请求是内部 Mock 的），正常的输出的话都是 HTTP 的输出。而目前看来你是想在脚本中调用然后获取返回结果，脚本中执行命令的话正常的话是获取 `stdout` 的内容，所以可以内部直接 `console.log()` 外部直接获取 `stdout` 内容来确认。当然你说的文件锁也可以。

**Comment by webignorant** [comment]
@lizheming 老哥，你能跟我说，为啥cli的路由设定不能带上反斜杠在前面的，搞得有点怪怪吖...
建议优化路由匹配逻辑...
```
# 正常的路由配置
[`/api/test`, 'test/index', 'get']

# Cli的路由配置
[`cli/test`, 'test/index', 'get']
```

我之前总是404的原因，就是因为带了反斜杠在前面，所以http-mock认为我在请求本地文件。
因为这个原因，导致CLI的路由配置，也得兼容这个情况，前面不能带上反斜杠

**Comment by lizheming** [comment]
可以带 "/" 开头的，本地测试了没有问题
