### ISSUE TITLE
koa版本 Support for generators will be removed in v3.

### ISSUE THREAD

**Issue by liuhuanhui** [thinkjs/thinkjs#1394]
为什么没人提这个问题呢？

Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/blob/master/docs/migration.md node_modules/thinkjs/lib/loader.js:55:17

**Comment by lizheming** [comment]
你是用了什么 koa 的中间件么？我们官方的中间件默认都是用 `async/await` 写的，没有使用 generator 语法。

**Comment by liuhuanhui** [comment]
> 你是用了什么 koa 的中间件么？我们官方的中间件默认都是用 `async/await` 写的，没有使用 generator 语法。
我不知道诶，我这是官方创建的项目，我没用任何其他第三方中间价。
    "thinkjs": "^3.0.0",

think-cli版本2.2.8

**Comment by liuhuanhui** [comment]
> 你是用了什么 koa 的中间件么？我们官方的中间件默认都是用 `async/await` 写的，没有使用 generator 语法。

我知道了，我用了个koa-cors /抱拳

**Comment by lizheming** [comment]
好的。
