### ISSUE TITLE
thinkjs的orm可以独立出来在其他nodejs框架使用吗？

### ISSUE THREAD

**Issue by liuhuanhui** [thinkjs/thinkjs#1398]
thinkjs的orm可以独立出来在其他nodejs框架使用吗？
如在koa，express里面使用thinkjs-model 或者thinjs-mysql

**Comment by lizheming** [comment]
可以的，您直接 `reuiqre('think-model/lib/model')` 即可，具体如何实例化您可以参考下 https://github.com/thinkjs/think-model/blob/master/index.js#L27-L35 index.js 中实例化的流程。

**Comment by lscho** [comment]
刚刚测试成功了。按照 @lizheming 大佬说的方法。

先安装一下
```
npm install think-model 
npm install think-model-mysql
```

代码如下

```javascript
const Model = require('think-model/lib/model');
const mysql = require('think-model-mysql');
const config = {handle: mysql, database: 'test', user: 'root', password: '123456',prefix:''};
const user = new Model('user', config);
```
配置部分参考官网就可以
