### ISSUE TITLE
think-logger3 不兼容node v12

### ISSUE THREAD

**Issue by Adgeros** [thinkjs/thinkjs#1403]
node v12 报错信息都是打印 { inspect: [Function: inspect] }
node v10 下没有问题

**Comment by lizheming** [comment]
可否提供下可复现的仓库和步骤？我自己在本地 12.4.0 新建了一个项目测试没有复现这个问题。

**Comment by Adgeros** [comment]
> 可否提供下可复现的仓库和步骤？我自己在本地 12.4.0 新建了一个项目测试没有复现这个问题。

比如数据库连接错误

**Comment by lizheming** [comment]
我这边试了没问题？
![image](https://user-images.githubusercontent.com/424491/61341403-b48a1180-a878-11e9-9350-6323192c1ffe.png)

**Comment by Adgeros** [comment]
> 我这边试了没问题？
> ![image](https://user-images.githubusercontent.com/424491/61341403-b48a1180-a878-11e9-9350-6323192c1ffe.png)

windown 10环境，我晚上用 mac 试试

**Comment by lizheming** [comment]
这个原因主要是 log4js 使用了一个 Node 即将废弃 API 的原因，具体 issue 请查看  PR。`think-logger3@1.2.0` 发布，已经更新 log4js 到最新的版本，欢迎更新使用。最后感谢反馈。
