### ISSUE TITLE
Thinkjs3.x如何写单元测试？

### ISSUE THREAD

**Issue by fanker** [thinkjs/thinkjs#1404]
## DESC
我在给thinkjs搭建的项目写单元测试的过程中遇到了一些问题：
	
	1. 使用think.controller提示“think.controller is not a function”
	thinkjs版本：3.2.10
	单元测试工具：ava（参考https://github.com/thinkjs/thinkjs/issues/841 这个issue里面你的回答）
	表现：执行think.controller(‘a/b’)测试该controller是否存在的时候，提示“think.controller is not a function”

	2. 使用think.model获取model模块，调用该model下函数的时候提示“model.xxx is not a function”
	thinkjs版本：3.2.10
	单元测试工具：ava（参考https://github.com/thinkjs/thinkjs/issues/841 这个issue里面你的回答）
	表现：调用该model下函数的时候提示“model.xxx is not a function”
### ENV

OS Platform:
MacOS
Node.js Version:
v10.16.0
ThinkJS Version:
3.2.10
### code

```js
const { expect } = require('chai');
const it = require('ava');
const path = require('path');

require(path.join(process.cwd(), 'development.js'));

it('first test', () => {
  const indexController = think.controller('ajax/index');
  expect(indexController).to.be.an('object');
});

```

### error message

```
Error: think.controller is not a function
```

### more description

1. `think.model("xxx").fn()`方式调用model模块里面函数的时候，提示`think.model("xxx").fn is not a function`。
2. 只能使用`ava`来写测试，可否使用`mocha`或者`jest`来写thinkjs的单元测试呢？
3. 使用cli初始化的demo是用mocha写的单元测试，但是thinkjs版本是v2.x，升级到v3.x之后就报错了`TypeError: thinkjs.load is not a function`

**Comment by welefen** [comment]
看下这个 issue， https://github.com/thinkjs/thinkjs/issues/841

**Comment by shasharoman** [comment]
借楼主宝地咨询个问题，目前项目启动时每个worker有初始化动作(db、redis连接，数据库内容等)，这个过程可能需要10-30s，那么在结合ava框架测试时，有没有好的办法让thinkjs初始化完成后再运行测试用例？

**Comment by fanker** [comment]
> 看下这个 issue， #841

我是参考issue[#841](https://github.com/thinkjs/thinkjs/issues/841)里面的demo来写的，但是执行`think.model('ajax/group').fn()`的时候提示`fn is not a function`，打印出来的`think.model('ajax/group')`的值为：
```js
Model {
  config:
   { logConnect: true,
     logSql: true,
     logger: [Function: logger],
     handle:
      { [Function: Mysql]
        Query: [Function: MysqlQuery],
        Schema: [Function: MysqlSchema],
        Parser: [Function: MysqlParser] 
   },
     loginname: 'fanker',
     database: 'test',
     user: 'root',
     password: 'root',
     host: '127.0.0.1',
     port: 3306,
     connectionLimit: 5,
     prefix: 't_apg_',
     Appid: 12345,
     SecretID: '***',
     SecretKey: '***',
     cl5: '123:123',
     type: 'mysql' },
  modelName: 'group',
  options: {},
  _cacheConfig:
   { type: 'file',
     file:
      { timeout: 86400000,
        handle: [Function: FileCache],
        cachePath: '/Users/fanker/Documents/gitcode/dev/demo/runtime/cache',
        pathDepth: 1,
        gcInterval: 86400000 
       }
    },
  [Symbol(think-model-relation)]:
   Relation { model: [Circular], relation: {}, relationName: true },
  [Symbol(think-models)]: {} 
}
```

**Comment by welefen** [comment]
@fanker 我新建了个 demo 项目测试了下，正常。
你的项目 package.json 里的 scripts 下是 `"test": "THINK_UNIT_TEST=1 nyc ava test/ && nyc report --reporter=html",` 这样么？

**Comment by welefen** [comment]
@shasharoman 连接会这么慢？ 单元测试一般是测试逻辑，可以把数据库之类的连接模拟掉

**Comment by shasharoman** [comment]
> @shasharoman 连接会这么慢？ 单元测试一般是测试逻辑，可以把数据库之类的连接模拟掉

多谢你的回答，我认为你说的对，单元测试环境问题不应该那么复杂。
目前网路没问题的话，初始化过程挺快，所以delay 1-3s执行ava能解决问题。

**Comment by fanker** [comment]
> @fanker 我新建了个 demo 项目测试了下，正常。
> 你的项目 package.json 里的 scripts 下是 `"test": "THINK_UNIT_TEST=1 nyc ava test/ && nyc report --reporter=html",` 这样么？
> 
> 通过 `thinkjs new demo standard` 新建个 demo 项目试试

@welefen 
1. scripts 下是 `"test": "THINK_UNIT_TEST=1 nyc ava test/ && nyc report --reporter=html"` 。
2. `think.model('ajax/group')`这种方式获取不了model下的函数，改成`think.model('group', {}, 'ajax');`就可以了。
3. `think.controller(xx)`这种方式获取不了controller实例，想请教一下，controller下的模块要怎么写测试用例?

**Comment by lizheming** [comment]
@fanker Controller 实例是与请求息息相关的，而请求的数据实际上会经历多个 middleware 处理，所以并不能简单的提供 `think.controller` 这种方式快速去实例化。如果你做的是单元测试，那正常的是你 mock 一个 ctx 的对象，然后把你的 controller 文件 require 进来直接 `new controller(ctx)` 进行实例化。

**Comment by fanker** [comment]
> @fanker Controller 实例是与请求息息相关的，而请求的数据实际上会经历多个 middleware 处理，所以并不能简单的提供 `think.controller` 这种方式快速去实例化。如果你做的是单元测试，那正常的是你 mock 一个 ctx 的对象，然后把你的 controller 文件 require 进来直接 `new controller(ctx)` 进行实例化。

@lizheming 好的，controller单元测试的问题我再研究研究。我这还有另外一个问题，相同的测试用例，ava可以测试通过，但是使用jest的时候，提示`  TypeError: think.model is not a function` 或者`TypeError: think.appendFile is not a function`，think对象下的功能函数几乎都不可用。

**Comment by lizheming** [comment]
@fanker 是不是缺少初始化的逻辑，本质上我们是初始化的时候判断环境变量有 THINK_UNIT_TEST 然后做一些 mock 初始化操作而不真实启动服务，这个你查一下，不行的话发一个简单可复现的 demo repo 我们看一下吧。

**Comment by fanker** [comment]
> @fanker 是不是缺少初始化的逻辑，本质上我们是初始化的时候判断环境变量有 THINK_UNIT_TEST 然后做一些 mock 初始化操作而不真实启动服务，这个你查一下，不行的话发一个简单可复现的 demo repo 我们看一下吧。

@lizheming 
下面是一个小demo，用`jest`来跑测试用例
```
// /src/ajax/model/group.js
const { think } = global;
module.exports = class extends think.Model {
  get pk() {
    return 'Fid';
  }
}
```
```
// /test/group.test.js
const { expect } = require('chai');
const path = require('path');

require(path.join(process.cwd(), 'production.js'));

describe('group test', () => {
  it('检测pk值为Fid', () => {
    const model = think.model('group', {}, 'ajax');
    const res = model.pk;
    expect(res).to.equal('Fid');
  });
})
```
```
// package.json
{
  ...,
  "scripts": {
    test: "jest"
  },
  "dependencies": {
    "thinkjs": "^3.0.0",
    ...
  },
  "devDependencies": {
    "chai": "^4.2.0",
    "jest": "^22.0.4",
    ...
  }
}
```
执行`npm test`的时候会报错，` TypeError: think.model is not a function`

**Comment by lizheming** [comment]
@fanker  scripts 是 `THINK_UNIT_TEST=1 jest`，少了一个环境变量的配置哦。

**Comment by fanker** [comment]
> @fanker scripts 是 `THINK_UNIT_TEST=1 jest`，少了一个环境变量的配置哦。

@lizheming 试了一下，执行`jest`之前，加上`THINK_UNIT_TEST=1`，测试用例运行成功。

**Comment by lizheming** [comment]
@fanker 嗯，下个版本我们加上了 jest 环境探测的支持，可以不用写这个环境变量了，具体可以看 #1408 这个 PR。
