### ISSUE TITLE
think-model-sqlite 无法安装

### ISSUE THREAD

**Issue by skyearthfeng** [thinkjs/thinkjs#1405]
## DESC
think-model-sqlite模块无法安装出错，sqlite3版本过低
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
`think-model-sqlite3@1.2.0` 已经发布，你可以试试，感谢反馈。
