### ISSUE TITLE
thinkjs+nuxtjs，前端能够访问到后端接口，但是无法返回json数据

### ISSUE THREAD

**Issue by hrj904064990** [thinkjs/thinkjs#1406]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code
```js

async initMenuAction() {
  let menuList = await this.model('home/home_menu').getMenuList();
  let map = {
      menu:menuList
  };
  const userInfo = await this.session('userInfo');
  if(userInfo){
    const cookie = this.cookie('thinkjs');
    const saveCookie = await this.cache(`uid-${userInfo.id}`);
    map.userInfo = userInfo;
    console.log(cookie);
    console.log(saveCookie);
  }
  console.log(menuList);
  if(menuList){
      for(let i=0;i<menuList.length;i++){
          menuList[i].picture =Config.picturePath+menuList[i].picture;
          menuList[i].dispic =Config.picturePath+menuList[i].dispic;
      }
      this.success(map);
  }
  else{
      this.fail('请求失败');
  }
}
```

### error message

```
// your error message here
```

### more description

// your detail description 
这是我请求的接口

**Comment by lushijie** [comment]
你能贴一下你的返回数据+config/middleware.js的配置么？如果正常按理返回：
```js
{
  errno: 0,
  errmsg: "",
  data: '你的map数据'
}
```

**Comment by hrj904064990** [comment]
我知道原因了。谢了




------------------ 原始邮件 ------------------
发件人: "Shijie Lu"<notifications@github.com>; 
发送时间: 2019年7月22日(星期一) 上午10:41
收件人: "thinkjs/thinkjs"<thinkjs@noreply.github.com>; 
抄送: "sunny"<904064990@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [thinkjs/thinkjs] thinkjs+nuxtjs，前端能够访问到后端接口，但是无法返回json数据 (#1406)




你能贴一下你的返回数据+config/middleware.js的配置么？如果正常按理返回：
 {   errno: 0,   errmsg: "",   data: '你的map数据' }
