### ISSUE TITLE
think-cache & think-debounce的一个缺陷

### ISSUE THREAD

**Issue by shasharoman** [thinkjs/thinkjs#1407]
## think-cache & think-debounce的一个缺陷

起因是系统中一个接口经常504，最终定位到与think-cache有关，复现代码如下：

``` javascript
await think.cache('key', async () => {
    await think.cache('key', 'value');
    await think.cache('key'); // if cache miss, this line will never return
}); // 内部不返回，导致外部同样hung住
```

固然代码本身写的不合理，因为think.cache使用function作为第二个参数时只需要返回最新的value，但写出这种代码不应该导致hung住，并且后续think.cache('key')的调用都会如此（相同key）。

最终我发现BUG产生的原因是由于`think-debounce`出现嵌套调用时，内部的状态出错导致return的Promise永远处于pending状态，触发代码如下：

``` javascript
const Debounce = require('think-debounce');
let d = new Debounce();

(async () => {
    setTimeout(() => {
        console.log('timeout');
        process.exit(1);
    }, 30000);

    await example('key');
    console.log('just ok'); // this line will not be executed
})();

async function example(key) {
    return d.debounce(key, async () => {
        await d.debounce(key, async () => {
            return 'ok';
        });

        return 'ok';
    });
}
```

更本质的问题原因出现在`think-debounce`的[line-19](https://github.com/thinkjs/think-debounce/blob/master/index.js#L19)与[line-36](https://github.com/thinkjs/think-debounce/blob/master/index.js#L36)，嵌套调用导致双方出现了相互等待，从而出现“死锁"现象，后续同实例相同key的debounce操作都将被hung住。

我遇到并发现了上述问题，是否应该定义为BUG交由库的维护者来判断，因为think-debounce没有开放issue，所以发在这里。

**Comment by lizheming** [comment]
感觉不太好解决，debounce 合并请求的时候是按照 key 来的，如果发生嵌套似乎并不能被知晓。只能先强调不要做嵌套使用了…

**Comment by welefen** [comment]
@shasharoman  debounce 的设计是为了提升在高并发下相同 key 的 cache 性能，并且 think.cache 方法第二个参数为 function 时不应该出现 cache 相关的逻辑（应该是从其他地方获取新的数据）。

当时真要这么写的话确实会有问题，不过这个问题解决的话只能去掉 debounce 的策略了，这样会有些得不偿失。所以这个问题暂不处理，我们在文档上加重说明吧。

如果非要有依赖，不用第二个参数为函数的方式就可以了。

```js
coonst value = await think.cache('key');
if (!value) {
    await think.cache('key', 'value');
    await think.cache('key');
}
```

**Comment by shasharoman** [comment]
@welefen 间接原因是由于代码编写不合理，直接原因如我前文所述，但也如@lizheming  所讲：”这个问题暂时不好从根本上解决“，目前在文档中给开发者一个tips是可接受的做法，避免他们写出同样的代码，issue你们可以在更新文档后close。
