### ISSUE TITLE
如何在ts项目里使用extend？

### ISSUE THREAD

**Issue by meltifa** [thinkjs/thinkjs#1412]
https://thinkjs.org/zh-cn/doc/3.0/extend.html

文档里缺少ts的内容，比如我想扩展context，并且想让this含有正确的context提示，我是这么写的
```javascript
import { Context } from 'thinkjs'
interface myContext extends Context {
  myProp: string
}

export default {
  get myProp() {
    return this.
  }
} as myContext
```
访问this没有代码提示，问题出在哪呢？

**Comment by meltifa** [comment]
```javascript
declare module 'thinkjs' {
  export interface Context {
    aaa(): void
  }
}

export default {
  aaa() {
    return '123'
  }
}
```

是不是只能这样扩展，this访问只能用于class实例里？

**Comment by lizheming** [comment]
是的，ThinkJS 扩展的定义需要包裹在 `thinkjs` module 声明里，然后在项目中 import 之后才能利用 TS 的声明合并。可以参考下 `think-model` 的写法：https://github.com/thinkjs/think-model/blob/master/index.d.ts

**Comment by meltifa** [comment]
谢谢，我这个需求还是用中间件来实现更好
