### ISSUE TITLE
think-model & think-model-postgresql 不解

### ISSUE THREAD

**Issue by shasharoman** [thinkjs/thinkjs#1413]
对think-model与think-model-postgresql不是很了解，想请教一个场景问题，假设某service中有如下代码：

``` javascript
// 下单
let order = {
    order_id: '001',
    status: 0
};
let r1 = await this.model('order').add(order);
if (!r1) {
    throw new Error('save order error');
}

// 订单被接收
let r2 = await this.model('order').where({
    order_id: order.order_id
}).find();
if (!r2 || r2.status !== 0) {
    throw new Error('order status is not pending');
}
let r3 = await this.model('order').where({
    order_id: order.order_id
}).update({
    status: 1
});

// 支付回调
let r4 = await this.model('order').where({
    order_id: order.order_id
}).find();
// 问题出在这，何种DB异常可以导致执行到这一步的时候r4为{}或者r4.status === 0
if (!r4 || r4.status !== 1) {
    throw new Error('order status is not accept');
}
```

***postgresql事务隔离级别设置的是read committed，何种DB异常或者场景可以导致r2正常但r4却是{}***

通过log我看到的状态:
``` text
timestamp: 1564714609153 r2.status: 0
timestamp: 1564714609163 r3: 0
timestamp: 1564714609176 r4.status: undefined
```

当时DB很多异常，pg_stat_activity看到大量的Lock，随后出现一堆transaction aborted，这些异常可能是系统其他地方触发了某些BUG导致，但也无法解释上述异常。

我目前能想到的一种可能是：“think-model 或者 think-model-postgresql底层对于model的一些操作合并事务comimt，r1，r2在同一个事务中，并且没有及时提交，但r3，r4处在另一个事务，所以无法读取到未提交的数据”。

上述只是我的一种猜测，想在issue这问一下此现象有没有更好的解释?

**Comment by lizheming** [comment]
我有一个问题，你的这个日志是在 SQL 执行成功之后打印的么？如果能看到结果为什么 SQL 没成功执行呢？按道理如果是有 LOCK 的话 SQL 会一直在队列中不被执行吧？

另外如果你的 r1,r2 和 r3,r4 不是在同一个接口中的话，那我感觉这个和事务的关系似乎不是非常的大。实际上这就是前者没写进去，后者自然就抛错了。如果是在同一个接口中的话，能走到 r3,r4 的话按道理 r1, r2 就执行成功了，没道理数据还没写进去的。

**Comment by shasharoman** [comment]
@lizheming 这几个步骤是我从一个接口中简化出来的用于描述问题的代码，在实际测试过程中的确出现r1，r2正常但r3，r4不正常的现象，经验判断是底层事务控制出现了问题，经过我昨天深入查看相关代码，发现一种可能：

> think-model-postgresql使用的pg库背后的pg-pool中，针对connection release有一个[error参数](https://github.com/brianc/node-pg-pool/blob/master/index.js#L249)，而think-model-postgresql使用时并没有针对处理，这可能导致一个有故障的client被归还到poll，从而导致后续的离奇问题

昨天定位问题，在think-model-postgresql中加了几行log：

``` javascript
// lib/socket.js
// L51
getConnection(connection) {
    if (connection) return Promise.resolve(connection);
    return this.pool.connect().then(c => {
        c.id = nanoid();
        log(Date.now(), c.id, 'apply'); // 我是日志
        return c;
    });
}

// L111
releaseConnection(connection) {
        // if not in transaction, release connection
        if (connection.transaction !== TRANSACTION.start) {
            // connection maybe already released, so and try for it
            try {
                log(Date.now(), connection.id, 'release'); // 我是日志
                connection.release();
            } catch (e) { }
        }
}

[QUERY](sqlOptions, connection, startTime) {
    //...
    // L133
    log(Date.now(), connection.id, sqlOptions.sql); // 我是日志
    this.releaseConnection(connection);
}
```

修改之后测试一次得到的日志文件，5w行输出有2k行可能异常，我这里贴一部分异常日志（SQL详情已经省略）：

``` text
1564746454761 -9QQy7vv8wjxBuwxRBE_j apply
1564746457416 -9QQy7vv8wjxBuwxRBE_j ROLLBACK
1564746457416 -9QQy7vv8wjxBuwxRBE_j SELECT
1564746457416 -9QQy7vv8wjxBuwxRBE_j release
1564746457416 -9QQy7vv8wjxBuwxRBE_j release

1564746453136 -JGxp_zX067HK2rG13YnP apply
1564746455565 -JGxp_zX067HK2rG13YnP ROLLBACK
1564746455565 -JGxp_zX067HK2rG13YnP release

1564746456537 -VU6wqOmeE_-TBkLkhRpf apply
1564746456543 -VU6wqOmeE_-TBkLkhRpf BEGIN
1564746456548 -VU6wqOmeE_-TBkLkhRpf INSERT INTO
1564746456551 -VU6wqOmeE_-TBkLkhRpf UPDATE
1564746459180 -VU6wqOmeE_-TBkLkhRpf UPDATE
1564746459180 -VU6wqOmeE_-TBkLkhRpf UPDATE
1564746459180 -VU6wqOmeE_-TBkLkhRpf UPDATE
1564746459180 -VU6wqOmeE_-TBkLkhRpf UPDATE
1564746459180 -VU6wqOmeE_-TBkLkhRpf release
1564746459180 -VU6wqOmeE_-TBkLkhRpf release
1564746459180 -VU6wqOmeE_-TBkLkhRpf release

1564746458037 -yki-BYT2MQgbW8Ku7i7C BEGIN
1564746458037 -yki-BYT2MQgbW8Ku7i7C apply
1564746458041 -yki-BYT2MQgbW8Ku7i7C INSER
1564746458041 -yki-BYT2MQgbW8Ku7i7C UPDATE
1564746460670 -yki-BYT2MQgbW8Ku7i7C UPDATE
1564746460670 -yki-BYT2MQgbW8Ku7i7C UPDATE
1564746460670 -yki-BYT2MQgbW8Ku7i7C UPDATE
1564746460670 -yki-BYT2MQgbW8Ku7i7C release
1564746460670 -yki-BYT2MQgbW8Ku7i7C release
1564746460670 -yki-BYT2MQgbW8Ku7i7C release
1564746463271 -yki-BYT2MQgbW8Ku7i7C ROLLBACK
1564746463271 -yki-BYT2MQgbW8Ku7i7C release

1564746448911 GwSqrd9bSNU8KoGh9kIBP UPDATE
1564746448912 GwSqrd9bSNU8KoGh9kIBP UPDATE
1564746448912 GwSqrd9bSNU8KoGh9kIBP UPDATE
1564746448912 GwSqrd9bSNU8KoGh9kIBP UPDATE
1564746448912 GwSqrd9bSNU8KoGh9kIBP release
1564746448912 GwSqrd9bSNU8KoGh9kIBP release
1564746448912 GwSqrd9bSNU8KoGh9kIBP release
```

> TIPS：项目中有使用一个pg文档中没有提到配置项[query_timeout](https://github.com/brianc/node-postgres/blob/master/lib/connection-parameters.js#L68)，在DB有压力时会使connection.query方法更频繁的出错，也就更有可能归还一个状态错误的client给pool

但从这份日志中反映出来的问题，用连接混用也难以解释，所以还在苦逼研究原因，希望这个日志能让你review这个问题时目标更明确。

**Comment by lizheming** [comment]
如果 r1, r2 正常后续不正常的话那应该是伪正常了。按道理是不会出现这种问题的，没有抛错的话可以按照你的思路在 https://github.com/thinkjs/think-model-postgresql/blob/master/lib/socket.js#L117 先在这块把错误抛出来试试。

**Comment by shasharoman** [comment]
问题的原因已经找到：“由于不恰当代码流程，导致think-model-postgresql在特殊场景下归还了一个异常状态的连接给pool”，下面举例描述所遇到的问题场景：假设需要在一个事务中执行两条SQL，service中的代码如下：

``` javascript
let m1 = this.model('table1');
let m2 = this.model('table2').db(m1.db());

try {
    await m1.startTrans();

    await Promise.all([
        m1.add({});
        m2.add({})
    ]);

    await m1.commit();
}
catch (err) {
    await m1.rollback();
}
```

这是一个初看没有毛病的代码，但`m1.add`与`m2.add`使用Promise.all方法组织会带来严重问题，最初的想法应该是觉得并行执行效率更高，但同事务中的SQL底层不能并行执行，所以这个代码无法达到目的。

解释异常产生的原因需要结合`think-model-postgresql`中连接管理相关代码，此处简单描述一遍出问题的流程：

1. 向pool申请connection，执行`m1.startTrans()`并成功返回
2. 执行`m1.add()` & `m2.add()`，pg中会维护两个`INSERT QUERY`在队列中
3. pg的QUERY执行队列正在串行执行第一条`INSERT`(`m1.add()`)时， 由于`query_timeout`逻辑触发，`m1.add()`与`m2.add()`几乎同时往外回调错误（Query read timeout）
4. 假设`m1.add()`出错被先捕捉会执行`m1.rollback()`，而**真正向DB发出ROLLBACK前，`think-model-postgresql`内部将connection.tranaction标记为END**
5. ROLLBACK被pg放入QUERY队列但未真正执行之前，`m2.add()`的错误接着被`think-model-postgresql`捕捉，由于`connection.tranaction`已经被标记成END，随后会执行`connection.release()`，**导致一个未执行COMMIT|ROLLBACK的connection被成功归还给了pool**
6. 刚才被归还的connection可能从pool中申请到用于其他写操作（INSERT，UPDATE等），这个写操作何时被COMMIT或者ROLLBACK取决于下一个使用此connection做事务操作的时机，未COMMIT之前此connection可以查询到该写操作的最新数据，而其他connection不行

回头看最初我举的例子，r1-r4的现象在上述流程中可以被完美解释，第二次贴的日志也能被解释，导致该问题的本质原因是**错误的代码导致`think-model-postgresql`归还了状态异常的连接给pool**。

除了这种的query_timeout + Promise.all误用触发，其他可能触发的场景暂时未想到，如果没有其他可能导致异常连接被正常归还给pool的流程，我认为库的维护者可以关闭这个issue。

**Comment by lizheming** [comment]
Promise.all 这个我们作为一个 badcase 收集下吧，感觉没有特别好的办法去解决这个问题，实际上是就是一个本来是先后执行的东西被搞成了同时执行，但是只接收了前者的抛错后者的抛错被业务逻辑忽略了的问题。鉴于这个写法比较少，我先关闭这个 issue，先让用户按照先后执行的逻辑去处理吧。
