### ISSUE TITLE
think-sequelize 里的sequelize还是4.x，可否升级到 5.x

### ISSUE THREAD

**Issue by 188007803** [thinkjs/thinkjs#1415]
同标题

**Comment by lizheming** [comment]
https://github.com/sequelize/sequelize/blob/master/docs/upgrade-to-v5.md 看了下升级日志，看起来直接升级版本问题不大，不过需要发一个大版本，有一些 breaking change。@lushijie

**Comment by 188007803** [comment]
希望能升个级。另外问一下，我希望把 think的官方orm 和 think-sequelize 一起用可以吗，因为我的项目之前是用官方 orm, 但有一些更高级更细腻的需求官方orm满足不了，但一下子切换orm不太可能，所以希望两个orm能共同使用，我可以逐步切换。

**Comment by lizheming** [comment]
@188007803 可以的，一个是 `this.model` 一个是 `this.sequel` 两个不冲突。

**Comment by 188007803** [comment]
谢谢@lizheming,  那 sequel的model文件，放在哪呢，放在model就和官方的orm冲突了。另外我能请教一下吗，我发现 Sequelize怎么都连不上阿里云的数据库，总是失败，不管是用think-sequlelize, 还是最新的Sequelize5,  而别的orm包括thinkjs官方orm都是可以连的，不知道您碰到过这个问题没。

**Comment by lizheming** [comment]
都放在 model 文件夹中，命名自己区别开吧。后面这个问题我没有碰到过。

**Comment by 188007803** [comment]
好的，感谢！
