### ISSUE TITLE
can not use pm2 cluster mode, please change exec_mode to fork

### ISSUE THREAD

**Issue by handoudou** [thinkjs/thinkjs#1418]
## DESC

1. 新建demo项目
2. 修改pm2.json
` "exec_mode": "cluster",`
2.  pm2 start pm2.json报错
`Error: can not use pm2 cluster mode, please change exec_mode to fork`
![屏幕快照 2019-08-27 下午5 10 10](https://user-images.githubusercontent.com/9360181/63757941-8f63d680-c8ed-11e9-9909-b579a30d3086.png)

### ENV

OS Platform: mac

Node.js Version:v10.16.1

ThinkJS Version: ^3.0.0

**Comment by lizheming** [comment]
> can not use pm2 cluster mode, please change exec_mode to fork

报错不是说的很清楚么？

**Comment by handoudou** [comment]
是不支持 cluster mode？

**Comment by lizheming** [comment]
对
