### ISSUE TITLE
关于thinkjs的计划任务

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#1419]
计划任务的interval 项是设置两次执行间的间隔，如果在这个间隔里上一次执行没有完成，就会“强行打断”，还是？
（遇到计划任务里包含事务和锁就麻烦了，还没提交或者回滚就被强行打断，直接锁死了）
我不知道具体是怎么处理那个interval的，是通过setInterval实现的吗？
现在我的计划任务是从远程服务器上同步数据到本地，每5分钟一次，但是偶尔因为网络原因5分钟内完不成，表现出来就是每次都同步不完。我尝试加了日志，发现同步到一半，就开始新的同步了。

**Comment by lizheming** [comment]
看了下代码，应该是当时就这么设计的 https://github.com/thinkjs/think-crontab/blob/master/index.js#L77 使用了 `timer.unref()` 方法取消了调用。

建议如果有这个需求的可以把 interval 时间设置长一点，毕竟如果一个间隔时间内执行不完的话很容易造成任务的堆积。当然如果非得这么短的时间的话建议不用 interval 使用 cron 形式比较好。

**Comment by KuoKongQingYun** [comment]
@lizheming 我干脆在bootstrap里的worker里，写个while死循环，配合think.timeout来实现周期执行，这样应该能实现一次任务完成以后 再间隔固定时间 再执行任务。
