### ISSUE TITLE
部分接口需要返回不同类型的json

### ISSUE THREAD

**Issue by Dpuer** [thinkjs/thinkjs#1422]
### ENV

OS Platform:

Node.js Version:8.9.1

ThinkJS Version:3.2.10

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description
在项目中有需求部分接口返回application/javascript的类型，但是think貌似只能在全局配置jsonContentType类型，不能针对指定接口返回对应类型，尝试了设置response header但是没有生效，请问有解决方案吗？

**Comment by lizheming** [comment]
controller 中直接定义 type 即可。
```js
this.ctx.type = 'application/javascript';
```

**Comment by Dpuer** [comment]
实际使用了并不可以,还是会返回application/json

`this.ctx.type = 'text/plain';`
`return this.json(data);`
![image](https://user-images.githubusercontent.com/11489830/65589027-fc38c200-dfba-11e9-829b-7aa0ecd31188.png)

**Comment by lizheming** [comment]
。。。。。https://github.com/thinkjs/thinkjs/blob/master/lib/extend/context.js#L93-L97 你先看看 `this.json()` 方法干了什么再说吧....

```js
this.ctx.type = 'application/javascript';
this.ctx.body = 'console.log('hello')';
```

**Comment by Dpuer** [comment]
OK，是我的问题，已经解决了谢谢
