### ISSUE TITLE
model多模块调用

### ISSUE THREAD

**Issue by guohuihot** [thinkjs/thinkjs#1427]
### ENV

OS Platform:
window10
Node.js Version:
node v10
ThinkJS Version:
ThinkJS v3.2
### code

```js
// 获取用户信息
    async userInfoAction() {
        await this.checkAuth()
        const model = this.mongo('users')
        const data = this.ctx.state.user
        const result = await model.where({_id: data.id}).find()

        if (!think.isEmpty(result)) {
            return this.success(result)
        }
        return this.fail('000002')
    }
```

### error message

```
model没起作用
```

### more description

// your detail description 
请问我这样调用对吗？好像没起作用
![image](https://user-images.githubusercontent.com/3119995/65382039-aac8d280-dd2f-11e9-9d9a-5c39892b6922.png)

**Comment by guohuihot** [comment]
貌似contoller要和model名称一致才可以调用

**Comment by lizheming** [comment]
稍微有点小问题，这里跨模块调用需要补充一下模块名

**Comment by guohuihot** [comment]
谢谢回答，这样是可以的，model里的代码没写好，误以为没调用

**Comment by lizheming** [comment]
好的。
