### ISSUE TITLE
请问thinkjs安装后命令无效该如何解决

### ISSUE THREAD

**Issue by zxdplay** [thinkjs/thinkjs#1431]
C:\Users\zxd2>npm install -g think-cli
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coff
eescript" (no hyphen)
C:\Users\zxd2\AppData\Roaming\npm\think-cli -> C:\Users\zxd2\AppData\Roaming\npm
\node_modules\think-cli\bin\thinkjs
C:\Users\zxd2\AppData\Roaming\npm\thinkjs -> C:\Users\zxd2\AppData\Roaming\npm\n
ode_modules\think-cli\bin\thinkjs
+ think-cli@2.2.9
updated 1 package in 161.131s

C:\Users\zxd2>thinkjs
'thinkjs' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

----------------------------------------------------------------------
安装后环境变量没有修改path，thinkjs命令无效

**Comment by lizheming** [comment]
那你加一下 path 吧，不配环境变量命令行找不到对应的命令。

**Comment by zxdplay** [comment]
加了全局路径，问题已经解决了，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Austin Lee"<notifications@github.com&gt;; 
发送时间: 2019年10月9日(星期三) 下午4:12
收件人: "thinkjs/thinkjs"<thinkjs@noreply.github.com&gt;; 
抄送: "月魂"<601908576@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thinkjs/thinkjs] 请问thinkjs安装后命令无效该如何解决 (#1431)




那你加一下 path 吧，不配环境变量命令行找不到对应的命令。
