### ISSUE TITLE
创建工程卡住了

### ISSUE THREAD

**Issue by zxdplay** [thinkjs/thinkjs#1433]
E:\H5\tests>
E:\H5\tests>
E:\H5\tests>thinkjs new luck_s

'git' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
�������ļ�
? Project name name_bac
? Project description abcdef
? Author zx
? Do you want to turn on babel? No

在最后一步卡住了

**Comment by lizheming** [comment]
Windows CMD 创建的时候会卡住这个是已知问题，不过依赖上游依赖，所以还在解决。此时直接 Ctrl+C 直接结束掉即可，不影响工程的创建。或者在 Windows 下使用 git bash 不会出现这个问题。

**Comment by zxdplay** [comment]
谢谢答复，只要不影响工程创建就ok了

**Comment by lizheming** [comment]
好的，感谢理解。
