### ISSUE TITLE
mysql唯一索引添加成功代码触发多次

### ISSUE THREAD

**Issue by limars874** [thinkjs/thinkjs#1434]
## DESC
我在mysql里面有一个表拥有一个唯一索引的字段（如unique_id），然后在thinkjs里面使用query方法，执行裸sql字符串，如 `insert ignore into uniq_test set unique_id=1 ` 。然后查看结果的affectedRows是否为1，来判断是否成功。如果成功则执行成功的语句，为0则执行失败的语句。按我的理解来说，unique_id相同的情况下（并发情况），这个成功的代码应该只会触发一次。但在实际测试中，成功的代码可能会触发多次。
之前我是在thinkjs2下面测出这样的结果，然后我又升级成thinkjs3，新建了一个纯demo项目，发现这个情况还是会出现。然后我另外直接用koa2+mysql的组合，也写了几乎相同的测试代码，affectedRows===1的情况只会出现1次（这个才是我想要的结果）。麻烦问问这个是怎么回事。

使用jmeter，并发30次访问接口，经常出现插入id相同（这个id之前数据库未写入）的情况下，打印ok不止一次的现象，两次三次四次不等。

### ENV

OS Platform:
windows10
Node.js Version:
10.15.3
ThinkJS Version:
2.2.25
3.2.10
mysql Version：
MariaDB 10.3.8
MySql 8.0

### code

```js
// 附thinkjs3测试代码：

 async uniqueAction() {
    const id = this.post('id');
    let _sql = `insert ignore into uniq_test set unique_id=${id};`;
    const res = await this.model('user').query(_sql);
    if (res && res.affectedRows === 1) {
      console.log('ok', id);
    } else {
      console.log('fail', id);
    }
    this.json(id);
  }

// koa代码：
router.post('/signup', async(ctx, next) => {
  const id = ctx.request.body.id
  let _sql = "insert ignore into uniq_test set unique_id=?;"
  const res = await model.query( _sql, [id] )
  if(res && res.affectedRows === 1){
    console.log('ok',id)
  } else {
    console.log('fail',id)
  }
  ctx.body = {
    data:res
  };
})
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by welefen** [comment]
这个情况要用 myql  模块返回的 `changedRows` 字段，不过现在读取是的 `affectedRows`，后续看怎么兼容下

**Comment by limars874** [comment]
在thinkjs群大佬的帮助下，找到原因了。因为用的query方法执行的sql，不管是thinkjs.2.x还是thinkjs3.x，这个query都有个类似缓存的机制，并发太高的时候会把上次sql执行的查询结果给返回来。所以，用execute就能避免这个问题。或者thinkjs.3.x里面，在 mysql 配置中加 debounce: false 关掉缓存机制，也能继续用query。
