### ISSUE TITLE
think.app无法正常使用 

### ISSUE THREAD

**Issue by PHPJourney** [thinkjs/thinkjs#1437]
本地项目移动到服务器后，在extend 加入websocket(think.app) model(think.app) 均提示app错误。

```bash
10|npm run begin  |   app.on('appReady', () => {
10|npm run begin  |       ^
10|npm run begin  | TypeError: Cannot read property 'on' of undefined
10|npm run begin  |     at module.exports.app (/mnt/pm2/payment/node_modules/think-websocket/index.js:7:7)
10|npm run begin  |     at Object.<anonymous> (/mnt/pm2/payment/app/common/config/extend.js:11:17)
10|npm run begin  |     at Module._compile (internal/modules/cjs/loader.js:778:30)
```

thinkjs 脚本本身错误

> thinkjs clean

```
▹▹▹▹▹ Clear the cache template...
/www/server/nvm/versions/node/v10.16.3/lib/node_modules/think-cli/bin/commands/clean.js:35
const cacheTemplatePath = path.join(config.templateCacheDirectory, thinkjsInfo.template.replace(/[\/\\:]/g, '-'));
                                                                               ^

TypeError: Cannot read property 'template' of undefined
    at Object.<anonymous> (/www/server/nvm/versions/node/v10.16.3/lib/node_modules/think-cli/bin/commands/clean.js:35:80)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/www/server/nvm/versions/node/v10.16.3/lib/node_modules/think-cli/bin/thinkjs-clean:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
`



> thinkjs sync


`
const cacheTemplatePath = path.join(config.templateCacheDirectory, thinkjsInfo.template.replace(/[\\/\\:]/g, '-'));
                                                                               ^

TypeError: Cannot read property 'template' of undefined
    at Object.<anonymous> (/www/server/nvm/versions/node/v10.16.3/lib/node_modules/think-cli/bin/commands/sync.js:33:80)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/www/server/nvm/versions/node/v10.16.3/lib/node_modules/think-cli/bin/thinkjs-sync:2:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)

```

**Comment by welefen** [comment]
把具体配置贴下

**Comment by PHPJourney** [comment]
> extends.js 

`
const view = require('think-view');
const model = require('think-model');
const cache = require('think-cache');
const session = require('think-session');
const websocket = require('think-websocket');

module.exports = [
  view, // make application support view
  model(think.app),
  cache,
  session,
  websocket(think.app)
];
`

> config.js

`
/**
 * config
 */
export default {
  //key: value
  port: 3000,
  workers: 0,
  host: '127.0.0.1',
  createServer: undefined,
  startServerTimeout: 3000,
  reloadSignal: 'SIGUSR2', // reload process signal
  stickyCluster: true, // sticky cluster, add from 3.1.0
  onUnhandledRejection: err => think.logger.error(err), // unhandledRejection handle
  onUncaughtException: err => think.logger.error(err), // uncaughtException handle
  processKillTimeout: 10 * 1000, // process kill timeout, default is 10s
  jsonpCallbackField: 'callback', // jsonp callback field
  jsonContentType: 'application/json', // json content type
  errnoField: 'errno', // errno field
  errmsgField: 'errmsg', // errmsg field
  defaultErrno: 1000, // default errno
  redis: {
    host: '127.0.0.1',
    port: 6379,
    password: ''
  },
  validateDefaultErrno: 1001 // validate default errno
};
`

> adapter.js

`
const fileCache = require('think-cache-file');
const nunjucks = require('think-view-nunjucks');
const redisSession = require('think-session-redis');
const mysql = require('think-model-mysql');
const { Console, File, DateFile } = require('think-logger3');
const path = require('path');
const isDev = think.env === 'development';
const config = require('./config.js');
const socketio = require('think-websocket-socket.io');

/**
 * cache adapter config
 * @type {Object}
 */
exports.cache = {
  type: 'file',
  common: {
    timeout: 24 * 60 * 60 * 1000, // millisecond
  },
  file: {
    handle: fileCache,
    cachePath: path.join(think.ROOT_PATH, 'runtime/cache'), // absoulte path is necessarily required
    pathDepth: 1,
    gcInterval: 24 * 60 * 60 * 1000, // gc interval
  },
};

/**
 * model adapter config
 * @type {Object}
 */
exports.model = {
  type: 'mysql',
  common: {
    logConnect: isDev,
    logSql: isDev,
    logger: msg => think.logger.info(msg),
  },
  mysql: {
    handle: mysql,
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'dbname',
    port: '',
    prefix: 'pay_',
    encoding: 'utf8',
    pageSize: 20,
    dateStrings: true,
  },
};

/**
 * session adapter config
 * @type {Object}
 */
exports.session = {
  type: 'redis',
  common: {
    cookie: {
      name: 'thinkjs'
    }
  },
  redis: {
    handle: redisSession,
    maxAge: '1d',
    ...config.redis
  }
};

/**
 * view adapter config
 * @type {Object}
 */
exports.view = {
  type: 'nunjucks',
  common: {
    viewPath: path.join(think.ROOT_PATH, 'view'),
    sep: '_',
    extname: '.html',
  },
  nunjucks: {
    handle: nunjucks,
    options: {
      tags: {
        // 修改定界符相关的参数
        variableStart: '{=',
        variableEnd: '=}',
      },
    },
  },
};

/**
 * logger adapter config
 * @type {Object}
 */
exports.logger = {
  type: isDev ? 'console' : 'dateFile',
  console: {
    handle: Console,
  },
  file: {
    handle: File,
    backups: 10, // max chunk number
    absolute: true,
    maxLogSize: 50 * 1024, // 50M
    filename: path.join(think.ROOT_PATH, 'logs/app.log'),
  },
  dateFile: {
    handle: DateFile,
    level: 'ALL',
    absolute: true,
    pattern: '-yyyy-MM-dd',
    alwaysIncludePattern: true,
    filename: path.join(think.ROOT_PATH, 'logs/app.log'),
  },
};
/**
 * websocket adapter config
 * @type {Object}
 */
exports.websocket = {
  type: 'socketio',
  common: {},
  socketio: {
    handle: socketio,
    // allowOrigin: '127.0.0.1:8360',  // 默认所有的域名都允许访问
    path: '/sock/socket.io',             // 默认 '/socket.io'
    adapter: null,                  // 默认无 adapter
    messages: {
      open: '/websocket/open', // 建立连接时处理对应到 websocket Controller 下的 open Action
      close: '/websocket/close', // 关闭连接时处理的 Action
      message: '/websocket/message', // 数据中转 Action
      room: '/websocket/room', // 数据中转 Action
    }
  }
};
`
> cache.js

`
export default {
  type: 'redis', //缓存类型
  timeout: 6 * 3600, //失效时间，单位：秒
  adapter: { //不同 adapter 下的配置
    file: {
      path: think.RUNTIME_PATH + '/cache', //缓存文件的根目录
      path_depth: 2, //缓存文件生成子目录的深度
      file_ext: '.json' //缓存文件的扩展名
    },
    redis: {
      prefix: 'pay_'
    },
    memcache: {
      prefix: 'pay_'
    }
  }
};
`
> gc.js

`
export default {
  on: true, //是否开启垃圾回收处理
  interval: 3600, // 处理时间间隔，默认为一个小时
  filter: function(){ //如果返回 true，则进行垃圾回收处理
    let hour = (new Date()).getHours();
    if(hour === 4){
      return true;
    }
  }
};
`
> redis.js

`
export default {
  host: '127.0.0.1',
  port: 6379,
  password: '',
  timeout: 0,
  log_connect: true
};
`
> view.js

`
'use strict';
/**
 * template config
 */
export default {
  type: 'ejs',
  content_type: 'text/html',
  file_ext: '.html',
  file_depr: '_',
  root_path: think.ROOT_PATH + '/view',
  adapter: {
    ejs: {}
  }
};
`
> session.js

`
'use strict';

/**
 * session configs
 */
export default {
  name: 'pay',
  type: 'redis',
  secret: '!$%F`J#P',
  timeout: 24 * 3600,
  cookie: { // cookie options
    length: 32,
    httponly: true
  },
  adapter: {
    file: {
      path: think.RUNTIME_PATH + '/session',
    }
  }
};
`
> bootstrap/global.js
`
/**
 * this file will be loaded before server started
 * you can define global functions used in controllers, models, templates
 * 全局变量
 */

/**
 * use global.xxx to define global functions
 * 
 * global.fn1 = function(){
 *     
 * }
 */
global.$socketChat = {};
`
> bootstrap/middleware.js

`
const path = require('path');
const isDev = think.env === 'development';
const payload = require('think-payload');

module.exports = [
  {
    handle: 'meta',
    options: {
      logRequest: isDev,
      sendResponseTime: isDev,
    },
  },
  {
    handle: 'resource',
    enable: true,
    options: {
      root: path.join(think.ROOT_PATH, 'www'),
      publicPath: /^\/(static|favicon\.ico)/,
    },
  },
  {
    handle: 'trace',
    enable: !think.isCli,
    options: {
      debug: isDev,
    },
  },
  {
    handle: payload,
    options: {
      keepExtensions: true,
      limit: '5mb',
    },
  },
  {
    handle: 'router',
    options: {},
  },
  'logic',
  'controller',
];
`
> bootstrap/redis.js

`
// 因为redis也算一个数据库
// 因此最好和redis的交流有一个比较规范的接口
// 不要随意使用redis原生方法
// 便于以后调整优化切换等
// 另外由于我很懒
// 所以我包了一些promise
const redis = require('redis');
const redisConfig = think.config('redis');
class Redis {
  constructor() {
    this.link = redis.createClient(redisConfig);
    this.link.on('error', this.error);
    const utils = redis.RedisClient.prototype;
    for (const name in utils) {
      this[name] = this.promisify(utils[name]);
    }
  }
  error(err) {
    console.error(err);
  }
  promisify(fn) {
    return (...args) => {
      return new Promise((resolve, reject) => {
        fn.call(this.link, ...args, (err, obj) => {
          return err ? reject(err) : resolve(obj);
        });
      });
    };
  }
}

global.rediser = new Redis();
`
> bootstrap/worker.js

`
require('./global');
require('./redis');
`

**Comment by lizheming** [comment]
评论输入框右下角就有 Markdown 语法教学链接，建议先去看看 Markdown 怎么用。ps. 自己发的内容自己都不看一眼的么

**Comment by PHPJourney** [comment]
> 评论输入框右下角就有 Markdown 语法教学链接，建议先去看看 Markdown 怎么用。ps. 自己发的内容自己都不看一眼的么

我直接调用的在线编辑器code ，哪知道它这个功能有问题

**Comment by welefen** [comment]
@PHPJourney  你依赖的 ThinkJS 是 v2 版本？

**Comment by PHPJourney** [comment]
@welefen 
问题解决了，缺少是版本问题导致。我没搞清楚你们不同版本差异化这么大。本地package是安装的v2，等安装websocket进行调试的时候demo是v3的，所以产生了一大堆的问题，浪费我了好几天时间

**Comment by welefen** [comment]
@PHPJourney  好的。根据语义化版本规则，大版本更新会有重构等 breaking change 的情况
