### ISSUE TITLE
使用super调用display（） 方法返回 ok，正常调用return this.dipaly() 却没有问题

### ISSUE THREAD

**Issue by hanjianheng** [thinkjs/thinkjs#1438]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by hanjianheng** [comment]
return this.display();   调用下面的方法
  
display(){
   调用父类得 方法，
      super.display('zh-CN/home/index_index')
    }
不解析页面返回ok， 模板用的nunjucks，请大佬们指点一下

**Comment by tihssiefiL** [comment]
display 是异步的，async await 试试看行么

**Comment by hanjianheng** [comment]
正解！ 加上async 和await 就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "YangYang"<notifications@github.com&gt;; 
发送时间: 2019年10月30日(星期三) 下午3:16
收件人: "thinkjs/thinkjs"<thinkjs@noreply.github.com&gt;; 
抄送: "余生"<764044966@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thinkjs/thinkjs] 使用super调用display（） 方法返回 ok，正常调用return this.dipaly() 却没有问题 (#1438)




display 是异步的，async await 试试看行么
