### ISSUE TITLE
__before函数中 根据客户端请求 给 全局对象 think 赋值一个变量  在不同的action 中会相互覆盖？

### ISSUE THREAD

**Issue by vjzning** [thinkjs/thinkjs#1440]
同一时间多个请求， 我发现  action A中 获取 think.xx 的值 会 是 action B中的值。

**Comment by vjzning** [comment]
是不这样的传递值 方式就是错的？ 只能通过 this.ctx.xxx 传递了

**Comment by welefen** [comment]
不能这样做，可以通过 this.ctx.state.xxx 来传递
