### ISSUE TITLE
中间件resource，支持视频文件拖动进度条播放

### ISSUE THREAD

**Issue by handoudou** [thinkjs/thinkjs#1447]
## DESC
框架内置的中间件resource支持header的Range
1：在静态目录中有一个视频文件
2：前端使用播放器进行播放该文件，不支持拖动进度条

### ENV
OS Platform:
mac
Node.js Version:
v10.16.1
ThinkJS Version:
3.2.10
### code

```js
// your code here
{
        handle: 'resource',
        options: {
            root: path.join(think.ROOT_PATH, 'www'),
            publicPath: /^\/(static|favicon\.ico)/
        }
    },
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by welefen** [comment]
用下 `koa-range` 模块，在配置文件 middleware 里 resource 前面加上：


```js
const range = require('koa-range'); // 记得加到依赖里

{
  handle: options => range
}
```

**Comment by handoudou** [comment]
测试可以使用。多谢 @welefen
