### ISSUE TITLE
think-crontab可否输出日志到文件

### ISSUE THREAD

**Issue by aov2005** [thinkjs/thinkjs#1448]
## DESC
定时任务的执行日志可不可以输出到单独的日志文件？
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by welefen** [comment]
代码里是通过 `think.logger.xxx` 来输出日志的么？

**Comment by aov2005** [comment]
代码没有打log，想问下能否在执行的时候获取控制器输出的内容输出日志到 logs/crontab.log 之类的

**Comment by welefen** [comment]
现在默认没有支持，你可以通过 middleware 来实现这个（获取 ctx.body 然后写入到文件）

**Comment by welefen** [comment]
```js
{
  handle: options => {
    return async (ctx, next) => {
      await next();
      if(ctx.isCli) {
         const body = ctx.body; // body may be `string/stream`
         // write body to file
      }
    }
  }
}
```
类似这样

**Comment by aov2005** [comment]
好的，这也是个方法，谢谢
