### ISSUE TITLE
thinkjs不支持cluster模式吗

### ISSUE THREAD

**Issue by chenyanji** [thinkjs/thinkjs#1452]
版本：3.2
我线上部署，把pm2.json配置下exec_mode修改为cluster，
再运行命令：pm2 start pm2.json  发现无法使用，如果exec_mode为fork则正常，
是不是说thinkjs不支持多线程处理，这样一来如果一个用户出错，全线崩溃？

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/deploy.html#pm2

**Comment by chenyanji** [comment]
@lizheming 我也是这样配置的，可以运行一段时间后，就卡死了

**Comment by lizheming** [comment]
两个问题，刚才回答你的是 PM2 相关。后续的这个原因有很多，建议先去打印下日志，看下 CPU，内存等的增长。
