### ISSUE TITLE
使用nginx并开启stickyCluster导致所有请求都只落在一个worker中

### ISSUE THREAD

**Issue by xioxin** [thinkjs/thinkjs#1455]
## DESC

![image](https://user-images.githubusercontent.com/5716100/71302834-1122c700-23eb-11ea-8414-dff611e28a2d.png)

使用nginx并开启stickyCluster导致所有请求都只落在一个worker中

发现是socket.remoteAddress一直返回的是127.0.0.1 导致的

但是我不知道该怎么取出请求头

https://github.com/thinkjs/think-cluster/blob/038188531d5332d72363acf932537bfdc37339f7/lib/master.js#L128-L129

https://github.com/thinkjs/thinkjs/blob/132ad906bee9348e6805280d517ab69d263bb90c/lib/application.js#L112-L114

config.production.js
```
module.exports = {
  workers: 4,
  stickyCluster: true,
  proxy: true
};
```

nginx配置
```
            proxy_http_version 1.1;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_set_header X-NginX-Proxy true;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Connection "upgrade";
            proxy_pass http://127.0.0.1:4567$request_uri;
            proxy_redirect off;
```

### ENV

OS Platform: centos 7

Node.js Version: v8.9.4

ThinkJS Version: thinkjs@3.2.7

### more description

// your detail description

**Comment by xioxin** [comment]
查了一下。没有办法获取请求头，因为这里还在传输层，并且收到请求后就暂停了，等发给了worker才开始接收数据。😵

**Comment by welefen** [comment]
这种只能启多个端口，然后 nginx 配置 upstream

**Comment by xioxin** [comment]
嗯 好的也只能这样了
