### ISSUE TITLE
view 下的目录可以多分级么

### ISSUE THREAD

**Issue by junziyangyang** [thinkjs/thinkjs#1464]
## DESC

 view 下的目录可以多分级么
 比如像下面这样
   view
      - admin
            - user
                add.html
                index.html
            - news
                add.html
                index.html

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/view.html 
模板配置里有一个 `sep` 配置，配置成 `/` 就可以按照文件夹划分了，默认是 `_` 所以都在同一层目录。

**Comment by junziyangyang** [comment]
@lizheming 感谢回复，我在看下。
