### ISSUE TITLE
怎样实现文件的上传下载呢，前端vue，数据库mysql

### ISSUE THREAD

**Issue by wsq-wushiqi** [thinkjs/thinkjs#1466]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
上传前端使用 multipart 表单上传，服务端通过 `this.files()` 获取 https://thinkjs.org/zh-cn/doc/3.0/controller.html#toc-88b

下载服务端使用 `this.download()` https://thinkjs.org/zh-cn/doc/3.0/controller.html#toc-545

**Comment by wsq-wushiqi** [comment]
您好~在改路径的时候会报这个错误{ [Error: EXDEV: cross-device link not permitted, rename 'C:\Users\wushiqi\AppData\Local\Temp\upload_bad64d961bc25a9859e25dbae0081296' -&gt; 'E:\wusq\bs\structure-admin-master\structure-admin-node\upload\a.jpg'] 请问要怎么解决呢，试了网上的方法都没有解决出来





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Austin Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月20日(星期一) 上午8:43
收件人:&nbsp;"thinkjs/thinkjs"<thinkjs@noreply.github.com&gt;;
抄送:&nbsp;"诗琪"<1450573816@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thinkjs/thinkjs] 怎样实现文件的上传下载呢，前端vue，数据库mysql (#1466)




上传前端使用 multipart 表单上传，服务端通过 this.files() 获取 https://thinkjs.org/zh-cn/doc/3.0/controller.html#toc-88b
 
下载服务端使用 this.download() https://thinkjs.org/zh-cn/doc/3.0/controller.html#toc-545

**Comment by lizheming** [comment]
这是由于 Windows 跨磁盘拷贝的问题导致的，默认上传的临时目录在 C 盘，你可以通过修改 `payload` 中间件的 `uploadDir` 属性将其修改为项目目录同一个盘的位置解决这个问题。https://github.com/thinkjs/think-payload#options
