### ISSUE TITLE
浏览器直接显示图片问题

### ISSUE THREAD

**Issue by shenjackson** [thinkjs/thinkjs#1467]
我是刚学thinkjs的新手，在已经实现图片上传和下载后，不知道怎么在浏览器上直接显示图片，有相应的例程或者说明吗，找了很久还是没找到

**Comment by lizheming** [comment]
`this.type = 'application/image';`  接口输出图片的时候需要根据图片格式设置一下对应的 `Content-Type` 这样浏览器才能识别为图片然后自己渲染。

**Comment by shenjackson** [comment]
还是不太懂，说明文档有例子就好了，
![image](https://user-images.githubusercontent.com/38517143/73137105-de29be00-408f-11ea-8274-787f65688ad1.png)
这样子怎么xiugai修改呢

**Comment by greenhat616** [comment]
@shenjackson 这样试试？
```javascript
let filename = '48d43e3f-0610-4eda-981a-6cce76317c4a.jpg';
let filepath = path.join(think.ROOT_PATH, runtime/upload/ + filename);
this.type = 'application/image';
return this.ctx.body = await readFile(filepath, 'utf8'); // 不过不推荐这样做，建议还是通过 streamReader 的方式提交给 body
// console.log('filepath');
```

**Comment by shenjackson** [comment]
@greenhat616 谢谢你的回复，还是不行，其实我只是想实现像  nodejs  的res.sendFile 的功能，而且streamReader 官方文档没有说明 = =

**Comment by greenhat616** [comment]
可能是 @lizheming 给出的示例有误，可以试试 `this.ctx.type = 'application/image'` ，参考文档： https://thinkjs.org/doc/3.0/context.html#toc-526

如果还不行，那估计就是 `readFile `这个函数存在问题了，你这儿没给出定义，我也看不出什么。

对了，你其实更应该了解 Koa 背后的底层，think 很多方法都是对这个框架的封装，或者说是语法糖。
P.S: `res.sendFile` 是 express 的语法糖

**Comment by greenhat616** [comment]
@shenjackson 
对于流这个概念，也是 Node.JS 的基础。参考文档：https://nodejs.org/api/stream.html
当使用 fs 包时，可以创建一个读取流： https://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options

以下，是一个使用读取流的案例（并非是针对 thinkjs 的）
```javascript
//引入koa-router包
const router = require("koa-router")();
// 引入fs文件系统
const fs = require("fs");
// 先实现返回图片流(buffer)
router.get("/img", async (ctx, next) => {
  let { imgName } = ctx.request.query; // 提取参数
  const res = await readImg(imgName);
  // res 为 Buffer流
  if (res) {
    ctx.type = "jpg";
    ctx.body = res;
  }
  await next();
});
// 用fs处理流
function readImg(filePath) {
  // 创建可读流
  let data = [];
  return new Promise((res, rej) => {
    const readerStream = fs.createReadStream(`./public/${filePath}`);
    readerStream.on("data", function(chunk) {
      data.push(chunk);
    });
    readerStream.on("end", function() {
      const finalData = Buffer.concat(data); // 合并Buffer
      res(finalData);
    });
  });
}```

**Comment by shenjackson** [comment]
@greenhat616   readFile 是这个
const readFile = think.promisify(fs.readFile, fs);

我改了还是不行，我先看看你发的

**Comment by lizheming** [comment]
@greenhat616 `application/image` 只是我举得一个示例，并不是真的就是这个类型。不同图片格式有不同的 `Content-Type` 值，具体参看 MDN 文档：https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Basics_of_HTTP/MIME_types 表里标的很清楚了我就不多说了，例如 jpg 应该是 `this.ctx.type = 'image/jpeg';`
