### ISSUE TITLE
请问有计划支持消息队列的发布与消费嘛？

### ISSUE THREAD

**Issue by greenhat616** [thinkjs/thinkjs#1468]
目前似乎没有官方的扩展，开发中有些不便。
我觉得这个应该还是比较常用的驱动吧，比如推送通知等服务场景。
这里想问问奇舞团的各位有没有计划支持消息队列相关的扩展呢？

**Comment by lizheming** [comment]
你们用的什么消息队列服务？kafka 是有现成的 node 模块的，直接接入就行。

**Comment by greenhat616** [comment]
您好，目前我们数据量比较小，所以我们选用的是 RabbitMQ。
目前我们的解决方案是直接在相关控制器基类配置服务，没在 Adapter 或者 Config 配置。
目前对 thinkjs 的研究还比较浅薄，所以暂时还没有了解到扩展上面提及的这两块的知识。
出于私心，所以想问问你们有没有计划官方支持 adapter ：D
新年快乐哈，顺颂商祺。

**Comment by lizheming** [comment]
RabbitMQ 也是有对应的客户端模块的，可以直接使用 https://www.npmjs.com/package/rabbitmq-nodejs-client adapter 只是一种设计模式，一般针对这种直接使用的场景直接初始化使用即可，如果确实有切换对接服务类型的需求再考虑支持下适配器模式吧。

**Comment by greenhat616** [comment]
明白了。那我先关闭这个问题了。
