### ISSUE TITLE
this.post 为什么无法接收参数了.

### ISSUE THREAD

**Issue by eugeneCN** [thinkjs/thinkjs#1472]
### ENV

OS Platform: Mac

Node.js Version: v8.12.0

ThinkJS Version: 3.0

### code

```js
// your code here
// src/controller/api/accounts.js
module.exports = class extends think.Controller {
 async createAction() {
    console.log(this.post()) // => {}
    const json = Object.assign(this.post(), { uuid: think.uuid() })
    console.log(json) // => {uuid: "835e6d06-674e-4b50-ad5c-2e6194330f4e"}
    return this.success(json, 'success')
  }
}
```

### fe code

```js
// view/index_index.html
$.ajax({
  url: '/api/accounts/create',
  type: 'post',
  dataType: 'json',
  contentType : "application/json", 
  data: JSON.stringify({ "name": "boy", "age": "11" })
})
```

### more description
奇怪了啊，项目之前还能接收post过来的参数，今天run起来突然发现无法接收参数了。
postman axios jquery.ajax 都试过，结果一样。
配置没有动过，只是重新装过依赖。

**Comment by lizheming** [comment]
提供下最小可复现的环境？看你这代码似乎也没啥问题。

**Comment by eugeneCN** [comment]
找到问题了，没有加载payload中间件，可是加了这个东西无法使用[代理中间件](https://github.com/eugeneCN/koa-server-http-proxy)了。。求科普！

**Comment by welefen** [comment]
@eugeneCN  把代理中间件放在 payload 前面应该就可以了

**Comment by eugeneCN** [comment]
@welefen @lizheming 感谢

**Comment by wudi98** [comment]
> 找到问题了，没有加载payload中间件，可是加了这个东西无法使用[代理中间件](https://github.com/eugeneCN/koa-server-http-proxy)了。。求科普！

请问您是如何加载payload中间件的呢?我在config的middleware.js里添加了payload中间件，但是并没有被应用，希望看一下您的那部分代码，感谢。邮箱：csdnwuxiaodi@qq.com

**Comment by binonxia** [comment]
有一样的问题，想知道怎么看payload中间件被加载了

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/middleware.html#toc-1fa
