### ISSUE TITLE
在think-model 里有这样对应的设置吗？能让数据库一直保持着连接？

### ISSUE THREAD

**Issue by 188007803** [thinkjs/thinkjs#1473]
## DESC

10分钟不用，数据库似乎就断开了，本地电脑和服务上都出现这种现象，做一次查询的时间会超过10秒，但查询过一次以后，查询又很快了，过一段时间不用，又断开了。

用Navicat这个工具连接数据库也是这样，但是Navicat里有个“保持连接”的设置，可以解决这个问题。

那在think-model 里有这样对应的设置吗？让数据库一直保持着连接？

### ENV

OS Platform: 
本地：MAC-OS 10.14
服务器：CentOS 7.2
数据库：腾讯云上的 mysql

Node.js Version:
本地：12.13.0
服务器：10.0.0

ThinkJS Version: 
thinkjs 3.2

**Comment by welefen** [comment]
没有类似心跳的机制，为啥连接要超过 10S，这也太慢了。

如果需要的话，可以自己利用定时任务来模拟个心跳查询

**Comment by 188007803** [comment]
也是个办法，谢谢！
