### ISSUE TITLE
think-redis连接泄漏

### ISSUE THREAD

**Issue by shasharoman** [thinkjs/thinkjs#1477]
thinkjs项目运行后redis连接数2000+，经过定位发现是think-redis & think-cache-redis导致，具体如下：

`think-redis`: [此处代码](https://github.com/thinkjs/think-redis/blob/master/index.js#L39)根据config做了一层cache用于连接复用，但`think-cache-redis`: [此处代码](https://github.com/thinkjs/think-cache-redis/blob/master/index.js#L22)支持一个timeout参数用于指定redis key的ttl，当应用设置不同有效期的key时，会导致`think-redis`的连接复用不生效以致出现连接泄漏，尤其是random的ttl。

从日志观察，可能是model层的cache机制出现random-ttl从而导致连接数2000+。

**Comment by lizheming** [comment]
https://github.com/thinkjs/think-cache-redis/blob/master/index.js#L50 set 的时候是支持传 timeout 参数的，就不要早 config 里面改了吧。

**Comment by shasharoman** [comment]
> https://github.com/thinkjs/think-cache-redis/blob/master/index.js#L50 set 的时候是支持传 timeout 参数的，就不要早 config 里面改了吧。

日志堆栈上看，应该是think-model层的cache引发了这个问题~

**Comment by shasharoman** [comment]
![image](https://user-images.githubusercontent.com/5089251/78124631-88341680-7442-11ea-802e-9b5ee44c55a6.png)

**Comment by lizheming** [comment]
@welefen https://github.com/thinkjs/think-model-abstract/blob/master/lib/query.js#L190 这块好像是会有问题，sql 语句会带在 config 里导致每次生成的 md5 会不一样

**Comment by shasharoman** [comment]
@lizheming 请原谅我，random ttl不是think-model设置的，而是项目开发人员在执行select方法cache时传入的、BUG客观存在，但诱因还是使用导致

类似这种代码：
``` javascript
this.where({}).cache({
    timeout: Math.floor(Math.random() * 1000) + 6000
}); 
```

**Comment by lizheming** [comment]
恩，刚才商量了下，可以优化下，这块需要把 timeout 配置拆出来，不能放在 cache 实例化里，否则会被传到 connection 里面去。

**Comment by lizheming** [comment]
`think-model@1.4.2` 和 `think-model-abstract@1.6.2` 已发布，将 cache 传入的 timeout 参数抽离出来，避免其污染 connection 的配置，这样能避免你所说的这个问题，可以更新下试试，最后感谢反馈。
