### ISSUE TITLE
关于事务的问题

### ISSUE THREAD

**Issue by lantongxue** [thinkjs/thinkjs#1478]
## DESC
有两个model，用其中一个的model的事务，会出现后面事务无法提交的问题。
### ENV

OS Platform: win10 x64 & macOS 10.14.5

Node.js Version:v13.11.0

ThinkJS Version:3.2.11

### code

```js
let model = think.model('order') as OrderModel;
let u = think.model('user') as UserModel;
try{
       await model.startTrans();
       await model.add({x:x});
       await u.where({id: 1}).update({x: x});
       await model.commit();
}catch(e){
       await model.rollback();
       throw e;
}
```

### more description

经过测试，注释掉 `await u.where({id: 1}).update({x: x});` 可以走通，但这不符合需求。
请问这是什么原因导致的？为什么有两个模型就不能提交事务？

或者针对这种情况有什么好的解决方案？

**Comment by lizheming** [comment]
https://thinkjs.org/doc/3.0/relation_model.html#toc-e30 事务中的模型需要复用连接，使用 `db()` 可以解决问题。

```js
let model = think.model('order') as OrderModel;
let u = think.model('user') as UserModel;
u.db(model.db());
```
