### ISSUE TITLE
thinkjs 的 Model 可以独立使用吗？

### ISSUE THREAD

**Issue by tumobi** [thinkjs/thinkjs#1480]
使用 Thinkjs 的 Model 操作数据库习惯了，觉得方便又好用。但是做一些非 web 项目时，如数据采集、定时任务简单项目时，想使用 thinkjs 的 Model 封装的方法操作数据库。

**Comment by welefen** [comment]
https://github.com/thinkjs/think-model/blob/master/index.js  参考这里调用就可以了

**Comment by lizheming** [comment]
https://github.com/thinkjs/thinkjs/issues/1398 相关 issue
