### ISSUE TITLE
似乎thinkjs3.2.11，运行模式为production时，只能运行在8360端口

### ISSUE THREAD

**Issue by Haiyang2017** [thinkjs/thinkjs#1482]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:3.2.11

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description 

thinkjs 3.2.11.生成的runtime/config/production.json中，port始终是8360，无论配置文件中如何配置端口

**Comment by lizheming** [comment]
没有这种限制的，查一下你的 `src/config/config.js` 和 `src/config/config.production.js` 的配置看看

**Comment by Haiyang2017** [comment]
> 没有这种限制的，查一下你的 `src/config/config.js` 和 `src/config/config.production.js` 的配置看看

神奇，刚刚又测了一下，真的没有问题。我之前反复试了好多遍,很确定配置文件没有改错，而且是把两个配置文件都改了，每次development可以，production不行，很纳闷端口为啥不对，才去检查的runtime/config/production.json。刚刚又试了一下，真的没有问题。真实诡异事件。不管了，反正现在是ok的了。
