### ISSUE TITLE
一个事务里操作多个model，其中一个插入失败，另一个不会回滚

### ISSUE THREAD

**Issue by iamdarcy** [thinkjs/thinkjs#1483]
OS Platform: macos catalina 10.15
Node.js Version:12.16.2
ThinkJS Version: 3.2.7

### code
```js
       async testAction() {
		let model = this.model('address');
		await model.transaction(async () => {
			let info = {
				name: '测试事务'
			}
			await model.add(info);
			let model2 = this.model('ad').db(model.db());
			await model2.add({
				link_type: 100000, // 这个字段类型tinyint 长度1，10000就插入不了
				image_url: '图片链接'
			})
		})
	}
```
### error message
![image](https://user-images.githubusercontent.com/19727444/79746136-13b31000-833c-11ea-8312-f2642c1771cf.png)

报错了，也显示rollback，为什么address还是插入了一条呢？不是应该回滚不插入吗？
address表
![image](https://user-images.githubusercontent.com/19727444/79746356-70162f80-833c-11ea-841d-7b97fa09963b.png)
ad表
![image](https://user-images.githubusercontent.com/19727444/79746381-7dcbb500-833c-11ea-93bc-3d4416de78cd.png)

### more description
是不是我的测试方法有问题？希望开发者大大能回复下，谢谢🙏

**Comment by welefen** [comment]
我本地测试了下，没啥问题。

你的数据是 Mysql 还是什么？

**Comment by iamdarcy** [comment]
谢谢开发者的回复，我知道原因了，引擎的原因
