### ISSUE TITLE
关于模型连接复用的问题

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#1489]
关系到事务的时候，
不同的模型之间要调用.db()来复用连接，
这个有点繁琐了，能不能默认复用一个链接？
我试过给数据库配置加上
`connectionLimit: 1`
但实际测试好像还是得手动用db()来复用，不然也会卡死。
很多时候，某些操作比较复杂，
所以如果出现这种情况：
controller A 调用service B，控制器A和服务B都要操作模型，
由于thinkjs不支持事务嵌套，当多个模块的操作要在同一个事务完成的时候，为了复用连接，我就得额外给service B的方法加一个参数，好让controller A把模型的调用db()的结果传递给service的方法，不然事务就卡死。

伪代码如下：
控制器A：
```
module.exports = class extends Base {
    async indexAction() {
      const user_id = this.get('user_id');
      const user_model = think.model('user');
      const db_connect = user_model.db();
       await user_model.transaction(()=>{
          await user_model.doSomething(user_id);
          const log_service = think.service('log');
          await log_service.doSomething('xxx',db_connect);
      })
  }
} 
```

服务B：
```
module.exports = class extends think.Service {
  constructor() {
    super();
  }
  async doSomething(content,dbConnection){
     const log_model = think.model('log').db(dbConnection);
     await log_model.doSomething(content);
  }
}
```

简而言之，为了复用连接，各个模块之间就得反复地传递一个额外的参数，
维护起来很不方便。虽然可以把日志操作放到控制器里一起，但实际项目要复杂得多，如果全部放控制器，冗余代码就太多了，因为有的功能是多个控制器复用的，所以我才单独放到一个服务里面，而且这个服务初始化比较消耗资源，所以是单例服务，启动项目以后初始化完成就直接挂到global全局变量里的，所有控制器共享，但都涉及数据库操作。

或者说是我思路有问题，有更好的办法？

**Comment by KuoKongQingYun** [comment]
我现在想要不然，项目启动的时候，就吧db()的结果保存到全局变量里，然后所有的模型默认都复用这个全局变量里保存的连接，但这种感觉也不太合适，总感觉怪怪的。

**Comment by lizheming** [comment]
感觉不太好处理，其实正常情况下是不需要连接复用的，只有事务的时候需要，但是目前 `startTrans()` 方法是和 Model 实例关联的，其他实例无法知晓开启了事务，所以需要显示传递。

**Comment by KuoKongQingYun** [comment]
> 感觉不太好处理，其实正常情况下是不需要连接复用的，只有事务的时候需要，但是目前 `startTrans()` 方法是和 Model 实例关联的，其他实例无法知晓开启了事务，所以需要显示传递。

我想了个思路就是，自己封装一个函数，如下：
```
model(name) {
    const model = think.model(name);
    if (think.isEmpty(global.app.db)) {
      global.app.db = model.db();
    } else {
      model.db(global.app.db);
    }
    return model;
  }
```
应用里把所有的think.model全替换成这个函数，
我本来想能不能把db放在ctx里面，这样的话单个请求就能共享同一个数据库连接，多个请求之间连接是独立的，后来发现ctx貌似只有在控制器和模型里面通过this.ctx才能访问，我尝试过think.ctx，发现并不可以，所以干脆就放global全局变量里了，不知道有没有什么隐患或者问题。

**Comment by lizheming** [comment]
你这种方式太局限性了，肯定是没办法写在框架里的。请求量小的情况下应该无所谓了，请求量大的话还是要多测一下。ctx 是请求相关的，非请求链路是无法获取到的。`this.model` 的话是在 `controller` 上，可以通过 `this.ctx` 获取到。

**Comment by KuoKongQingYun** [comment]
> 你这种方式太局限性了，肯定是没办法写在框架里的。请求量小的情况下应该无所谓了，请求量大的话还是要多测一下。ctx 是请求相关的，非请求链路是无法获取到的。`this.model` 的话是在 `controller` 上，可以通过 `this.ctx` 获取到。

这个方法我目前是放在一个service里面的，里面都是些助手函数，service里面也获取不到ctx，所以只好放global里了，刚刚想到一个写控制器里的办法，
就是所有的控制器都从common里的base控制器继承，然后把刚刚那个model方法写在那个控制器基类里面，然后就能把数据库连接放ctx里了，这样会不会好一点。

**Comment by KuoKongQingYun** [comment]
试了一下，发现还是有问题，这样的话，只有在控制器里才能使用这个model方法，模型里面又访问不到这个model函数了，因为model不能反向获取到controller实例.
先暂时放service里保存到全局变量里，有问题再看看解决办法了。

**Comment by KuoKongQingYun** [comment]
还是建议官方能够改进一下这个地方，大题思路就是，在一个ctx里面，复用一个连接，这个就已经覆盖绝大多数情况了。
可以考虑在框架层面把连接保存在ctx里面，然后在同一个ctx下，不管在什么地方调用think.model，都默认复用同一个连接，这个在框架层面应该好实现，但在应用层面就难了，原因就是上面所说的：ctx只能在middleware、controller、logic中获取到，如果在这三个地方以外有使用到模型，哪怕想自己封装，也不好办。
对于数据完整性要求不高的项目来说，比如论坛，博客什么的，开不开事务无所谓，不开事务还能提高性能，就算有异常，问题也不大。但如果项目关系到交易订单，资金结算了，用到事务就比较多，每次都要手动共享连接就很容易漏掉，维护的时候也容易漏掉，特别是多个部分有互相调用的情况，最典型的情况就是
1：结算订单，同时要修改订单状态、修改多个用户余额、记账……
2：用户提现，修改多个用户余额、记账……
就以修改用户余额来说，正常的做法是单独封装成一个方法，在结算订单和提现的时候，就直接调用修改用户余额的方法，但因为目前这个情况，两个选择：
1.要么就要增加一个db参数，把连接也传递过去；
2.要么就把修改用户余额的逻辑写成几份，全部放在控制器里，有几个地方需要修改用户余额就放几份。
不管哪个，都不好维护

**Comment by welefen** [comment]
@KuoKongQingYun  现在 Model/Service 是跟 ctx 默认隔离的，要用的话需要手动把 ctx 传递进去。如果想默认就复用连接的话，只能通过一个扩展处理（自动传递 ctx 进去，然后把db 实例绑定到 ctx 上）

**Comment by welefen** [comment]
@KuoKongQingYun  通过添加了一个配置 `reuseDB: true` 来支持这个功能了（默认为 false），具体见： https://thinkjs.org/doc/3.0/relation_model.html#toc-e30

**Comment by KuoKongQingYun** [comment]
@welefen 非常感谢

**Comment by KuoKongQingYun** [comment]
@welefen 还有个地方，不知道合不合适修改，我看了一下think-model最新的代码，只处理了控制器里的model方法，但实际上也有一个模型里调用另一个模型的情况：
我的model里添加了一个自定义的方法，比如user模型我添加了一个addUser()
但是这个方法又用到了其它模型（因为有些关联表的操作），目前我只能用
`this.model('xxx').db(this.db())`
这种形式，虽然只需要多一点点代码，但也有点繁琐了，既然增加了reuseDB这个配置项，那模型里使用this.model是否也可以默认复用？
也就是说模型的model方法也会根据resuseDB来决定是否复用。
