### ISSUE TITLE
thenAdd 判断出错！！

### ISSUE THREAD

**Issue by grapewheel** [thinkjs/thinkjs#1494]
### ENV

OS Platform: Deepin 20

Node.js Version: v12.13
 
ThinkJS Version: 3.2.11

ThinkModel Version: 1.5.1

ThinkModelMysql Version: 1.1.2

### code

```js
const result = await this.where({ mobile: data.mobile }).thenAdd(data)
```

### error message

```
result = { id: undefined, type: 'exist' } 
```

### more description

没有在数据库中查找到相应的mobile，却返回exist！

**Comment by lizheming** [comment]
可以把输出的 SQL 语句自己执行下看看

**Comment by grapewheel** [comment]
SELECT * FROM `partner` WHERE ( `mobile` = '13326477878' ) LIMIT 1
在数据库中执行是没有数据返回的

**Comment by grapewheel** [comment]
![截图录屏_选择区域_20200616162824](https://user-images.githubusercontent.com/490426/84750896-7b10d780-afee-11ea-82c0-bfdc11a72ab1.png)

**Comment by grapewheel** [comment]
如果在数据库能找到对应数据 ，返回值应该是 result = { id: xxx, type: 'exist' }  ，id 应该有的，不应该是 undefined 的！

**Comment by grapewheel** [comment]
@lizheming 我知道为何会出错了，看你们源代码发现你们还是用回 find 这个钩子函数，这个好像不对吧，因为这些钩子函数程序员会二次复写，就会导致了其实数据库返回是undefined，但因为find 钩子函数给 结果增加了 默认参数，导致find返回有数据，从而判断为 exist

源代码是不是不应该调用 find 钩子函数？

**Comment by lizheming** [comment]
`thenAdd()` 只是基础方法的包装，毕竟需求不一样有些人还可能想要这个地方用 `find()`。这块你们的逻辑里兼容下吧，没有数据的时候不添加值就好了。

**Comment by grapewheel** [comment]
好吧，但最好还是文档要提醒下，如果不踩一下坑，然后看你们源代码，真的没有发现这个bug

**Comment by lizheming** [comment]
OK，已添加说明

![image](https://user-images.githubusercontent.com/424491/84757624-f4142d00-aff6-11ea-8cab-541b98cf37d1.png)
