### ISSUE TITLE
this.post()无法获取参数，中间件只应用了serve和router

### ISSUE THREAD

**Issue by wudi98** [thinkjs/thinkjs#1497]
### ENV

OS Platform:MacOS

Node.js Version:10.15.3

ThinkJS Version:2.2.9

### code
// src/config/middleware.js
```js
const path = require('path');
const isDev = think.env === 'development';

module.exports = [
  {
    handle: 'meta',
    options: {
      logRequest: isDev,
      sendResponseTime: isDev
    }
  },
  {
    handle: 'authValidate',
    options: {
      open: true
    }
  },
  {
    handle: 'resource',
    enable: isDev,
    options: {
      root: path.join(think.ROOT_PATH, 'www'),
      publicPath: /^\/(static|favicon\.ico)/
    }
  },
  {
    handle: 'trace',
    enable: !think.isCli,
    options: {
      debug: isDev
    }
  },
  {
    handle: 'payload',
    options: {}
  },
  {
    handle: 'router',
    options: {}
  },
  'logic',
  'controller'
];
```

// src/controller/api/v1/user.js
```js
const Base = require('../../base');

module.exports = class extends Base {
  // 编辑用户
  async editUserAction() {
    this.setCorsHeader();
    console.log('11111112asdas', this.post()); // 这里输出的是{}，获取不到值 。【额外补充，其他get请求可以通过this.get()获取参数】

    let data = JSON.parse(this.ctx.request.body);
    console.log('111111111111', data);

    const user = this.ctx.model('user');
    const res = await user.editUserInfo(data);
    return this.success(res);
  }
};

```

### more description

![image](https://user-images.githubusercontent.com/47620997/86424281-b6144a00-bd14-11ea-9749-717361772af4.png)

**Comment by wudi98** [comment]
thinkjs是3.0.0版本，上面写错了

**Comment by lizheming** [comment]
看看是否是因为 `authValidate` 中间件有影响，如果确认没有的话可以提供一个最小可复现的 demo 给我们看看。
ps. `trace` 中间件最好放在最前面，否则在 `trace` 之前的错误没办法 catch 到。

**Comment by wudi98** [comment]
> 看看是否是因为 `authValidate` 中间件有影响，如果确认没有的话可以提供一个最小可复现的 demo 给我们看看。
> ps. `trace` 中间件最好放在最前面，否则在 `trace` 之前的错误没办法 catch 到。

我之前把authValidate注释了也是不行的。我这边将我的项目开源一下发给您地址，麻烦提供下邮箱

**Comment by wudi98** [comment]
https://gitee.com/wd1336791007/supermarket-system.git

**Comment by lizheming** [comment]
![image](https://user-images.githubusercontent.com/424491/86428896-76ebf600-bd20-11ea-8549-084649715a41.png)
我试了下没问题呀，可以正常获取数据。

**Comment by wudi98** [comment]
![image](https://user-images.githubusercontent.com/47620997/86429126-2d4fdb00-bd21-11ea-8db2-fa85ca6380a0.png)

**Comment by wudi98** [comment]
您截的图看不到下面

**Comment by wudi98** [comment]
![image](https://user-images.githubusercontent.com/47620997/86429318-c1ba3d80-bd21-11ea-815d-2586f7fb4190.png)

**Comment by lizheming** [comment]
看不懂你说的意思，我截图不是已经红框标出来了么。代码这块是 OK 的，没有数据的话你看下你 POST 提交数据的 Content-Type

**Comment by wudi98** [comment]
![image](https://user-images.githubusercontent.com/47620997/86429936-86207300-bd23-11ea-82f2-1bfdfd6cdab4.png)

**Comment by lizheming** [comment]
你截图提供的是 Response Header，需要你自己去看一下 Request Header 的 Content-Type。如果不了解提交数据格式的话建议去看一下 https://imququ.com/post/four-ways-to-post-data-in-http.html 这篇文章。

另外我试了下你截图的这个 editUser 接口，也是可以正常获取到数据的，后附 curl 直接调用接口的命令可以提供测试。所以框架这块是没有问题的，剩下的就是你自己代码逻辑上的问题了，你自己再看看吧。

```
curl --location --request POST 'http://127.0.0.1:8360/api/v1/user/editUser' \
--header 'Content-Type: application/json; charset=utf-8' \
--data-raw '{"a":1,"b":2}'
```
![image](https://user-images.githubusercontent.com/424491/86433381-3181f580-bd2d-11ea-9527-920711448006.png)

**Comment by wudi98** [comment]
> 你截图提供的是 Response Header，需要你自己去看一下 Request Header 的 Content-Type。如果不了解提交数据格式的话建议去看一下 https://imququ.com/post/four-ways-to-post-data-in-http.html 这篇文章。
> 
> 另外我试了下你截图的这个 editUser 接口，也是可以正常获取到数据的，后附 curl 直接调用接口的命令可以提供测试。所以框架这块是没有问题的，剩下的就是你自己代码逻辑上的问题了，你自己再看看吧。
> 
> ```
> curl --location --request POST 'http://127.0.0.1:8360/api/v1/user/editUser' \
> --header 'Content-Type: application/json; charset=utf-8' \
> --data-raw '{"a":1,"b":2}'
> ```
> 
> ![image](https://user-images.githubusercontent.com/424491/86433381-3181f580-bd2d-11ea-9527-920711448006.png)

谢谢，我这里的前端的headers没有写上。
