### ISSUE TITLE
多租户场景下自动切换数据库实现方式，问题出在哪里？

### ISSUE THREAD

**Issue by zhangyanzt** [thinkjs/thinkjs#1498]
## DESC
现有一个单租户系统改造成多租户，打算采用单实例，多数据库的方式实现。对think-model进行了改造：

```js
function model(name, config, m = 'common') {
    const models = app.modules.length ? (app.models[m] || {}) : app.models;
    const Cls = models[name] || Model;
    const modelName = name ? path.basename(name) : name;

    //租户标识注入
    if(think.config('tenant')){
      config.database = think.config('tenant')
    }
    const instance = new Cls(modelName, config);
    // add models in config, it's need in model when get relation model instance
    instance.models = models;
    return instance;
  };
function injectModel(name, config, m) {
    const modelConfig = app.think.config('model', undefined, m);
    const cacheConfig = app.think.config('cache', undefined, m);
    config = helper.parseAdapterConfig(modelConfig, config);

    //租户标识注入
    if(think.config('tenant')){
      config.database = think.config('tenant')
    }
    const instance = model(name, config, m);
    instance._cacheConfig = cacheConfig;
    return instance;
  }
```
 
在实例化model之前修改了数据库名称，并且屏蔽了Debounce，100并发场景下做测试，读取数据正常，但是写入新数据和更新数据时仍然会写入到其他数据库去，似乎传入的database配置在update和add操作时并未生效。想问一下，可能是哪里除了问题，有没有什么解决的思路。

### ENV

OS Platform:Cent OS 7.4

Node.js Version: 12

ThinkJS Version: 3.0

**Comment by lizheming** [comment]
看了下 MySQL 这块在初始化的时候就创建了连接池，连接池的配置里固定了 database 名称，所以我觉得你这么魔改可能没有用。https://github.com/thinkjs/think-mysql/blob/master/index.js#L39-L68

https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#toc-d2e 有一个 `parser` 回调方法允许后期修改数据库的配置，你看看能否使用。

**Comment by zhangyanzt** [comment]
就是之前试过用parser不行，才去魔改的，目前的情况是读取一切正常，但是新增和写入异常，我研究下think-mysql的源码。

**Comment by lizheming** [comment]
为什么 `parser` 不行？看起来你也就是通过 config 改个 database 名称，我觉得没啥问题呀

**Comment by zhangyanzt** [comment]
> 为什么 `parser` 不行？看起来你也就是通过 config 改个 database 名称，我觉得没啥问题呀

高并发场景下测试，3/4的数据是错的，并且是连续出现相同的数据，所以推测跟防抖有关，多个相同的sql请求给合并了，但是配置debounce: false 后还是如此，所以才动手从model里修改。

**Comment by lizheming** [comment]
debounce 的确可能会有影响，因为 debounce 是按照 SQL 语句来做缓存的。https://github.com/thinkjs/think-mysql/blob/4aa875fe652259d7f4ab3311cb676bd80eb226ad/index.js#L227-L228 

理论上 parser 是可以的，因为每次获取连接的时候流程是这样的：

1. 在 `think-model-mysql` 中调用 parser 方法合并生成最终的 config https://github.com/thinkjs/think-model-abstract/blob/master/lib/query.js#L38
2. 获得 config 之后再根据它去获取连接的实例 https://github.com/thinkjs/think-model-abstract/blob/master/lib/query.js#L42 
3. 连接实例对应到 MySQL 中就是 https://github.com/thinkjs/think-mysql 注意代码最终返回的是 `think-instance` 的包装 https://github.com/thinkjs/think-mysql/blob/4aa875fe652259d7f4ab3311cb676bd80eb226ad/index.js#L271
4. 在 `think-instance` 的逻辑里实际上就是对实例进行了缓存，缓存的 key 就是整个传入的配置 https://github.com/thinkjs/think-instance/blob/master/index.js#L25-L41

按照这个流程所以理论上只要 parser 返回的配置不同，那么 `think-instance` 这边缓存的 md5 key 就不一样就能获取到新的连接实例，而在新的 `think-mysql` 连接实例中实例化的时候就会使用新的配置。

大体上流程就是这个流程，你可以按照这个流程看看具体问题出在哪里。上述所有的操作都是同步的，所以高并发下应该也是可以的。

**Comment by zhangyanzt** [comment]
好嘞，这样流程清楚多了，我研究下

**Comment by lizheming** [comment]
我今天试了下，其实没有那么复杂，直接创模型的时候就可以动态传入配置的，这个配置会合并到实例的 `config` 属性中，然后在上一个评论中的流程1中进行一次合并。所以不需要魔改的其实…

```js
const UserModel = this.model('user', {database: 'xxx'});
```

**Comment by zhangyanzt** [comment]
> 我今天试了下，其实没有那么复杂，直接创模型的时候就可以动态传入配置的，这个配置会合并到实例的 `config` 属性中，然后在上一个评论中的流程1中进行一次合并。所以不需要魔改的其实…
> 
> ```js
> const UserModel = this.model('user', {database: 'xxx'});
> ```

太好了！这个方案确实可行，但是代码修改量比较大，我试试覆写下model方法让自动添加。
之前修改parser的方案实验也可行，出现问题的原因是，在高并发场景下，controller中用think.config中设置租户id，在model中读取到可能不一致，通过设置global全局变量也不行，研究了一上午没找到解决方法。

**Comment by lizheming** [comment]
嗯嗯，实例化模型的方法在文档中都有描述 https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#toc-7da 。另外 ThinkJS 是单实例模型，所以启动后的 `global` , `think` 变量所有的请求都是对应的同一份数据，请求相关的数据值在 `ctx` 中存在。所以和用户和请求相关的数据不要存在 `global`, `think` 中，除非是你自己做了哈希映射。
