### ISSUE TITLE
NODE_ENV=test时，windows和linux所有应用均无法启动。

### ISSUE THREAD

**Issue by shrek82** [thinkjs/thinkjs#1507]
通过脚手架创建全新的应用，当环境变量NODE_ENV=test时，development.js、test.js、production.js 三个启动文件均无法正常启动，也都没有任何报错，最终会卡住。

**Comment by lizheming** [comment]
https://github.com/thinkjs/thinkjs/blob/master/lib/application.js#L206 这是正常的行为，我们会根据 NODE_ENV=test 判断是在单元测试环境中运行，由于单元测试过程中不需要真的进行端口监听，所以不会发生端口的监听。
