### ISSUE TITLE
如何禁止某个控制器被访问？

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#1510]
现在是这样，我写了个控制器基类curd，然后其他article、user这些类继承自curl类。
我只需要在article、user这些类的构造函数那把model名称传递给curl这个父类里，就能共用curd类的一些基本的查询修改删除方法了。

但是目前的问题是，
用户通过浏览器也能直接访问这个curd类的action，这属于无意义的操作，虽然我可以在_before里加个判断，如果没有子类传递来的model名称，就直接返回400，但这样做貌似不太优雅。有没有更好的方法？

**Comment by lizheming** [comment]
我能想到的一些方法
1. 给基类创建个同名 logic，然后在 `__before()` 中直接 `this.ctx.throw(404)` 
2. 自定义路由将基类的路由指定到 404 
3. 在基类的 `__before()` 中判断 `this.contructor === Base` 的话就 404 
还有你说的方法，理论上应该都是可以的，你可以参考一下

**Comment by KuoKongQingYun** [comment]
> 我能想到的一些方法
> 
> 1. 给基类创建个同名 logic，然后在 `__before()` 中直接 `this.ctx.throw(404)`
> 2. 自定义路由将基类的路由指定到 404
> 3. 在基类的 `__before()` 中判断 `this.contructor === Base` 的话就 404
>    还有你说的方法，理论上应该都是可以的，你可以参考一下

感谢建议，我改成1这个方案了，后面两个也可以，只不过如果有多个类似的基类，就得单独设置。1相对通用一点。
