### ISSUE TITLE
think-model对json类型的字段支持不大好

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#1511]
比如我friends字段是JSON类型的
`model.where({id:1}).update({name:"test",friends:[1,2]});`
竟然会不起作用
必须先把[1,2]通过JSON.stringify转成字符串才能用update来更新

另一方面，select读取的时候，返回结果里的json类型字段也是字符串形式的，按道理应该直接可以转为object吧。但实际每次都要自己处理，本来javascript对JSON就“天然支持“……

**Comment by lizheming** [comment]
是的，think-model 对 `JSON` 数据类型的支持还不是非常好，我最近也碰到了这个问题，我之后看看吧，如果你那边有时间也可以帮忙提个 PR 处理下。

**Comment by KuoKongQingYun** [comment]
> 是的，think-model 对 `JSON` 数据类型的支持还不是非常好，我最近也碰到了这个问题，我之后看看吧，如果你那边有时间也可以帮忙提个 PR 处理下。

不好意思  这两天在外面，现在才看到，您那边已经提了pr了，我暂时关掉这个issue，麻烦了。

**Comment by lizheming** [comment]
`think-model-mysql@1.1.3` 已发布，增加了一个 `jsonFormat` 配置，支持 JSON 类型数据直接存储以及读取后自动解析。

**Comment by grapewheel** [comment]
> `think-model-mysql@1.1.3` 已发布，增加了一个 `jsonFormat` 配置，支持 JSON 类型数据直接存储以及读取后自动解析。

这个好，以前都要在beforeAdd和beforeUpdate 那里自己手动写 序列和反序列

**Comment by KuoKongQingYun** [comment]
> > `think-model-mysql@1.1.3` 已发布，增加了一个 `jsonFormat` 配置，支持 JSON 类型数据直接存储以及读取后自动解析。
> 
> 这个好，以前都要在beforeAdd和beforeUpdate 那里自己手动写 序列和反序列
> 
> 但在那里设置呢？文档没有提及

adapter里mysql的设置里，也就是你配置数据库名称和密码的地方
