### ISSUE TITLE
think-i18n 多语言设计太复杂了

### ISSUE THREAD

**Issue by liuhuanhui** [thinkjs/thinkjs#1513]
zh-CN.js文件的
```
module.exports = {
  localeId: "zh-CN",
  translation: {
    messages: {
      "": {
        domain: "messages",
        lang: "zh-CN",
        plural_forms: "nplurals=2; plural=(n != 1);",
      },
      "name": ["中文版本", "v1"],
    },
  },
};
```
不知道messages下的""空key这个对象domain，lang，plural_forms意义是什么，删除会报错

**Comment by liuhuanhui** [comment]
还有 view里面为什么定义成__两根下滑线

**Comment by lizheming** [comment]
think-i18n 底层是使用的 http://messageformat.github.io/Jed/ 这个模块进行的 i18n 翻译，所以配置这块有什么问题可以去搜一下 Jed 相关的配置，空 key 这个相当于对 `messages` 这个的语言配置，里面都是一些必要字段。`__` 定义双下划线方法主要是沿袭了之前的模板语言翻译的时候是使用类似的方法名称。

不过 `think-i18n` 在我看来的确也是非常复杂，大部分简单场景其实就只需要一个简单的对象映射即可。你可以搜一下 `koa i18n` 找一下类似的模块使用即可。

**Comment by liuhuanhui** [comment]
对的，大部分场景都是 语言包做下 映射下好了

**Comment by liuhuanhui** [comment]
直接用加个 extend这个方式了。简单快捷。

module.exports = {
  $t(key) {
    const headerLocal = this.ctx.header["accept-language"].split(",")[0];
    const queryLocal = this.get("locale");
    const cookieLocale = this.cookie("locale");
    const local = queryLocal || cookieLocale || headerLocal;
    return require(`../i18n/${local}`)[key];
  },
};

**Comment by liuhuanhui** [comment]
@lizheming  能不能扩展往view里面扩展$t方法～给点思路～

**Comment by lizheming** [comment]
直接调 this.assign 方法把 t 函数注进去就好啦

**Comment by liuhuanhui** [comment]
> 直接调 this.assign 方法把 t 函数注进去就好啦

那要在每个action都这样做，我试过在middleware里面去做的话，assign还不存在

**Comment by lizheming** [comment]
可以看看 think-i18n 看看它是怎么注入 `__` 的

**Comment by liuhuanhui** [comment]
think-i18n
```
 if (app) {
      app.on('viewInit', (view, controller) => {
        view.assign('__', controller.getI18n());
      });
    }
```
我在bootstrap master下
```
// invoked in master

think.app.on("appReady", () => {
    think.app.on('viewInit', (view, controller) => {
        const name = '测试';
        view.assign('t', name);
      });
  })
```
我去看过源代码了，一直再尝试，没注入进去。明天再看吧

**Comment by liuhuanhui** [comment]
> 可以看看 think-i18n 看看它是怎么注入 `__` 的

已解决～
