### ISSUE TITLE
中间件中使用自定义错误模板是否可以用nunjucks等模板引擎的语法

### ISSUE THREAD

**Issue by DickyNet** [thinkjs/thinkjs#1521]
// your detail description 
如题
自定义错误模板中是否可以用nunjucks等模板引擎的语法

**Comment by lizheming** [comment]
现有的 `think-trace` 中间件由于需要兼顾到有模板和无模板的项目，所以是没有使用模板引擎的。如果你需要的话，可以考虑 fork trace 自己写一个 https://github.com/thinkjs/think-trace

**Comment by DickyNet** [comment]
> ~现有的 `think-trace` 中间件由于需要兼顾到有模板和无模板的项目，所以是没有使用模板引擎的。如果你需要的话，可以考虑 fork trace 自己写一个 https://github.com/thinkjs/think-trace ~
> 
> 更新，看了下感觉可以通过自定义错误返回来实现
> 
> ```
> const trace = require('think-trace');
> module.exports = [
>   {
>     handle: trace, 
>     options: {
>       error(err, ctx) {
>         return ctx.display('404.html');
>       }
>     }
>   }
> ];
> ```

可惜ctx不支持display方法 :(

**Comment by lizheming** [comment]
嗯，可以给 think-view 提个 PR，在这加一下应该可以 https://github.com/thinkjs/think-view/blob/master/index.js 你试试。现有的话估计你直接自己调 nunjucks 模块处理了

**Comment by DickyNet** [comment]
算了，还是等官方实现吧。error.html模板我直接调用写死的html，不嵌套公用的头尾了

**Comment by lizheming** [comment]
突然有个想法，你如果不需要错误信息的话直接 error 里 redirect 跳转到一个 500 的路由去应该也可以的吧

**Comment by DickyNet** [comment]
error.html里可以调用{{errMsg}}，能拿到404等错误，看了trace里源码是直接替换这个固定的字符串变量的

**Comment by lizheming** [comment]
对，因为 trace 不确定是否项目里有 `think-view` 这个模块，所以不能依赖模板语法。如果你要 errMsg 的话可以 redirect 的时候通过参数的形式带过去。目前可能这样做会简单点

**Comment by DickyNet** [comment]
> 对，因为 trace 不确定是否项目里有 `think-view` 这个模块，所以不能依赖模板语法。如果你要 errMsg 的话可以 redirect 的时候通过参数的形式带过去。目前可能这样做会简单点
好的。谢谢解答

**Comment by DickyNet** [comment]
> 



> 

为毛 ctx.redirect在trace的error回调函数里不起作用啊？
