### ISSUE TITLE
请问websocket怎么和微信小程序的websocket对接

### ISSUE THREAD

**Issue by ktkxc** [thinkjs/thinkjs#1660]
## DESC
    因为微信小程序引用不了socket.io.js，作为客户端的微信小程序怎么和服务器进行websocket通信？
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
https://github.com/thinkjs/think-websocket-ws 这是原生的 WebSocket 的 Adapter，你可以试试？

**Comment by ktkxc** [comment]
@lizheming 感谢提供方式，但是这种怎么和之前的socketio同时存在配置adapter，因为之前的socketio已经在多处使用，配置了ws，则socketio不能用，有socketio则ws不能配置，因为都是exports.websocket

**Comment by lizheming** [comment]
目前应该是只能新启一个项目了，WebSocket 好像是唯一的，不太好一个项目多个。

**Comment by ktkxc** [comment]
![QQ截图20201203183437](https://user-images.githubusercontent.com/30922230/100998333-57d6e600-3596-11eb-8fc4-92042412a5f0.jpg)
研究了下，感觉这样改动可以，加上2次 websocket(think.app),
  websocket(think.app,"wswebsocket"),，还没有多方测试，只是2个socket都能初始化和send，不知道你们能不能升级下那个文件；

**Comment by lizheming** [comment]
你可以先自己本地修改下试试。

**Comment by ktkxc** [comment]
因为这些socket整体原理，我还是整不明白，希望你们能从整体框架上整成2种方式都能用的，方便大家使用，感谢！

**Comment by lizheming** [comment]
目前应该是太不太好支持的，WS 需要启动实例化配置，不太好做多 adapter 动态切换。我个人建议你还是分开项目比较简单。
