### ISSUE TITLE
Use think-cli generate vue template, 'To get started' is flawed

### ISSUE THREAD

**Issue by DullSword** [thinkjs/thinkjs#1661]
### ENV

OS Platform: windows

Node.js Version: 14.15.1

Think-cli Version: 2.2.9 

### code

```js
 think-cli · Generated vuetemplate

  To get started:

  # enter path
  $ cd vuetemplate

  # install dependencies:
  $ npm install

  # run the app
  $ npm start
```

### more description

如何开始的提示不太对，一开始我按提示来，提示找不到package.json，看了下生成的目录才明白。think-cli那边没开issue，所以就在这提了，不是大问题，如果理解错误，请包涵。

How to start is not quite right. At the beginning, I followed this, tell me that could not be found package.json. After looking at the generated directory, I understood. think-cli no open issue , so I mentioned it here. It is not a big problem. If i understand it wrong, please forgive me.

**Comment by lizheming** [comment]
不好意思，之前已经看到了你的 issue 但是忘记回复你了。你说的地方的确有问题，可以优化一下。

Sorry, I have read the issue but forget reply to you. It's a really problem that we can enhance it.

**Comment by DullSword** [comment]
😊
