### ISSUE TITLE
定时任务中获取controller实例

### ISSUE THREAD

**Issue by anjina** [thinkjs/thinkjs#1664]
## DESC

请问在定时任务中，可以获取到 controller实例吗， 并且调用controller实例中定义的方法
### ENV

OS Platform:

Node.js Version: 12.0+

ThinkJS Version:  3.0

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
定时任务的 `handle` 配置可以直接是路由地址调用路由的，你试试 https://thinkjs.org/zh-cn/doc/3.0/crontab.html#toc-224
