### ISSUE TITLE
model切换type时，获取的数据异常

### ISSUE THREAD

**Issue by ArkYk** [thinkjs/thinkjs#1665]
### ENV

OS Platform:win10

Node.js Version:12.13.0

ThinkJS Version:3.0.0

### code

```js
// your code here
const a=await this.model('goods','A').select();
const b=await this.model('goods','B').select();
```

### error message

```
// your error message here
mysql://root:123456@127.0.0.1:3306/B
```

### more description

// your detail description 
1.数据A和数据库B，在同一台电脑。配置文件中分为A和B两种type，除了database属性分别是A和B，其他属性一样。两者的goods表结构相同:[id,quantity]。其中id相同，quantity不同。

2.在同一个Action中，运行上面的代码，第二句代码获取的数据和第一句一样，即a.quantity=b.quantity。

3.我观察到日志运行第二句时，没有进行sql查询的日志，只有连接数据库的日志。即上面的error message。相当于放弃了第二句的sql查询，直接返回了第一句sql查询的结果。

4.当我加了第三条语句const b1=await this.model('goods','B').select();时，数据正常。即获取的数据和数据库中相同。

**Comment by lizheming** [comment]
如果有动态的切换的需求，建议把 `debounce` 功能关闭一下，https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#toc-839

**Comment by ArkYk** [comment]
> 如果有动态的切换的需求，建议把 `debounce` 功能关闭一下，https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#toc-839

感谢你的及时回复，但我个人觉得我这是已经切换了数据库，不应该算作相同sql[A:'SELECT * FROM A',B:'SELECT * FROM B']，在debounce 时应该判别下数据库。并且我的第三句代码与第二句是相同的，如果debounce 生效，数据也应该会与第二句相同才对。
如果我的需求既希望数据库中debounce生效，又避免我上面bug。通过您的方法就无法实现了。

**Comment by lizheming** [comment]
嗯，debounce 需要一个唯一 key，目前是使用 SQL 语句作为 key 的，https://github.com/thinkjs/think-mysql/blob/master/index.js#L227-L228 可以考虑将 MySQL 连接配置也传入其中，目前你先临时关闭 debounce 处理吧。

**Comment by ArkYk** [comment]
> 嗯，debounce 需要一个唯一 key，目前是使用 SQL 语句作为 key 的，https://github.com/thinkjs/think-mysql/blob/master/index.js#L227-L228 可以考虑将 MySQL 连接配置也传入其中，目前你先临时关闭 debounce 处理吧。

好的，期待您的改进
