### ISSUE TITLE
ts中使用mysql作为model层时没有定义beforeAdd、beforeUpdate方法

### ISSUE THREAD

**Issue by wujiiu** [thinkjs/thinkjs#1666]
## DESC
查了下官方文档发现使用MongoDB做model时的文档里面没有写beforeAdd钩子，不过在关系型数据库的文档里面写了，后来尝试做扩展但是没有找到扩展的方法
### ENV

OS Platform:
Mac os 10.15.7 (19H2)
Node.js Version:
v14.5.0
ThinkJS Version:
3.2.13
### code

```js
// your code here
```
![image](https://user-images.githubusercontent.com/31948326/108318598-0f28e380-71fb-11eb-8af0-865c1798d889.png)

### error message

```
Property 'beforeAdd' does not exist on type 'Model'.ts(2339)
```

### more description

// your detail description

**Comment by lizheming** [comment]
https://github.com/thinkjs/think-model/blob/master/index.d.ts 嗯可以在这里提个 PR 帮忙补充一下

**Comment by lizheming** [comment]
fixed with https://github.com/thinkjs/think-model/pull/13
