### ISSUE TITLE
thinkjs是不是废弃了

### ISSUE THREAD

**Issue by stys35** [thinkjs/thinkjs#1667]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

我看自18年以后已经不再更新了
3.2.82018.06.20
移除 Bluebird Promise Polyfill

更新 think-router 模块依赖

是放弃这个项目了吗

**Comment by zhangbowy** [comment]
thinkjs开发者飘过！！！！

**Comment by zhangbowy** [comment]
> ## DESC
> ### ENV
> OS Platform:
> 
> Node.js Version:
> 
> ThinkJS Version:
> 
> ### code
> ```js
> // your code here
> ```
> 
> ### error message
> ```
> // your error message here
> ```
> 
> ### more description
> 我看自18年以后已经不再更新了
> 3.2.82018.06.20
> 移除 Bluebird Promise Polyfill
> 
> 更新 think-router 模块依赖
> 
> 是放弃这个项目了吗

据说是因为稳定 没更新了

**Comment by stys35** [comment]
> > ### more description
> > 我看自18年以后已经不再更新了
> > 3.2.82018.06.20
> > 移除 Bluebird Promise Polyfill
> > 更新 think-router 模块依赖
> > 是放弃这个项目了吗
> 
> 据说是因为稳定 没更新了


好吧，这个项目还是很不错的，对熟悉thinkphp的人非常友好

**Comment by lizheming** [comment]
你好，还有在维护的，有问题可以 issue 反馈。
