### ISSUE TITLE
How to specify the Keep Alive timeout parameter in the thinkjs application.

### ISSUE THREAD

**Issue by shasharoman** [thinkjs/thinkjs#1668]
Such as the title, it should be possible to specify the default Keep-Alive time of Http Server, but I did not find relevant information in the document.

![image](https://user-images.githubusercontent.com/5089251/110424699-29f5c600-80de-11eb-97a2-a45a8042a2d9.png)

The returned timeout=5 in the picture, I hope to increase this value to match the outer nginx.

**Comment by lizheming** [comment]
https://nodejs.org/api/http.html#http_server_keepalivetimeout

```
//production.js
think.app.keepAliveTimeout = 10000;
instance.run();
```

**Comment by shasharoman** [comment]
okie, thx.

**Comment by shasharoman** [comment]
think.app.on('appReady', () => {
    think.app.server.keepAliveTimeout = 60 * 1000;
})
