### ISSUE TITLE
cookie中的PHPSESSID和thinkphp_show_page_trace属性名可以修改吗

### ISSUE THREAD

**Issue by stys35** [thinkjs/thinkjs#1671]
访问thinkjs服务的时候，
cookie列表中有
PHPSESSID和thinkphp_show_page_trace两个key，请问可以修改这个名称吗？

**Comment by lizheming** [comment]
ThinkJS 中没有定义这两个 cookie 名称

**Comment by stys35** [comment]
> ThinkJS 中没有定义这两个 cookie 名称

已经查明问题，和thinkphp混合部署的问题，感谢
