### ISSUE TITLE
this.file 无法获取 node version > v12

### ISSUE THREAD

**Issue by cube3power** [thinkjs/thinkjs#1676]
### ENV

OS Platform:

Node.js Version: v14.16.0

ThinkJS Version: v2.3.0

### code

```js
async uploadAction()
  {
    console.log(this.http.file("file"))
  
    
    let file = this.file('file');
    console.log(`upload file->`,file)

    return this.success({status:file})
    
  }
```

### error message

```
无法获取 file {}
```

### more description

// your detail description 
 node v10.23.0
是可以获取的

{fieldName: 'file', originalFilename: 'intern.jpg', path: 'D:\works\thinkjsNodejsv12\testv14\runtime\upload\iK87KSAhOmDBmDUucD38TWGo.jpg‘}

{
  host: "localhost:8360",
  connection: "keep-alive",
  "content-length": "8491",
  "sec-ch-ua": "\" Not;A Brand\";v=\"99\", \"Microsoft Edge\";v=\"91\", \"Chromium\";v=\"91\"",
  accept: "application/json, text/javascript, */*; q=0.01",
  "x-requested-with": "XMLHttpRequest",
  "sec-ch-ua-mobile": "?0",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36 Edg/91.0.864.59",
  "content-type": "multipart/form-data; boundary=----WebKitFormBoundaryrIziwUlAnpKograk",
  origin: "http://localhost:8360",
  "sec-fetch-site": "same-origin",
  "sec-fetch-mode": "cors",
  "sec-fetch-dest": "empty",
  referer: "http://localhost:8360/",
  "accept-encoding": "gzip, deflate, br",
  "accept-language": "zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6",
}

**Comment by lizheming** [comment]
`this.file()` 的逻辑在这块 https://github.com/thinkjs/thinkjs/blob/2.x/src/core/http.js#L411-L419 你可以本地调试一下看看具体问题在哪里

**Comment by cube3power** [comment]
@lizheming 您好，通过调试发现在中间件 parse_form_payload.js 是可以获取文件信息的，存在一个问题是parse_form_payload.js 赋值给http._file 的时间远远落后于 controller 获取 this.file()  ,导致在控制器里无法获取。此问题如何解决呢？

**Comment by lizheming** [comment]
parse_form_payload 肯定是在 controller 之前执行的，为何会导致赋值落后于  controller 的执行时间呢？下面是相关代码的位置

https://github.com/thinkjs/thinkjs/blob/2.x/src/config/hook.js#L5
https://github.com/thinkjs/thinkjs/blob/2.x/src/core/think.js#L604
https://github.com/thinkjs/thinkjs/blob/2.x/src/core/http.js#L151
https://github.com/thinkjs/thinkjs/blob/2.x/src/core/app.js#L64

而且这个解释似乎也无法说明你反馈的低版本可以高版本不行的问题？

**Comment by cube3power** [comment]
@lizheming  问题解决了，请升级  "multiparty": "^4.1.2", 到  "multiparty": "^4.2.2",  
 multiparty 已经解决
form-data file is empty with node version 14.1.0 #226
https://github.com/pillarjs/multiparty/issues/226

@lizheming  谢谢！

**Comment by lizheming** [comment]
@cube3power 优秀，给你点个赞。如果方便的话可以帮忙提个 PR 把依赖的版本更新一下，非常感谢~

**Comment by zdhsoft** [comment]
@lizheming multiparty在thinkjs 2.3.0中，没有升级啊！

**Comment by lizheming** [comment]
@zdhsoft 嗯，要不你帮忙提个 PR 处理下？

**Comment by zdhsoft** [comment]
发了PR了，你处理一下
