### ISSUE TITLE
Spelling errors in English documents

### ISSUE THREAD

**Issue by anprettyboy** [thinkjs/thinkjs#1678]
## Spelling errors in English documents
Action Execution
Action execution is done via think-controller middleware, According to ctx.action value to match controller xxxAction mehtod, call this method and related hook method, **ithe** specific order as bellow:

ithe,There is no word called it

**Comment by anprettyboy** [comment]
method也写错成了'mehtod'

**Comment by lizheming** [comment]
Thank you for your mention, I fixed theme at https://github.com/thinkjs/en.thinkjs.org/commit/b07b21722eae1e11470674875180ac801c0251bf and https://github.com/thinkjs/en.thinkjs.org/commit/a82944a69d6060e599d951a01f59aad4c6884d0a. btw, it's glad to click the bottom link to help us fix those typo.

![image](https://user-images.githubusercontent.com/424491/125764420-de1b0c18-0825-43a4-9058-adea34457de9.png)
