### ISSUE TITLE
反馈一个bug

### ISSUE THREAD

**Issue by geesmart** [thinkjs/thinkjs#1679]
think-model-mysql  中  db.getSchema 这个函数 

             "name": "id",
            "type": "int(11)",
            "required": true,
            "default": "",
            "primary": true,
            "unique": false,
            "autoIncrement": true,
            "tinyType": "int",
            "unsigned": true,

数据库的id字段是 not null , 但是这里返回  "required": false

**Comment by lizheming** [comment]
`think-model-mysql@1.1.6` 已发布，感谢反馈。
