### ISSUE TITLE
取上传文件，结果为{}

### ISSUE THREAD

**Issue by zdhsoft** [thinkjs/thinkjs#1685]
### ENV

OS Platform:

Node.js Version:
14.x
ThinkJS Version:
2.2.18
### code

```js
// your code here
think.file()
```

### error message
无报错，但是报不到上传文件的信息。
```
// your error message here
```

### more description
上传文件功能。
在node.js 10.x，node.js 8.x的版本， think.file()返回正常
将node升级到12，14后,think.file()返回{} 空对象。
// your detail description

**Comment by lizheming** [comment]
release issue https://github.com/thinkjs/thinkjs/issues/1676

**Comment by zdhsoft** [comment]
已经确认是，第三方库：multiparty的问题。https://github.com/pillarjs/multiparty/commit/6afaf7aa02121d7542cc1d9f7b42a563d215e521
