### ISSUE TITLE
反馈一个BUG

### ISSUE THREAD

**Issue by geesmart** [thinkjs/thinkjs#1693]
当数据库表 ID 类型为 bigint 的时候，通过 select() 会报错

ER_DATA_TOO_LONG: Data too long for column

这个好像是 node.js 的问题，但是请问下，这个怎么处理更好点呢？

**Comment by lizheming** [comment]
https://github.com/mysqljs/mysql 有两个 `supportBigNumbers` 和 `bigNumberStrings` 两个配置在 adapter config 里配下
