### ISSUE TITLE
think-model-sqlite支持的版本太老了

### ISSUE THREAD

**Issue by 332lfgb6** [thinkjs/thinkjs#1694]
```bash
npm i think-model-sqlite --registry=https://registry.npmmirror.com/
```
## 以下是报错
![图片](https://user-images.githubusercontent.com/51245335/151689580-a1c37676-00e5-4f1a-8911-b305b634d89e.png)

**Comment by lizheming** [comment]
http://npm.anvaka.com/#/view/2d/think-model-sqlite think-model-sqlite 整个依赖树里都没有使用到 `got@5.7.1` 这个模块，你可以查看下是否是你自己的其它依赖导致的。

**Comment by 332lfgb6** [comment]
> http://npm.anvaka.com/#/view/2d/think-model-sqlite think-model-sqlite 整个依赖树里都没有使用到 `got@5.7.1` 这个模块，你可以查看下是否是你自己的其它依赖导致的。

解决了，要先`npm i node-gyp`和`npm i windows-build-tools`一次才行。
