### ISSUE TITLE
怎么进行真机调试？

### ISSUE THREAD

**Issue by 332lfgb6** [thinkjs/thinkjs#1697]
类似于vue中的这个：
![图片](https://user-images.githubusercontent.com/51245335/154901915-d8032120-0578-4d2f-be0d-eaf727a34070.png)
发送网络请求的时候，调用的是127.0.0.8306，但是对于手机来说，无法请求到本地服务器的数据。
实现类似于这样的效果：
![图片](https://user-images.githubusercontent.com/51245335/154902338-7a2056ec-6fa8-4be5-b148-6cc3b49d099b.png)

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/config.html host 配置为你的局域网 IP 或者直接配置成 `0.0.0.0` 都可以
