### ISSUE TITLE
distinct貌似有bug

### ISSUE THREAD

**Issue by 332lfgb6** [thinkjs/thinkjs#1700]
### ENV

OS Platform: windows10

Node.js Version: v16.9.0

ThinkJS Version: 2.2.9

### more description

![图片](https://user-images.githubusercontent.com/51245335/160968240-b97f16f4-c5b4-45a2-a78b-ad7395364867.png)
对数据表comment2查评论总数，结果如下，没有问题，是6.
![图片](https://user-images.githubusercontent.com/51245335/160968397-9efe7fb7-44d5-498f-b5ef-dcc2b1f12c71.png)
对数据表comment2去重后查评论数，出现问题，预期是5，但是实际还是6。
![图片](https://user-images.githubusercontent.com/51245335/160968579-af5e76db-64ee-40ca-bf67-b5d1223b7b7c.png)

#### 这种现象在`select`上不会出现
![图片](https://user-images.githubusercontent.com/51245335/160968922-49ebb23c-d13a-4b1d-b3dd-20241ce06688.png)
上图没有问题，查询结果是6个RowDataPacket
![图片](https://user-images.githubusercontent.com/51245335/160969154-ce4679d6-217e-454c-a483-93e86f515a30.png)
上图只有5个RowDataPicket，不过是去重了的，所以也没问题。

#### 这种现象在`countSelect`上也会出现问题
![图片](https://user-images.githubusercontent.com/51245335/160969510-3c5599b5-e87a-4bc9-90df-8df79632f3da.png)
上述图片中，查询的是第三页的数据，查到了两条数据，总数是6，没有问题。
![图片](https://user-images.githubusercontent.com/51245335/160969662-1485e6d2-c2e6-4580-bbf3-5f64bd4aa050.png)
上述图片中，查询的是第三页的数据，查到的只有一条数据，但是总数显示的还是6，感觉应该显示5才对。

## 我是在一下场景下，发现该问题的。
![图片](https://user-images.githubusercontent.com/51245335/160969954-a2492044-f3c6-47aa-98ff-de29c824db10.png)
![图片](https://user-images.githubusercontent.com/51245335/160970194-d750de30-f314-4ec6-9f18-e7677f2abb1d.png)
以上一个是评论表，一个是评论对应的图片表，一对多的关系。总数是6，带有图片的总数是2，就是前2条评论。
查询评论的总数，很简单，用以下方式即可。
```js
this.model('comment2').count()
```
查询必须带有图片的评论的总数时就出现问题了。我是用的内连接的方式查询的。
![图片](https://user-images.githubusercontent.com/51245335/160971186-039fe800-daf9-4ded-a36b-bbd3061fd48d.png)
上述图片是，内连接后的查询结果，4条数据没有问题。
![图片](https://user-images.githubusercontent.com/51245335/160971448-1e26d58b-dac7-4f58-82b7-47a9e9db0ec1.png)
上述图片是，去重后的查询结果，2条数据没有问题。
![图片](https://user-images.githubusercontent.com/51245335/160971606-f5a76932-c426-4f1b-adaa-ed415ab37fc1.png)
上图发现，把select改成了count，答案是4，而不是2.
> 注意：这个bug我是在别人的开源项目中发现的，那个nideshop商城 https://github.com/tumobi/nideshop  。他计算带有图片的评论数量时，出现问题了：带有图片的评论比总评论还要多。
![图片](https://user-images.githubusercontent.com/51245335/160972033-0b5901e4-ff80-4de2-bfac-80006ef784ab.png)
## 如果这个distinct没有问题，那有什么办法可以求出带有评论的图片的数量吗？实在想不到了，请指教。

**Comment by yoder** [comment]
mdel('xxx').count('distinct(content)')
