### ISSUE TITLE
如何禁用 ESLINT 检测功能

### ISSUE THREAD

**Issue by chenqiandaxianren** [thinkjs/thinkjs#1706]
如何整个项目全局禁用 ESLint 检测功能?

**Comment by lizheming** [comment]
编辑器自行关闭 ESLint 检测即可，默认的项目模板只有手动触发，没有自动检测。https://github.com/think-template/standard/blob/master/template/eslintrc

**Comment by chenqiandaxianren** [comment]
好的，多谢😄


在 2022年7月22日 12:22，Austin ***@***.***> 写道：


编辑器自行关闭 ESLint 检测即可，默认的项目模板只有手动触发，没有自动检测。https://github.com/think-template/standard/blob/master/template/eslintrc
