### ISSUE TITLE
Ubuntu server 22.04.01  执行安装 npm install -g think-cli  后 提示 uuid@3.4.0: Please upgrade  to version 7 or higher. 

### ISSUE THREAD

**Issue by Frank0400Dong** [thinkjs/thinkjs#1707]
## DESC
Ubuntu server 22.04.01 执行安装 npm install -g think-cli  后 
提示  **npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.** 
Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
### ENV

OS Platform:
 Description:Ubuntu 22.04.1 LTS 
linux内核版本号:Linux version 5.15.0-46-generic (buildd@lcy02-amd64-115)   
gcc编译器版本号:gcc version 11.2.0             
Ubuntu版本号:Ubuntu 11.2.0-19ubuntu1        

npm Version: 
8.1.2 
Node.js Version:
v16.17.0
ThinkJS Version:
计划安装 2.2.9  
### code
 npm install -g think-cli

### error message
命令行窗口:
![Think问题](https://user-images.githubusercontent.com/111981012/186933605-9efb3ba6-efc4-4ffe-ab44-90628e8b2ca3.png)

Log:
1372 timing reifyNode:node_modules/think-cli/node_modules/utility Completed in 1743ms
1373 warn deprecated uuid@3.4.0: **Please upgrade  to version 7 or higher**.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
1374 timing reifyNode:node_modules/think-cli/node_modules/uuid Completed in 1743ms

### more description
1.尝试降低到 Ubuntu server 20.04，但问题依旧... 
2.我目前分析是npm安装开源框架think-cli时，函数uuid@3.4.0已经弃用了

__想了两个解决的方向_，可能理解的不太对，想请教下大家：）_
A.升级npm中的uuid@version 
尝试参考链接的解决方案后，问题依旧：
https://github.com/nteract/hydrogen/issues/2151
B.在thinkjs开源框架的源码，升高uuid@version版本编译后上传到npm，在用npm重新安装

**Comment by lizheming** [comment]
看了下 uuid 是在 `think-helper` 模块中使用的，warning 不影响使用。如果可以的话，可以提个 PR 帮忙更新下 think-helper 的 uuid 版本号。

**Comment by zhangbowy** [comment]
> 下uuid 是`think-helper`如果模块中使用的，warning 不影响使用的话，提个PR 帮忙更新下think-helper 的uuid 可以在版本号。

提了 https://github.com/thinkjs/think-helper/pull/7

**Comment by Frank0400Dong** [comment]
> > 下uuid 是`think-helper`如果模块中使用的，warning 不影响使用的话，提个PR 帮忙更新下think-helper 的uuid 可以在版本号。
> 
> 提了 [thinkjs/think-helper#7](https://github.com/thinkjs/think-helper/pull/7)

Thanks,多谢您了，我也学着修改下，这次确实不太会修改，不知改怎么入手...

**Comment by Frank0400Dong** [comment]
> > > 下uuid 是`think-helper`如果模块中使用的，warning 不影响使用的话，提个PR 帮忙更新下think-helper 的uuid 可以在版本号。
> > 
> > 
> > 提了 [thinkjs/think-helper#7](https://github.com/thinkjs/think-helper/pull/7)
> 
> Thanks,多谢您了，我也学着修改下，这次确实不太会修改，不知改怎么入手...



> 看了下 uuid 是在 `think-helper` 模块中使用的，warning 不影响使用。如果可以的话，可以提个 PR 帮忙更新下 think-helper 的 uuid 版本号。


您好，
1.1.我这边的情况是影响使用了...
尝试如下
1）执行了清缓存
npm cache clean
2）强制安装最新版
npm install -g uuid@latest --force
3）确认版本
npm list --depth=0
4）最后再重新安装 think-cli
npm install -g think-cli**
5）还是报 “ uuid@3.4.0: Please upgrade to version 7 or higher”
6）查询安装情况提示
root@ming:~# thinkjs -v
-bash: thinkjs: command not found

2.小伙伴zhangbowy 已经修改了，是不是您那边在合并下,
我这边就能继续执行这个指令试下=>npm install -g think-cli

谢谢您和zhangbowy ：）

**Comment by lizheming** [comment]
你的问题和 uuid 版本无关，下面的 `node: Permission denied` 才是问题，自行检查下相关的权限看下

**Comment by Frank0400Dong** [comment]
> 你的问题和 uuid 版本无关，下面的 `node: Permission denied` 才是问题，自行检查下相关的权限看下

您好，
1.我检查了下，我是用的nvm方式安装的Node.js,
在执行$npm install -g think-cli 后，出现的警告和错误...
2.我采用这种方式curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
在执行$npm install -g think-cli 后，出现的警告,但think.js 安装成功了.

想进一步请教下：
1）.Linux(ubuntu)系统环境是不是推荐用nodesource这种方式先安装NodeJs
再安装 think-cli ？

2）.另外发现（ubuntu 22.04）安装PM2也是报这个警告但不影响使用，是不是要从npm的源代码入手，和安装的think、pm2没有关系
![image](https://user-images.githubusercontent.com/111981012/187015990-6554876a-1828-4688-9c5f-0724108eee70.png)

非常感谢您的耐心解答，我刚接触Linux不久，
有很多基础的知识需要尽快熟练掌握,提出的问题有些小白，请您见谅：)

**Comment by lizheming** [comment]
warning 不影响使用，uuid 的版本已升级已合入发版。你的疑问，建议学习下 Node.js 的基础部分，相信会有所帮助

**Comment by Frank0400Dong** [comment]
> warning 不影响使用，uuid 的版本已升级已合入发版。你的疑问，建议学习下 Node.js 的基础部分，相信会有所帮助

非常感谢您，我在查查资料，希望有一天也能向您和其他小伙伴一样，可以维护Think.js :)
