### ISSUE TITLE
请问ThinkJS 底层依赖的库有必要升级吗？

### ISSUE THREAD

**Issue by geesmart** [thinkjs/thinkjs#1712]
RT，想长期使用 ThinkJS，但是考虑到长时间未更新了，功能很完善了，但是请问ThinkJS 底层依赖的库有必要升级吗 ？

**Comment by zhangbowy** [comment]
3.x?

**Comment by lizheming** [comment]
@geesmart 有必要升级，可以说下是哪些依赖库，我升级下

**Comment by geesmart** [comment]
@lizheming 好的，感谢

**Comment by geesmart** [comment]
warning thinkjs > think-payload > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau

**Comment by zhangbowy** [comment]
多说几个， 我帮你提PR hh

**Comment by geesmart** [comment]
warning thinkjs > think-payload > formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
warning think-typescript > think-helper > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

**Comment by lizheming** [comment]
@geesmart warning 都可以忽略，这些都是非必须升级的。但你可以报出来，我们官方抽空更新下。

**Comment by geesmart** [comment]
好的，感谢作者还在维护
