### ISSUE TITLE
怎么设置请求超时时间？

### ISSUE THREAD

**Issue by Ailein** [thinkjs/thinkjs#1715]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
https://www.npmjs.com/search?q=koa%20timeout 自己搜个中间件的包使用应该就可以了~

**Comment by Ailein** [comment]
都试过，都很久没维护的了，都无法使用，会报错

**Comment by Ailein** [comment]
我看koa 项目下的反馈是需要拿到koa 实例在外部全局设置，thinkjs 怎么拿到koa 实例吗？

**Comment by lizheming** [comment]
think.app 就是
