### ISSUE TITLE
希望能在请求里输出请求id

### ISSUE THREAD

**Issue by moshengrenzenme** [thinkjs/thinkjs#1719]
希望能在请求里的日志输出请求id，在请求里的think.logger可以输出对应的请求id，每个请求里的请求id都一样，同时数据库也可以带上对应的请求id

**Comment by lizheming** [comment]
目前 `think.logger` 是实例级别的，所以没办法做针对请求级别的事情。所以我增加了 `ctx.logger` 的注入，通过给 logger 设置 context 实现请求 id。

1. 升级相关依赖：
  - `thinkjs@3.2.15` https://github.com/thinkjs/thinkjs/pull/1720
  - `think-logger3@1.4.0` https://github.com/thinkjs/think-logger/pull/13
2. 项目的启动文件 `production.js` 中，添加 `asyncLocalStorage: true` 配置
  ```js
  const path = require('path');
  const Application = require('thinkjs');

  const instance = new Application({
    ROOT_PATH: __dirname,
    APP_PATH: path.join(__dirname, 'src'),
    proxy: true,
    env: 'production',
    asyncLocalStorage: true
  });

  instance.run();
  ```
3. `src/config/middleware.js` 中增加自定义中间件，建议加到最开头
  ```
   // src/config/middleware.js
  module.exports = [
    {
      handle() {
        return (ctx, next) => {
          const logger = ctx.logger.getLogger();

          logger.addContext('request_id', think.uuid());

          return next();
        };
      },
    },
  ];
  ```
4. `src/config/adapter.js` 中自定义 MySQL 请求 logger
  ```js
  exports.model = {
    type: 'mysql',
    mysql: {
      logConnect: true,
      logSql: true,
      logger(msg) {
        const ctx = think.app.currentContext;
        return ctx.logger.info(msg);
      }
  }
  ```
5. 所有自己代码内部的请求相关 `think.logger` 调用都替换成 `this.ctx.logger`

**Comment by moshengrenzenme** [comment]
谢谢
