### ISSUE TITLE
官方文档网站 thinkjs.org 证书到期了 || The certificate of the official documentation website thinkjs.org has expired

### ISSUE THREAD

**Issue by chenyu445** [thinkjs/thinkjs#1724]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description 

---
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
好了，谢谢反馈
