### ISSUE TITLE
官网现在进不去了 || The official website cannot be accessed now

### ISSUE THREAD

**Issue by XiaoPuO** [thinkjs/thinkjs#1726]
官网现在进不去了 可以修复一下不 ，没文档 有点寸步难行了 或者能下pdf文档的地址也可以的

---
The official website can’t be accessed now. Can you please fix it? There is no document and it’s a bit difficult. Or you can download the address of the pdf document.

**Comment by lizheming** [comment]
域名过期了，先临时用 https://wwwthinkjsorg-thinkjs.vercel.app/ 这个访问吧

**Comment by lizheming** [comment]
已经好了，感谢反馈
