### ISSUE TITLE
logic校验 ‘boolean|required’ 时参数值为0 false 无法通过验证

### ISSUE THREAD

**Issue by microchang** [thinkjs/thinkjs#317]
## DESC

如题，假如我logic代码如下： 
this.rules = {
id: "required|boolean"
}

那么当我id传0,false,或者其他有类似意义的值时，会返回参数验证错误。
## ENV

Platform: ubuntu 14.04 LTS

Node.js Version: 5.10.1

ThinkJS Version: 2.2.1

**Comment by lizheming** [comment]
ThinkJS 3 have fixed this bug https://github.com/thinkjs/thinkjs/issues/1222
