### ISSUE TITLE
求：在ThinkJS里调用存储过程，并返回结果集

### ISSUE THREAD

**Issue by zhaoguoquan** [thinkjs/thinkjs#352]
## DESC

**我需要**：
 在ThinkJS里调用存储过程，并返回结果集（存储过程可以接收调用者传递过来的参数）

**为什么需要**：
使用MySQL数据库时候，常需要调用其存储过程来提高执行效率以及保持事务性。
目前ThinkJS里model.query 和 model.execute貌似都不返回结果。
对于关系型数据库 如mysql ，sqlserver 等 存储过程是非常重要的。

**我有多么需要：**
 没有这个功能，如同上厕所没有了厕纸！用mysql就只能干一些小孩玩的功能了。
## ENV

windows 10

Platform:

node ：V6.0.0
thinkjs:最新的

**Comment by Messilimeng** [comment]
@zhaoguoquan 是是的

**Comment by rindybo** [comment]
有返回结果的
如:
await this.model('user').query("call get_user_list(1,@count)")
输出：
[[{name:'aa'},{name:'bb'}],[{count:10}]]这样的格式

**Comment by nguyennb9** [comment]
Hi guys,

Do you want to share this open source to the world? It better if people around the world can read all the resources in English.

**Comment by zhaoguoquan** [comment]
@rindybo  ：  存储过程是独立于某个表的。   换句话说如果model的是aaa这个表而不是user这个表 那下面的语句还能正常执行吗?
await this.model('aaa').query("call get_user_list(1,@count)")

**Comment by rindybo** [comment]
@zhaoguoquan 可以的 执行存储过程不区分表

**Comment by Messilimeng** [comment]
怎么还没解决啊  去群里call 我一下 Pepsi Cola

**Comment by Messilimeng** [comment]
https://github.com/mysqljs/mysql/issues/1553

**Comment by im-kulikov** [comment]
@nguyennb9 i tried to tell them about that, but no result..
if you need help with this project in english write to me (@im-kulikov) or @welefen

**Comment by welefen** [comment]
@Messilimeng You can set `multipleStatements: true` in  `config/db.js`, then use model.query to get result.

```js
export default {
  type: 'mysql',
  adapter: {
    mysql: {
      host: '127.0.0.1',
      port: '',
      database: 'test',
      user: 'root',
      password: 'root',
      prefix: '',
      multipleStatements: true
    }
  }
};
```

```
let data = await this.model('test').query('SELECT 1; SELECT 2');
```
