### ISSUE TITLE
 在插件内封装action的话要怎么实现比较好呢

### ISSUE THREAD

**Issue by zengyuhang** [thinkjs/thinkjs#379]
在插件内封装action的话要怎么实现比较好呢
## DESC

你好,我在使用thinkjs的时候遇到一种需求:要封装一个重一点npm通用插件, 基于插件开发框架,可以在插件内通过扩展model,adapter和middleware访问到这些实例,但如果要把action也封装到插件内的话,还找不到一种扩展或者注册的方式,求指导 在插件内封装action的话要怎么实现比较好呢
## ENV

Platform:

Node.js Version:

ThinkJS Version:2.2.5

**Comment by welefen** [comment]
你是想调用一个 Action 的时候然后调用插件里的一些东西？
