### ISSUE TITLE
Swagger integration

### ISSUE THREAD

**Issue by cojack** [thinkjs/thinkjs#380]
## DESC

Hello guys,
I would like to see an integration with Swagger as an API documentation for models.

What do you think about this feature, integration concept?

Regards.

P.S. by swagger I mean this tool: http://swagger.io/
## ENV

Platform: linux

Node.js Version: v6

ThinkJS Version: v2.2.5

**Comment by yiyunzhi** [comment]
loopback did it,its good for RestApi.

**Comment by welefen** [comment]
Thanks for your advice, it will be considered in next main version
