### ISSUE TITLE
mongodb 没有 getfield 吗

### ISSUE THREAD

**Issue by magicknight** [thinkjs/thinkjs#386]
## DESC

[Error] TypeError: this.model(...).where(...).getField is not a function
## ENV

npm 3.9.5

Platform:
ubuntu 16.04

Node.js Version:
node v6.2.2
ThinkJS Version:

v2.2.5

---

|__   **| |   (_)     | |      | |/ __**|
   | |  | |__  _ _ __ | | __   | | (___  
   | |  | '_ | | '_ | |/ /   | |___ \ 
   | |  | | | | | | | |   < |**| |__**) |
   |_|  |_| |_|_|_| |_|_|\__**_/|__**_/

**Comment by magicknight** [comment]
官网文档的 mongo 类写着：
“think.model.mongo 继承类 think.model.base。”
因为 think.model.base类有getfield这个方法，我以为是bug。
但看了thinkjs源代码， mongo是继承的_base 类。

**Comment by welefen** [comment]
mongo 暂时没有这个方法
