### ISSUE TITLE
Discuss for next ThinkJS Version

### ISSUE THREAD

**Issue by welefen** [thinkjs/thinkjs#404]
## Need discuss
- Next big version is 2.3 or 3.0?
- Deprecate multi module?
- Deprecate generator function, use async/await directly?
- Deprecate support TypeScript?
- Convert http object to context?
- Based on KoaJS 2.x(can use KoaJS middleware)?
- Node.js version need >= 4.0 or >= 6.0?

## Confirmed
- Use `ava + nyc` to test
- Remove init method in class, use constructor directly
- Optimize auto update
-  [Refactoring config](https://github.com/75team/thinkjs/issues/409)
- Remove Support ES5 mode
- Seperate Adapter from framework, only give a interface in ThinkJS
- Remove dynamic install package(`think.npm`)

**Comment by qq312384485** [comment]
废弃支持Generator?

**Comment by welefen** [comment]
@qq312384485  更推荐直接使用 async/await

**Comment by qq312384485** [comment]
能不能优先把sql连接的几个问题给fix一下 现在发现两个问题 1. 多连接的情况下有可能中断事务  2. 数据库重启还是会有重连失败的问题,之前是肯定连不上,2.2.5之后是偶尔连不上
希望能开放更多基类和底层api出来,比如控制当前连接池的api,便于大型项目定制,
不再支持es5模式后 顺便也可以构造函数用回来

**Comment by fegg** [comment]
废弃 ts 的支持可以的，减少不必要的精力，专注开发。

**Comment by im-kulikov** [comment]
How about to use the Asset-pipeline or third-party modules, such as connect-assetmanager || node-sass-middleware.

I can share middleware, which I have done for my project.

**Comment by im-kulikov** [comment]
Or implement a simple method to use external (connect-like) middleware.
Examples:
https://github.com/senchalabs/connect#middleware

**Comment by eurekao** [comment]
express有强大额meanjs支持
thinkjs是否考虑出一个类似的mantjs(mysql angular node thinkjs)？

**Comment by llqgit** [comment]
#### 优化自动更新机制 要得，要得
自动更新机制确实比较占用cpu使用率，尤其在服务器上开启多个项目时

#### 关于是否要废弃多模块的功能
希望能够去掉，然后支持多数据库操作，比如我们的项目，现在如果要同时访问 mysql 和 mongodb，就要创建两个项目，而且两个项目互相调用的情况很痛苦😖

#### 最好能够支持集群，微服务
减少维护和开发成本，尤其当项目越来越大时

#### 另外
另外： 如果直接更新至 3.0 希望 LOGO 能够换一个帅气一点的，额～～ 也不是说现在的不帅气，只是，额，好吧，我觉得现在的很丑 :P 哈哈

thinkjs 要是能够支持 React 就爽了，请原谅我的不明所以

**Comment by welefen** [comment]
@llqgit

现在如果要同时访问 mysql 和 mongodb，就要创建两个项目 -- 现在一个项目里是可以同时访问 mysql 和 mongodb 的

**Comment by welefen** [comment]
@im-kulikov  Thanks for your advice, it will be compatibility with koa plugins in next main version

**Comment by duwenqi** [comment]
1、如果要确认要更新已经确定的内容，那么我建议直接3.0 毕竟改动还是挺大的
2、多模块功能在我看来就是一个工程管理的方式，但是方式有几种，废弃不废弃主要还是看每个人的习惯用法
3、支持完全使用async/await
4、支持废弃 把精力集中做更有意义的事情上
5、支持换成context，因为看上去更cool一些，而且更符合某些人的口味

**Comment by snadn** [comment]
- 是开发 2.3 版本还是直接到 3.0 版本？

如果更新后有不兼容，建议直接 3.0。npm默认用的 ^x.x.x。用 2.3 更新的时候会出事。

- 是否要废弃多模块的功能？

新版本对以前多模块的文件结构支持吗？若迁移，工作量大不？工作量大的话，建议缓一个版本，加个开关，默认警告不推荐再使用多模块功能

**Comment by zihuxinyu** [comment]
是否要废弃对 TypeScript 的支持？
答：不要，TypeScript很棒

**Comment by dingyiming** [comment]
- 整合swagger不？
https://github.com/75team/thinkjs/issues/380

**Comment by philoles** [comment]
是否要废弃多模块的功能？（多模块引入了很多使用上的不便，且现在已经直接支持了多级控制器功能了）
多模块的功能多好啊，项目结构清晰，没看出有哪不方便，而且创建项目的时候本来就可以选择是否启用多模块，想用的用，不想用的不用，干嘛删除啊。而且如果删除，现有代码修改工作量太大。这种不删除没影响，删了影响很大的功能还是保留的好。

**Comment by rekey** [comment]
是开发 2.3 版本还是直接到 3.0 版本？

用3.0吧，否则 2.x 系列假如有 bug 需要修复，没法发版本号。

**Comment by im-kulikov** [comment]
@welefen hi there! Can i help with anything to speed up the development of the third version?

**Comment by welefen** [comment]
@im-kulikov  hi, my facebook account is [welefen](https://www.facebook.com/welefen), we can discuss on the facebook.

**Comment by philoles** [comment]
能不能加个测试内存泄漏的功能，现在我基本就没找到一个能测试内存泄漏的简单有效方法

**Comment by hodgevk** [comment]
我本身是用TypeScript开发的，但是我个人建议废弃TypeScript版本，至少在下个版本废弃，专心把es6做好就行。
多模块建议保留，毕竟结构毕竟清晰。
如果能基于koa是最好了，能直接使用其大量的middleware

**Comment by MiYogurt** [comment]
多模块：应该废弃，实在无法接受 Thinkphp 那样的，模块机制。

期待路由可以像`Koa,Laravel,Rails,Django`那样用，而不是重写一下路由格式，存在一个数组里面。
```
$route.get('/foo',fucntion(req,res){
  // todo something
})
$route.resouces('/post','PostController')
````

typescript,其实这几天我一直在尝试`ts`，但是遇见了很多坑，尽管用起来感觉不错，但也非必要，假如精力不够的话，可以暂时停止开发这方面的。

版本直接上3吧，顺便搞个好看点的图标。

像这样图标类似的。
http://easyicon.net/1205584-mushroom_from_Mario_icon.html

基于koa的话，可以接受。

**Comment by UtillYou** [comment]
Deprecate multi module?

 I don't think so. Multi module is very useful. In our project, we have front-end and back-end module in one project. The two modules share some common code.

**Comment by UtillYou** [comment]
咱们尽量用英文吧，虽然我英文也不好，但是这样能推动项目国际化发展，吸引更多的开发者。我看有个老外完全融不进来真捉急

**Comment by UtillYou** [comment]
About whether base on Koa.
I am not familiar with Koa, but I do have used Express. I think Thinkjs should not come together with Express or Koa. The one point which I love on Thinkjs is the Router. I do not need write one line by one line to assign a path to a handler. Convention Over Code!
There are some performance reasons to be mentioned. If based on Koa, how about the performance? Can Thinkjs still keep its speed?

**Comment by wzquyin** [comment]
如果没了ts，估计我要放弃thinkjs了，这个要看thinkjs以后就打算做小项目，还是大项目，大项目多人协作的，如果没有ts的各种js+的东西支撑，团队开发成本太高，只能放弃

**Comment by wzquyin** [comment]
想象一下，每个类的public函数，先要对传入参数做类型检查，这对团队项目，简直是愚蠢至极，
实际上thinkjs预期去掉ts，不如把ts的编译部分脱离babel。
不管是es6还是es7，不是强类型，没有interface，多人项目开发效率和除错成本，。。。。

**Comment by wzquyin** [comment]
我反而觉得thinkjs自己应该做好规划，你到底面向个人小开发者，还是团队用户，到底是要做大项目还是小项目，如果大项目就要拥抱ts，把修饰符啊各种ts特性都用上，极大的加快团队开发速度，写出易读简练安全的代码。另外吧ts的编译依赖去掉babel，我们团队编译ts全部修改thinkjs的src，吧babel去掉了，小项目感觉不到，大项目会发现babel编译出来的玩意调试还是太坑了，乱七八糟，反而ts自己的编译结果，很容易调试容易找到错误。

thinkjs我最早用的时候就是觉得他架构在思路上有一些硬性的规范，这点很好能规范多人协作一些结构性的认知整出来的程序结构很整齐，加上ts以后通过ts 的特性控制住了团队合并时候的出错概率，不错，，，，结果ts越进化越。。。。。。，最后弄出一套koa或者express的中国山寨版，有多大意义？？？

目前来说thinkjs的特点就是es6+和thinkphp的那种规范化的开发，加上ts的严格化，成为了一套最接近商业和大型项目开发的框架，结果3.0居然放弃自己的特点，走回头路，。。。

那我问一下，我何必要用thinkjs，直接用koa多好啊？

**Comment by welefen** [comment]
@wzquyin TS 的编译你改了哪些呢？是否可以提交个 pull request。3.0 里不支持 TS 是考虑到目前没什么人使用。如果使用人数较多的话，也是可以考虑继续支持的。

**Comment by welefen** [comment]
@wzquyin 有些地方借鉴 Koa，是考虑到 Koa 的生态，毕竟在国内创造一个生态是几乎不可能的。

**Comment by UtillYou** [comment]
@wzquyin ts的确有利于多人协作，我们目前用es6多人协作就有很多不便，项目的规范完全靠文档。但是ts怎么解决回调的问题，用es6最好的一点就是可以用async/await.

**Comment by wzquyin** [comment]
@UtillYou ts很早就支持了await了。。。。。

**Comment by wzquyin** [comment]
@welefen 只是把watchcomplie 里面的compliets函数里面再调用compliebabel去掉了，直接ts自己编译成es6以后直接保存map和js，没多大改动，实在没脸去提交pull，，，，，，有一定的限定比如node版本不能低了。。。ts版本必须是某个稳定版本。。。

**Comment by wzquyin** [comment]
@welefen 很希望thinkjs的核心团队有个自己的定位，否则你始终都是跟着别人做，别人有什么我们做一遍，那think真的就没希望了，与其弄个什么都砍不死的大刀，如果做一把锋利的小刀，一刀毙命。
国内的开源和node氛围肯定不如国外，如果你要在普通框架范围内和国外的同类框架在同质的功能上竞争，不用想最后都是死，所以我觉得thinkjs团队没必要听取太多用户意见，新的东西别人没有或者做不好的东西你做出来做好听意见ok，别人有自己也有只是实现不同的东西就没必要去人云亦云，，，所谓发展的最好体制就是独裁是有道理的，用户只能作为你的参政者，至于你要走哪条路一定自己定，让用户发表一些种什么花花草草的意见就行了！

**Comment by wzquyin** [comment]
Next big version is 2.3 or 3.0？
I don't care...all ok
Deprecate multi module?
o nono,but thinkjs need keep single module for personal developers,and change single module route system from module/controler/action to custom define route system like koa or express
Deprecate generator function, use async/await directly？
yes !
Deprecate support TypeScript？
nono,for team development ,ts is very helpful
Convert http object to context ？
that's ok
Based on KoaJS 2.x(can use KoaJS middleware)？
for a lot middleware maybe that's cool,but thinkjs need make the users develop thinkjs project like current version,encapsulate koa to current thinkjs version like. I like thinkjs

**Comment by hodgevk** [comment]
其实thinkjs没有必要去与koa比什么，毕竟生态不一样，这是中国国情。
ThinkPHP在国内是很多公司在实践使用的，它有很多实际案例，比如我们公司只要是php项目一定是使用thinkphp，简单方便文档全。所以我个人认为thinkjs去模仿的thinkphp部分优秀的东西和理念不是个坏事，比如java、C#和Swift；angularjs、reactjs还有很多相似和借鉴呢。
个人觉得thinkjs是一个后台框架，那注重的就是逻辑和安全，Typescript在这块应该讲是要优于ES6的，尤其是团队合作的情况下。更多的约束是减少Bug，提高代码可阅读性。如果thinkjs团队能有精力，并想把thinkjs做大还是弄Typescript版比较好。

**Comment by ckken** [comment]
Next big version is 2.3 or 3.0？
3.0
Deprecate multi module?
Middleware 是未来方向，结合koa  express 模型
Deprecate generator function, use async/await directly？
未来方向
Deprecate support TypeScript？
可以考虑完全用ts ，ts 也可以写出babel 的结果
Convert http object to context ？
这个跟下面问题一样
Based on KoaJS 2.x(can use KoaJS middleware)？
说说我总结和对这个问题的一些感受
从15年开始用think,包括我之前也自己做过类似的框架，从think php 1.0就开始用的老用户，给我最大的感受就是简单，快，特别是namespace 的引入之后，但是thinkphp 给我的感觉就是第三方接入的困难性，可拓展性，而在nodejs 大环境下，所有人已经习惯了express,koa 那种开发模型，一大波的开源插件开箱即用，所以我建议在koa 2的基础之上开发是最好的选择，从插件提供者的角度来看，当然做出来的东西可以越多人用约好，不喜欢think 完全可以用koa 在安装插件，后续贡献者参与度会有质的增长！
题外话
看了很多上面的评论，支持react  前端这些想法应该是建立在think 之上的另外一个框架，我认为think 更应该关注在服务的稳定性，可拓展性，和性能上面，尽量做到轻，去view 也是未来方向，微服务模型构建，多库，分表，数据层缓存的构建等各方面后端的深挖，目前我们已经把整个think 项目支持到所有阿里云，微信的服务，但是没有去封装组建的冲动，如果是基于koa ，现在我们会推出一个体系的工具包！
目前用think 或者nodejs 遇到最大问题是分布式的原子事务支持，以及异步debug 跟踪，......
目前自动化当年已经做到初步的devops 模型！

**Comment by yuu2lee4** [comment]
next version depercate babel?  pick up babel-runner from thinkjs so we can directly run thinkjs on node7(or 8)，or run it on node4~6 with a extra babel-runner .

**Comment by im-kulikov** [comment]
> Deprecate support TypeScript？

Nope. I think we should use Typescript for core development of ThinkJS. This will allow us to implement autocompletion for code editors. Moreover, developing in Typescript, we will be able to eliminate errors before tests :) . For example, in Angular2, Typescript is used as a basis. 

IMHO: Duck typing in VanillaJS it is a headache for the developer

@welefen what u think about that?

**Comment by im-kulikov** [comment]
Some packages, that we mb can use in next version of ThinkJS:

KoaJS-like engine - https://github.com/trekjs/engine
Routing - https://github.com/trekjs/router
QueryBuild - https://github.com/tgriesser/knex (SQL-like) - not always convenient to use a model, especially if it is easier to do using QueryBuilder

**Comment by zhaoweijing2003** [comment]
thinkjs现在在后台来说已经非常便捷强大了，thinkjs现在的软肋是前端的支持比较薄弱，仅仅靠js模板。我认为可以借鉴falsk_appbuilder 框架的功能，对前端的开发增强

**Comment by jguang** [comment]
Deprecate multi module?  建议保留，在nodejs框架趋于相同的现在，这个还是很实用的 特别是在成熟的公司内部，项目多变化快！！
generator function？ 建议废弃 ；
ts？ 可废弃，实话书写上其实对ts&es6 一直没太大明显界限，除了那些也不怎么会用的类型；

**Comment by dingyiming** [comment]
支持  Based on KoaJS 2.x(can use KoaJS middleware)，目前看 thinkjs 生态还是很欠缺 延伸拓展的，希望能和 主流框架对接起来，大家更热情些

**Comment by songguangyu** [comment]
是否可以支持同时链接多个mysql

**Comment by Harris-Aaron** [comment]
建议新的版本更好的支持Typescript,在中型项目或中上型项目上，Typescript实在太重要了。如果不使用TS不如考虑meteor1.4。

**Comment by Harris-Aaron** [comment]
建议新的版本更好的支持Typescript,在中型项目或中上型项目上，Typescript实在太重要了。如果不使用TS可能就转向meteor1.4。
       建议同时修缮和增加常用函数的，虽然通过很多办法也能实现第三方数据请求、文件批处理、数据自动json化...,但是官方提供的话可以写更少的代码、获得较好的性能。尽可能减少一般操作必须引入第三方包的麻烦。
       建议尝试割除View,实现前后端分离。 前端只使用API + AccessToken + other 渲染数据。这样前端可以使用任意框架。
       建议不同模块处理不同数据库实现快慢库读写。module1 对应mongo&RethinkDB，module2、module2 对应MariaDB & mysql。
       建议尝试 WebSockets API 实现移动端应用数据实时同步。

**Comment by welefen** [comment]
@songguangyu https://thinkjs.org/zh-cn/doc/2.2/model_config.html#toc-82e

**Comment by welefen** [comment]
@Harris-Aaron 感谢建议 
8.  如果觉得 thinkjs.t.ds 有什么问题，可以提 Pull request 哦
9. 不能使用驼峰命名主要有 2 个原因，1）Node.js 不建议驼峰  2）windows 和 Mac 不区分大小写，Linux 区分大小写，避免出现文件大小写的问题导致线上事故。

**Comment by welefen** [comment]
@zhaoweijing2003 你觉得 flask_appbuilder 哪些功能比较好呢？

**Comment by zhangbihua** [comment]
1. 建议新的版本更好的跟es原生走，Typescript版本的可以单独分支做个基本语法转换。ES7发展很快，typesctript 也是基于es来迭代，主流还是es更重要，依赖越少，产品才能更安全，快速。
2. 建议使用 ES6 语法开发，基于旧项目，以及es5, 建议constrcutor 代替init, 更好的支持原生语法
3. 建议thinkjs优化Middleware(中间件)的状态管理，让这一个过程更加透明，现在thinkjs这一步就像小黑屋里的窗户太高，外面的人看不清里面的
4. 希望thinkjs开发插件可以更加友好，可以让开发者从koa或者express中的插件转为thinkjs的插件。
5. koa 是小而美，我想thinkjs不仅可以是大而全，而且可以是小而全，thinkjs基于babel的预编译很好的解决了开发环境的hrm(热更新), 并且封装了view,sql,socket,部署的各种基础模块，以及各种基础中间件,可以说是现阶段nodejs最好的试炼场和点金石，增加曝光率，这样使用人的基数更快增长。
------------------------
这些都是我个人不成熟的建议，希望thinkjs better and better

**Comment by im-kulikov** [comment]
@welefen @Harris-Aaron - macOS can use non case-sensitive partition

If we are talking about the file/folder to be named in camelCase - it's bad idea

**Comment by welefen** [comment]
@im-kulikov  
Now we use eslint to verify js code.  
yarn.lock it's a good idea, also npm support use npm-shrinkwrap.json (use npm shrinkwrap generated) to lock dependencies version.

**Comment by im-kulikov** [comment]
@welefen 

> Now we use eslint to verify js code.

yes, i talk about it, but standardjs is most popular and in trend.
mb we can change eslint (i call it js-lint in previous message) to standardjs 😃

**Comment by zhangbihua** [comment]
1. nodejs, thinkjs, koajs. 为什么要用nodejs,什么是thinkjs,作者自己的想法
2. nodejs的好与坏，
3. koa2.0的middleware 的透明化状态管理模型，
4. 现在thinkjs的优点是什么(傻瓜式构建?完整的demo,HRM(热加载),babel的深度配置),
5. thinkjs 想达到什么进步，目标是什么(最多人使用的nodejs框架？or 最贴近公司业务逻辑的nodejs框架?);
------------------------------------------------------------------------------------
6. babel预编译,typescript的类型检查， async-await 是人人都喜欢的. typescript 的人数会比es原生多吗
7. thinkphp带来的是构建目录模式，koajs带来的是middleware 透明化状态管理模型；
8. 选择thinkjs的都是那些人，偏前端还是偏后端，肯定是偏前端的jser, 要是能写java,可选的太多(Double,spring)，要是php, 喜欢thinphp转来的人，Laravel会是更好吗
9. 如果想做nodejs下最多人用的框架，jser们的最好选择(thinkjs在一步步接近这个目标), 基于koa重构3.0就对了,重构完之后在做typescript 的支持也不迟；
10. 基于thinphp下的2.x, thinkjs 和其他的的后端语言框架优势又有多大？
11. 还是要看作者和thinkjs团队自己心里面的想法；
-------------------------------------------------------
以上是个人不成熟的建议

**Comment by arden** [comment]
1、多模块可以去掉，其实没啥用。
2、支持集群、微服务。
3、直接async/await，Node7.6或者8.0已经直接支持了。
4、基于koa 2.0开发，生态现成的，这很重要。
5、可以考去掉typescript支持，集中精力把js版本先弄出来，毕竞现在es2016已经很好了，如果后面有这强烈的需求再单独发个typescript版本就OK.
6、数据库这支持建议以中间件或者插件支持，减少框架的依赖，毕竞现在微服务是趋势，其实数据层项目发展到一定阶段，数据层很多时候都已经通过RPC方案来弄了。

**Comment by hhdem** [comment]
mariadb 可以有么？
