### ISSUE TITLE
ThinkJS LOGO Design

### ISSUE THREAD

**Issue by welefen** [thinkjs/thinkjs#410]
欢迎贡献 ThinkJS LOGO 设计，请提供矢量图

**Comment by im-kulikov** [comment]
![thinkjs](http://img.kulikov.im/thinkjs-logo.svg)

just for fun 😃

**Comment by hisland** [comment]
![polygon 1](https://cloud.githubusercontent.com/assets/417448/19518028/40e528d8-9637-11e6-8b54-a86ecaf0848b.png)

hehe

**Comment by llqgit** [comment]
![thinkjs](https://cloud.githubusercontent.com/assets/8063914/19849014/c0206722-9f8b-11e6-8415-72c9a4986c86.jpg)
half-complete.....
just 4 fun 2 :P

**Comment by hisland** [comment]
![bitmap](https://cloud.githubusercontent.com/assets/417448/20039356/63761d7c-a47d-11e6-93dd-380f358dc6b7.png)
fun
