### ISSUE TITLE
关于 __after() 和记录日志的需求

### ISSUE THREAD

**Issue by llqgit** [thinkjs/thinkjs#412]
## DESC

不知道有没有这个功能，我想使用 `controller` 中的 `__after()` 方法拦截 `action` 的结果，并在错误的时候记录日志，并记录方法名称。

如果正常写，我需要在每个 **action** 的最后都加上日志语句，破坏程序结构，而且不美观。

现在的做法是：

> 在 `__before()` 中获取当前 **action** 的名字，并设置到 `this` 的属性 _name 中。
> 在 `__after()` 中判断 `action` 返回值，如果有错误，取出 this._name 并记录日志

问题是：

> 如果 **action** 中调用 `return` 则 `__after()` 失效，不能记录日志或进行其他滞后操作。

所以，现在让我觉得 `__after()` 方法至少在这个情况下是没有意义的
## ENV

Platform: mac os

Node.js Version: 6.2.0

ThinkJS Version: 2.2.1

**Comment by welefen** [comment]
如果有错误后续就不会在执行了。你这种需要可以在通用错误里记录，具体见项目里的 `controller/error.js` 文件

**Comment by llqgit** [comment]
额～～，我的意思是
假如，我想在多个不同的 action 返回成功时，执行统一的操作，比如这些操作成功后，为这个用户添加积分或者其他奖励。而且又不想影响原方法的主要功能。
这种情况，如果将它纳入错误中，觉得不是很合理，因为这应该是正常情况。

**Comment by welefen** [comment]
@llqgit  恩，那就调用 `display`, 'success' 之类的方法是前面不加 return 就可以了。现在这些方法会返回一个特定的 Reject Promise，用来阻止后面的执行。

**Comment by llqgit** [comment]
额，原来是这样。那看来这个需求是行不通了。

**Comment by linyan02** [comment]
我也有这样的需求，结果没有办法实现

**Comment by welefen** [comment]
3.0 可以直接通过 middleware 来实现
