### ISSUE TITLE
logic的验证的一些建议

### ISSUE THREAD

**Issue by AnzerWall** [thinkjs/thinkjs#431]
## DESC

1、希望提供对object的子项目的验证（像是joi那样）
post:
{
 p:{
  c:1
 }
}
希望能对p下面的c进行验证，在p是object的情况下能指定field参数
2、像object同样希望支持对数组的每一项进行验证。
3、希望区分开没有传递参数和传递的参数isEmpty返回空的情况。。
或者添加能检测实际有无传递参数的检查功能
比如string我希望知道他是传递了空字符串还是没有传递参数（比如用户有个签名，他今天突然想清空签名这样的操作），设置required传递空字符串直接报错，不required我根本无法区分者这两种情况（我是最后再logic的 __before前做了记录）。。
比如另一个issue提到的boolean为required的时候且false时候报错，boolean型一般是指定开关之类的，按照论坛上的回复只能传递true我要这个参数干嘛，（最后我改成用字符串指定enable和disabel）
还有数字，也会出现这样的问题

总之要不提供能检出实际是否传递了参数的功能 
或者
未传递参数的情况下，设置required就验证失败，设置default时用default覆盖，均未设置保持undefined，
传递了会被空类型（isEmpty()===true）的数据情况下，希望不反馈验证错误
4、不希望默认的类型为string，有比如某一个参数可能允许单个值或者传递array的情况，这样我可以很灵活的自定义一个验证器，而不是报错说不是string
## ENV

Platform:
window 10
Node.js Version:
v6.2.1
ThinkJS Version:
v2.2.9

**Comment by welefen** [comment]
OK 多谢反馈

**Comment by welefen** [comment]
已经在 3.0 里实现
