### ISSUE TITLE
bug: logic validate int type error

### ISSUE THREAD

**Issue by vsuyi** [thinkjs/thinkjs#490]
## DESC

a controller logic like this: 
this.rules = {
    key_type: 'int|required|in:0,1'
};

when the client post data with value: 0, it response 'key_type can not be blank'.
{
 "key_type": 0
}

change the post data to other nonzero int, or string value will be ok. like:
{
  "key_type": "0" 
  // or 
  // "key_type": 1 
}
## ENV

Platform:
windows10

Node.js Version:
v6.5.0

ThinkJS Version:
v2.2.13

**Comment by lizheming** [comment]
`required` have add 0 check, please upgrade your thinkjs version. 
https://github.com/thinkjs/thinkjs/commit/fc117b335ed5a74ee2a3d4a30b6379197996cfc6#diff-04af938fa394eac6e8599240304a08aaR20
