### ISSUE TITLE
Typescript 下使用global编写全局函数

### ISSUE THREAD

**Issue by huang6349** [thinkjs/thinkjs#505]
## DESC

我在"src/common/bootstrap/global.ts",中准备添加一个全局函数，
发现Typescript提示"Cannot find name 'global'"，
然后我在这个ts文件中添加了"/// <reference path="../../../typings/thinkjs/think.d.ts" />"这段申明，任然报错。
请我我该怎么获得global这个变量，需要我自己定义吗？

## ENV

Platform:Windows10

Node.js Version:5.12.0

ThinkJS Version:2.2.13

**Comment by XGHeaven** [comment]
如果你是手动使用 `tsc` 编译的话，那必然会出现这个问题，如果你是使用 `npm run compile` 的话，请联系作者。

**Comment by SijieCai** [comment]
This is not thinkjs issues, please search answers in TS forum
