### ISSUE TITLE
npm install @types/thinkjs in TypeScript 2.x ?

### ISSUE THREAD

**Issue by watonyweng** [thinkjs/thinkjs#517]
DefinitelyTyped recommended to use  @types/thinkjs ?

**Comment by XGHeaven** [comment]
Yes.... I also suggest to use @types/thinkjs

**Comment by SijieCai** [comment]
Please attach your environment and thinkjs version next time.
We don't put declaration in module instead of DefinitelyTyped which is also suggested by DefinitelyTyped
