### ISSUE TITLE
使用typescript调用Promise方法时，无法使用await，提示 'Operand for 'await' does not have a valid callable 'then' member.'

### ISSUE THREAD

**Issue by sdfsun** [thinkjs/thinkjs#526]
## DESC
使用typescript调用Promise方法时，无法使用await，提示 'Operand for 'await' does not have a valid callable 'then' member.'
如图：
![image](https://cloud.githubusercontent.com/assets/2117890/21259359/fc00f35c-c3bb-11e6-9365-4b1cce43b736.png)

## ENV

Platform:win10

Node.js Version:v4.6.1

ThinkJS Version:v2.2.15

**Comment by SijieCai** [comment]
请升级或者关注 thinkjs 3.0 对 typescript 的支持。https://zhuanlan.zhihu.com/p/31057738
