### ISSUE TITLE
建议添加 schema 字段映射功能

### ISSUE THREAD

**Issue by ufologist** [thinkjs/thinkjs#529]
## DESC

主要为了解决在数据库中建立的字段名称与接口中提供的数据字段名称可能不一致的问题

例如: 在表中字段的名称为 `table_filed_name`, 而在接口中输出的字段需要变成 `field1`
```javascript
export default class extends think.model.base {
    schema = {
        field1: {
            name: 'table_filed_name'
        }
    }
}
```

类似 [Sails 提供的 model.attributes 功能](http://sailsjs.com/documentation/concepts/models-and-orm/attributes)

## ENV

Platform: `Windows 7`

Node.js Version: `6.9.1`

ThinkJS Version: `2.2.15`

**Comment by jnotnull** [comment]
Sequelize这个ORM支持，可以参考下https://github.com/jnotnull/thinkjs-Sequelize

**Comment by welefen** [comment]
恩，3.0 里考虑这个功能，2.x 暂时先不考虑了。

如果需求迫切的话，你可以帮忙实现下，然后发个 pull request

**Comment by handoudou** [comment]
@welefen 这个问题在3.0版本解决了吗，多谢
