### ISSUE TITLE
view.js中设置多模板语言

### ISSUE THREAD

**Issue by Iamlars** [thinkjs/thinkjs#537]
## DESC
请问如何在thinkjs 2.2中设置多个模板语言，比如 jade ejs并存？目前我设置type为jade，则ejs无法被编译。

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by snadn** [comment]
jade和ejs的分成两个module，分别设置view。

或者this.view().display的时候传config。https://github.com/75team/thinkjs/blob/master/src/core/view.js#L47
