### ISSUE TITLE
think.model.MANY_TO_MANY时， rModel只有填真实表名才能关联成功，使用模型关联关系模型名会找不到表格

### ISSUE THREAD

**Issue by hdumok** [thinkjs/thinkjs#544]
## DESC

在创建表的model时，当使用 think.model.MANY_TO_MANY时， rModel只有填真实表名才能关联成功。
比如，有个关联关系表 bind , 存储了 device表和user的多对多关系，如果在建bind表时，将其建成device_user.js  , 然后再init 函数里 将 this.tableName = "bind" 方式制定模型的表名，那在 user表里关联device时，使用rModel："device_user", 会报错 找不到表格 device_user，使用rModel："bind"才能关联成功

## ENV

Platform:windows

Node.js Version: 7.3.0

ThinkJS Version:2.2

**Comment by welefen** [comment]
不支持这种方式
