### ISSUE TITLE
对于Post请求，在logic中验证int类型，如果使用application/json格式传递数据，验证有问题

### ISSUE THREAD

**Issue by Qyf-Aaron** [thinkjs/thinkjs#546]
## DESC
对于Post请求，在logic中验证int类型，如果使用application/json格式传递数据，验证有问题。
具体表现为当int=0是，ThinkJS会认为该值不存在而返回参数不存在的错误。当使用application/x-www-form-urlencoded格式，则能够正确处理int=0的情况。
（例如：
    this.allowMethods = 'post';
    this.rules = {
      id: 'required',
      type: 'required|int|in:0,1'
    };

    如果type=0，则在application/json格式下验证错误
）

## ENV

Platform: mac

Node.js Version: v6.7.0

ThinkJS Version: 2.2.13

**Comment by welefen** [comment]
已经在 2.2.19 版本中修复
