### ISSUE TITLE
development环境下 用命令行 执行脚本，不能正常退出

### ISSUE THREAD

**Issue by duwenqi** [thinkjs/thinkjs#549]
## DESC
development环境下 用命令行 执行脚本，不能正常退出
testing
production模式下 没问题

## ENV

Platform: mac

Node.js Version: v6.7.0

ThinkJS Version: 2.2.15

**Comment by welefen** [comment]
逻辑里有链接什么服务么？除了数据库之外

**Comment by duwenqi** [comment]
没有 只有数据库操作

**Comment by lizheming** [comment]
development.js  会监听文件变化做编译相关的操作所以是常驻的，属于 feature。
