### ISSUE TITLE
官网文档错误 rest api

### ISSUE THREAD

**Issue by thinkido** [thinkjs/thinkjs#553]
## DESC
rest 4个action中的获取参数表述错误,
async postAction() {
    console.log("postAction");
    let data = this.post();   获取的post 数据为空,
应该改为 let data = this.get(); 
4077725@qq.com   附带视频录像&教程
## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
请帮忙修改下，然后发 Pull request。

文档项目在： https://github.com/thinkjs/www.thinkjs.org/tree/master/view/zh-cn/doc
