### ISSUE TITLE
typescript，在编译过程中，似乎无法像gulp一样编译报错

### ISSUE THREAD

**Issue by jinmarcus** [thinkjs/thinkjs#558]
配置成typescript，在编译过程中，似乎无法像gulp一样编译报错，
比如：
const str: number = "string"
使用gulp编译的时候会报错类型不正确，但是thinkjs配置了typescript却不会报错。
请问，这是我配置的问题。还是就是不会报错？

还有，建议如果thinkjs后面一个版本，可否考虑在node7的环境中，node7中直接可以使用es6的语法，这样typescript直接就可以编译成es6，直接就可以运行了，而不需要再编译成es5了。

**Comment by welefen** [comment]
下个版本会升级 TypeScript 解决这个问题

**Comment by epirus** [comment]
下一个版本是指3.0版本吗？

**Comment by SijieCai** [comment]
是的，可以看看这篇文章 https://zhuanlan.zhihu.com/p/31057738

最新版 thinkjs@3.2  think-cli@2.11
