### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by melkir** [thinkjs/thinkjs#559]
## DESC

Hi there,
I would like to use Firebase instead of MongoDB and MySQL.
Since the syntax is very different from them, mostly url based request and socket how can I implement this?
Do I need to create an specific Adapter / Model to be able to use it with my rest API ?
Is there a simple way to skip this ?

## ENV

Platform: Archlinux

Node.js Version: 7.4.0

ThinkJS Version: 2.2.15

**Comment by welefen** [comment]
ThinkJS can not support Firebase now, if you want to use Firebase to store data, you can use Firebase API in model, like this:

```js
// src/home/model/firebase.js

export default class extend think.base {
   getData(){
     //use Firebase API here
   }
}
```
