### ISSUE TITLE
ThinkJS 3.x development wechat group

### ISSUE THREAD

**Issue by welefen** [thinkjs/thinkjs#561]
![Alt text](http://p9.qhimg.com/t01181f13577d91da7f.jpg)

由于群二维码会失效，请先加我个人微信，我拉入到群里（加入时请注明是参与 ThinkJS 3.0 开发）。

注：加群者务必能参与 3.0 的开发

**Comment by dingyiming** [comment]
请问，有具体计划说明吗？
