### ISSUE TITLE
ts版本在2.1.0以下不支持解构，但是项目目前只支持2.0.3的ts，什么时候能使用上2.1.x的ts？？？

### ISSUE THREAD

**Issue by xueyuchen** [thinkjs/thinkjs#565]
## DESC
我们项目目前想从es6转到ts
ts版本在2.1.0以下不支持解构，但是项目目前只支持2.0.3的ts，什么时候能使用上2.1.x的ts？？？

## ENV

Platform:
macos
Node.js Version:
v6.3.1
ThinkJS Version:
v2.2.16

**Comment by welefen** [comment]
TS 在 2.0.3 接口之后有较大改动，下个版本会修复这个问题。
* 会升级 TS 到最新的版本
* TS 编译不在使用 Babel 进行二次编译

**Comment by welefen** [comment]
Fix by https://github.com/thinkjs/thinkjs/commit/b902e701cf733813da31dd61f754e34056507368
