### ISSUE TITLE
连接MongoDB 时，如果密码里面出现了@符号，会连接不上

### ISSUE THREAD

**Issue by yuexing0921** [thinkjs/thinkjs#569]
## DESC
连接MongoDB 时，如果密码里面出现了@符号，会连接不上，错误如下

![image](https://cloud.githubusercontent.com/assets/18208187/23094420/8ee92a00-f633-11e6-962b-e0f5836ceda3.png)

用Robomongo 0.9 是可以正常连接的。

## ENV

Platform: windows10 

Node.js Version: 7.4

ThinkJS Version: 2.2.16

Mongo Version: 3.2

**Comment by welefen** [comment]
直接用 mongodb 模块呢？ ThinkJS 是依赖这个模块处理的

**Comment by jnotnull** [comment]
之前也遇到过这个问题，使用sequelize建立连接也要求连接串中不能带上% 否则导致sequelize库这行var urlParts = url.parse(arguments[0]);
