### ISSUE TITLE
请问 PRELOAD 输出如何关闭？

### ISSUE THREAD

**Issue by vrworking** [thinkjs/thinkjs#578]
## DESC

使用 CLI 方式运行，会出现 [PRELOAD] 的运行提示，导致服务器的mail 里面很多数据。
```
[2017-03-07 23:41:57] [PRELOAD] preload packages finished 250ms
```

设置 Log 也不行。
```
log_error: false,
log_request: false,
```

请问如何关闭这个输出？

CLI 
```
node www/production.js /backend/quot/index
```

## ENV

Platform: CentOS 6.x

Node.js Version: v7.4.0

ThinkJS Version: v2.2.17

**Comment by welefen** [comment]
下个版本 2.2.18 版本会去掉这个日志

**Comment by welefen** [comment]
Fixed by https://github.com/thinkjs/thinkjs/commit/b819b83a46d440d55f2d201ba71cfdfbd76843ad
