### ISSUE TITLE
跨控制调用，支持多级控制器么？

### ISSUE THREAD

**Issue by 2681137811** [thinkjs/thinkjs#583]
好像不支持多级控制器调用

`this.controller('shop/admin/user');`
this.controller('shop').controller('admin/user');
`

**Comment by welefen** [comment]
现在不支持多级控制器的调用

**Comment by junmaqiang** [comment]
如果是按照多级控制器来部署项目,那么项目结构应该是啥样子的,config放在那个位置? @welefen

**Comment by lizheming** [comment]
ThinkJS 3 中已支持。
