### ISSUE TITLE
adapter创建问题

### ISSUE THREAD

**Issue by ntfs32** [thinkjs/thinkjs#588]
## DESC

使用`thinkjs plugin [name]` 创建的adapter默认已经使用babel 6+ 了 ，但是创建插件后`yarn run compile`生成只是会拷贝一份src到lib而已，并没有实际的转成es5代码呢？
请教

## ENV

Platform:

Node.js Version:6.95

ThinkJS Version: v2.2.16

**Comment by welefen** [comment]
为啥用的是 `yarn run compile` 命令？

**Comment by ntfs32** [comment]
@welefen 用npm一样的 用其他项目下面的babel5正常 现在项目里面babel6的话，创建adapter 不会被编译成es5了 不知道何解

**Comment by welefen** [comment]
adapter 是在  src/common/adapter 下么？其他代码会被转译么？

**Comment by ntfs32** [comment]
@welefen  不是的 是`thinkjs plugin`创建的独立插件，compile后会出现app目录，但是app目录里面还是es6形式的，只是被拷贝了一份过去

**Comment by welefen** [comment]
看下你项目下的 .thinkjsrc 文件，里的 es 是为 true 么？

**Comment by lizheming** [comment]
ThinkJS 3 can use native node 8+ without babel, you can try it!
