### ISSUE TITLE
thinkjs 在nodejs 7下的性能如何

### ISSUE THREAD

**Issue by wstygk** [thinkjs/thinkjs#589]
thinkjs 在nodejs 7下的性能如何,以及如何利用其原生的async/await

**Comment by welefen** [comment]
性能你可以测试对比下。
2.x 下还不太好使用原生的 async.await，目前正在开发 3.0，会支持使用原生的 async/await

**Comment by ZQun** [comment]
@welefen 3.0大概什么时候上线？

**Comment by welefen** [comment]
我们正在加紧开发，预计 6 月底。

**Comment by grapewheel** [comment]
已在项目中投入使用，nodejs 9下配合mysql 8.0，性能不错 @wstygk
