### ISSUE TITLE
如何捕捉controller内的异常

### ISSUE THREAD

**Issue by yuexing0921** [thinkjs/thinkjs#597]
## DESC
代码如下
``` javascript
//controller/index.js
 indexAction() {
    throw new Error('this is Error');
}
```
现在逻辑层的异常，不捕捉，统一抛出到controller层，然后现在想在controller error内的统一收集，或者其他方式收集可以，因为要监测API，所以需要统一收集异常信息

这个thinkjs有什么方法可以收集吗？

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
可以在最外面加个 try，但这种方式并不优雅。
更好的方式是修改 common/controller/error.js 文件，在对应的错误类型 Action 里修改。

**Comment by yuexing0921** [comment]
对，就是不限用try
目前是在common/controller/error.js内加了如下代码
```
displayError(status) {
		let http = this.http;
		if(status >= 500 && http.error){
			logger.error(http.error);
		}
}
```
希望thinkjs3.0能有更好的解决方案
