### ISSUE TITLE
model  "query" 函数总是被缓存了.

### ISSUE THREAD

**Issue by zero0-1one** [thinkjs/thinkjs#598]
## DESC
在model 中调用 this.query('select * from lock where id = 1 for update');  导致执行多个加锁操作无效果.
查看日志发现只执行了一次该 sql.  而使用 execute 则正常.  仔细查看发现query 总是被缓存了, 即使不使用this.cache()   , 或者在 config/db.js 中设置  cache.on = false.   也没效果.   query总是自动被缓存了.  这应该是不正常的.

## ENV

Platform: windows

Node.js Version: 7.7.1

ThinkJS Version: 2.2.17

**Comment by zero0-1one** [comment]
发现是 think.await 的原因,     只能绕道而行了.

**Comment by welefen** [comment]
恩，先使用 `execute` 方法吧，后续版本增加参数控制。

**Comment by tonybala** [comment]
我在檔案(暫時改正這問題)
node_modules\thinkjs\src\adapter\db\base.js 中的 query函數
加上   think.uuid()
如下
         return think.await(sql+think.uuid(), () => {
===================================
還有請官方注意一下
think.await 返回的資料是全域變數
如有程式將資料改掉，會導致另一個連入的人資料發生問題(這問題比較嚴重，我個人認為)

**Comment by welefen** [comment]
@tonybala  这个设计是减少同一个时刻多次相同的查询请求，比如：同时三次触发 `SELECT * FROM xxx LIMIT 3`，此时只要执行一次，然后把结果给其他二次请求就可以了。

如果不是查询类请求或者查询类请求里更新的操作，则不能使用该方法，可以选择 `execute` 方法。
