### ISSUE TITLE
建议使用更严格的代码规范

### ISSUE THREAD

**Issue by MinJieLiu** [thinkjs/thinkjs#600]
在阅读 `thinkjs` 源码的时候，难免会发现一些并不是那么美观的问题。请原谅我的强迫症😅😅
所以呢，我希望 `thinkjs` 可以做得更好，可以被更多人所推崇，我建议使用 `airbnb` 的规范。

```json
{
  "parser": "babel-eslint",
  "extends": "airbnb-base"
}
```

我的初衷只是让 `thinkjs` 成为更完美的框架😄

**Comment by welefen** [comment]
多谢建议，我们评估下 airbnb 的规范

**Comment by welefen** [comment]
https://github.com/thinkjs/eslint-config-think
