### ISSUE TITLE
cluster模式下，cron重复执行的问题

### ISSUE THREAD

**Issue by delayhsiao** [thinkjs/thinkjs#602]
一般是为了尽可能使用系统资源开启的cluster模式，这样就在后台跑了多个进程，这样就导致在bootstrap里面的定时任务在多个进程里重复执行，在不把cluster数量强制设置为1个的情况下，怎么规避crontab重复执行呢？
@welefen

**Comment by welefen** [comment]
恩，2.x 下暂时可以通过 cluster.worker.id 来判断下，比如： cluster.worker.id === 1 这样只在第一个子进程下执行。
3.0 下会系统性的解决这类问题。

**Comment by delayhsiao** [comment]
@welefen get√
另外，问一下，比如说我有个操作是异步的，在这个操作里面循环写数据进session
然后我在其他方法里读取这个session值
在这个异步方法执行结束前，我在其他方法里读不到它写入的session是什么情况？

**Comment by delayhsiao** [comment]
@welefen 这个可以关了
