### ISSUE TITLE
production环境启动不能找到静态资源

### ISSUE THREAD

**Issue by zhipenglin** [thinkjs/thinkjs#604]
## ENV

Platform:MAC OS

Node.js Version:v6.3.0

ThinkJS Version:2.2.18

https://github.com/zhipenglin/exhibition

**Comment by zhipenglin** [comment]
需要配置/common/config/env/production.js  resource_on: true，默认是false

**Comment by welefen** [comment]
production 下默认关闭了 resource_on，建议使用 nginx 代理
