### ISSUE TITLE
关于在异步操作中使用session无法连续记录的问题

### ISSUE THREAD

**Issue by delayhsiao** [thinkjs/thinkjs#606]
我有个需求是这样的：
在Action中有个操作是耗时操作，所以我并没有使用await来阻塞而是让它进行异步执行
```
mianAction(){
  this.child()
  return this.end()
}
```
然后在这个async方法里进行循环写入session
```
async child(){
  for(var i = 0; i < 10; i++){
    await this.session('value' + i, Math.random())
  }
}
```
然后，我查看了session文件（我的session是file类型），session只有一条记录，也就是value0的值，求问怎么解决这个问题。
另外，我试过在child方法里用fs写文件，同样是写文件的耗时操作，fs的结果没毛病，session就不行，为什么？
@welefen

**Comment by welefen** [comment]
Session 是在请求结束的时候统一来写的，也就是调用 `this.end` 来写入，一个请求中后续在调用是无效的。

你的需求是为了解决什么问题呢？

**Comment by delayhsiao** [comment]
我在执行异步操作的时候需要实时返回执行进度，想法是通过session保存进度，然后在其他方法中读取session里面的进度来实现。

**Comment by delayhsiao** [comment]
解决了 @welefen 
我在执行完session写入后，手动调用了flush方法
```
var session = think.session(this.http)
session.flush()
```

**Comment by welefen** [comment]
@delayhsiao 好机智
