### ISSUE TITLE
使用middleware时如何更新内容？

### ISSUE THREAD

**Issue by Tabjy** [thinkjs/thinkjs#613]
## DESC
```js
// src/common/config/hook.js
export default {
  view_after: ['append', 'test-filter'],
};
```
```js
// src/common/bootstrap/middleware.js
think.middleware('test-filter', async(http, content) => {
  if (!content) {
    return;
  }
  console.log(content); // 这里得到了正确渲染后的 HTML String

  // some operations done to content
  content = 'test';

  return content;
});
```
但是最后在浏览器得到的还是原来的内容 而不是更新之后的 "test"。Google了一下其他用到了 Middleware 的项目，浏览了一下 Middleware 相关的源代码，确实找不到问题所在。请问我这是哪里没有处理正确。
希望能够得到您的答复，谢谢。
## ENV

Platform: *Arch Linux x86_64*

Node.js Version: *v7.9.0*

ThinkJS Version: *v2.2.18*

**Comment by welefen** [comment]
`view_after` 是指 view 处理完成之后的操作，如果想修改内容的话，需要使用 `view_filter`

**Comment by Tabjy** [comment]
啊原来是这样！大意了，抱歉。（虽然我记得写的是 `view_filter` 来着…）
非常感谢，很好用的框架。

**Comment by welefen** [comment]
觉得好的话多推荐给你的朋友哦
