### ISSUE TITLE
thinkjs 3.0 能否也可以同时支持不需要监听一个端口的应用框架？

### ISSUE THREAD

**Issue by arden** [thinkjs/thinkjs#614]
很多时候我们只需要写一个简单的App应用，不需要Web服务和监听一个端口。但是很多时候依赖一些基础性的东西，如数据库、配置文件等，但这些其实是可以封装成一个类似java里的spring框架那样只用来创建一个普通的App应用。

**Comment by welefen** [comment]
ThinkJS 是支持命令行执行的
