### ISSUE TITLE
进行数据库查询时，使用between的某个用法时报错。

### ISSUE THREAD

**Issue by melonHuang** [thinkjs/thinkjs#616]
## DESC
使用以下用法：
```javascript
 return this.where({id: ['BETWEEN', fromDate, toDate]}).select();
```

拼接处SQL语句：
```sql
SELECT * FROM `performance` WHERE (  (`time` BETWEEN '2017-04-13 00:00:00' AND undefined) ) AND ( `path` = 'index' ) AND ( `platform` = 'pc' ) AND ( `timings` IS NOT NULL )
```

mysql报错：
![image](https://cloud.githubusercontent.com/assets/2511418/25228225/350f8ff6-25fe-11e7-80cb-54c2d1b4c6af.png)

## ENV

Platform: osx

Node.js Version: v6.2.0

ThinkJS Version: v2.2.15

**Comment by qgy18** [comment]
这里逻辑有问题：
https://github.com/thinkjs/thinkjs/blob/f52f4a14e67b3d9f260f31784ae08a84491da1e5/src/adapter/db/_parse.js#L312

`['BETWEEN', fromDate, toDate]` 这样使用时，val[1] 如果是 string，split 之后肯定是 array，导致 val[2] 就为 undefined 了。


```javascript
else if(val0 === 'BETWEEN'){
        data = think.isString(val[1]) ? val[1].split(',') : val[1];
        if (!think.isArray(data)) {
          data = [val[1], val[2]];
        }
        whereStr += ' (' + key + ' ' + val0 + ' ' + this.parseValue(data[0]);
        whereStr += ' AND ' + this.parseValue(data[1]) + ')';
      }
```
