### ISSUE TITLE
如何获取当前路由

### ISSUE THREAD

**Issue by flftfqwxf** [thinkjs/thinkjs#618]
## DESC
需要在模板文件中判断，选中当前链接，故需要知道当前路由是哪个，查看文档，未发现有此类方法。
目前的思路，是写一个公共的class 然后在 __before方法中获取到当前路由，然后通过 assgin方法，传递给VIEWS层，请问是否方法可以在 __before中获取到当前的路由，或者可以在VIEWS层直接判断当前路由，谢谢。

## ENV

Platform:
mac
Node.js Version:6.9.1

ThinkJS Version:2.2.12

**Comment by welefen** [comment]
`http.url`，或者通过 `http.module`, `http.controller`, `http.action` 联合判断
