### ISSUE TITLE
mongo 用select查询数据

### ISSUE THREAD

**Issue by xiongxt** [thinkjs/thinkjs#619]
## DESC
await model.where({ "_id": {'$in':ids} }).select(); 
这样查询不出数据
但是：
await model.where({ "name": {'$in':['aaa','bbb']} }).select()
就查询得出

不知道什么原因，如何通过id数组查询数据？

## ENV

Platform:mongo最新

Node.js Version:6.10.0

ThinkJS Version:2.2

**Comment by xiongxt** [comment]
ids 的数据
ids[]:58fc674882ba1847135cfe0d
ids[]:58fc675782ba1847135cfe0e
ids[]:58fc6d0b82ba1847135cfe0f
ids[]:58fc6d1082ba1847135cfe10
ids[]:58fc6d4682ba1847135cfe12
ids[]:58fc6d4d82ba1847135cfe13
ids[]:58fc6d5282ba1847135cfe14
ids[]:58fc76f5856c7bd21359aa45

**Comment by xiongxt** [comment]
_id 为mongo自动生成的

**Comment by xiongxt** [comment]
`ids = ids.map((id) => {
                return new ObjectId(id);
            });`

**Comment by xiongxt** [comment]
有没有更好的方法？

**Comment by welefen** [comment]
现在没有自动转换的过程，需要开发者自己来加
