### ISSUE TITLE
前端使用react-router的browserHistory时，thinkjs应该如何配置？

### ISSUE THREAD

**Issue by KidLau** [thinkjs/thinkjs#620]
## DESC
最近需要自己一个人完成一个项目，后端使用thinkjs，前端使用react，在使用react-router时，使用了browserHistory，thinkjs应该如何配置支持？

## ENV

Platform: deepin linux 15.4

Node.js Version: 6.3.1

ThinkJS Version: 2.2

**Comment by welefen** [comment]
可以通过自定义路由，将请求都映射到一个 Action 下。或者可以借助 404 来实现，如：https://github.com/firekylin/firekylin/blob/master/src/common/controller/error.js#L74

**Comment by KidLau** [comment]
OK！明白了，谢谢作者亲自指导
