### ISSUE TITLE
mysql数据库现有的表名为大写，linux大小写敏感，导致thinkjs提示找不到表

### ISSUE THREAD

**Issue by tobyforever** [thinkjs/thinkjs#623]
## DESC
mysql数据库现有的表名为大写，linux大小写敏感，导致thinkjs提示找不到表
Error: ER_NO_SUCH_TABLE: Table 'hbpd.APP_colleaguehelp' doesn't exist

## ENV

Platform:
ubuntu 16.04

Node.js Version:
6.10.2

ThinkJS Version:
2.2.18

**Comment by xb594328980** [comment]
你调节mysql数据库为兼容模式 这样数据库就全部为小写了 sql语句、表明也兼容大小写
