### ISSUE TITLE
__before无法阻止action被执行

### ISSUE THREAD

**Issue by wstygk** [thinkjs/thinkjs#628]
我看了源代码, controller里面的__before里面除非抛出异常,否则无法阻止action被执行.但是开发者可以在什么地方截获和处理该异常?

**Comment by welefen** [comment]
可以 `return think.prevent()`

**Comment by wstygk** [comment]
好的,谢谢.希望能在文档中有所体现

**Comment by SPARON** [comment]
return think.prevent()，也无发阻止action的继续执行，仍然调用了action
