### ISSUE TITLE
如果有类似于 thinkphp 那样详细的手册就好了

### ISSUE THREAD

**Issue by choicky** [thinkjs/thinkjs#630]
[thinkjs 官网](https://thinkjs.org/zh-cn/doc/index.html) 有文档，但远远不如 thinkphp 的手册详实。我这种业余人士很难上手 ....

如果有类似于 thinkphp 那样详细的手册就好了

**Comment by welefen** [comment]
具体觉得哪些地方不够详细呢？

**Comment by choicky** [comment]
每个人的基础不一样，所以要求不一样。

印象中，前几年，我在几乎没有基础的情况下，看了 thinkphp 的手册以及李炎恢的视频教程，就能自己捣鼓出一个小程序给自己使用了。

我现在看了 thinkjs 的文档，感觉还是不知道如何下手……

我觉得，thinkjs 的文档可以附加一个简单的demo，例如从0搭建一个留言板或blog之类，让新手知道从创建 mysql 数据库、创建M、V、C，并顺带引出 thinkjs 特有的或常用的对象/方法等。

thinkjs 框架可以附带上这个 demo 一起发布。

**Comment by vipzrx** [comment]
@choicky s/详实/翔实/
