### ISSUE TITLE
数据库的update, increment能否使用一个命令实现

### ISSUE THREAD

**Issue by wstygk** [thinkjs/thinkjs#631]
数据库的update, increment能否使用一个命令实现.这在原生sql语句是能实现的.如果执行两个命令,我感觉效率和事务会有问题.

**Comment by welefen** [comment]
具体的 SQL 是啥？
如果包装的方法不能满足的话，暂时可以用 query 或者 execute 方法来执行 SQL 语句。

**Comment by wstygk** [comment]
例如用户登录后,修改user表中的登录地址,登录时间字段,并同时增加登录次数字段.

**Comment by welefen** [comment]
那这个用 update 方法可以实现。

**Comment by wstygk** [comment]
具体呢?

**Comment by wstygk** [comment]
我在源代码里面看到了,但是你们的文档好像没有说明呀!!!

**Comment by wstygk** [comment]
我看了你们的代码,你们的redis里面有个wrap函数,可以更加灵活的操作redis.
这可以放出来让大家使用.
文档,文档,文档完善很重要,重要的事情说三遍.
