### ISSUE TITLE
關於文件說明的 使用 node-crontab 模块执行定时任务

### ISSUE THREAD

**Issue by tonybala** [thinkjs/thinkjs#634]
## DESC
我依照官網的說明做測試，發現如果crontab.js
有修改內容，之前的定时任务會一直存在
多改幾次crontab.js就會有多個任务
請問這樣算是正常?

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
现在开发环境里是这样的，线上不会出现这种情况。
2.x 里开发环境下暂时不太好弄，3.0 版本里会解决这个问题。
