### ISSUE TITLE
支持redis数据库，该怎么修改？

### ISSUE THREAD

**Issue by phpcs** [thinkjs/thinkjs#635]
怎么添加redis客户端，支持redis各种操作

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
可以 require 内置的 redis，也可以引入一个外部的 redis 模块

**Comment by phpcs** [comment]
内置的redis 想再封装一下，还有一些通用的类，放哪个位置比较好啊？
暂时是放到global里面，但是感觉怪怪的
