### ISSUE TITLE
0 应该算是整数吧，Logic 整数检测不通过，很难受

### ISSUE THREAD

**Issue by 2681137811** [thinkjs/thinkjs#636]
## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
具体是怎么使用的

**Comment by 2681137811** [comment]
id : "int:0,1000000000|required"

**Comment by dsonet** [comment]
Same as issue #546 .

**Comment by humbass** [comment]
所有的语言，0 都是无法通过的，默认情况下

**Comment by welefen** [comment]
已经在 2.2.19 版本里修复
