### ISSUE TITLE
为什么在2.2.8版本中，又用node-mysql 替代 node-mysql2？

### ISSUE THREAD

**Issue by DellaDu** [thinkjs/thinkjs#638]
## DESC

2.2.2版本中，因为node-mysql2的性能优势， node-mysql 被替换为 node-mysql2.
那为什么又重新使用node-mysql?

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
node-mysql2  虽然在性能上有所提升，但稳定性方面有问题，所以又切回去了。

**Comment by DellaDu** [comment]
谢谢！了解了。
