### ISSUE TITLE
Is it possible to disable babel complier when nodejs version > 7 in thinkjs 3?

### ISSUE THREAD

**Issue by dsonet** [thinkjs/thinkjs#639]
## DESC
Since node 7 already support almost all ES new features, can we just skip the compile step?

## ENV

Platform:

Node.js Version: 7.10

ThinkJS Version: 3

**Comment by welefen** [comment]
Yes, you can close compile in ThinkJS 3.0.

https://github.com/thinkjs/think-demo/blob/master/development.js

when remove code
```js
  transpiler: [babel, {
    presets: ['think-node']
  }],
```
in development.js, watch compile will be closed.
