### ISSUE TITLE
是否支持 text/plain格式的数据接收

### ISSUE THREAD

**Issue by flftfqwxf** [thinkjs/thinkjs#641]
## DESC
客户端POST数据，POST类似是 text/plain，不是常用的【form-data】,【x-www-form-urlencoded】

目前在POSTMAN中测试，无法在服务端获取到数据，是否是不支持此类型

## ENV
dev
Platform:
MAC
Node.js Version:
v6.9
ThinkJS Version:
2.6.1

**Comment by welefen** [comment]
可以通过 https://thinkjs.org/zh-cn/doc/2.2/api_http.html#toc-c0b 获取上传的内容，然后自己解析

**Comment by flftfqwxf** [comment]
@welefen 谢谢，我自己写了个插件来解决了，think-raw-body
