### ISSUE TITLE
关于MYSQL的model查询问题

### ISSUE THREAD

**Issue by zhangyanhao** [thinkjs/thinkjs#642]
## DESC
  执行语句A：let data = await model.limit(2).select(
  后台记录：
            [SQL] SHOW COLUMNS FROM `a_temp` 8ms
            [SQL] SELECT * FROM `a_temp` LIMIT 2 1ms

   执行语句B： let data = await model.query('SELECT * FROM `a_temp` LIMIT 2');
  后台记录：
            [SQL] SELECT * FROM a_temp` LIMIT 2 2ms

   请问，为何用model的查询，会自动做一次 SHOW COLUMNS 的查询，是我设置有问题吗，谢谢！

## ENV

Platform: windows

Node.js Version: v6.10.2

ThinkJS Version: v2.2.18

**Comment by welefen** [comment]
开发环境下会实时查询数据表的字段变化，线上环境只会第一次有这个执行
