### ISSUE TITLE
thinkjs 3.0 能按计划6月份出来吗？

### ISSUE THREAD

**Issue by choicky** [thinkjs/thinkjs#645]
最近在从0开始自学 nodejs ，打算用 thinkjs 做个很小的工具自用。

如 thinkjs 3.0 能在6月份出来，我就等 3.0 了

**Comment by welefen** [comment]
计划是 6 月底，应该差不多

**Comment by javiermu** [comment]
3.0有哪些新功能或者特性期待？

**Comment by welefen** [comment]
alpha1 版本已经发布，6 月初开始写文档， 6 月底或者 7 月初发布正式版

**Comment by welefen** [comment]
https://github.com/thinkjs/think-demo
