### ISSUE TITLE
使用数据库为 mongo 的时候是不是只能按 model.base model.mongo 里的方法使用？

### ISSUE THREAD

**Issue by zheeeng** [thinkjs/thinkjs#648]
## DESC

有没有办法使用 mongodb 的原生方法呢？使用 model.find() 只能返回一条，model.select() 才返回多条，查询用 model.where ，实在感觉怪，太关系型了。另外 model.aggregate 的返回结果也不是很理解：

```
this.model.aggregate({
  $project: {
    '_id': 0,
    'id': '$id'
  }
})
```
在 mongodb 里可以这样用，在 tj 里返回的是 model 的信息？初学，不是很理解这些结果

**Comment by welefen** [comment]
那可以参考这篇文章，http://welefen.com/post/use-mongoose-in-thinkjs.html，直接使用 mongoose
