### ISSUE TITLE
使用model.add方法添加数据后，不返回ID

### ISSUE THREAD

**Issue by flftfqwxf** [thinkjs/thinkjs#650]
## DESC
文档显示，应该返回ID，但由于创建的数据字段 并没有设置主键ID而是生成的随机hash作为ID，所以无法返回
请问在此情况下，如何状态数据是否添加成功？

## ENV
DEV
Platform:
mac
Node.js Version:
6.9
ThinkJS Version:
2.2.12

**Comment by welefen** [comment]
数据表里有主键的字段么？如果有的话，可以设置下 pk 属性

**Comment by flftfqwxf** [comment]
@welefen 在设置了主键，依然不行，插入数据成功，依然返回 0

**Comment by guangzhoujason** [comment]
这个问题，跟我提的issue 一样

貌似只能上一层 try。。没有出错就成功了 @welefen
