### ISSUE TITLE
Does thinkjs support remote template?

### ISSUE THREAD

**Issue by miaojiuchen** [thinkjs/thinkjs#651]
I want to render remote template in my project, I tried controller.fetch like this:

`
  let tpl = await this.fetch("http://10.100.100.xx:xxxx/aa/bb/index.html");
`

but I got this error 

> can't find template file `/Users/infinity/WorkSpace/thinkdemo/view/home/http://10.100.100.xx:xxxx/aa/bb/index.html`

## so... what's the correct practice to render remote template?

Platform:  macOS Sierra 10.12.4

Node.js Version: 7.10.0

ThinkJS Version: 2.2.0

**Comment by welefen** [comment]
Not support render remote template!

**Comment by miaojiuchen** [comment]
thanks

**Comment by miaojiuchen** [comment]
I solve this by doing this:
```javascript
async fetchLeonidTpl(name) {
            let url = `http://localhost:8000/${name}.html`;
            return await requestAsync({ url });
        }

let tpl = await fetchLeonidTpl("index");
        this.type("text/html");
        this.end(tpl);
```
