### ISSUE TITLE
Mongo主键_id查询$in无结果

### ISSUE THREAD

**Issue by zhaozww** [thinkjs/thinkjs#652]
## DESC
使用Mongo作为数据库，查询_id在一个数组中数据，采用如下方式：
let data = await this.model('current').where({_id:{$in: ['590fda043ee6502444f1ef4a']}}).select();
无结果（该数据存在）
然后怀疑是_id类型的问题，引入
import ObjectID from 'mongodb';
let data = await this.model('current').where({_id:{$in: [ObjectID('590fda043ee6502444f1ef4a')]}}).select();
依然无结果
## ENV
window8

Platform:windows8

Node.js Version: 6.10.3
ThinkJS Version:2.2.18

**Comment by zhaozww** [comment]
已解决，引入objectID函数有误

**Comment by liuhuanhui** [comment]
怎么解决的
