### ISSUE TITLE
路由支持大写，替换可通过配置项实现

### ISSUE THREAD

**Issue by jiangdefu** [thinkjs/thinkjs#654]
## DESC
现在 thinkjs 里面访问路由不支持大写，比如（cityAPI/getCityList）这样，可以命中 cityAPI

 控制器 下的 getCityList Action ，这个  应该怎么配置呢？
## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
city_api  https://thinkjs.org/zh-cn/doc/2.2/route.html#toc-bed
