### ISSUE TITLE
模板引擎希望支持 xtemplate

### ISSUE THREAD

**Issue by Messilimeng** [thinkjs/thinkjs#659]
http://book.apebook.org/minghe/koa-action/xtemplate/use.html

**Comment by welefen** [comment]
官方短期内应该不会支持，你可以帮忙实现下这个 adapter

**Comment by welefen** [comment]
@Messilimeng 有意愿帮忙实现么？

**Comment by Messilimeng** [comment]
@welefen 估计难以胜任啊, 最近一直在看3.0源码

**Comment by lizheming** [comment]
xtemplate 的 adapter 已经实现，欢迎使用 <http://npmjs.com/think-view-xtemplate>
