### ISSUE TITLE
关于websocket的疑问

### ISSUE THREAD

**Issue by humbass** [thinkjs/thinkjs#660]
## DESC

框架直接集成了 websocket ，相当的方便，不过有个地方不是很明白，如果我希望一个controller或者module常驻后台，这个该怎么整？

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
```js
let isLoad = false;

function dosomething(){
  setInterval(() => {}, 1000)
}
testAction(){
  if(!isLoad){
    isLoad = true;
    dosomething();
  }
}
```
类似这样

**Comment by humbass** [comment]
这样也行？ 有点屌。    刚使用thinkjs完成一个小项目，thinkphp转thinkjs完全没有压力，感谢感谢！
