### ISSUE TITLE
Can we turn off the babel compiler when running on node > 8?

### ISSUE THREAD

**Issue by dsonet** [thinkjs/thinkjs#664]
## DESC

Or add strategies based target node version, newer version will need less transform.

## ENV

Platform:

Node.js Version: 8

ThinkJS Version: 3

**Comment by SijieCai** [comment]
I turn off babel compiler on node > 7.

It is possible to set a strategy:

``` js
const Application = require('thinkjs');
const babel = require('think-babel');
const watcher = require('think-watcher');
const notifier = require('node-notifier');

function useTranpiler() {
  //..
.}

const instance = new Application({
  ROOT_PATH: __dirname,
  watcher: watcher,
  transpiler: useTranpiler() ? [babel, {
    presets: ['think-node'] 
  }] : undefined,
  notifier: notifier.notify.bind(notifier),
  env: 'development'
});

instance.run();
```

**Comment by dsonet** [comment]
@SijieCai Thanks for that. Just came up an idea, we may can use uglifyJS to compress the source code in src before copy to app directory.
