### ISSUE TITLE
logic 数据验证中 验证不通过 使用 think.statusAction 404 不起作用

### ISSUE THREAD

**Issue by tenjj** [thinkjs/thinkjs#667]
## DESC
logic 层验证数据 不想使用默认的this.fail() 形式返回json, 想直接返回404页面, 为何 
return think.statusAction(404, this.http) 后 还是走到了controller里面呢

## ENV development

Platform: osx

Node.js Version: 7.1

ThinkJS Version: 2.2

**Comment by welefen** [comment]
贴下具体的代码

**Comment by tenjj** [comment]
development 重启了几下 可以了 估计是编译的问题
