### ISSUE TITLE
请问thinkjs对RESTFul的支持如何，如何获取路径参数？

### ISSUE THREAD

**Issue by SPARON** [thinkjs/thinkjs#669]
1. 请教下ThinkJS对RESTFul的支持力度如何呢？
2. 请问下路由中的路径参数如何定义？
3. 如何获取路径参数呢？

**Comment by epirus** [comment]
https://thinkjs.org/zh-cn/doc/2.2/api_controller.html#toc-9ef

**Comment by SPARON** [comment]
@epirus 谢谢你的答复，不过我说的是路径参数，貌似，你说的这个取不到路径参数吧！

**Comment by SPARON** [comment]
@epirus 不好意思，刚才没看到官方文档，实际官方文档中有对REST支持的描述，不过支持力度不够，很简单。

定义和取参都有描述，[参考这里](https://thinkjs.org/zh-cn/doc/2.2/rest_api.html)
