### ISSUE TITLE
如何关闭请求中的这个字段  X-Powered-By:

### ISSUE THREAD

**Issue by epirus** [thinkjs/thinkjs#671]
如上面的标题，文档中没找到，希望加入faq

ThinkJS Version:
2.2.x

**Comment by welefen** [comment]
现在不支持关闭这个 header，下个版本考虑加入配置开关

**Comment by tenjj** [comment]
@epirus 可以在nginx 里面设置 proxy_hide_header X-Powered-By

**Comment by jguang** [comment]
加个hook删除：

```
if (!http.res.headersSent) {
        http.res.removeHeader('X-Powered-By');
 }
```

**Comment by tangjoin** [comment]
How to use
config file src/config/middleware.js

const meta = require('think-meta');
module.exports = [
  {
    handle: meta,
    options: {

    }
  }
]
Support options
{
  requestTimeout: 10 * 1000, //request timeout, default is 10s
  requestTimeoutCallback: (ctx, options) => {}, //request timeout callback
  sendPowerBy: true,  //send powerby
  sendResponseTime: true, //send response time
  logRequest: true //log request
}
