### ISSUE TITLE
怎么在插入或者更新数据的时候使用 timestamp

### ISSUE THREAD

**Issue by zheeeng** [thinkjs/thinkjs#673]
手动维护的要这样，update({ name: 'Jhon', updateTime: new Date() }, { where: { id: 123 }})
然而它并不是 timestamp 类型。

**Comment by epirus** [comment]
updateTime 改成整数类型？

**Comment by zheeeng** [comment]
@epirus mysql 有 timestamp 类型，mongo 有 $currentTime。之前用 laravel ，某字段定义好是 timestamp 更新或插入时不手动指定会自动更新。更重要的是，它会用数据库自带的时间函数，用 js 的时间函数总觉得不太好，也不智能。

**Comment by epirus** [comment]
https://thinkjs.org/zh-cn/doc/2.2/api_think.html#toc-095
 看看这个有没有帮助

**Comment by humbass** [comment]
在thinkjs框架下，我的习惯是纯bigint(13)的格式。 用php的话int(11)方式

**Comment by welefen** [comment]
`think.datetime()`

**Comment by zheeeng** [comment]
@welefen 你好，这个方法仍然是手动插入，对 order 也不友好。能否直接让数据库使用它自己的时间函数？

**Comment by welefen** [comment]
@zheeeng  可以通过 `exp` 表达式，如：

```js
this.add({
   time: ['exp', 'CURRENT_TIMESTAMP()'] //这里CURRENT_TIMESTAMP为mysql 函数，exp 必须为小写
})
```

**Comment by humbass** [comment]
不知道大家存时间（需要用来order的），用哪种格式比较好，俺目前使用bigint(13) 是不是比较奇葩的方式？

**Comment by zheeeng** [comment]
@welefen 我在文档里寻找 exp 的用法，似乎没有详细的介经，https://thinkjs.org/zh-cn/doc/2.2/api_model.html#toc-411 这里 exp 用的大写，你的回复说用小写。mongo 里也可以用 exp 吗

**Comment by guohuihot** [comment]
mongodb里管用吗？好像不管用
