### ISSUE TITLE
如何在其他的action里头调用 websocket 的方法

### ISSUE THREAD

**Issue by humbass** [thinkjs/thinkjs#674]
## DESC

无论是用this.action，还是this.emit 都会提示下面的信息
**emit method can only used in websocket request**

socket.io 官网有方法  io.sockets.xxxx 

请教下如何拿到 io 对象呢？

## ENV

Platform: centos 7

Node.js Version: v7.8.0

ThinkJS Version: 2.0

**Comment by welefen** [comment]
https://thinkjs.org/zh-cn/doc/2.2/adapter_websocket.html#toc-112

**Comment by humbass** [comment]
在 指定的
    messages: {
        open: 'socket/index/open',
        close: 'socket/index/close',
        chat: 'socket/index/chat',
        chat2: 'socket/index/chat2',
    }
下，例如socket/index/chat2下 可以使用 this.http.io ，
在另外一个 home/index/test 就拿不到这个this.http.io

**Comment by cnzin** [comment]
我也遇到过这个问题, 后来参考 [adapter/socket.io.js](https://github.com/thinkjs/thinkjs/blob/master/src/adapter/websocket/socket.io.js#L69) 用 `thinkCache` 保存 io 句柄引用. 关于 #672 也可用相同的方法解决.

**Comment by humbass** [comment]
#672 后来也解决了，采用global就可以了，不过初始化如果要从数据库获得数据，还没折腾出来。

**Comment by yunliang-ding** [comment]
为什么我这个总是不打印呢？
![_svvizqulf__e534o eb14](https://user-images.githubusercontent.com/18275334/28005343-9b73bde0-657c-11e7-9f8e-e47c33d9c273.png)

**Comment by humbass** [comment]
感觉路径不对啊。

2017-07-10 14:32 GMT+08:00 yunliang-ding <notifications@github.com>:

**Comment by humbass** [comment]
@yunliang-ding  chat: '/index/chat' 的路径不对吧？

**Comment by jiangb** [comment]
@humbass 具体如何做的呢？如何保存 io 句柄？

**Comment by lushijie** [comment]
this.ctx.req.io 保存着当前io
