### ISSUE TITLE
修改文件重新编译问题，定时器问题

### ISSUE THREAD

**Issue by epirus** [thinkjs/thinkjs#678]
如果我在修改源文件，然后thinkjs对这个文件开始 compiling  

如果源文件中有定时器，那么编译后的定时器还是会执行的，也就是说好像node进程并没有重启，所有所有的定时器都会保存下来？

ThinkJS Version:2.2.x

**Comment by welefen** [comment]
恩，2.x 下是有这个问题。这时候需要把服务重启下。3.0 版本里换了实现方式，已经解决这个问题了
