### ISSUE TITLE
是否支持特殊的项目布局

### ISSUE THREAD

**Issue by libery** [thinkjs/thinkjs#679]
## DESC
是否支持类似如下的代码布局：
src/server (后台代码，通过babel生成到app/)
src/xxx (前台代码，通过babel生成到 www/xxx.js)

## ENV
thinkjs2.0
Platform:

Node.js Version:

ThinkJS Version:

**Comment by epirus** [comment]
gulp webpack 都可以吧，这个自己配置就可以

**Comment by libery** [comment]
默认thinkjs编译src下所有文件到app下

**Comment by epirus** [comment]
嗯. 我觉得原来的目录安排就很合理.
