### ISSUE TITLE
bootstrap 目录下面的文件执行两次

### ISSUE THREAD

**Issue by epirus** [thinkjs/thinkjs#680]
如果我修改了bootstrap里面的文件，这个时候运行 npm start 那么这么这里面的文件会执行两次.

感觉thinkjs的逻辑好像是 先运行，如果监测到文件有变化在重新执行。如果这样子执行的话那么很多前期的准备的工作就会执行两遍。

```bash
npm run compile && npm start 
```
是不是应该这么处理

但是我觉得运行执行了多次应该通知一下，或者这是一个逻辑bug

ThinkJS Version:2.2.x

**Comment by welefen** [comment]
恩，2.x 版本里是有这个问题。遇到这个问题时可以把服务重启下。
3.x 里重新设计了自动编译和自动更新的机制，解决了这类问题
