### ISSUE TITLE
min and max and  is not a function?

### ISSUE THREAD

**Issue by shihuojian** [thinkjs/thinkjs#681]
李老大min、max、avg使用的时候提示这几个方法未找到？
let result = await this.model(params.table).where(params.where).max(params.field);

**Comment by welefen** [comment]
是 Mysql 还是 mongo?

**Comment by shihuojian** [comment]
mongo

发自我的 iPhone

**Comment by shihuojian** [comment]
暂时用find替代了

发自我的 iPhone
