### ISSUE TITLE
在__before中提供非跳转方式的阻止后续代码继续执行

### ISSUE THREAD

**Issue by SPARON** [thinkjs/thinkjs#683]
在__before中做了某些操作后需要阻止后续代码执行，包括get、post等方法调用，但现实情况是仅仅阻止了request请求的输出，后台代码仍在继续运行。

**Comment by SPARON** [comment]
根据问题[#628](https://github.com/thinkjs/thinkjs/issues/628)，发现只要返回think.Promise类型的都是可以阻止的！

**Comment by welefen** [comment]
返回一个 Rejected Promise 就可以了，也可以返回 `think.prevent()`
