### ISSUE TITLE
如何关闭深层 relation，查询时不带出数据

### ISSUE THREAD

**Issue by aNd1coder** [thinkjs/thinkjs#684]
## DESC
我这里有 3 个表（彼此有 id 关联），关系如下：
model/table1.js
```
table2: {
  type: think.model.HAS_MANY
}
```
model/table2.js
```
table3: {
  type: think.model.HAS_MANY
}
```

当我在 controller/table1.js 进行查询时，如何不把 table3 的数据都查询出来？
`await this.modelInstance.select()`

## ENV

Platform:
MacOS

Node.js Version:
v6.10.2

ThinkJS Version:
v2.2.15

**Comment by welefen** [comment]
你的意思是关联查询 table2 的时候不想把 table3 的数据也带出来？

**Comment by aNd1coder** [comment]
@welefen 是的，setRelation 只能关闭当前层次的关联

**Comment by welefen** [comment]
这个目前还不支持，后续考虑下怎么支持下。

**Comment by aNd1coder** [comment]
@welefen 👌  等后续更新

**Comment by welefen** [comment]
@aNd1coder  https://thinkjs.org/zh-cn/doc/2.2/model_relation.html#toc-0ec  发现之前已经支持了，更新了下文档

**Comment by aNd1coder** [comment]
@welefen 验证没问题，nice job~

**Comment by Lutreer** [comment]
`get relation() {
    return {
      goods: {
        type: think.Model.MANY_TO_MANY,
        rModel: 'topic_goods',
        rfKey: 'goods_id',
        where: {status: 1},
        relation:['goods'] // 支持数组形式过滤掉关联数据，希望完善文档
      }
    }
  }`
