### ISSUE TITLE
thinkjs 3.0 有消息了么，非常期待

### ISSUE THREAD

**Issue by 2681137811** [thinkjs/thinkjs#686]
## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by xiaogaofudao** [comment]
等了快 一个月了。正式版大概何时能发布啊

**Comment by zuoyanart** [comment]
好像又跳票了 @xiaogaofudao

**Comment by yaolynzc** [comment]
非常期待+1

**Comment by welefen** [comment]
已经发布了 beta1，我们内部正在试用和写文档，会尽快和大家见面

**Comment by 2681137811** [comment]
@welefen
比较关心 3.0 的一些地方：

1. think 对象有没有列出所有模块的所有 Action 的接口，用于检索所有 API 进行统一安全管理
2. 定时任务功能有没有改进，开发模式下会不会还有重复载入定时任务的 BUG ？
3. 多级控制器无法实例化，我不知道这是一个 bug 还是架构设计上的一个缺陷。

```
例如我有一个三层的控制器 admin/user/address，使用以下方法无法实例化该控制器：
think.controller('user/address', http, 'admin');
this.controller('admin/user/address') ;
```

4. 使用 think.controller('user', http, 'admin');实例化控制器时， http 参数是否必传？如果在定时任务中没有 http 对象如何实例化该控制器？目前我是用 request 模块去直接访问 http://127.0.0.1:8360/model/controller/action  来解决，有点小尴尬。

**Comment by 2681137811** [comment]
model mysql 有没有创建表的代码以及检测某张表是否存在，或者是执行 sql 代码的方法，文档上面好像没有说清楚

**Comment by welefen** [comment]
@2681137811
1、为啥需要列出所有的 Action 接口呢？
2、定时任务已经改为配置的形式了，开发模式已经没有重载的 bug
3、4  什么场景下要脱离 controller 之外调用其他的 controller 呢？

**Comment by 2681137811** [comment]
@welefen
1、所有 Action 都是可以通过 http 链接访问的，如果能列出所有控制 Action ，在 API 接口管理（权限识别、角色控制、安全检测）上会更加智能化，当然这只是个人建议。

3、用户通过 http 链接调用程序才会有 http 对象，如果是程序自己主动调用自己就没有 http 对象的。比如定时任务，每隔一段时间调用一次，或是程序初始化时候我就要立即执行控制器的一个方法。

-----------------------------------------

另外就是如果我想从数据库来加载 config 的话，框架好像并没有这样的一个方案，只能加载本地的
 config ，只有程序完全运行起来后，才能开始使用 think.config() 修改配置，如果能给个钩子之类的就好了。

**Comment by welefen** [comment]
@2681137811 
1、可以通过 `think.app.controllers` 获取所有的 controller。一般这种验证也需要后台去一一配置 Action 具体有什么权限，也不需要程序获取所有的 Action。
3、内置的定时任务会自动创建 ctx 对象（也就是 2 里面的 http 对象）

动态设置 config、router 可以通过 `think.beforeStartServer` 方法里处理。

当然这些是需要在 3.0 里使用的。

**Comment by adeweb** [comment]
啥时候发布3.0呢，期待中！:)

**Comment by welefen** [comment]
@adeweb 正在写文档，这周会把文档放一版出来。

**Comment by SPARON** [comment]
@welefen 不知道有没有办法在action上通过增加注解的方式配置参数，类似spring那样，这样的话就可以动态实现wadl接口文档

**Comment by xb594328980** [comment]
@SPARON 可以通过apidoc这个来生成接口文档，可用信息包含header、parms、response、response_error可以满足文档需求。

**Comment by humbass** [comment]
version 2 开发模式重载，看来大家都遇到了，我目前的解决方式是 增加一个global.init 判断
if (!global.init) {
    global.init = true;
    globan.fn = () => {}
    global.schedule = require('node-schedule');
     // do schedule
}

**Comment by welefen** [comment]
3.0 beta 版文档已经出炉， https://thinkjs.org/doc/3.0/index.html  欢迎试用。

**Comment by welefen** [comment]
@humbass 3.0 版本里自动更新是通过重新 fork 子进程来完成，不在有此问题。

**Comment by humbass** [comment]
下个项目使用吧，刚才看了下发现3.0基于Koa,原来的代码得做较多的修改，无法平滑升级啊。

**Comment by welefen** [comment]
@humbass  底层改动很大，但使用上变化不是太大，一般一个项目可能 1-2 天就调整完了。

**Comment by xiaogaofudao** [comment]
大神问下啊，thinkjs 3 相比 2 性能如何呢

**Comment by welefen** [comment]
先关闭该 issue

**Comment by xiaogaofudao** [comment]
很奇怪，大部分项目维护者都喜欢关闭 issue 这算是强迫症么

**Comment by welefen** [comment]
@xiaogaofudao 有其他的问题可以再提 issue
