### ISSUE TITLE
controller.download()   中文名文件报错

### ISSUE THREAD

**Issue by houxiaozhao** [thinkjs/thinkjs#690]
## DESC

要是先下载功能，文件名为中文。
```javascript
 this.download(data[0].path, data[0].headers['content-type'], "af-api文档.md");
```
```
[Error] TypeError: The header content contains invalid characters
```
## ENV

win10

Node.js Version 6.10.21

ThinkJS Verssion 2.2.19

**Comment by welefen** [comment]
可以先通过 `encodeURIComponent` 把文件名编码下，下个版本会修复这个问题。

**Comment by welefen** [comment]
Fixed by  https://github.com/thinkjs/thinkjs/commit/9193b5f0468ffe0fb46abb28c478a1e633eaf6e4
