### ISSUE TITLE
typescript环境下model部分方法出现未声明错误

### ISSUE THREAD

**Issue by xueyuchen** [thinkjs/thinkjs#691]
## DESC

think.d.ts中think_model_$base_instance接口中某些方法的返回值需要定义成think_model_base_instance

比如think_model_$base_instance.where()、think_model_$base_instance.field()

## ENV

Platform:

Node.js Version:
6.3.1
ThinkJS Version:
2.2.17

**Comment by gushiaoke** [comment]
我也遇到同样的问题。
希望官方提供一套推荐的typescript用法，而不是简单写个.d.ts，哪怕是个简单的小demo

**Comment by SijieCai** [comment]
请升级或者关注 thinkjs 3.0 对 typescript 的支持。https://zhuanlan.zhihu.com/p/31057738

**Comment by SijieCai** [comment]
请更新版本，问题已经修复
