### ISSUE TITLE
How to disable default routes?

### ISSUE THREAD

**Issue by hosos** [thinkjs/thinkjs#692]
I know the version 3 beta has the enableDefaultRoute parameter. But how can I do this for version 2?

萬分感謝

**Comment by welefen** [comment]
什么场景下需要关闭默认的路由解析呢？

**Comment by hosos** [comment]
No special reason.

But is it possible for ThinkJS 2?

**Comment by welefen** [comment]
@hosos  Sorry, can not disable default router parser in v2.x
