### ISSUE TITLE
关联模型怎么查询总数呢？

### ISSUE THREAD

**Issue by zD98** [thinkjs/thinkjs#693]
## DESC
例如 A表与B表是HAS_MANY的关系。设置了B是A的一对多关联模型。
在查询A时，希望可以获得对应的B表项目的总数。

我翻阅了thinkjs的文档，没有发现这个API

如果在A表中添加B表的总数的话，是不符合范式的...所以想来问一下...

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
不支持这种，只会把对应的列表数据拉出来。
一般这种情况下，还是建议在 A 表中添加对应总数的字段，效率上要高很多。不然每次 count 下 B 表是很慢的。

就像文章的评论数一样，一般是在文章表里加个 comment_nums 来表示评论数。
