### ISSUE TITLE
thinkjs 3.0 对比 egg 如何？ 

### ISSUE THREAD

**Issue by dingyiming** [thinkjs/thinkjs#694]
## DESC
- 前段时间有使用egg做过项目，今天看了一遍 thinkjs 3.0 文档，感觉很是相近（当然都是基于koa进行的），想了解下有何异同，该如何取舍（个人更偏向用thinkjs ,感觉文档和命令行打印做的更好一些）

- 目前看 thinkjs 3.0 暂时只支持 Mysql, 是否有扩展其他数据库（如 Mongodb）的计划？

- 感谢奉献好工具，辛苦了。

## ENV

Platform:  windows 10

Node.js Version: 8.x

ThinkJS Version: 3.0

**Comment by brucecodezone** [comment]
项目刚开始做，就发现3.0 beta发布，我用的mongo，求3.0 mongo支出时间~

**Comment by lizheming** [comment]
@dingyiming @brucecodezone model 这块目前算是从2迁移过来，本月会加上 mongo 的支持。

**Comment by brucecodezone** [comment]
@lizheming 这个框架是怎么回事？和thinkjs3.0相似度好高[thinkkoa](http://thinkkoa.org/)

**Comment by lizheming** [comment]
@brucecodezone 应该是社区产物，看官网应该是有参考 ThinkJS 的。

**Comment by brucecodezone** [comment]
@lizheming 谢谢解答～3.0还会有模块概念吗？个人感觉很好用。官方有相应社区吗？

**Comment by lizheming** [comment]
@brucecodezone 有的，有社区的，官网下方有 QQ 群。

**Comment by welefen** [comment]
@brucecodezone  https://thinkjs.org/zh-cn/doc/3.0/multi_module.html  还是有多模块结构的，只是弱化了这个功能，更建议用多级控制器功能。 https://thinkjs.org/zh-cn/doc/3.0/controller.html#toc-04e

**Comment by brucecodezone** [comment]
@welefen 谢谢～
