### ISSUE TITLE
[thinkjs 3.0] 启动项目之后，添加一个controller文件控制台即报文件名称未定义

### ISSUE THREAD

**Issue by dingyiming** [thinkjs/thinkjs#695]
## DESC

- 正常按照最新 `thinkjs 3.0` 文档快速入门创建的项目

- 在启动的 `thinkjs 3.0` 项目情况下，在 `controller` 中新增一个名为  `test.js`  的文件，控制台即打出 `test is not defined` 的报错，然后，添加一个  `testAction` ， 在浏览器尝试访问则显示 404即找不到该路由/方法

- 重启 `npm run start` 则可以正常访问 `/test/test`

![image](https://user-images.githubusercontent.com/12537013/27987982-061970b0-644a-11e7-8cf8-1d041eb108e9.png)

![image](https://user-images.githubusercontent.com/12537013/27987995-2f619a1a-644a-11e7-8767-9178ae7b0788.png)

## ENV

Platform: windows 10

Node.js Version:  v7.7.4

ThinkJS Version: 3.0-beta2

**Comment by welefen** [comment]
这个问题还出现么？这边未能复现。

**Comment by welefen** [comment]
无响应，先关闭
