### ISSUE TITLE
[thinkjs 3.0] rest 的数据库连接表名不正确

### ISSUE THREAD

**Issue by hodgevk** [thinkjs/thinkjs#696]
## DESC
3.0中用命令行创建rest 控制器
```javascript
thinkjs controller home/user -r
```
访问 http://127.0.0.1:8360/home/user 后台一直查询rest表，而不是user这个表

## ENV

Platform:mac

Node.js Version:8.1.3

ThinkJS Version:thinkjs 3.0 beta-2

**Comment by songguangyu** [comment]
Is a bug, I fix it tomorrow.

**Comment by songguangyu** [comment]
创建项目的时候 thinkjs controller /home/user -r 少了一个斜杠

**Comment by hodgevk** [comment]
我这创建的是多模块，如果加了/斜杠，将直接在src下面创建controller、logic、model、config、view等文件夹，而不是在对应模块了创建了

**Comment by welefen** [comment]
@hodgevk  需要配置自定义路由才能生效。https://thinkjs.org/zh-cn/doc/3.0/rest.html#toc-6b0

**Comment by hodgevk** [comment]
配置了，查看了代码，rest表名是用_filename来获取的但是user控制器是继承rest的，所以表名一直是rest

**Comment by welefen** [comment]
@hodgevk  user 是继承 rest 的，所以执行的时候 this.__filename 拿到的是 user 的文件地址

你通过 `DEBUG=think-router npm start` 启动看下控制台下打印的 debug 信息，会看到路由解析后的 controller 和 action
```
think-router RouterParser: path=/test/www, module=, controller=test, action=www, query={} +9s
```

**Comment by welefen** [comment]
请问这个问题解决了么？

**Comment by welefen** [comment]
无响应，先关闭这个 issue
