### ISSUE TITLE
websocket的实现机制是轮询吗？

### ISSUE THREAD

**Issue by yunliang-ding** [thinkjs/thinkjs#699]
## DESC
为什么我的network一直都是在发送数据？是不是我代码的问题

![1 2](https://user-images.githubusercontent.com/18275334/28007343-a3a65834-6585-11e7-837c-0df02965606e.png)

## ENV

Platform:
win10
Node.js Version:
5.+
ThinkJS Version:
2.0

**Comment by welefen** [comment]
这个是 socket.io 的机制，开始握手过程会有多个请求。

**Comment by yunliang-ding** [comment]
@welefen 谢谢你，我一直用的是2.2版本的thinkjs昨天参照官网的那个socket.io的demo总是没有效果，之后报了javascript内存溢出。
