### ISSUE TITLE
并行插入大量数据的时候会提示错误 read ECONNRESET

### ISSUE THREAD

**Issue by shihuojian** [thinkjs/thinkjs#700]
并行插入大量数据,比如10万、5万，有时候会提示错误 read ECONNRESET，数据库mongo、thinkjs版本2.2

**Comment by welefen** [comment]
你直接用 mongoose 试下这么大的数据量呢，如果也不行的话，就分拆插入吧，比如：一次插入一万条

**Comment by shihuojian** [comment]
。问题已经解决了，经测试是本机mongo占用内存太大问题，线上就没事了
