### ISSUE TITLE
求问thinkjs3.0版本的数据库支持

### ISSUE THREAD

**Issue by weihongyu12** [thinkjs/thinkjs#703]
刚看了一下3.0的文档，数据库模型是不是只能支持MySQL？
![3ae3931172188e9d5ab09e614794240](https://user-images.githubusercontent.com/19792747/28061133-0cdc193e-665c-11e7-892c-433070d72f49.png)

2.x版本支持MySQL、MongoDB、PostgreSQL、SQLite，我认为，如果3.0只支持MySQL，会造成迁移成本过大，最终导致开发者流失

**Comment by lizheming** [comment]
后续后增加的，敬候佳音 😃

**Comment by welefen** [comment]
已经支持 MySQL、PostgreSQL、SQLite，具体见： https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#toc-c1f
