### ISSUE TITLE
thinkjs 3.0 如何支持多目录watch

### ISSUE THREAD

**Issue by libery** [thinkjs/thinkjs#705]
## DESC
默认支持的src --> app的watch和自动编译重启，如果界面部分也是用es6写，需要src-web --> view或www/static/js ,怎么配置

## ENV

Platform:
MacOS
Node.js Version:
v8.0.0
ThinkJS Version:
Thinkjs 3.0 beta2

**Comment by welefen** [comment]
虽然支持多目录转译，但不建议把前端的代码放在一起，因为转译的参数都不一样。前端代码转译可以使用 `webpack` 之类的工具处理。

**Comment by libery** [comment]
前后端代码是分离的，前端代码单独转译，前后台代码配置不同的转译参数，用gulp／webpack是可以，那要在一个项目中使用两种监控文件改动->转译的机制，能够通过配置多目录转译更简单些，多目录转译目前3.0怎么配置？
