### ISSUE TITLE
VSC think关键词高亮问题

### ISSUE THREAD

**Issue by epirus** [thinkjs/thinkjs#709]
大家有没有发现如果你使用vsc来编写代码，纳闷think这个词 或者this里面的对象都是高亮的，显示红色的下划线？

看着好难受呀

ThinkJS Version:2.2.x

**Comment by epirus** [comment]
要是可以是使用VSC来调试代码就好了

**Comment by welefen** [comment]
@epirus 是 TypeScript 项目么？ 可以在 `.eslintrc` 里把 think 对象加到 global 里。

```
"globals": {
    "think": true
  },
```

**Comment by epirus** [comment]
@welefen  是typescript 项目但是，typescript 是不是应该使用tslint ，但是这个我不会，不知道怎么配置，你可以新建一个ts项目，放到VSC里面看看，调用think的时候就会高亮

**Comment by junmaqiang** [comment]
```
// .eslintrc里面这样写

{
    "extends": [
        "eslint-config-airbnb",
        "think"
    ],
    "rules": { //0|off; 关闭; 1|warn 警告; 2|error 错误;
        "indent": ["error", 4]
    }
}

```

表示规则里面用 
` "eslint-config-airbnb"  和  "think" `

@epirus
