### ISSUE TITLE
ThinkJS@3.0 中关于自定义全局常量或者一些公共方法

### ISSUE THREAD

**Issue by ihubcode** [thinkjs/thinkjs#710]
## DESC
ThinkJS@3.0 中：
1、如果项目中我要调用新建common.js中写一些全局公共的方法，比如API数据加减密方法，common.js建议放到哪里？又该怎么引入调用？

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
参考  https://thinkjs.org/zh-cn/doc/3.0/bootstrap.html#bootstrap

**Comment by ihubcode** [comment]
ok! tks~
