### ISSUE TITLE
2.2版本连接postgresql报密码错误，但是直接用pg连接和操作都是没问题的

### ISSUE THREAD

**Issue by cloverShadow** [thinkjs/thinkjs#711]
db.js的配置写成这样：
```js
export default {
    type: 'postgresql',
    adapter: {
        postgresql: {
            user: 'root',
            host: '127.0.0.1',
            database: 'my_db',
            password: 'root',
            port: 5432
        }
    }
};
```
用户名和密码是没问题的，我用pg直接连接没问题，但是放在thinkjs上就不行，请问是配置参数不对吗，你们的官方文档上配置那块留了个空，没有写明，希望能告知。

**Comment by welefen** [comment]
控制台下打印的连接  pg 的日志是对的么？

**Comment by cloverShadow** [comment]
我删除了原来的pg模块，下载了6.4版本的pg模块，现在连接正常了，可能是框架内带的pg模块的版本问题吧

**Comment by welefen** [comment]
好，下个版本升级下 pg 模块的版本

**Comment by welefen** [comment]
https://github.com/thinkjs/thinkjs/commit/8742599f32274925b24b668e8915ce2966d8ea89

**Comment by welefen** [comment]
已经发布 2.2.21 版本升级了 pg 的依赖库
