### ISSUE TITLE
thinkjs 3.0 是否有与swagger-node集成方案

### ISSUE THREAD

**Issue by libery** [thinkjs/thinkjs#715]
## DESC
[swagger-node](https://github.com/swagger-api/swagger-node) 封装了swagger的yaml与接口实现的映射关系，thinkjs封装了router与action的映射关系，确定了接口映射的规范，如何把两者结合起来，由swagger yaml确定发布的接口以及接口与action的映射关系，两者结合起来就完美了。

## ENV

Platform:
Mac OS
Node.js Version:
v8.0.0
ThinkJS Version:
thinkjs 3.0 beta3

**Comment by lizheming** [comment]
感觉不是很难，欢迎你提交一下呀~直接封装一个 swagger-think 出来

**Comment by welefen** [comment]
模块名建议为 think-swagger，弄好后可以申请加到 https://github.com/thinkjs/think-awesome 列表中

**Comment by libery** [comment]
ok

**Comment by libery** [comment]
| 名称 | 说明 |  
| --- | --- |  
| [think-swagger](https://github.com/libery/think-swagger) | 说明 |  
| [think-swagger-parser](https://github.com/libery/think-swagger-parser) | 文档解析模块 |  
| [think-swagger-router](https://github.com/libery/think-swagger-router) | 路由模块 | 
| [think-swagger-controller](https://github.com/libery/think-swagger-controller) | 控制器模块 | 
| [think-swagger-demo](https://github.com/libery/think-swagger-demo) | 示例程序 |

**Comment by lizheming** [comment]
@libery README 的格式再修改下，另外，建议 `think-swagger` 直接把三个 middleware 包一下，这样只要用一个中间件就好了，方便多了。

**Comment by libery** [comment]
@lizheming 拆开是考虑这个能力包括了router和controller的功能，  如果合并的话就只能放在logic插件后面，现在logic位于router和controller的中间。

**Comment by welefen** [comment]
@libery 辛苦

**Comment by FuHongBiao** [comment]
请问这个库现在还能用吗？demo运行会有报错呢。
