### ISSUE TITLE
ThinkJS 3.0 断点调试

### ISSUE THREAD

**Issue by guangzhoujason** [thinkjs/thinkjs#716]
## DESC

thinkjs3.0 beta3 用`thinkjs new demo` 生成的项目，在webstorm里面点击 调试 development.js 不能启动

## ENV
development
Platform:
mac
Node.js Version:
8.1.4
ThinkJS Version:
3.0 beta

**Comment by songguangyu** [comment]
有什么错误信息？

**Comment by songguangyu** [comment]
报了什么错误吗？是不是IDE的环境配置问题？

**Comment by guangzhoujason** [comment]
@songguangyu 没有出现什么错误。 
按webstorm的 debug development.js
控制台出现

/usr/local/bin/node --inspect-brk=57695 /Users/Jason/Documents/demo/development.js
Debugger listening on ws://127.0.0.1:57695/6df33742-9d92-4c3b-962c-cdbf095f287b
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:57698/71f247da-3ddd-4ec5-a82b-17c558c77950
For help see https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:57696/3b45c168-8744-4182-8f4e-93c5769e1b23
For help see https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:57697/481d8ae5-606c-4b7b-8f5b-02d63e8bc221
For help see https://nodejs.org/en/docs/inspector
Debugger listening on ws://127.0.0.1:57699/2af0b65b-a52f-49ee-a168-2ff20a898477
For help see https://nodejs.org/en/docs/inspector

就没有任何反应了。。服务没有启动起来

同样的环境，同样的操作  我用think 2.x 是没有问题的

**Comment by guangzhoujason** [comment]
就是很简单的 thinkjs new demo

**Comment by songguangyu** [comment]
嗯 这个是 node --inspect=27210 --debug-brk development.js 中 -brk 导致 子进程fork失败导致的，我们尽快给出解决方案

**Comment by guangzhoujason** [comment]
ok，thanks

**Comment by guangzhoujason** [comment]
有解决这个问题的时间表吗

没有调试，麻烦啊，不断的log

**Comment by songguangyu** [comment]
争取在这周末前修复这个问题。

**Comment by guangzhoujason** [comment]
thank you
by the way

pm2不能启动，应该也是跟这个一样的问题吧

**Comment by yaolynzc** [comment]
VS Code下面启动调试，也是报这样的错误，应该是同类问题。

**Comment by guangzhoujason** [comment]
so，有进展吗

**Comment by songguangyu** [comment]
@guangzhoujason  在 webstrom 里 直接 debug development.js  是可以设置断点的

**Comment by guangzhoujason** [comment]
都没有启动起来，怎么能断点
@songguangyu 

都没有出来 服务器启动成功，监听什么端口的信息

官方貌似还没有给出解决方案

**Comment by songguangyu** [comment]
![image](https://user-images.githubusercontent.com/6869168/28668645-7404989e-7303-11e7-9205-d1b1f5001545.png)

兄弟，在webstrom里 点击 Debug development.js 选项，debug 模式启动项目，然后在项目文件里，设置断点，就能进行断点调试了。 请问你这边有什么报错信息吗？

WebStorm 2017.2
Build #WS-172.3317.70, built on July 14, 2017
Licensed to WebStorm Evaluator
Expiration date: August 23, 2017
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.2   

这个是我的webstrom 的版本，请问你的webstrom 的版本是什么？

**Comment by guangzhoujason** [comment]
没有报错
启动的时候就出现，类似你这样的

直接run的时候，会出现
[2017-07-29 10:58:50.509] [INFO] - Server running at http://0.0.0.0:8888
[2017-07-29 10:58:50.513] [INFO] - ThinkJS version: 3.0.0-beta3
[2017-07-29 10:58:50.513] [INFO] - Enviroment: development
[2017-07-29 10:58:50.514] [INFO] - Workers: 4
成功的消息


但是debug的时候，不会出现。。
浏览器试着访问，也访问不了

所以何来的可以断点


WebStorm 2017.2
Mac OS X 10.11.2   


btw，2.x 没有问题

**Comment by junmaqiang** [comment]
成功过没有? 兄弟们,我一次都没有启动成功过! 
用的是VScode, thinkjs 3.0
@yaolynzc @guangzhoujason @songguangyu

**Comment by welefen** [comment]
@lzy3366 这块在多进程下还有问题，目前还没找到好的解决方案。

**Comment by guangzhoujason** [comment]
@welefen @lizheming 

今天发布的版本，也没有解决这个问题哦

**Comment by guangzhoujason** [comment]
还是不能调试启动

**Comment by lizheming** [comment]
vscode 使用 `--debug-brk` 启动调试会阻碍子进程监听创建，解决方法还得再找找。目前有需求的可以自行使用 `node --debug` 或者 `node --inspect` 模式启动，使用 Chrome 调试。或者用 WebStorm 也是可以的。另外 Webstorm 我也试了下，是可以启动调试的：
![image](https://user-images.githubusercontent.com/424491/29493657-18ea0c28-85cd-11e7-8d26-4bee4704a071.png)

@guangzhoujason 我的版本是今天刚下的，和你的是一样的，Node 6 和 Node 8 的版本我都试过。我直接 `development.js` 上右键选择 debug 启动的。你是有什么其它的特殊操作么？

**Comment by jnotnull** [comment]
@guangzhoujason 同样的问题。 
@lizheming 你可以换几台机器试下么，急

**Comment by lzy3366** [comment]
我试了下调试, debug的是development中运行的启动服务器的代码, request进来的controller业务代码无法单步

**Comment by zhobby** [comment]
@guangzhoujason 你现在是使用什么方案避规？

**Comment by wurining** [comment]
* 这是调试截图开始
<img width="664" alt="2017-08-28 4 23 16" src="https://user-images.githubusercontent.com/26198634/29753651-b3cc91d0-8ba8-11e7-898f-75f5bd34cd09.png">
* 这是调试的配置，配置好后直接点击右上角的绿虫子就可以调试了。因为每次request进来新请求，都会在node的消息队列中添加新消息，所以调试过程中也可以打断点。webstorm是最新版，thinkjs是最新版。
<img width="1071" alt="2017-08-28 4 23 26" src="https://user-images.githubusercontent.com/26198634/29753666-0299cf62-8ba9-11e7-9a9c-a7a387c391cc.png">

**Comment by junmaqiang** [comment]
@wurining  咱们用的IDE不同

**Comment by jnotnull** [comment]
@welefen 这个问题无解了么，就没有其他降级方案了么。让我们先升级上来的情何以堪啊 😢

**Comment by welefen** [comment]
@jnotnull vsc 有点麻烦，正在想办法处理

**Comment by jnotnull** [comment]
我分享下我的webstorm下的规避步骤吧：
1. worker设为1个
2.遇到启动不了情况卡在那，直接关闭webstorm，然后杀死所有node进程

**Comment by zhobby** [comment]
@lizheming [https://github.com/thinkjs/thinkjs/issues/872](url) 我这里是使用chrome断点的，还是没有效果。是我操作步骤有问题吗？

**Comment by welefen** [comment]
VS Code 断点调试方式如下：

* 升级 `think-cluster@1.5.0`
* 在项目根目录下添加文件 `debug.js` （与 development.js 文件同级），内容如下：

```js
const InspectorProxy = require('inspector-proxy');
const proxy = new InspectorProxy({ port: 9999 });
const childProcess = require('child_process');

const instance = childProcess.fork('./development.js', {
  execArgv: [ '--inspect' ]
})
instance.on('message', msg => {
  if(msg.act === 'inspectPort' && msg.port) {
    proxy.start({ debugPort: msg.port });
  }
})
```
* `npm install inspector-proxy` 安装依赖
* 添加 VS Code 的调试文件 `.vscode/launch.json`，内容如下：

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach Worker",
      "type": "node",
      "request": "attach",
      "restart": true,
      "port": 9999
    }
  ]
}
```
* 命令行下通过 `node debug.js` 启动服务，然后在 VS Code 里打开断点调试。

**Comment by feng003** [comment]
启动  node  debug.js  报错呢。thinkCluster.isAgent is not a function

**Comment by makeco** [comment]
@feng003 升级think-cluster

**Comment by feng003** [comment]
@makeco 升级了  谢谢。

**Comment by feng003** [comment]
vscode  设置断点 但是还未绑定  是什么情况？不知道这个问题  有没有终极解决方案？

**Comment by welefen** [comment]
@feng003 是按照上面的步骤一步步来的么？

**Comment by feng003** [comment]
@welefen  vscode 可以调试   新建的项目按照上面的步骤可以的。以前的项目 可能依赖太多了 bluebird 就报错。先学习一下 thinkjs 结构。十分感谢

**Comment by wzquyin** [comment]
@welefen 你给出的方案，有些问题， proxy在获得了调试debugport后，start，但是thinkjs自己会wachter到文件变化重启所有worker，也就是说只要修改了东西，开发者就必须重启debug.js和vscode(在边调试边开发的时候非常麻烦,而且在mac上会出现需要手动lsof +kill的情况-端口占用)，我在你的基础上做了修改，使用方法基本一致，但是不需要不停的重启vscode的调试和debug.js，脚本如下:

`const inspector = require("inspector-proxy");
const  proxy = new inspector({ port: 9999 });
const childProcess = require("child_process");
const inst = childProcess.fork("./development.js", {
  execArgv: ["--inspect=9900"],
  silent: true
});
var debugPort = 0;
inst.on("message", msg => {
    console.info(msg);

    if (msg.act === "inspectPort" && msg.port) {
      debugPort = msg.port;
        proxy.start({ debugPort: msg.port });

    }
})

const str = "Debugger listening on ws://127.0.0.1:"
inst.stderr.on('data', (data) => {
  console.log(`${data}`);
  if (data.indexOf(str) != -1) {
    data = data.slice(data.indexOf(str) + str.length);
    data = data.slice(0, data.indexOf("/"));
 
    var port=parseInt(data)
    if (isNaN(port) == false&&port>debugPort&&debugPort!=0) {
      console.log("切换端口:" + data);
      debugPort = port;
      proxy.end();
      proxy.start({
        debugPort: parseInt(data)
      });
    }
  }
 
});`
写的比较简陋，但是能用，主要是增加了 silent: true来fork，然后通过监控std消息中的每次thinkjs重启了所有worker后打印出新的端口后，切换端口

**Comment by welefen** [comment]
@wzquyin 已经修复这个问题，升级 `think-cluster@1.5.1`，且在 `debug.js` 最后加上 `instance.on('exit', () => proxy.end());` 代码即可。

**Comment by callmez** [comment]
webstorm debug 报错:

```js
[2017-11-01 16:47:02.210] [10442] [INFO] - Server running at http://127.0.0.1:8000
[2017-11-01 16:47:02.212] [10442] [INFO] - ThinkJS version: 3.2.3
[2017-11-01 16:47:02.212] [10442] [INFO] - Enviroment: development
[2017-11-01 16:47:02.212] [10442] [INFO] - Workers: 1
Debugger listening on ws://127.0.0.1:55387/ad180361-f19d-4cef-830e-76e9faaf8673
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
Unhandled rejection TypeError: process.send is not a function
    at Master.sendInspectPort (/Volumes/File/go/demo/node_modules/think-cluster/lib/master.js:161:15)
    at promise.then.data (/Volumes/File/go/demo/node_modules/think-cluster/lib/master.js:170:12)
    at tryCatcher (/Volumes/File/go/demo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Volumes/File/go/demo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Volumes/File/go/demo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Volumes/File/go/demo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Volumes/File/go/demo/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Volumes/File/go/demo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Volumes/File/go/demo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Volumes/File/go/demo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by chj-damon** [comment]
运行node debug.js可以启动，在控制台看到有这句话：
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8onl
y=true&ws=localhost:9231/07642f57-0a14-4967-89af-f5003c66bf10
复制到chrome里面，可以debug，但是我在vscode里面打断点是没有用的。
同时，如果我修改了js文件，上面的这个链接会发生改变，也就意味着我需要重新复制一遍到chrome里面，新的代码才会生效。
请问有什么方式可以直接在vscode里面debug吗？

**Comment by chj-damon** [comment]
升级到v8.9.0之后，控制台的这句话也没有了。vscode中打断点还是没有办法调试。

**Comment by nicholaslai** [comment]
node inspector &
node --debug development.js

Server running at http://127.0.0.1:1234
ThinkJS version: 3.2.3
Enviroment: development
Workers: 1

在chrome 中没有进入断点, 就是简单的 demo 项目

**Comment by amoxoo** [comment]
关于断点的问题，困扰了我两天，今天解决了，个人提供这个场景及对应的思路。

### 环境：
MAC 10.12 ＋ Webstorm v2017.3 + Thinkjs v3.2.4 + node v8.9.0

### 现象：
在src里打了断点，然后在WS的Run/Debug Configuration中添加了类型为Nodejs，Javascrip file为development.js的启动项（见下图1），以Ctrl+D的方式启动调试，打了断点，浏览器发请求，死活进不了断点，也把workers设为1什么一堆上面的方法都试了，都进不了断点。

_（图1）_
![p1](https://user-images.githubusercontent.com/4747759/33601517-741bf1d8-d9e7-11e7-9df2-21bf8e07591b.png)

### 分析：
1.  了解启动配置文件的加载情况，控制台输入：
    ```
    DEBUG=think-loader-config-* npm start
    ```
    发现如图2所示，加载了app目录下的配置文件，猜测thinkjs内部可能是发现有编译后的文件就使用编译后的，否则就用src目录下的源码，就猜想了一下会不会代码也是如此。
    
    _（图2）_
    ![p2](https://user-images.githubusercontent.com/4747759/33601588-a9388106-d9e7-11e7-9917-c04532595774.png)


2.  抱着试试看的心态跑到app目录下，在转译后控制器上打了个断点，一请求居然进来了。如图3所示。

    _（图3）_
    ![p3](https://user-images.githubusercontent.com/4747759/33601689-f0abe8ca-d9e7-11e7-8050-c32aeca9269b.png)


3.  好吧，看源码，原来thinkjs的Application类的构造方法就在处理应用目录的问题，如图4所示。

    _（图4）_
    ![p4](https://user-images.githubusercontent.com/4747759/33601705-fc325e54-d9e7-11e7-8f8a-34c5742c222f.png)

4.  如此一来，看来如果调试不需要跑转译后的代码的话，只需要在development.js加上APP_PATH的选项就可以了，如图5所示。
    
    _（图5）_
    ![p5](https://user-images.githubusercontent.com/4747759/33601731-0db6325e-d9e8-11e7-8da1-66a0d1f27380.png)



### 结论：
如果调试想在源码下断点，有两招：
1. 调试前把把app目录删掉。
2. 按以上方法在development.js加上APP_PATH。

**Comment by wangbaolongbbl** [comment]
websotrm debug就报这个，怎么都进不去断点
Debugger listening on ws://127.0.0.1:49373/fd9e682f-2724-429a-abf9-30a3366a3891
For help see https://nodejs.org/en/docs/inspector
Debugger attached.
(node:969) [DEP0062] DeprecationWarning: `node --inspect --debug-brk` is deprecated. Please use `node --inspect-brk` instead.

**Comment by lizheming** [comment]
VSCode 1.22+ 已经原生支持多进程调试了，所以调试特别简单，只要按照如下内容配置 `.vscode/launch.json` 即可：

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "port": 9229,
      "type": "node",
      "restart": true,
      "request": "launch",
      "name": "ThinkJS Debug",
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": "node",
      "autoAttachChildProcesses": true,
      "runtimeArgs": ["--inspect", "development.js"]
    }
  ]
}
```
配置完直接 F5 启动调试就好啦~

**Comment by zdhsoft** [comment]
> VSCode 1.22+ 已经原生支持多进程调试了，所以调试特别简单，只要按照如下内容配置 `.vscode/launch.json` 即可：
> 
> ```json
> {
>   "version": "0.2.0",
>   "configurations": [
>     {
>       "port": 9229,
>       "type": "node",
>       "restart": true,
>       "request": "launch",
>       "name": "ThinkJS Debug",
>       "cwd": "${workspaceRoot}",
>       "runtimeExecutable": "node",
>       "autoAttachChildProcesses": true,
>       "runtimeArgs": ["--inspect", "development.js"]
>     }
>   ]
> }
> ```
> 
> 配置完直接 F5 启动调试就好啦~
> 另外也有新出的 ndb 可以非常方便的进行多进程调试，可参考文档：https://thinkjs.org/zh-cn/doc/3.0/debug.html

我用你的方法，试了一下，没有完美解决问题。程序可以跑了，但是调试报错。断点连接超时。。。。

**Comment by FightToDawn** [comment]
为什么我vscode下断后 看到的this.ctx是undefined？
`  async getcodeAction() {
    //获取验证码
    const account = this.post('account');
    const clientIp = this.ctx.ip;    //this.ctx在vscode的debug窗口实时查看是 undefined
`

**Comment by stys35** [comment]
idea2020.1 版本 
thinkjs版本3.0  无法进入断点调试
