### ISSUE TITLE
關於3.0模組使用分目錄的 建議

### ISSUE THREAD

**Issue by tonybala** [thinkjs/thinkjs#719]
## DESC
目前我想升版(因為將來資料表會4-500個左右)，之前2版模組使用時可分目錄
使用時 加上 斜線 可做區分 列如 let arrList1=await this.model('ac/ac_group')

但是3版看我有去查看源碼
\node_modules\think-model\lib\index.js 第31行 
const model = function (name, config, m = 'common') {
  .....
}
好像無法做分目錄動作，請問將來有規劃會做分目錄的動作?
要不然大一點的專案會蠻困擾的

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by lizheming** [comment]
还是像之前一样操作即可，可以分目录的。
