### ISSUE TITLE
3.0 model.page(this.get('page'),20)方法，page()的第一个参数,没有默认第一页。

### ISSUE THREAD

**Issue by arterli** [thinkjs/thinkjs#722]
## DESC
3.0 `model.page(this.get('page'),20)` 方法，page()的第一个参数,没有默认第一页。
`model.page(this.get('page')||1,20)` 要这样用才会正确显示。

## ENV

Platform:

Node.js Version:

ThinkJS Version:3.0

**Comment by lizheming** [comment]
Fixed, please upgrade `think-model`version to 0.0.13
