### ISSUE TITLE
model.aggregate(options).page is not a function

### ISSUE THREAD

**Issue by brucecodezone** [thinkjs/thinkjs#723]
## desc
mongo在使用聚合查询后，不能使用原有的page方法进行分页处理，这样如何对聚合查询后的数据进行分页处理呢？
`model.aggregate(options).page(pageNum, pageSize).countSelect()`

## ENV

Platform:ubuntu

Node.js Version:8

ThinkJS Version:2.2

**Comment by brucecodezone** [comment]
@welefen

**Comment by welefen** [comment]
聚合查询后已经执行了查询，后面不能接 page 之类的方法了
