### ISSUE TITLE
路由会请求两遍

### ISSUE THREAD

**Issue by guanbiao33** [thinkjs/thinkjs#724]
## DESC
用户提交表单（method=“POST”）会自动请求两遍，第一遍post,能正常获取参数，第二遍会请求get，导致参数全部undefined，导致think.validator的rule始终不通过并提示参数不能为空。

## ENV

Platform:win10

Node.js Version:6.10

ThinkJS Version:3.0 bete 3

**Comment by welefen** [comment]
把系统控制台下的日志贴下

**Comment by lizheming** [comment]
@welefen 他这个是前端问题，在 Chrome 的 Network 就能看到两次请求。

**Comment by matinjugou** [comment]
这个跟axios以及thinkjs的跨域设置有关，但是求能不能在3.0文档里介绍一下怎么解决这个问题。。。

**Comment by pz25925** [comment]
同样遇到这个问题. 
network 有2次请求, 第一次是 OPTIONS, 第二次是 POST.

第一次 OPTIONS , this.ctx.method === 'OPTIONS '  =>  false,应该为  OPTIONS, 实际为 POST
第一次 POST,  this.ctx.method = 'POST'  =>  true, 应该为 POST
