### ISSUE TITLE
3.0  let ret = await this.add(_Data);  返回值问题

### ISSUE THREAD

**Issue by guangzhoujason** [thinkjs/thinkjs#725]
## DESC
```js
 let ret = await this.add(_Data); 
```

这里的ret 为  0 ，然后代码跟踪进去，底层的最后实现处

think-model - >base ->execute

最后一行，加了输出，这里ret =1
```js
let ret= data.affectedRows || 0;
console.log('execute',ret,data.affectedRows);
return ret;
```

为何会这样，最上层是  0 ，底层是 1 ？

事实上add是已经写入数据库了。

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
add 返回的是插入的 id, 你的数据表主健是 id 么？

**Comment by guangzhoujason** [comment]
user_id

**Comment by welefen** [comment]
那要配置下 pk 属性

**Comment by guangzhoujason** [comment]
已经配置好 this.pk='user_id'

上面我也写了，事实上，this.add已经写入了库，只是返回值，为何是 0

**Comment by welefen** [comment]
@lizheming 弄个例子调试下为啥返回值不对。

**Comment by lizheming** [comment]
我构造了一个最简单的环境测试了，没有复现该问题，表结构如下：

```mysql
CREATE TABLE `fk_test` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `id` int(11) DEFAULT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=latin1;
```

model 文件 `test.js` 如下：

```js
module.exports = class extends think.Model {
  constructor(...args) {
    super(...args);
    this.pk='user_id';
  } 
}
```

调用接口示例代码如下：

```
module.exports = class extends think.Controller {
  async testAction(){
    let data = await this.model('test').add({id: 13234});
    return this.success(data);
  }
}
```

接口正确的返回了新增数据的 ID，另外单元测试的 https://github.com/thinkjs/think-model/blob/master/test/mysql/index.js#L615-L636 这几个用例都有对返回结果进行校验，应该是没有问题的。 @guangzhoujason 麻烦你给一个简单的复现步骤吧，谢谢！

**Comment by guangzhoujason** [comment]
代码：

//接口类
module.exports = class grade extends think.Controller {

   async  createAction(){
       //测试
        let data = this.post();
        let ret = await this.model().add(data);
       console.log('数据库返回',ret);
       this.success(ret);
    }

};


运行输出

node development.js 
[2017-07-24 16:31:03.689] [INFO] - Server running at http://127.0.0.1:8888
[2017-07-24 16:31:03.693] [INFO] - ThinkJS version: 3.0.0-beta3
[2017-07-24 16:31:03.694] [INFO] - Enviroment: development
[2017-07-24 16:31:03.694] [INFO] - Workers: 4
[2017-07-24 16:31:08.829] [INFO] - mysql://root:@192.168.1.188:6666/db
[2017-07-24 16:31:08.891] [INFO] - SQL: SHOW COLUMNS FROM `base_grade`, Time: 13ms
[2017-07-24 16:31:08.930] [INFO] - SQL: INSERT INTO `base_grade` (`grade_name`,`grade_desc`) VALUES ('eda\n','12312'), Time: 37ms
数据库返回 0

**Comment by guangzhoujason** [comment]
新建一个空白工程，测试如下

表结构为
DROP TABLE IF EXISTS `base_grade`;
CREATE TABLE `base_grade` (
  `grade_id` int(2) NOT NULL,
  `grade_name` varchar(16) NOT NULL,
  `grade_desc` varchar(128) NOT NULL DEFAULT '',
  `createAt` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`grade_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;


新建一个controller grade.js
代码为：
const Base = require('./base.js');

module.exports = class extends Base {
 
   async createAction(){

    let id = Math.floor(Math.random()*99);
    let data = await this.model('grade').add({grade_name:id,grade_desc:id,grade_id:id});
    console.log('数据库返回',data);
    return this.success(data);
  }
};


新建一个模型 grade.js
module.exports = class extends think.Model {
  constructor(...args) {
    super(...args);
    this.pk='grade_id';
  } 
}


测试结果
add的接口返回还是为 0

**Comment by welefen** [comment]
PRIMARY KEY 为 `grade_name `，但这个字段类型 `varchar(16)`，都不是数值型的，肯定有问题啊

**Comment by guangzhoujason** [comment]
刚才怀疑是主键问题，设置了grade_name为主键

一开始grade_id是主键，也是然后值为 0 

也就是说跟谁是主键没有关系

**Comment by lizheming** [comment]
`add` 接口返回的是数据添加后的 `last_insert_id`，不是 `affectRows`。返回的 `last_insert_id` 为 0 应该是没有设置主键为 `auto_increment` 的原因。

**Comment by lingruibin** [comment]
> `add` 接口返回的是数据添加后的 `last_insert_id`，不是 `affectRows`。已和 @guangzhoujason 沟通，返回的 `last_insert_id` 为 0 应该是没有设置主键为 `auto_increment` 的原因。

不设置auto_increment ，可以返回正常的id吗？我的id为主键，32位。但是第一次添加都是0

**Comment by lizheming** [comment]
@lingruibin `INSERT` 操作完返回 `last_insert_id` 本质是 MySQL 本身的逻辑，也就是说返回的什么本质是 MySQL 本身决定的。你可以尝试使用 `this.model('user').query('SELECT LAST_INSERT_ID()`)` 看看能否获取到正确的 ID，如果这样也不行那应该没办法吧。
