### ISSUE TITLE
thinkjs 3.0 多级控制器 跳转后默认前缀有子目录/文件，怎么跳转子目录其他文件

### ISSUE THREAD

**Issue by wuch1995** [thinkjs/thinkjs#726]
## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
没太明白意思，具体需求是啥？

**Comment by wuch1995** [comment]
redirect页面跳转，url{字符串}会自动添加当前的controller子目录/文件，这样就跳转不到其他子目录的文件action对应的页面了

**Comment by welefen** [comment]
```js
this.redirect('/console/user');
```
是这种绝对路径么？

**Comment by wuch1995** [comment]
是的，这样的话可以跳转到其他文件的对应页面了。谢谢
