### ISSUE TITLE
v2.2.20版本  无论db.js配置如何  npm start mysql数据库的连接日志都为127.0.0.1

### ISSUE THREAD

**Issue by junerleer** [thinkjs/thinkjs#727]
## ENV

Platform:windows

Node.js Version:node 7.1

ThinkJS Version:2.2.20

切换回2.2.18版本正常。

![error](https://user-images.githubusercontent.com/14024936/28459734-5361215a-6e41-11e7-9fa0-aeaedbbf90a0.png)

**Comment by welefen** [comment]
具体配置是什么样的

**Comment by junerleer** [comment]
具体的配置如下图所示，真的不是配置的锅，我package.json thinkjs的版本由2.2.x强行改成2.2.18  重新npm
 install就ok  再切换回2.2.20  数据库连接就出错  这个很容易验证的
![err2](https://user-images.githubusercontent.com/14024936/28464657-c193ac08-6e58-11e7-9533-e3d0e754e29f.png)

**Comment by junerleer** [comment]
启动项目调用接口，2.2.20版本下报错，错误消息如下。图一里面我特意找到源码中输出了config，发现config居然不是我配置的db.js，如果大神比较忙，我等会儿分析下源码看看问题原因

[2017-07-21 21:12:01] [SOCKET] Connect mysql with mysql://:@127.0.0.1:3306/
[2017-07-21 21:12:01] [Error] Error: Connection refused, mysql://:@127.0.0.1:3306/. http://www.thinkjs.org/doc/error_message.html#econnrefused
    at e:\gitlab\flighthubmanage\node_modules\thinkjs\lib\adapter\socket\mysql.js:139:17
    at _class.run (e:\gitlab\flighthubmanage\node_modules\thinkjs\lib\util\await.js:52:40)
    at Object.think.await (e:\gitlab\flighthubmanage\node_modules\thinkjs\lib\core\think.js:1032:25)
    at _class.getConnection (e:\gitlab\flighthubmanage\node_modules\thinkjs\lib\adapter\socket\mysql.js:115:23)
    at _class._callee2$ (e:\gitlab\flighthubmanage\node_modules\thinkjs\lib\adapter\socket\mysql.js:169:27)

**Comment by junerleer** [comment]
\node_modules\thinkjs\src\core\think.js  row 755

```
 if (think.isString(superClass) && isConfig) {
    **methods = think.extend({}, think.config('db'), methods);**
    let base = methods.type === 'mongo' ? 'model_mongo' : '';
    let cls = think.lookClass(superClass, 'model', module, base);
    let names = superClass.split('/');
    return new cls(names[names.length - 1], methods);
  }
```

这里think.extend混合值的时候
think.config是默认值
methods是配置值
但是可能是层级错误的原因，最终的methods是
{
  type: 'mysql',
  adapter: {
    mysql: {
      host: '127.0.0.1',
      port: '',
      database: '',
      user: '',
      password: '',
      prefix: '',
      encoding: 'utf8',
      nums_per_page: 10,
      log_sql: false,
      log_connect: true,
      camel_case: false,
      cache: [
        Object
      ]
    }
  },
  log_sql: true,
  log_connect: true,
  schema_force_update: true,
  host: '我的数据库host',
  port: '3306',
  database: '数据库名',
  user: 'root',
  password: '我的密码!',
  prefix: '',
  encoding: 'utf8',
  nums_per_page: 10,
  cache: {
    on: true,
    type: '',
    timeout: 3600
  }
}
通过这个去getInstance的时候 ，传入base的config是最顶部回复的fff打印的值
话说thinkjs这里去获取配置的逻辑实在太复杂，快晕了

**Comment by lizheming** [comment]
把 MySQL 的配置写在 `adapter.mysql` 级下吧，全部写根下面合并容易出现问题。

**Comment by welefen** [comment]
@junerleer 把配置改为

```js
export default {
   type: 'mysql',
   adapter: {
      mysql: {
         host: '',
         user: ''
      }
   }
}
```
下个版本会修复这个问题。

**Comment by junerleer** [comment]
好的

**Comment by welefen** [comment]
已经发布 2.2.21 版本修复该问题
