### ISSUE TITLE
3.0.0-beta3连接数据库报错（问题已解决）

### ISSUE THREAD

**Issue by hbsygzs** [thinkjs/thinkjs#732]
## DESC

大神们辛苦了~~
照着官方文档，连接数据库，报错 ：# Error: ER_NO_DB_ERROR: No database selected

下面是数据库连接代码：
```js
module.exports = {
    type: 'mysql',
    common:{
    	log_sql:true,
    	log_connect:true,
    },
    adapter: {
      mysql: {
        host: '127.0.0.1',
        port: '3306',
        database: 'my-pink-hat', //数据库名称
        user: 'root', //数据库帐号
        password: '', //数据库密码
        prefix: 'xyb_',
        encoding: 'utf8'
      }
    }
  };
```
新建了个模型user:
```js
module.exports = class extends think.Model {
	constructor(...args){
		super(...args);
		this.pk = 'userId';
	}
	async getList(){
		let data = this.limit(2).select();
		return data;
	}
};
```

在控制器中读取代码：
```js
module.exports = class extends Base {
  async indexAction() {
  	
    let data =await this.model('user').getList();
    this.success(data);
  }                                                   
};
```

访问首页出现Error: ER_NO_DB_ERROR: No database selected

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by hbsygzs** [comment]
官网这样写的：
数据库配置

修改以下内容，并将其写入到 src/config/adapter/model.js 文件中：
  module.exports = {
    type: 'mysql',
    common: {
      log_sql: true,
      log_connect: true,
    },
    adapter: {
      mysql: {
        host: '127.0.0.1',
        port: '',
        database: '', //数据库名称
        user: '', //数据库帐号
        password: '', //数据库密码
        prefix: 'think_',
        encoding: 'utf8'
      }
    }
  };
直接这样配置，出错，亲测把 adapter：{}这一层去掉才行：
module.exports = {
    type: 'mysql',
    common: {
      log_sql: true,
      log_connect: true,
    },
      mysql: {
        host: '127.0.0.1',
        port: '',
        database: '', //数据库名称
        user: '', //数据库帐号
        password: '', //数据库密码
        prefix: 'think_',
        encoding: 'utf8'
      }
  };

贴出来希望新手少点踩坑
另祝愿thinkjs发展越来越好！！

**Comment by welefen** [comment]
感谢建议，我们调整下文档。
