### ISSUE TITLE
3.0 支持 mongo

### ISSUE THREAD

**Issue by welefen** [thinkjs/thinkjs#736]
## DESC

Extend，注入 think.Mongo 和 think.mongo、controller.mongo

模块名为 [think-mongo](https://github.com/thinkjs/think-mongo)

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by brucecodezone** [comment]
@welefen 3.0 mongo model会加入scheme的类型检查吗？

**Comment by welefen** [comment]
@brucecodezone 后续会，但初期版本可能暂不会有检查的功能

**Comment by welefen** [comment]
已经支持
