### ISSUE TITLE
配置跨域问题

### ISSUE THREAD

**Issue by shihuojian** [thinkjs/thinkjs#738]
我这边遇到个个问题，在base里面设置跨域，上传图片正常，但是canvas图片跨域失败，配置nginx之后canvas跨域正常，上传图片失败？

**Comment by welefen** [comment]
具体的错误信息呢？

**Comment by shihuojian** [comment]
Access to Image at 'http://image.ecs001.com/images/cover/20170725/unIbwMEPYfXdeDHRX_CUACme.png' from origin 'http://127.0.0.1:8081' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:8081' is therefore not allowed access.

**Comment by lizheming** [comment]
@shihuojian https://segmentfault.com/q/1010000000768672/a-1020000002436172 试试

**Comment by shihuojian** [comment]
@lizheming 是这样的，我如果base的跨域设置去掉，改为写在nginx里面却是可以的，但是写在nginx里面，图片跨域上传又不行了

**Comment by shihuojian** [comment]
createCanvas=(result,data)=>{
    let canvas = document.createElement("canvas"),
      ctx = canvas.getContext("2d");
    let img = new Image;
    img.crossOrigin = "Anonymous";
    img.src = data.active.template;
    img.onload = ()=>{
      canvas.width = data.active.template_width;
      canvas.height = data.active.template_height;
      ctx.drawImage( img, 0, 0 );
      //qeCode
      let qrCode = new Image;
      qrCode.crossOrigin = "Anonymous";
      qrCode.src = result.data.code_url;
      qrCode.onload=()=>{
        ctx.drawImage( qrCode, data.active.qrCode_left, data.active.qrCode_top, data.active.qrCode_width, data.active.qrCode_height );
        let src = canvas.toDataURL("image/png");
        console.log(src);
        $('img').attr('src', src).css({width: window.screen.width + 'px'});
      }
    };
    this.setState({loading:false});
  };

**Comment by lizheming** [comment]
你 Base 设置的是什么跨域，Nginx 设置的是什么跨域。还有 Markdown 格式代码请用代码块包裹。

**Comment by shihuojian** [comment]
` createCanvas=(result,data)=>{
    let canvas = document.createElement("canvas"),
      ctx = canvas.getContext("2d");
    let img = new Image;
    img.crossOrigin = "Anonymous";
    img.src = data.active.template;
    img.onload = ()=>{
      canvas.width = data.active.template_width;
      canvas.height = data.active.template_height;
      ctx.drawImage( img, 0, 0 );
      //qeCode
      let qrCode = new Image;
      qrCode.crossOrigin = "Anonymous";
      qrCode.src = result.data.code_url;
      qrCode.onload=()=>{
        ctx.drawImage( qrCode, data.active.qrCode_left, data.active.qrCode_top, data.active.qrCode_width, data.active.qrCode_height );
        let src = canvas.toDataURL("image/png");
        console.log(src);
        $('img').attr('src', src).css({width: window.screen.width + 'px'});
      }
    };
    this.setState({loading:false});
  };`

**Comment by shihuojian** [comment]
@lizheming 我qq跟你说

**Comment by shihuojian** [comment]
解决了，在base里面配置好接口跨域后，图片跨域需要在Nginx的 static里面配置
    location ~ /static/ {
        etag         on;
        expires      max;
        add_header Access-Control-Allow-Origin '*';
        add_header 'Access-Control-Allow-Headers' 'X-Requested-With';
        add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS';
        add_header 'Access-Control-Allow-Credentials' 'true';
    }

**Comment by shihuojian** [comment]
#738
