### ISSUE TITLE
从ThinkJS2.X迁移到ThinkJS3.X过程中的一点疑惑？

### ISSUE THREAD

**Issue by yaolynzc** [thinkjs/thinkjs#740]
## 提一点小疑惑？
看了ThinkJS3.0的文档说3.0抛弃了2.0中的核心架构。
最近将一个cms系统从ThinkJS2.x迁移到ThinkJS3.x过程中发现以前使用的think对象内置的方法依然有效，比如think.md5()、think.uuid()、think.isEmpty()等等。
这些在ThinkJS3.0文档中的think对象描述部分并没提及。
## 弱弱的问一下
2.0版本中think对象下的这些内置方法，在3.0中是真的抛弃了吗？个人很喜欢这些内置方法，感觉非常实用，建议3.0中能继续保留。

**Comment by lizheming** [comment]
你说的这几个都会有的，没有抛弃，文档会尽量把区别讲出来，至于原本有的可能会暂时顾及不到，欢迎帮忙补充文档，谢谢！

**Comment by brucecodezone** [comment]
@lizheming 3.0 typescript支持时间？项目月来越大，越感觉typescript必要

**Comment by lizheming** [comment]
@brucecodezone 3.0 是支持 Typescript 的呀，只是目前没有 ts 描述文件而已

**Comment by brucecodezone** [comment]
那就是创建项目时加入 --ts就可以？

**Comment by lizheming** [comment]
@brucecodezone 刚问了下，缺少描述文件还不行....支持时间还待定。

**Comment by brucecodezone** [comment]
@lizheming ok

**Comment by welefen** [comment]
@yaolynzc  内置的方法是集成过来的，https://thinkjs.org/zh-cn/doc/3.0/think.html#api，后面把文档再搬过来

**Comment by yaolynzc** [comment]
@welefen 看到了，原来都是在think-helper里面，谢谢！感谢你们奉献这么好用的NodeJS框架！

**Comment by welefen** [comment]
@yaolynzc 多谢支持，请帮忙推荐给你的朋友、同事
