### ISSUE TITLE
希望model部分能支持更复杂的查询需求

### ISSUE THREAD

**Issue by limars874** [thinkjs/thinkjs#744]
## DESC

最近在用thinkjs写业务代码，发现有些逻辑相对复杂的查询需求无法直接用model自带的api完成。比如
```
(
	start_date <= "2017-01-01"
	AND end_date >= "2017-01-01"
)
OR 
(
	start_date <= "2017-01-10"
	AND end_date >= "2017-01-10"
)
```
这种字段名重复，但后面的条件有区别的逻辑查询。

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
需求移动到 https://github.com/thinkjs/thinkjs/issues/746 中，这个 issue 先关闭

**Comment by lizheming** [comment]
It have supported in `think-model-abstract@1.2.4`, please upgrade to it. You can write where query like:
https://github.com/thinkjs/think-model-abstract/blob/master/test/lib/parser.js#L1065-L1081
