### ISSUE TITLE
logic有缓存? 请求类型校验这里的问题

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#748]
## DESC
下面是我写的logic文件
```js
// src/user/logic/login.js

    async outAction() {
        //  只允许 get 请求类型
        this.allowMethods = 'get';
    }

```
我把请求类型校验改为post之后,会出现如下提示:
`{"errno":1001,"errmsg":"METHOD_NOT_ALLOWED"}`

在改回get之后, 依然出现上面的错误提示, 重启服务也还是这个提示,请问是缓存?

## ENV

Platform:

Node.js Version:
v7.10.0
ThinkJS Version:
3.0

**Comment by lushijie** [comment]
This bug has been fixed. Please update thinkjs to the latest version. Or you can just use like this 
`this.allowMethods = 'POST';` without update thinkjs.

**Comment by junmaqiang** [comment]
我现在已经升级到最新版本了, 发现这个参数一定要大写才有效!

**Comment by welefen** [comment]
@junmaqiang 恩，已经兼容处理了，等待发版。先可以写成大写

**Comment by junmaqiang** [comment]
close
