### ISSUE TITLE
请问如何查看自己thinkjs的版本?

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#749]
我用 thinkjs -v 看到的是 v1.0.8
我想升级thinkjs版本 用了 npm update 命令,提示我: ` thinkjs@3.0.0-beta4  invalid`

请问咋办?

**Comment by lizheming** [comment]
`think-cli` 只是一个 cli 脚手架模块，不包含 ThinkJS 项目本身代码。ThinkJS 3.x 的架构已经修改，不会包含在全局模块里了，你直接更新项目内的 ThinkJS 模块就可以了。

**Comment by junmaqiang** [comment]
您的意思是修改package.json 文件里面 "thinkjs": "3.0.0-beta4" 这样子?  @lizheming

**Comment by lizheming** [comment]
改成 `next` 就可以了
