### ISSUE TITLE
啥情况才会提示这个错误 TypeError: this.isPost is not a function

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#750]
## DESC

1,  我访问地址是 http://127.0.0.1:1888/user/login/index

2, `src/user/controller/login.js` 代码如下:
```
const Base = require('./base.js');
module.exports = class extends Base {
    async indexAction() {
        if (this.isPost()) {
            let data = this.post();
            // console.log(data);
         }
     }
}
```

3, 提示我 `TypeError: this.isPost is not a function`

## ENV
我的项目部署是 多级控制器 方式

Platform:

Node.js Version:
V7
ThinkJS Version:
最新版

**Comment by lizheming** [comment]
如果是 3.0 版的话是已经变成 getter 了，直接用 `this.isPost` 就可以了。文档：https://thinkjs.org/zh-cn/doc/3.0/controller.html#toc-f8e

**Comment by junmaqiang** [comment]
很显然我就是直接用 this.isPost 的! @lizheming

**Comment by lizheming** [comment]
看文档，是 `this.isPost` 不是 `this.isPost()` !!!!

**Comment by junmaqiang** [comment]
看得都是3.0文档

**Comment by junmaqiang** [comment]
哦哈哈, im sorry  哈哈!

**Comment by lizheming** [comment]
![image](https://user-images.githubusercontent.com/424491/28905632-71ce3f1c-7844-11e7-8931-51089e6ef389.png)
