### ISSUE TITLE
[3.0] [bug] 内部错误打印为not found

### ISSUE THREAD

**Issue by jhyvictory** [thinkjs/thinkjs#753]
## DESC

![w z4x aru8sq6e3ii i0k](https://user-images.githubusercontent.com/18344919/28916298-5963253e-7874-11e7-9c22-f955d99bc4f2.png)

## ENV

Platform: 

Node.js Version: 

ThinkJS Version: 3

**Comment by lizheming** [comment]
fixed, please upgrade think-trace to 1.0.12.
