### ISSUE TITLE
[3.0] trace中将错误提示按照2中方式，可在错误信息errmsg中返回

### ISSUE THREAD

**Issue by jhyvictory** [thinkjs/thinkjs#754]
## DESC
这是在2中的使用方法
![yzzyak ayf6 0 sj 9zeh](https://user-images.githubusercontent.com/18344919/28916593-49865ad6-7875-11e7-9c48-b8876d2cef16.png)

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by lizheming** [comment]
https://github.com/thinkjs/think-trace

**Comment by jhyvictory** [comment]
我这么用不是为了方便调试的，而是在错误的时候给用户一个简短提示。

**Comment by lizheming** [comment]
简单设置 `error` 方法为  `err =>{ err.message = 'Service Error'; }` 即可。

**Comment by jhyvictory** [comment]
![vgbuj p0vdh tuv r 0hs5](https://user-images.githubusercontent.com/18344919/28917165-4e221b64-7877-11e7-9e4b-e78a3a9a621c.png)
这样不行，而且我也不想显示错误页面，而是返回json，像2里面的this.fail()

**Comment by lizheming** [comment]
设置 content-type 为 application/json 即可。

**Comment by lizheming** [comment]
https://github.com/thinkjs/think-trace#options 增加了 `contentType` 参数，用来设置 error 返回的 `content-type` 当设置为 `application/json` 的时候则返回 `json` 结果。

**Comment by jhyvictory** [comment]
ok
