### ISSUE TITLE
在VScode编辑器下用thinkjs3.0 可以断点调试?

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#756]
## DESC

官方文档里的内容看了, https://thinkjs.org/doc/debug.html 但是因为是2.x版本的, 
我目前用的是3.0版本thinkjs
我这边调试下来错误如附件图片

![44](https://user-images.githubusercontent.com/1819457/29224235-03bf7df6-7efc-11e7-8913-2fb698678ea5.png)

## ENV

Node.js Version:v7.10.0

ThinkJS Version:3.0

**Comment by welefen** [comment]
#716

**Comment by junmaqiang** [comment]
好像还不可以吧? @welefen

**Comment by guangzhoujason** [comment]
这个问题我一个月前就提过了。。好像没有解决

**Comment by junmaqiang** [comment]
真希望早点实现 VScode下 断点调试

**Comment by xiaoyicn** [comment]
用node --debug-brk 在vscode中启动调试时遇到多进程时有问题，尚无完美方案。
目前临时方案如下：master和worker分别用不同的launch配置。master启动配置配合在npm配置中用node --inspect，worker附加到进程。
1、launch.json
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "master+NPM",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script", "debug"
            ],
            "port": 9876,
            "sourceMaps": true
        },
        {
            "name": "worker",
            "type": "node",
            "request": "attach",
            "port": 9877,
            "outFiles": [
				"${workspaceRoot}/app/**/*.js"
			],
            "sourceMaps": true
        }
    ]
}`

2、package.json中假如debug
`  "scripts": {
    "debug": "node --nolazy --inspect=9876 development.js"
  }`

3、按F5应该可以出现正常启动
![image](https://user-images.githubusercontent.com/26409596/30905525-a79b24fa-a3a7-11e7-89f3-724c6dffee3b.png)

4、启动worker配置的调试，打断点，刷新网页，断点可达。
![image](https://user-images.githubusercontent.com/26409596/30905589-da97b8dc-a3a7-11e7-9ff0-78d6c0f2f01f.png)

![image](https://user-images.githubusercontent.com/26409596/30905665-07a5f104-a3a8-11e7-9f1c-ed6a0e05c082.png)

**Comment by AkashiX** [comment]
@xiaoyicn It works well for me, but I run by master+NPM in development. Just closed the cluster that would be ok, let it run in a single thread.

**Comment by AkashiX** [comment]
![image](https://user-images.githubusercontent.com/23026766/31005881-2ceba3d2-a4c0-11e7-8e84-db58f44ea844.png)

**Comment by xiaoyicn** [comment]
@AkashiX Can you post the detailed settings of turning off cluster?

**Comment by lizheming** [comment]
@xiaoyicn He is using ThinkJS 2.x, not the latest version. 3.x can't close cluster mode. You can use webstorm instead of vscode temporatory.

**Comment by AkashiX** [comment]
@xiaoyicn Yeah. he's right, I'm using the Thinkjs 2.x...If you want to close cluster mode by yourself, just change to 2.x of version, otherwise do as lizheming' advice...

**Comment by zhangzongshan** [comment]
VSCODE 还是没有办法调试啊,

**Comment by callmez** [comment]
debug调试 能有个文档么?

**Comment by welefen** [comment]
https://github.com/thinkjs/thinkjs/issues/716#issuecomment-337449445
