### ISSUE TITLE
在视图里面如何读取session的二维字段

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#757]
## DESC

{{ctx.session('user')}}  读取的是一个数组对象;
但是我想取这个对象里面的信息: user.username; 

请问咋样写?

**Comment by lizheming** [comment]
`{{ctx.session('user').username}}`

**Comment by junmaqiang** [comment]
// session文件为: runtime/session/6170a3ea-9561-4db7-ab04-2735cbd2852f 
内容如下:
```
{"expires":1501867568486,"data":{"wjbuser":{"uid":171,"username":"haha","mobile":"13111119999","last_login_time":2147483647}}}
```

// 模板文件里面我这么写的
```
{{ctx.session('wjbuser').mobile}}
```

可是为啥读取不到数据呢?  
求助 @lizheming @welefen

**Comment by lizheming** [comment]
。。。还以为你能获取到呢。。。`ctx.session` 获取是异步操作，你在 controller 里面 await 获取再 assign 给模板吧。

**Comment by welefen** [comment]
session/cache 为异步操作，需要在 controller 里获取然后赋值，如：

```js
async indexAction() {
  const userInfo = await this.session('userInfo');
  this.assign('userInfo', userInfo)
}
```

**Comment by welefen** [comment]
https://thinkjs.org/zh-cn/doc/3.0/view.html#toc-f46 已经更新文档

**Comment by junmaqiang** [comment]
那你看我的需求这样用session适合不?

我需要用到session的地方是模板文件共用的头部模板;
主要是读取当前登录的用户名;
因为模板是共用的, 是不是意味着很多控制器方法里面都要赋值才可以?
有没有方法只要赋值一次就可以了呢?

**Comment by lizheming** [comment]
在 Controller 的 __before 方法里写就可以了，参考 https://github.com/firekylin/firekylin/blob/master/src/admin/controller/base.js#L7

**Comment by junmaqiang** [comment]
感谢 @lizheming  问题得到解决!

**Comment by junmaqiang** [comment]
closed
