### ISSUE TITLE
多模块调用问题

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#761]
## DESC
我项目是多模块方式部署, `src/user` 用与用户登录之类的事物,代码如下:
```
// src/user/controller/base.js
    /** 
     * 前置操作
     */
    async __before() {
        // 初始化用户信息
        this.user = {};
        // 初始化是否登录
        this.is_login = await this.islogin();
        // 访问控制
        if (this.is_login) {
            // 1,获取用户信息
            this.user = await this.session(this.config('cookied'));
            // 2,获取角色id
            this.user.gid = await this.getGid(this.is_login);
            // 3,获取角色名称
            this.user.gname = await this.getGname(this.user.gid);
            // 4,通用赋值
            this.assign('user', this.user);
        }
    }

```

我想在` src/member/controller/` 下面调用` src/user/controller/base` 里面写好的东西,请问咋调用? 
特别是这个前置操作` __before()` 
以下是我的写法,但是出问题了! 
```
// src/member/controller/base.js
    async __before() {
        // 获取其他控制器实例，然后调用其方法
        const userController = this.controller('user/base');
        userController.__before();
    }
```

哥哥们 @welefen @leeight  指点我下,谢谢哈!

**Comment by welefen** [comment]
是 2.x 项目还是 3.0 项目？

**Comment by welefen** [comment]
@junmaqiang 可以用 `this.action` 方法调用，会自动执行对应的 __before __after 方法

**Comment by junmaqiang** [comment]
官方3.0手册对于多级控制器只是介绍目录结构, 没看到调用方式等介绍! @welefen

**Comment by junmaqiang** [comment]
项目是 3.0版本 部署的!  
我用下来感觉,文档缺少对多级控制器的介绍, 目前介绍太少,仅仅是目录结构!
对多模块介绍也不多!

**Comment by welefen** [comment]
@junmaqiang 后续会完善这块的文档

**Comment by junmaqiang** [comment]
我的项目是多模块部署方式
我想在`/src/member/controller/base.js` 里面, 能够用到 `/src/user/controller/base.js `里面` __before` 内的东西, 请问咋个调用方法?  主要是写法, @welefen  哥哥给个参考呗!

**Comment by junmaqiang** [comment]
我发现,文静 `// src/member/controller/base.js` 要是这样写,至少不报错!
```
    __before() {
        // 获取其他控制器实例，然后调用其方法
        const userController = this.controller('index', 'user');
        userController.indexAction();
    }
```
意味着  `userController.indexAction(); `  这里要写全称!

**Comment by welefen** [comment]
那就让 /src/member/controller/base.js 继承 /src/user/controller/base.js，然后调用 super.__before 就可以了

```js

const Base = require('../member/controller/base.js');

module.exports = class extends Base {
  __before() {
    return super.__before().then(flag) => {
      if(flag === false) return false;
    }
  }
}
```

**Comment by junmaqiang** [comment]
报错了 @welefen 
```
/Users/ajun/web/thinkjs/src/company/controller/base.js:7
        return super.__before().then(flag) => {
                    ^
SyntaxError: Unexpected token .
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
```

**Comment by guohuihot** [comment]
> 报错了 @welefen
> 
> ```
> /Users/ajun/web/thinkjs/src/company/controller/base.js:7
>         return super.__before().then(flag) => {
>                     ^
> SyntaxError: Unexpected token .
>     at createScript (vm.js:53:10)
>     at Object.runInThisContext (vm.js:95:10)
>     at Module._compile (module.js:543:28)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
> ```

是的报错

**Comment by lizheming** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/super 这是 super 语法的文档，正常使用应该是没有问题的，你们再检查下是否有其它的问题？
