### ISSUE TITLE
事务无法 commit&rollback 

### ISSUE THREAD

**Issue by tigerui** [thinkjs/thinkjs#762]
## DESC

> 事务使用方式

```
let model = this.model('log')
  	try {
  		await model.startTrans()
  		let res = await model.where({ id: 10 }).update({
  			text: 'xxxxxxx'
  		})
  		await model.commit(model.connection)
  		return this.success()
  	} catch(e) {
  		await model.rollback()
  		return this.fail()
  	}
```
commit/rollback 无反应
https://github.com/thinkjs/think-model/blob/master/src/mysql/instance/base.js#L244
https://github.com/thinkjs/think-model/blob/master/src/mysql/instance/base.js#L251
很着急 我现在临时将commit rollback 方法 先设置默认 connection = this.connection

## ENV

Platform:
mac

Node.js Version: 
v6.10.0

ThinkJS Version: 
3.0.0-beta4

**Comment by welefen** [comment]
恩，那你先这么改吧，Model 这块这周会发布一个重构的版本，底层有较大的改动，使用上没有太大的差别

**Comment by tigerui** [comment]
是不是要上 think-waterline 了，如果model 的api 变化不大就好了

**Comment by welefen** [comment]
那倒不是，把 Model 进行了重写

**Comment by tigerui** [comment]
是 think-model  think-mysql 两个项目吗，我想关注一下，因为这个项目也挺着急的

**Comment by welefen** [comment]
think-model  think-model-mysql

**Comment by welefen** [comment]
模型已经重构，欢迎使用。https://thinkjs.org/zh-cn/doc/3.0/relation_model.html
