### ISSUE TITLE
schema = {            ^  SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by huanz** [thinkjs/thinkjs#763]
## DESC

```
schema = {            ^  SyntaxError: Unexpected token =
```

## ENV

Platform: mac

Node.js Version: 8.2.1

ThinkJS Version: next

**Comment by huanz** [comment]
3.x的文档有问题啊。。。默认不支持这种写法。
改成了这样：
```javascript
constructor(...args) {
        super(...args);
        this.schema = {};
}
```
另外好像也没看到对`schema`的使用的代码啊。

**Comment by welefen** [comment]
模型這塊正在重構，這幾天會發新版

**Comment by welefen** [comment]
模型已经重构完成，欢迎使用。 https://thinkjs.org/zh-cn/doc/3.0/relation_model.html

**Comment by huanz** [comment]
@welefen 3.0现在接口上还会有变动么？？？
