### ISSUE TITLE
thinkjs 3.0版本的websocket配置

### ISSUE THREAD

**Issue by humbass** [thinkjs/thinkjs#765]
## DESC

感觉3.0相比2.x牛逼很多，很想从2.2迁到3.0， 期待看到websocket的配置（使用）例子。

官方的think-websocket 感觉是前几天才上线的，文档还没这么快上来吧

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
正在写单元测试，准备先发一版，然后再补单元测试，哈哈

**Comment by humbass** [comment]
感谢！

**Comment by qq781548819** [comment]
@welefen 您好作者，socket.io的拓展不支持微信小程序的原生websocket.io，作者大大考虑封装下ws的库，谢谢

**Comment by lushijie** [comment]
嗯嗯，正在着手写，请稍后


原始邮件
发件人:赖notifications@github.com
收件人:thinkjs/thinkjsthinkjs@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2017年10月9日(周一) 06:58
主题:Re: [thinkjs/thinkjs] thinkjs 3.0版本的websocket配置 (#765)


@welefen 您好作者，socket.io的拓展不支持微信小程序的原生websocket.io，作者大大考虑封装下ws的库，谢谢
