### ISSUE TITLE
[3.0]根据官网提供例子热重启失败

### ISSUE THREAD

**Issue by ckken** [thinkjs/thinkjs#766]
## DESC
根据官网提供的例子，修改 /src/common/config/config.production.js 的 配置 重启后仍然获取不到value
```
#!/bin/sh
cd ~/ro_read_online; # 进入项目根目录
nodepid=`ps auxww | grep node | grep production.js | grep -v grep | awk '{print $2}' `
if [ -z "$nodepid" ]; then
    echo 'production service starting'
    nohup node production.js &
else
    echo 'production service is running'
    kill -s USR2 $nodepid 2>/dev/null
    echo 'gracefull restart'
fi
```

## ENV

Platform:

Node.js Version:8.2.1

ThinkJS Version:3.0.4 beta

**Comment by welefen** [comment]
是 Windows 還是什麽，看下進程的時間有沒有修改

**Comment by ckken** [comment]
ubuntu 生产服务器 ，进程时间有修改，操作步骤：
从SVN clone 代码，执行 reload 操作，代码更新了 但是 服务端获取不到更新后的变量

**Comment by ckken** [comment]
其他controller logic 我都试过 好像都可以 唯独 配置不行 我看看是什么问题

**Comment by welefen** [comment]
配置是动态设置的，还是什么的？

**Comment by ckken** [comment]
静态配置，跟官网提供的配置一样 放到 config.development.js 里面 杀死进程可以使用 热重启不行

**Comment by welefen** [comment]
具體是什麽時候用的配置沒更新，請提供具體的信息

**Comment by welefen** [comment]
@ckken ping

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/29300355-88db4d64-81a7-11e7-8569-602b9cacdc84.png)
修改这部分变量 热重启 不产生影响

**Comment by welefen** [comment]
@ckken 是指修改 `host`？修改 host 需要完全重新才能生效，这是 Node 的机制决定的，虽然子进程里可以 createServer 然后 listen，但实际上是通知给主进程去启动服务的。
