### ISSUE TITLE
[3.0]日志配置无效

### ISSUE THREAD

**Issue by ckken** [thinkjs/thinkjs#767]
## DESC
src/common/config/adapter.js 添加如下配置 
正是环境 production 日志为 file 而不是 dataFile 日志目录 /runtime/logs/file.log
```
exports.logger = {
  'type': isDev ? 'console' : 'dateFile',
  'console': {
    'layout': {
      'type': 'pattern',
      'pattern': '%[[%d] [%z] [%p]%] %m'
    }
  },
  'file': {
    'filename': `${think.RUNTIME_PATH}${path.sep}logs${path.sep}file.log`,
    'maxLogSize': 51200,
    'backups': 10
  },
  'dateFile': {
    'level': 'INFO',
    'filename': `${path.join(think.ROOT_PATH, 'runtime')}${path.sep}logs${path.sep}file.log`,
    'pattern': '-yyyy-MM-dd',
    'alwaysIncludePattern': false,
    'layout': {
      'type': 'pattern',
      'pattern': '%[[%d] [%z] [%p]%] %m'
    }
  }
}
```

## ENV

Platform:windows

Node.js Version: 8.2.1

ThinkJS Version: 3.0.4 beta

**Comment by welefen** [comment]
你想要在正式环境下日志类型为 file 而不是 dateFile ?

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/logger.html 麻烦查看下文档哦。

1. 首先每一个 adapter 配置都需要传一个 handle 对象哦，参考文件日志的示例：
    ```js
    const path = require('path');
    const {File} = require('think-logger3');
    
    exports.logger = {
      type: 'file',
      file: {
        handle: File,
        backups: 10,
        absolute: true,
        maxLogSize: 50 * 1024,  //50M
        filename: path.join(think.ROOT_PATH, 'logs/xx.log')
      }
    }
    ```
2. 你如果要生产环境下是 `file` 的话需要指定对应的 type 为 file 而不是 dateFile 哦

**Comment by welefen** [comment]
框架有默認的 logger 配置，需要在官網的文檔裏說明下

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/29200141-76c8ef34-7e85-11e7-9ea6-ff9e6542c9d4.png)
 大概是这个问题

**Comment by lizheming** [comment]
你的意思是说文件名没有包含日期是么？这个是由 `alwaysIncludePattern` 参数控制的，你设置为 `true` 即可。默认 `false` 的话当天的记录日志是不带日期的，只有到明天之后今天的日志才会带上日期。具体可参考文档：https://thinkjs.org/zh-cn/doc/3.0/logger.html#toc-93a

**Comment by ckken** [comment]
got it
