### ISSUE TITLE
npm ERR! code EINTEGRITY

### ISSUE THREAD

**Issue by lijinghust** [thinkjs/thinkjs#772]
## DESC
项目创建后执行 npm install时报错

![image](https://user-images.githubusercontent.com/6525044/29198429-97d4975a-7e76-11e7-9264-83432ebb7147.png)

## ENV

Platform: mac pro

Node.js Version:v8.2.1

ThinkJS Version: think-cli@1.0.10

**Comment by welefen** [comment]
這個是 npm 你們問題

**Comment by welefen** [comment]
可以通过 `npm install -g npm` 重装下试下
