### ISSUE TITLE
socket 房间概念怎么配置呢

### ISSUE THREAD

**Issue by liuhuanhui** [thinkjs/thinkjs#774]
socket 房间概念怎么配置呢？能不能通过path设置？

**Comment by liuhuanhui** [comment]
socket的join是否封装？

**Comment by welefen** [comment]
ThinkJS 版本是什么？

**Comment by liuhuanhui** [comment]
thinkjs2额~

**Comment by welefen** [comment]
可以的，可以大致看下 https://github.com/thinkjs/thinkjs/blob/2.x/src/adapter/websocket/socket.io.js#L37 这里的代码
