### ISSUE TITLE
多模块配置子域名映射后的url跳转问题

### ISSUE THREAD

**Issue by mxh861001** [thinkjs/thinkjs#777]
## DESC
模块有"admin,home,user"
子域名映射如下:

```js
subdomain:{
 admin: 'admin'
}
```

/admin/controller/base.js代码如下:

```js
async __before(){
    const userInfo = await this.session('userInfo');
    if(think.isEmpty(userInfo)){
      return this.redirect('/user/login');
    }
  }
```
为什么访问admin.xx.com跳转到/user/login时候会提示
NotFoundError: url `/user/login` not found.

请问怎么解决?

## ENV

Platform: windows

Node.js Version:8.3.0

ThinkJS Version:3.X

**Comment by welefen** [comment]
有对应的 Action 处理 `/user/login` 的请求么？

**Comment by mxh861001** [comment]
@welefen 测试过后好像发现项目多模型下并且配置了子域名映射后,在配置了子域名映射的模型下无法用redirect跳转到其他模型去
比如我上面只配置了admin模型的子域名映射,然后用admin.xx.com访问时实际redirect的地址还是在admin模型下,无法跳转到user模型

**Comment by welefen** [comment]
含有域名改变的跳转时，需要指定对应的域名，如：`this.redirect('http://user.xxx.com/login')`
