### ISSUE TITLE
[Thinkjs@3.x] 中关于cookie的使用

### ISSUE THREAD

**Issue by ihubcode** [thinkjs/thinkjs#780]
## DESC
请问，如果在非 ctx、controller、logic 中调用cookie,该怎么处理，比如在启动项自定义文件中读取cookie，现在这么写：

```js
global.token = function (ctx) {
    let token = ctx.cookie('token') ? ctx.cookie('token') : '';
    return token;
}
```

如可以 

```js
global.token = think.cookie('cookieName') ? think.cookie('cookieName') : 0;
```

更好，但目前好像不支持这么写。

## ENV

Platform:

Node.js Version:

ThinkJS Version:
3.X

**Comment by welefen** [comment]
Cookie 是跟请求相关的，global 里操作 cookie 你想往哪儿存呢？

**Comment by ihubcode** [comment]
只读数据，不存啊

**Comment by welefen** [comment]
那也是跟请求相关，非要这么做的话就把 ctx 传递进去
