### ISSUE TITLE
模板文件里面用think.datetime的问题

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#782]
## DESC

我用了两种写法,可是都没有得到效果! 请指教! @welefen 
写法一
```
<td>{{item.created_at|think.datetime()}}</td>
```

写法二
```
<td>{{think.datetime(item.updated_at,"YYYY-MM-DD")}}</td>
```

提示我: ```Error: Unable to call `think[\"datetime\"]`, which is undefined or falsey```

## ENV
Node.js Version:v7

ThinkJS Version:3.0

**Comment by welefen** [comment]
nunjucks 把全局变量给屏蔽了，模板里使用的话需要手工注册进去，https://github.com/thinkjs/think-view-nunjucks#beforerender

**Comment by welefen** [comment]
@junmaqiang ping

**Comment by junmaqiang** [comment]
确实 好了!  @welefen
