### ISSUE TITLE
think对象的文档中并未提及在view里面的使用方法

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#783]
## DESC

https://thinkjs.org/zh-cn/doc/3.0/think.html
这里开头是这样写的  框架中内置 think 全局对象，方便在项目中随时随地使用。

但是文档翻遍了也没有找到在view下面如何使用的例子!
至少我在尝试的方法上都没有成功过!

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
nunjucks 把全局变量给屏蔽了，见： https://github.com/thinkjs/thinkjs/issues/782
