### ISSUE TITLE
[think-model-mysql] countSelect() where 条件为['IN', '1,2,3' ] 时 异常

### ISSUE THREAD

**Issue by tigerui** [thinkjs/thinkjs#784]
## DESC

查询的代码
```js
async getByIds(ids) {
    let where = {
      id: ["IN", ids]
    }
    return this.model('goods').where(where).countSelect()
 }
```

```
[2017-08-16 20:00:04.118] [85397] [INFO] - SQL: SELECT COUNT(mt_goods.id) AS think_count FROM `mt_goods` WHERE ( `id` IN ('344','345','352','360','363','374','375','376','384','382') ) LIMIT 1, Time: 357ms
[2017-08-16 20:00:04.302] [85397] [INFO] - SQL: SELECT * FROM `mt_goods` WHERE ( `id` IN ('\'344\'','\'345\'','\'352\'','\'360\'','\'363\'','\'374\'','\'375\'','\'376\'','\'384\'','\'382\'') ) LIMIT 0,10, Time: 178ms
```
结果是
```js
res = {
  count: 10,
  data: []         <===========   结果为空
  currengPage: 1,
  pageSize: 10
}
```

应该是countSelect() 时 where IN 条件引号转义问题

## ENV

Platform:

Node.js Version:
Node 8
ThinkJS Version:
thinkjs 3.0 beta4
think-model 1.0.3
think-model-mysql 1.0.4
think-model-abstract 1.0.7

**Comment by jameskid007** [comment]
对， 我也遇到这个问题了。  还有一个问题， 就是如果where条件里面写了 _login: or, 用countSelect(), sql生成出来是 and, 用select(), 生成出来的sql，就是正常的.

**Comment by tigerui** [comment]
@jameskid007  你贴一下打印出的 sql，看看countSelect 和 select 查询的区别，看看是不是也是转义的问题

**Comment by jameskid007** [comment]
![1](https://user-images.githubusercontent.com/7554002/29400586-62941df6-8360-11e7-99c0-1a2f9ede8953.png)
![2](https://user-images.githubusercontent.com/7554002/29400593-6dd0b468-8360-11e7-91fc-8acdfba18128.png)
![3](https://user-images.githubusercontent.com/7554002/29400599-72519c32-8360-11e7-8622-ad20c70611b2.png)
![4](https://user-images.githubusercontent.com/7554002/29400601-749a2f90-8360-11e7-986e-95b0b7919f00.png)

**Comment by lizheming** [comment]
@tigerui @jameskid007 fixed at think-model@1.0.5
