### ISSUE TITLE
[think-model-mysql] model.where({}).find() 未找到记录 返回 {}

### ISSUE THREAD

**Issue by tigerui** [thinkjs/thinkjs#787]
## DESC
```
[2017-08-17 16:26:12.585] [6358] [INFO] - SQL: SELECT * FROM `mt_shop_design` WHERE ( `shop_id` = 117981 ) LIMIT 1, Time: 139ms
[2017-08-17 16:26:12.586] [6358] [DEBUG] -     {}
```

如题 返回 {} 之前做的简单的判断 if(res) => true

## ENV

Platform:
mac
Node.js Version:
node 8
ThinkJS Version:
beta4
think-model@1.0.5

**Comment by lizheming** [comment]
使用 `think.isEmpty(res)` 判断即可。

**Comment by tigerui** [comment]
以前的model api 查询为空, 返回的null 吧，我觉得应该像之前一样。

**Comment by lizheming** [comment]
以前有可能是因为你 `LIMIT 1` 的原因，没取到返回了 undefined。不过还是有很多情况例如 select 空结果返回的就是 `[]` 的，所以推荐你还是用 `think.isEmpty` 判断。

**Comment by tigerui** [comment]
恩
