### ISSUE TITLE
升级正式版thinkjs3.0 中间件ctx.session没有用了

### ISSUE THREAD

**Issue by jameskid007** [thinkjs/thinkjs#788]
## DESC

![1502963880 1](https://user-images.githubusercontent.com/7554002/29407071-a460a280-8375-11e7-8b3c-82d2c2ef9214.png)

## ENV

Platform: thinkjs 3.0

Node.js Version: 8.1.0

ThinkJS Version: thinkjs 3.0

**Comment by jameskid007** [comment]
在中间件中ctx.session不能用了.  之前没问题的.

**Comment by lizheming** [comment]
ThinkJS 不自带 `think-session` 了，你需要重新安装一下。

**Comment by jameskid007** [comment]
好的
