### ISSUE TITLE
[ts] 所有调用await的地方，都显示红线。但代码可以正常跑

### ISSUE THREAD

**Issue by gushiaoke** [thinkjs/thinkjs#792]
## DESC

![ts](https://user-images.githubusercontent.com/7317348/29466713-85931b70-8470-11e7-885a-e81ff9709354.png)

## ENV

Platform: win 10

Node.js Version: 8.0.0

ThinkJS Version: 2.2.21

**Comment by welefen** [comment]
恩，d.ts 的描述文件有一些问题，我们会在 3.0 里重新设计这块

**Comment by welefen** [comment]
ThinkJS 3.2 版本已经支持 TypeScript

**Comment by SijieCai** [comment]
最新实现对 TypeScript 支持的方式需要更新 think-cli 2.0，用 thinkjs new project typescript 重新生成项目。
