### ISSUE TITLE
thinkjs3.0升级指南，欢迎大家补充

### ISSUE THREAD

**Issue by jnotnull** [thinkjs/thinkjs#798]
Node: 8.4
不打开Babel

### 升级指南

1. 导入导出
	
	1. 导入：

	```
	import Sequelize from 'sequelize';
	```
	改为
	
	```
	const Sequelize = require('sequelize');
	```

	2. 导出：

	```
	export default class extends think.base
	```
	
	改为
	
	```
	module.exports = class sequelizeAdapter extends base
	```

2. 基础类继承
	
	1. controller由以前的继承 extends think.controller.base 改为 继承 extends think.Controller
	
	2. Service由以前的继承 extends think.service.base 改为 继承  extends think.Service

3. service

	1. 注册到全局

		worker.js中增加：
		
		```
		let redis_mgr = think.service("redismgr", "sys");
	        think.redis_mgr = redis_mgr;
		```

4. 3.0中没有think.base类了，可以在common/base下新建了一个base.js作为基类
     
    ```
    'use strict';

   module.exports = class base {

    constructor(...args){
        this.init(...args);
    }

    init(){

    }
    }```

5. this.http改为this.ctx

6. config目录下不是所有js文件都会加载了，非common工程下只会加载redis和config两个js。对于其他js要在config.js中引入：

	```
	'use strict';

	const event_redis = require('./event_redis');
	const event_sys = require('./event_sys');
	const redis_sys = require('./redis_sys');

	/**
	 * config
	 */
	module.exports = {
	    event_redis: event_redis,
	    event_sys: event_sys,
	    redis_sys: redis_sys
	};
	```

7. controller下不支持多级控制器 [https://github.com/thinkjs/thinkjs/issues/797](https://github.com/thinkjs/thinkjs/issues/797)

**Comment by welefen** [comment]
文档改动可以更新到 https://github.com/75team/www.thinkjs.org/edit/master/view/zh-cn/doc/3.0/upgrade.md，然后发 pr。

controller 是支持多级控制器的，已经在排查问题。

此 issue 先关闭。

**Comment by lushijie** [comment]
经过排查，多级模块下多级控制器的功能是正常的。
[项目结构示例](https://p1.ssl.qhimg.com/t01c365b3a1ff28af79.png) 
请使用 DEBUG=think-router npm start 查看路由匹配情况
注：如果项目建立于很久之前，请更新一下模块依赖
