### ISSUE TITLE
默认配置下，启动服务无法通过IP地址访问服务

### ISSUE THREAD

**Issue by jnotnull** [thinkjs/thinkjs#801]
## DESC
默认配置下，host是127.0.0.1
```
host: '127.0.0.1', // server host
```
这样启动起来的服务只能通过127来访问了，却不能通过本机的IP来访问了，比如我的IP是192.168.14.7，我只能配置config文件增加一个host来覆盖下了，这么做的目的是啥？

## ENV

Platform: MAC

Node.js Version: 8.4

ThinkJS Version: 3.0

**Comment by welefen** [comment]
是为了避免 node 的端口直接被访问到，后续考虑改为框架默认不加，创建项目里添加

**Comment by jnotnull** [comment]
黑线。。。刚开始还以为我自己电脑网络问题呢

**Comment by zhengqingxin** [comment]
把 host 默认配置去掉了，现在可以 ip 访问
