### ISSUE TITLE
可以动态创建中间件吗?

### ISSUE THREAD

**Issue by jameskid007** [thinkjs/thinkjs#803]
## DESC
因为我有需求是需要传递不同的参数，多次使用中间件的。 能不能动态创建中间件?  或者说多次传递不同参数使用中间件的解决办法是什么?

## ENV 

Platform: 3.0

Node.js Version: 8.1.2

ThinkJS Version: 3.0

**Comment by welefen** [comment]
传递不同的参数是跟请求相关的么？ middleware 配置支持 enable 和 match 规则的，应该可以满足你的需求。

不行的话你详细描述下你的需求场景。

**Comment by jameskid007** [comment]
我有多个公众号,而且以后会不间断添加新的公众号，然后我用think-wechat中间件，think-wechat需要在option上配置token,appid等参数，然后我需要关联我所有的公众号统一做自定义回复. 这个怎么做?

**Comment by welefen** [comment]
那你怎么判断请求然后用哪个公众号来做回复呢？根据 URL ？

**Comment by welefen** [comment]
这种情况下可以对 think-wechat 做一层 wrap 包装，如：

```js
const wechat = require('think-wechat');
module.exports = [
  {
    handle: options => {
      return (ctx, next) => {
        const config = parseConfigWithCtx(ctx);
        const handle = wechat(config);
        return handle(ctx, next);
      }
    }
  }
]
```

**Comment by jameskid007** [comment]
好的， 已解决!.  谢谢
