### ISSUE TITLE
代码放在extend目录下,好像master进程也会执行

### ISSUE THREAD

**Issue by wstygk** [thinkjs/thinkjs#804]
首先我指定worker数量为1,然后
我在src/extend/目录下放了个文件,例如service.js
放了一个console.log('service');
该语句会被执行2次.
如果指定worker数量为2
该语句会被执行3次.
表明master进程也执行了该语句,但是按照文档的master启动流程,不应该执行该文件.

**Comment by welefen** [comment]
这块有过调整，我们在讨论评估下。

**Comment by wstygk** [comment]
保持文档和程序一致性对我们这些使用者来说是很重要的!
