### ISSUE TITLE
关于think-mongo配置集群

### ISSUE THREAD

**Issue by shihuojian** [thinkjs/thinkjs#805]
集群有多个host怎么配置呢？

**Comment by welefen** [comment]
可以把 host 和 port 配置为数组，见： https://thinkjs.org/zh-cn/doc/3.0/mongo.html#toc-206

**Comment by welefen** [comment]
@shihuojian 问题解决了么？

**Comment by shihuojian** [comment]
@welefen 还是连不上
` [2017-08-30 10:57:24.851] [14877] [INFO] - mongodb://root:pwd@s-bp10362d58484854.mongodb.rds.aliyuncs.com:3717,s-bp1c174278a2c7c4.mongodb.rds.aliyuncs.com:3717/aide`
这个一直在循环

**Comment by shihuojian** [comment]
@welefen 这是服务器线上链接的，密码什么的都没错，用shell单个都可以连上，不知道是哪问题，求指教

**Comment by welefen** [comment]
@shihuojian  think-mongo 底层是基于 MongoDB 模块来弄的，你按照 http://mongodb.github.io/node-mongodb-native/2.2/tutorials/connect/  这里看能连接上么？

**Comment by shihuojian** [comment]
@welefen 好的，我试试

**Comment by shihuojian** [comment]
@welefen 搞定了，我的问题，链接的数据库没单独创建账号密码

**Comment by welefen** [comment]
好的，现在除了用 think-mongo 模块外，你也可以尝试下用 [think-mongoose](https://github.com/thinkjs/think-mongoose)，可以直接使用 mongoose 里所有功能
