### ISSUE TITLE
日志配置layouts设置无效

### ISSUE THREAD

**Issue by zhobby** [thinkjs/thinkjs#808]
## DESC
我设置日志配置layouts，但没有达到预期结果。
按照官网配置 pattern: '%[[%d] [%z] [%p]%] - %m' ，期望的输出应该是：时间 进程id 日志等级 -内容
从打印结果来看我这个配置是没有生效的。
![conf](https://user-images.githubusercontent.com/17928085/29748341-a698c076-8b47-11e7-93e2-abc9e470d0c7.png)
![log](https://user-images.githubusercontent.com/17928085/29748342-a807367c-8b47-11e7-9e0d-2bd632db2ef0.png)

## ENV

Platform:
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64 GNU/Linux

Node.js Version:
v6.11.2

ThinkJS Version:
3.0

**Comment by lizheming** [comment]
感觉你的 think-logger3 版本没有到最新诶，我们现在默认的格式就是你要的这个格式了。

**Comment by zhobby** [comment]
think-logger3 版本是 "version": "1.0.7"。我就是想要现在默认的格式，可是无论我配不配置layouts，日志的输出格式都是我图片的那个样子

**Comment by lizheming** [comment]
那你把所有的依赖和依赖缓存都清一下重新安装下依赖吧，你这个版本肯定是有问题的。

**Comment by zhobby** [comment]
think-logger3 应该使用哪个版本呢？能给一个稳定版本吗？因为线上在跑的系统，依赖直接配最新存在隐患

**Comment by lizheming** [comment]
think-logger3 你已经是最新版了，可能是 ThinkJS3 你装的太老了，重装下试试吧。

**Comment by zhobby** [comment]
刚重装时候发生了错误，我贴下我的package.json。
{
  "name": "thinkjs-application",
  "description": "application created by thinkjs",
  "version": "1.0.0",
  "scripts": {
    "start": "node development.js",
    "compile": "babel --no-babelrc src/ --presets think-node --out-dir app/",
    "lint": "eslint src/",
    "lint-fix": "eslint --fix src/"
  },
  "dependencies": {
    "babel-runtime": "6.x.x",
    "comma-separated-values": "*",
    "ejsx": "^1.0.0-b2",
    "excel-export": "^0.5.1",
    "moment": "2.x.x",
    "nodemailer": "^2.4.2",
    "pm2": "^2.5.0",
    "request": "^2.74.0",
    "source-map-support": "0.4.0",
    "think-cache-file": "~1.0.8",
    "think-logger3": "*",
    "think-model": "*",
    "think-model-mysql": "^1.0.2",
    "think-session-file": "^1.0.5",
    "think-view": "^1.0.0",
    "think-view-ejs": "0.0.11",
    "think-view-nunjucks": "^1.0.1",
    "thinkjs": "next",
    "transliteration": "^1.6.2",
    "validator": "^5.5.0",
    "ws": "^3.0.0"
  },
  "devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-preset-think-node": "^1.0.0",
    "node-notifier": "^5.0.2",
    "think-watcher": "^3.0.0",
    "think-inspect": "0.0.2",
    "think-babel": "^1.0.3",
    "eslint": "^4.2.0",
    "eslint-config-think": "^1.0.0"
  },
  "repository": "",
  "license": "MIT",
  "engines": {
    "node": ">=6.0.0"
  },
  "readmeFilename": "README.md"
}
![1](https://user-images.githubusercontent.com/17928085/29748635-c79a274c-8b4c-11e7-9823-0ec99166b327.png)

**Comment by lizheming** [comment]
你明明装的是 3.0 beta 版怎么在问题里写 3.0 啊…囧… package.json 里面 thinkjs 的版本从 `next` 修改成 `^3.0.0`。

**Comment by zhobby** [comment]
node刚接触不久...所以你懂的。thinkjs已经更新成3.0.0 。结果还是一样。

**Comment by lizheming** [comment]
更新了重启了没

**Comment by zhobby** [comment]
npm run compile
node production.js

**Comment by lizheming** [comment]
所以你在线上直接用 `node production.js` 跑的？

**Comment by zhobby** [comment]
是的。因为我日志配在adapter.production.js.

**Comment by lizheming** [comment]
你没用 pm2 ?

**Comment by zhobby** [comment]
没有

**Comment by lizheming** [comment]
好吧，你 `npm list thinkjs` 看一下 thinkjs 的版本，`npm list think-logger3` 看下 think-logger3 的版本。

**Comment by zhobby** [comment]
└── thinkjs@3.0.0 
└── think-logger3@1.0.7

**Comment by lizheming** [comment]
`adapter.js` 和 `adapter.production.js` 的代码贴一下。

**Comment by zhobby** [comment]
###########adapter.js###############################
const fileCache = require('think-cache-file');
const nunjucks = require('think-view-nunjucks');
const ejs = require('think-view-ejs');
const fileSession = require('think-session-file');
const path = require('path');
const mysql = require('think-model-mysql');
const isDev = think.env === 'development';


/**
 * cache adapter config
 * @type {Object}
 */
exports.cache = {
  type: 'file',
  common: {
    timeout: 24 * 60 * 60 * 1000 // millisecond
  },
  file: {
    handle: fileCache,
    cachePath: path.join(think.ROOT_PATH, 'runtime/cache'), // absoulte path is necessarily required
    pathDepth: 1,
    gcInterval: 24 * 60 * 60 * 1000 // gc interval
  }
};

/**
 * model adapter config
 * @type {Object}
 */

exports.model = {
  type: 'mysql',
  common: {
    logConnect: isDev,
    logSql: isDev,
    logger: msg => think.logger.info(msg)
  },
const fileCache = require('think-cache-file');
const nunjucks = require('think-view-nunjucks');
const ejs = require('think-view-ejs');
const fileSession = require('think-session-file');
const path = require('path');
const mysql = require('think-model-mysql');
const isDev = think.env === 'development';


/**
 * cache adapter config
 * @type {Object}
 */
exports.cache = {
  type: 'file',
  common: {
    timeout: 24 * 60 * 60 * 1000 // millisecond
  },
  file: {
    handle: fileCache,
    cachePath: path.join(think.ROOT_PATH, 'runtime/cache'), // absoulte path is necessarily required
    pathDepth: 1,
    gcInterval: 24 * 60 * 60 * 1000 // gc interval
  }
};

/**
 * model adapter config
 * @type {Object}
 */


/**
 * session adapter config
 * @type {Object}
 */
exports.session = {
  type: 'file',
  common: {
    cookie: {
      name: 'thinkjs'
      // keys: ['werwer', 'werwer'],
      // signed: true
    }
  },
  file: {
    handle: fileSession,
    sessionPath: path.join(think.ROOT_PATH, 'runtime/session')
  }
};

/**
 * view adapter config
 * @type {Object}
 */
exports.view = {
  type: 'ejs',
  common: {
    viewPath: path.join(think.ROOT_PATH, 'view'),
    sep: '_',
    extname: '.html'
  },
  nunjucks: {
    handle: nunjucks
  },
  ejs: {
    handle: ejs,
    beforeRender: (ejs, handleOptions) => {
      //do something before render the template.
    }
  }
};


/**
 * session adapter config
 * @type {Object}
 */
exports.session = {
  type: 'file',
  common: {
    cookie: {
      name: 'thinkjs'
      // keys: ['werwer', 'werwer'],
      // signed: true
    }
  },
  file: {
    handle: fileSession,
    sessionPath: path.join(think.ROOT_PATH, 'runtime/session')
  }
};

/**
 * view adapter config
 * @type {Object}
 */
exports.view = {
  type: 'ejs',
  common: {
    viewPath: path.join(think.ROOT_PATH, 'view'),
    sep: '_',
    extname: '.html'
  },
  nunjucks: {
    handle: nunjucks
  },
  ejs: {
    handle: ejs,
    beforeRender: (ejs, handleOptions) => {
      //do something before render the template.
    }
  }
};
##########adapter.production.js#####################
const path = require('path');
const {DateFile} = require('think-logger3');
exports.logger = {
  type: 'dateFile',
  dateFile: {
    handle: DateFile,
    level: 'ALL',
    absolute: true,
    pattern: '-yyyy-MM-dd',
    alwaysIncludePattern: false,
    filename: path.join(think.ROOT_PATH, 'logs/ccm.log'),
    layouts: {
      type: 'coloured',
      pattern: '%[[%d] [%z] [%p]%] - %m',
    }
  }
};

**Comment by zhobby** [comment]
adapter.js 代码如下：
###############################
const fileCache = require('think-cache-file');
const nunjucks = require('think-view-nunjucks');
const ejs = require('think-view-ejs');
const fileSession = require('think-session-file');
const path = require('path');
const mysql = require('think-model-mysql');
const isDev = think.env === 'development';


/**
 * cache adapter config
 * @type {Object}
 */
exports.cache = {
  type: 'file',
  common: {
    timeout: 24 * 60 * 60 * 1000 // millisecond
  },
  file: {
    handle: fileCache,
    cachePath: path.join(think.ROOT_PATH, 'runtime/cache'), // absoulte path is necessarily required
    pathDepth: 1,
    gcInterval: 24 * 60 * 60 * 1000 // gc interval
  }
};


/**
 * session adapter config
 * @type {Object}
 */
exports.session = {
  type: 'file',
  common: {
    cookie: {
      name: 'thinkjs'
      // keys: ['werwer', 'werwer'],
      // signed: true
    }
  },
  file: {
    handle: fileSession,
    sessionPath: path.join(think.ROOT_PATH, 'runtime/session')
  }
};

/**
 * view adapter config
 * @type {Object}
 */
exports.view = {
  type: 'ejs',
  common: {
    viewPath: path.join(think.ROOT_PATH, 'view'),
    sep: '_',
    extname: '.html'
  },
  nunjucks: {
    handle: nunjucks
  },
  ejs: {
    handle: ejs,
    beforeRender: (ejs, handleOptions) => {
      //do something before render the template.
    }
  }
};
#########adapter.production.js#####################
const path = require('path');
const {DateFile} = require('think-logger3');
exports.logger = {
  type: 'dateFile',
  dateFile: {
    handle: DateFile,
    level: 'ALL',
    absolute: true,
    pattern: '-yyyy-MM-dd',
    alwaysIncludePattern: false,
    filename: path.join(think.ROOT_PATH, 'logs/ccm.log'),
    layouts: {
      type: 'coloured',
      pattern: '%[[%d] [%z] [%p]%] - %m',
    }
  }
};

**Comment by lizheming** [comment]
。。。。帮你把代码高亮加上了。。。你居然还改回去了。。。。。。受不了了。。。。
能不能先去学习下 Markdown 怎么贴代码块。。。。。

logger 输出截全一点我看一下。

**Comment by zhobby** [comment]
开始截错了。。
![2221](https://user-images.githubusercontent.com/17928085/29748875-10a6cc2e-8b52-11e7-9f3e-c63d806ec45f.png)

**Comment by lizheming** [comment]
唔，好像是我把 `layout` 写成 `layouts` 了，你把 think-logger3 更新到 1.0.8 然后把配置的 `layouts` 改成 `layout` 试试。

**Comment by zhobby** [comment]
。。按照你方式做了， think-logger3@1.0.8，还是原来样子

**Comment by lizheming** [comment]
我试了下，好像 log4js 本身 dateFile 自定义 layout 就有问题，晚些时候我再看看。

**Comment by zhobby** [comment]
好吧。File那个可以用吗？尽快解决下吧

**Comment by lizheming** [comment]
调查 OK，你设置的 `layouts.type` 有问题，要用 `layouts.type = 'pattern'` 即可。

**Comment by zhobby** [comment]
666，终于解决了。。。话说，我这配置从官网拷下来的，赶紧修改官网文档吧

**Comment by zhobby** [comment]
666，终于解决了。。。那个type我以为是只是设置颜色的。。。

**Comment by zhobby** [comment]
是layout.type才对。。官网文档写的还是layouts。。尽快修改下文档。辛苦了

**Comment by lizheming** [comment]
文档已更新，如果有觉得不合适的你也可以帮忙修改，给 ThinkJS 贡献下自己的力量。

**Comment by zhobby** [comment]
发现还是有点小问题。。日志输出在文本编辑器会有一些占位符

[32m[2017-08-27 20:42:26.643] [7672] [INFO][39m - WebSocketServer started
[32m[2017-08-27 20:42:27.955] [13700] [INFO][39m - Server running at http://0.0.0.0:1688
[32m[2017-08-27 20:42:27.955] [13700] [INFO][39m - ThinkJS version: 3.0.0-beta4
[32m[2017-08-27 20:42:27.955] [13700] [INFO][39m - Enviroment: production
[32m[2017-08-27 20:42:27.955] [13700] [INFO][39m - Workers: 4

**Comment by lizheming** [comment]
文本内不支持色彩标签，去掉 `%[ %]` 这个包裹即可。

**Comment by zhobby** [comment]
ok.完美解决了

**Comment by wurining** [comment]
看对话要笑死了😆😆😆😆😆😆@lizheming 
ThinkJs很棒！已经第二次用它进行开发了，如果有机会以后可以加入ThinkJS做贡献！

**Comment by welefen** [comment]
@wurining  觉得不错的话，要安利给周边的同事、朋友哦
