### ISSUE TITLE
腾讯云centos使用3.0 创建项目无法访问

### ISSUE THREAD

**Issue by klwfwdk** [thinkjs/thinkjs#811]
## DESC

更新后3.0创建的项目运行后，初始项目 http无log，访问无效，运行以前创建的项目是没有问题的，排除安全策略的问题。win10环境（nodejs8.4.0）测试后没有问题

## ENV

Platform:

Node.js Version:6.10.3

ThinkJS Version:think-cli@1.0.14

**Comment by welefen** [comment]
是怎么访问的呢？在 `src/config/config.js` 添加如下的配置试试：

```js
module.exports = {
  host: '0.0.0.0'
}
```

**Comment by klwfwdk** [comment]
添加后问题解决
