### ISSUE TITLE
上传文件校验是否为图片，规则image不生效

### ISSUE THREAD

**Issue by darkmice** [thinkjs/thinkjs#812]
## DESC

上传文件校验是否为图片，规则image不生效

查看了源码发现think-payload包中引用的“formidable”处理上传文件，最终文件返回的格式是

```js
  var file = new File({
    path: this._uploadPath(part.filename),
    name: part.filename,
    type: part.mime,
    hash: self.hash
  });
```

而think-validator中的验证image的代码是：

```js
Rules.image = value => {
  if (helper.isObject(value)) {
    value = value.originalFilename;
  }
  return /\.(?:jpeg|jpg|png|bmp|gif|svg)$/i.test(value);
};
```

上面验证是的file的originalFilename，而不是name, 

## ENV

Platform: win10

Node.js Version:v7.7.1

ThinkJS Version: 3.x

**Comment by lushijie** [comment]
think-validator 1.2.5版本已经修复该问题，请及时更新。多谢反馈

**Comment by welefen** [comment]
@darkmice 现在 OK 了么？

**Comment by darkmice** [comment]
正常啦
