### ISSUE TITLE
在用户操作之前怎么可以拿到操作的CRUD方法

### ISSUE THREAD

**Issue by shihuojian** [thinkjs/thinkjs#813]
在用户操作之前怎么可以拿到操作的CRUD方法，我想写个权限的，需要做判断

**Comment by welefen** [comment]
没太明白你的意思，具体场景是啥？
权限判断可以统一在 `__before` 或者 middleware 里做来，可以通过 `ctx.controller` 和 `ctx.action` 获取解析后的控制器和操作名。

**Comment by shihuojian** [comment]
@welefen 我想在用户create、delete、update、selecct之前来判断用户是否有权限操作。
PS：目前我自己解决办法是重新把增删查改重新封装了下， 然后用户操作的时候来判断。但是我想如果不封装的方法的的情况下能否拿到用户操作？

**Comment by welefen** [comment]
@shihuojian 是在 model 里封装了？权限判断可以在 __before 或者 middleware 里统一来做啊

**Comment by shihuojian** [comment]
@welefen 但是不是要先拿到用户操作的action吗？

**Comment by welefen** [comment]
@shihuojian 恩，可以通过 `ctx.controller` 和 `ctx.action` 来获取，如果是多模块项目，可以通过 `ctx.module` 获取模块名

**Comment by shihuojian** [comment]
@welefen 好的，是可以实现，但是估计只能自己用了
