### ISSUE TITLE
根目录下404页面反馈

### ISSUE THREAD

**Issue by xuexb** [thinkjs/thinkjs#815]
## DESC
访问 `/xxx.{非html的后缀}` 下不存在的文件时不显示404页面, 如:

- <https://thinkjs.org/11.php>
- <https://thinkjs.org/11.txt>
- <https://xuexb.com/xx.txt>
- <https://xuexb.com/xx.asp>

## ENV

Platform:

Node.js Version: 7.8.0

ThinkJS Version: 2.2.21

**Comment by lizheming** [comment]
ThinkJS 3 have fixed this issue, so I'm closing it.
