### ISSUE TITLE
定时任务可以动态设置吗?

### ISSUE THREAD

**Issue by jameskid007** [thinkjs/thinkjs#816]
## DESC

比如说我固定是设置每6个小时执行一次的定时任务，但是可能这种固定的定时任务不太满足需求，需要每次修改成4个小时执行一次然后可能几个小时后我又想该会6个小时执行一次。 可不可以我做个配置的页面，配置4个小时执行一次，点保存，然后就动态修改成4个小时执行一次这样.

## ENV 

Platform:  Ubuntu

Node.js Version: 8.0

ThinkJS Version: 3.0

**Comment by welefen** [comment]
不能动态设置定时任务时间间隔，但你可以换个思路: 将定时任务时间间隔设置为最小，比如：后台配置的时间间隔最小是1个小时，那么就把时间间隔设置为 1 个小时，不是一个小时的任务就在执行的时候判断下，如果没到后面的逻辑就不执行。

**Comment by jameskid007** [comment]
谢谢。

**Comment by welefen** [comment]
@jameskid007 能满足你的需求么？

**Comment by welefen** [comment]
无响应，先关闭
