### ISSUE TITLE
middleware问题，webpack热更新404

### ISSUE THREAD

**Issue by lizhiyang1** [thinkjs/thinkjs#827]
## DESC
https://github.com/lizhiyang1/thinkjs-react/tree/dev
我用thinkjs + webpack，热更新能正常获取__webpack_hmr，但是获取 hot-update.json 出现404
这是否会跟 think-resource 这个 middleware 有关?
webpack-dev-middleware 采用的是 memory-fs，无实体文件。

## ENV
webpack --progress --colors --config webpack.config.vendor.js
webpack

**Comment by lizheming** [comment]
可以设置 `webpack-hot-middleware/client?reload=true` 设置刷新来搞定。

不过确实会有 `think-resource` 的问题，因为获取打包文件的时候 `think-resource` 会从实体文件里读，所以会有点冲突，这个之后再考虑下怎么修复吧。

**Comment by lizhiyang1** [comment]
临时用写实体文件的方式，将热更新文件写入到磁盘中。

const WriteFilePlugin = require('write-file-webpack-plugin');
const webpackConfig = {
    ...
    plugins: [
        new WriteFilePlugin(),
        ...
    ]
    ...
}
module.exports = webpackConfig;

**Comment by lizheming** [comment]
刚了解到 `think-resource` 有一个 `noFoundNext` 参数，在无实体文件的时候不报错，你可以试一下。

**Comment by welefen** [comment]
@lizhiyang1  这个问题解决了么？

**Comment by lizhiyang1** [comment]
暂时用别的方式解决了。
