### ISSUE TITLE
thinkjs升级3之后报错win7 node7.9

### ISSUE THREAD

**Issue by oksite** [thinkjs/thinkjs#829]
## DESC

$ thinkjs new demo;
$ cd demo;
$ npm install; 
$ npm start;

我是按照官方的流程跑下来的
一直提示 thinkCluster.isAgent is not a function 导致项目跑不起来

## ENV

Platform:

Node.js Version: 7.9

ThinkJS Version: cli@1.0.16

**Comment by welefen** [comment]
@oksite  ThinkJS 3.1.1 版本已经修复该问题

**Comment by oksite** [comment]
ok
