### ISSUE TITLE
在方法里面return false不能阻住后续代码运行

### ISSUE THREAD

**Issue by shihuojian** [thinkjs/thinkjs#833]
例如下面结果为何还是会打出“test”：
```js
 async add(){
    await this.test();
    console.log('test');
  }


  async test(){
    return false;
  }
```

**Comment by lizheming** [comment]
```js

function a() {
  return false;
}

(function() {
a();
console.log(123);
})();
```

**Comment by shihuojian** [comment]
@lizheming 方法里面如何才能阻住，2.2中return think.prevent()可以的

**Comment by lizheming** [comment]
直接 `return await this.test();`

**Comment by shihuojian** [comment]
@welefen 能否封装一个think.prevent()？感觉这个比较好，这样直接return后面的肯定都不能执行了

**Comment by welefen** [comment]
@shihuojian think.prevent 虽然能很好的阻止，但也会带来副作用。
如果有些接口返回了 think.prevent，但外层没有返回或者正确处理的话，会触发 `unhandledRejection` 错误。有些开发者看到这个错误后就蒙圈了，这也是为什么在 3.0 版本里去掉这个功能了。

**Comment by shihuojian** [comment]
@welefen 好的
