### ISSUE TITLE
think.cache 缓存（redis）自动序列化以及无缓存时预置的函数没有执行

### ISSUE THREAD

**Issue by 2681137811** [thinkjs/thinkjs#836]
1、使用 redis 缓存存储 Object 的时候好像没有自动序列化，我记得 thinkjs 2.0 版本是有的。
2、文档中好像没有提到能动态配置缓存参数，thinkjs 2.0 版本好像是这样：think.cache (key ,val, options )，thinkjs 3.0版本好像并没有，是否有方法动态配置缓存时间呢？

**Comment by welefen** [comment]
1、确实有这个问题，我们处理下
2、可以设置的，见： https://thinkjs.org/zh-cn/doc/3.0/cache.html#toc-a95

**Comment by welefen** [comment]
@lushijie  think-cache-redis 和 think-cache-memcache 都有没处理 Object 的问题，需要处理下。

**Comment by lushijie** [comment]
1. think-cache-redis 1.1.0 版本支持了自动序列化 请更新

**Comment by 2681137811** [comment]
@welefen 
好像使用以下方法是无法动态设置缓存时间的：
```
 await this.cache('name','val5',{
    type: 'redis',
    timeout: 8888888
})
```

**Comment by lushijie** [comment]
```
await this.cache('name', 'value', {
   type: 'redis',
   redis: {
     timeout: 24 * 60 * 60 * 1000
   }
});
```

文档写错了，已经更正，请按照这种方式进行动态配置。

如果当时是 ‘redis‘ 类型的，只是想修改timeout ，需要如下设置：

```
await this.cache('name', 'value', {
   redis: {
     timeout: 24 * 60 * 60 * 1000
   }
});
```

**Comment by xb594328980** [comment]
现在好像用着用写法即使是缓存中没有数据也不会执行传递的function。
think.cache(cachekey, async () => {
     return await this.modelInstance.getModelBySkAndAk(ak, sk);
 });

**Comment by lushijie** [comment]
redis空的时候返回了null，判断的时候直接判断 undefined 导致的bug，已经修复。
请更新 think-cache到 1.0.6  think-cache-redis到1.1.12

**Comment by xb594328980** [comment]
是更新 think-cache@1.0.6 think-cache-redis@1.1.2吧  我更新了半天1.1.12 一直报错

**Comment by lushijie** [comment]
think-cache和think-cache-redis 都要最新的？有问题？

**Comment by xb594328980** [comment]
没试了  我是说版本是1.1.2， 不是1.1.12，你看你上面的回复。

**Comment by lushijie** [comment]
哦 哦  think-cache-redis  1.1.12 ， 更新之后问题解决没？

**Comment by lushijie** [comment]
无反馈，关闭
