### ISSUE TITLE
think-model中关于关联模型使用非int值关联错误问题

### ISSUE THREAD

**Issue by xb594328980** [thinkjs/thinkjs#838]
## DESC
think-model中关于关联模型使用非int值关联错误问题详细情况如下图所示：
<img id="base64-img" src="http://images.cnblogs.com/cnblogs_com/xingbo/683790/o_QQ%E5%9B%BE%E7%89%8720170908145933.png" >
如图所示，应该属于失误，烦请尽快修复。

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by welefen** [comment]
请升级 `think-model@1.0.7`

**Comment by xb594328980** [comment]
ok 辛苦
