### ISSUE TITLE
关于数据查询缓存使用redis的问题

### ISSUE THREAD

**Issue by 5ini99** [thinkjs/thinkjs#840]
## DESC
在使用`think.model('xxx').cache('test', {timeout: 3600*1000}).find();`查询缓存时如果用file缓存正常，切换成redis就报 `TypeError: Cannot read property '0' of null`
![524b3db6-6b38-4e4d-83e8-9a3aba227e16](https://user-images.githubusercontent.com/14342127/30255429-7bede456-96d6-11e7-96b2-1374360f34eb.png)

## ENV

Platform:macos 10.12.5

Node.js Version:8.1.3

ThinkJS Version:3.0.0

**Comment by 5ini99** [comment]
@welefen think-model@1.0.5

**Comment by welefen** [comment]
@5ini99 升级到最新版（1.0.7）试下

**Comment by 5ini99** [comment]
@welefen 升级到1.0.7后提示 `{ AssertionError [ERR_ASSERTION]: config.handle must be a function`，应该是model的配置项有变动了，有没有最新的Model配置demo
![wx20170912-094455](https://user-images.githubusercontent.com/14342127/30304316-6d38af8a-979f-11e7-80d7-4bed01358a72.png)
![wx20170912-094520](https://user-images.githubusercontent.com/14342127/30304317-6d3cf838-979f-11e7-9fe0-522d562901f9.png)

**Comment by welefen** [comment]
@5ini99  https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#toc-c1f

**Comment by 5ini99** [comment]
@welefen think-model升到1.0.7了，还是报
```
TypeError: Cannot read property '0' of null
    at /xxxxx/node_modules/think-model/lib/model.js:596:35
    at Generator.next (<anonymous>)
    at step (/xxxxxx/node_modules/think-model/lib/model.js:1:191)
    at /xxxxxx/node_modules/think-model/lib/model.js:1:361
```

异常情况：
```
this.cache(`test`, 'redis').where
```

正常情况
```
this.cache(`test`, 'file').where
```

**Comment by wurining** [comment]
`think.model('xxx').cacle('test', {timeout: 3600*1000}).find();`
这一句`cacle`应该是`cache`吧。确认没有问题吗？
@5ini99

**Comment by 5ini99** [comment]
@lizheming 老大，这个bug看了吗

**Comment by lushijie** [comment]
已经修复，请更新 think-cache@1.0.6  think-cache-redis@1.1.12

**Comment by lushijie** [comment]
长时间无反馈，关闭 issuse
