### ISSUE TITLE
使用3.0文档的例子写完，发现客户端总是自动断开连接

### ISSUE THREAD

**Issue by zhenxiyinger** [thinkjs/thinkjs#842]
## ENV

Platform:

Node.js Version:v8.4.0

ThinkJS Version:3.1.1

**Comment by lushijie** [comment]
请问你说的什么文档？客户端总是自动断开连接指的是什么？粘贴一下详细代码

**Comment by zhenxiyinger** [comment]
按照https://github.com/thinkjs/think-websocket-socket.io写的例子，访问的时候总是显示错误
WebSocket connection to 'ws://127.0.0.1:8360/socket.io/?EIO=3&transport=websocket&sid=TOEQkyWem24fsmxgAAAV' failed: Error during WebSocket handshake: Unexpected response code: 400

**Comment by lushijie** [comment]
贴一下 服务端代码、客户端代码，以及 extend和adapter的配置，或者给下仓库地址

**Comment by lushijie** [comment]
src/config/config.js 中  stickyCluster: true 你是不是没有打开？

**Comment by zhenxiyinger** [comment]
打开了，连接和关闭都输出了，就是过会儿就400，然后在输出open和close，下面是地址，我初学，谢谢您的指导
https://github.com/zhenxiyinger/Zxye

**Comment by lushijie** [comment]
在集群环境中，WebSocket 要求使用粘性会话，来确保给定客户端请求命中相同的 worker，否则其握手机制将无法正常工作。 为了实现这一点，需要开启 stickyCluster 配置。

在你的项目中  src/common/config/config.js

```js
module.exports = {
  stickyCluster: true,
};
```
对于 ThinkJS 3 我们建议使用单模块方式组织代码，因为目前支持了多层级控制器，可以在绝大数场合代替多模块。

**Comment by zhenxiyinger** [comment]
太感谢您了 @lushijie

**Comment by zhenxiyinger** [comment]
能再问您一个问题么，如何给指定的socket发送消息呢，实现私聊功能？

**Comment by lushijie** [comment]
```js
    let socketId = this.ctx.websocket.conn.id;
    this.ctx.req.io.sockets.connected[socketId].emit('opend', 'for your eyes only');
```

给特定的client 发送消息你需要首先要知道socketId, 然后再根据socketId 指定发送。

**Comment by zhenxiyinger** [comment]
谢谢啦

**Comment by lushijie** [comment]
```js
let ids = [];
module.exports = class extends think.Controller {

  constructor(...arg) {
    super(...arg);
  }

  indexAction() {
    return this.display();
  }

  closeAction() {
    let socketId = this.ctx.websocket.conn.id;
    console.log('断开连接', socketId);
    ids = ids.filter(val => val !== socketId);
  }

  openAction() {
    let socketId = this.ctx.websocket.conn.id;
    console.log('创建连接', socketId);
    ids.push(socketId);
  }

  addUserAction() {
    console.log('当前连接列表：', ids);
    this.ctx.req.io.sockets.connected[ids[0]].emit('addUserCallBack', '只有第一个连接可以收到这个消息');
  }
}
```

更完整的示例

**Comment by zhenxiyinger** [comment]
谢谢您，我去试试，this.websocket.id，也能获取socket的id吧

**Comment by lushijie** [comment]
是的，this.websocket.id也能获取socket的id

**Comment by zhenxiyinger** [comment]
文档上说，在 Action 里可以通过 this.ctx.io 来获取 io 对象，该对象为 socket.io 的一个实例。这个怎么用呢

**Comment by lushijie** [comment]
写错了已经更正，应该是this.ctx.req.io，具体使用请查看 socket.io 文档

**Comment by zhenxiyinger** [comment]
哦哦，好的，我让我同事连接我的服务器，我们好像不在一起socket上，ids也被重新赋值了，我的两个浏览器发送广播能看见，他发送的不行。怎么办呀

**Comment by zhenxiyinger** [comment]
刚才我打印了socket对象信息，我同事跟我的conn.Socket.id不一样，我们两个好像真的是两个socket，怎么能到一个中呢

**Comment by lushijie** [comment]
你们是两个连接，当然是两个 socketid , 即便是浏览器刷新也会导致 socketid 变化

**Comment by zhenxiyinger** [comment]
我的意思是一台机器两个浏览器连接我的服务就可以互相通信，两台机器就不行

**Comment by zhenxiyinger** [comment]
我用我公司的测试服务器(公网)搭建的没问题，用我自己电脑做服务器就会出现我之前说的情况。。。

**Comment by zhenxiyinger** [comment]
你好，我想问一下，websocket如果实现多个房间，或者小组广播呢

**Comment by zhenxiyinger** [comment]
再请教您一下呗，如果利用 socket.io 进行消息主动推送~感谢

**Comment by lushijie** [comment]
可以看一下 websocket 的原理。服务端可以 emit 或者 broadcast 主动推消息，但是前提是建立了连接

**Comment by zhenxiyinger** [comment]
感谢~
