### ISSUE TITLE
在 middleware 中无法获取 ctx.module  ctx.controller  ctx.action

### ISSUE THREAD

**Issue by 2681137811** [thinkjs/thinkjs#846]
RT，有没有解决方案，只能自己手动解析 path 么？
有业务需要在 middleware 中做用户身份识别，以及判断该用户是否对该路由有操作权限
另外文档里面没有提及如何在 middleware 调用 controller 的 action
以前 2.0 是 think.controlle( name, http, module )
后面折腾半天才发现 3.0 是 new think.app.controllers[module][controller](ctx)
建议写入文档中

**Comment by welefen** [comment]
@2681137811 在 router 之后的 middleware 就可以通过 `ctx.controller`、`ctx.action` 来获取

**Comment by welefen** [comment]
@2681137811  ping
