### ISSUE TITLE
关于PM2的日志问题

### ISSUE THREAD

**Issue by ZH5223** [thinkjs/thinkjs#847]
是不是在使用了log4js日志后，就不能显示PM2的global log？
感觉有冲突？

**Comment by lizheming** [comment]
pm2 的 log 是记录的终端的 `console.log` 吧，如果你有 `console.log` 就没啥问题。

**Comment by welefen** [comment]
通过 console.xxx 输出的日志会记录导 pm2 的 log 里，但项目里建议使用 `think.logger.xxx` 来输出日志，具体见：https://thinkjs.org/zh-cn/doc/3.0/logger.html

**Comment by wonyun** [comment]
@welefen thinkjs项目依赖的一些模块内部可能会用console.xxx来输出日志信息，比方访问资源404时会将信息通过控制台输出，这些日志信息能否通过think.logger.xxx来输出？不然造成日志碎片化，有的在pm2中记录，有的在我们制定的日志文件中记录

**Comment by chenyuncai** [comment]
trace中间件里可以打404日志
