### ISSUE TITLE
请问thinkjs怎么自定义404页面？

### ISSUE THREAD

**Issue by jameskid007** [thinkjs/thinkjs#848]
## DESC
请问thinkjs怎么自定义404页面

## ENV

Platform: Ubuntu

Node.js Version: 8.0

ThinkJS Version: 3.0

**Comment by lushijie** [comment]
// src/config/middleware.js

```
{
    handle: 'trace',
    enable: !think.isCli,
    options: {
      debug: isDev,
      templates: {
        404: path.join(think.ROOT_PATH, 'view/common/error_404.html'),
        500: path.join(think.ROOT_PATH, 'view/common/error_500.html'),
      }
    }
  },
```

**Comment by jameskid007** [comment]
我pm2 log, 404的时候会报红。 加上了404页面还是会报红。 怎么不报红呀?

**Comment by jameskid007** [comment]
production模式， 也会报红

**Comment by jameskid007** [comment]
谢谢~

**Comment by AspenLuoQiang** [comment]
@lushijie thinkjs3.0 按照该方法不起效！

**Comment by lushijie** [comment]
@AspenLuoQiang  你贴一下 trace 的配置来看一下

**Comment by AspenLuoQiang** [comment]
@lushijie 直接复制上面的，确认模板路劲没有出错，在`think-trace/lib/tracer.js` 中 `getTemplateContent` 方法中打印 `this.templatesPath`，结果及目录结构如下：
![image](https://user-images.githubusercontent.com/12598256/33426816-16d58a58-d5fe-11e7-94ec-2e13443b9164.png)
![image](https://user-images.githubusercontent.com/12598256/33426850-3aad2cc4-d5fe-11e7-9818-d26cfe132551.png)
![image](https://user-images.githubusercontent.com/12598256/33426866-423ce2ea-d5fe-11e7-8dc9-56de3b6789a0.png)

**Comment by AspenLuoQiang** [comment]
补充一下，是多项目结构
![image](https://user-images.githubusercontent.com/12598256/33426951-92ef95fc-d5fe-11e7-8b74-00bce0f198b9.png)

**Comment by AspenLuoQiang** [comment]
@lushijie 补充一下，是多项目结构
![image](https://user-images.githubusercontent.com/12598256/33426985-a11e6630-d5fe-11e7-8704-c2bc4d7afe2d.png)

**Comment by lizheming** [comment]
@AspenLuoQiang 我看你打印的路径没啥问题额，你后面打一下 `this.templates.404` 看看模板内容获取是否正常。
