### ISSUE TITLE
mysql model operate.

### ISSUE THREAD

**Issue by wuchuguang** [thinkjs/thinkjs#849]
## DESC
mysql model
can i define getAttr(){}, setAttr(){}

## ENV

Platform:

Node.js Version:
node 8

ThinkJS Version:
v.3.2

**Comment by welefen** [comment]
@wuchuguang  你是想获取数据表的 schema？

**Comment by welefen** [comment]
@wuchuguang ping

**Comment by wuchuguang** [comment]
i use think-sequlize middle
