### ISSUE TITLE
手机观看文档不方便

### ISSUE THREAD

**Issue by SmallRuralDog** [thinkjs/thinkjs#851]
## DESC
手机或平板电脑在官网观看文档不方便
所以就弄了一个小程序可以看3.0最新文档，希望可以对大家有帮助
![](http://ww1.sinaimg.cn/large/b0202fcagy1fjiunqtt7ej20d20evq48.jpg)

## ENV

Platform:

Node.js Version:6.0

ThinkJS Version:3.0

**Comment by welefen** [comment]
@SmallRuralDog  真棒

**Comment by varnbu** [comment]
cool
