### ISSUE TITLE
我的网站需要加入emoji表情，thinkjs需要配置做什么设置吗?

### ISSUE THREAD

**Issue by jameskid007** [thinkjs/thinkjs#852]
## DESC
我需要做emoji表情，然后mysql改成了utf8mb4的字符集。 简单的❤可以出来，但是表情打上去就是乱码，？？？？这样了，thinkjs需要配合设置一下字符集吗?

## ENV

Platform: Ubuntu

Node.js Version: 8.0

ThinkJS Version: 3.0

**Comment by welefen** [comment]
https://github.com/mysqljs/mysql#connection-options 配置 charset

**Comment by liuguanyu** [comment]
要加两个配置：
    encoding: 'utf8mb4'
    charset: 'utf8mb4'
