### ISSUE TITLE
ThinkJS 3.1 默认rest基类 modelInstance.getPk报错

### ISSUE THREAD

**Issue by wangmx** [thinkjs/thinkjs#853]
## DESC
创建 REST Controller
`thinkjs controller user -r`
默认生成的rest.js里这句会报错
getPk  is not a function
`const pk = await this.modelInstance.getPk();`

## ENV

Platform: Debian 7

Node.js Version:v6.10.3

ThinkJS Version:3.1.0

**Comment by lizheming** [comment]
`think-cli` 的版本需要升级一下，然后你改成 `this.modelInstance.pk` 即可。

**Comment by wangmx** [comment]
我是这样改的，原来是think-cli版本太旧了
