### ISSUE TITLE
REST api.  modelInstance.getPk() is not a function

### ISSUE THREAD

**Issue by 4pider** [thinkjs/thinkjs#856]
## DESC
使用命令生成controller ,
`thiskjs controller info -r;`
数据表为 info ，key 为 user_id;
controller info.js 接收put/post请求报错
`TypeError: _this.modelInstance.getPk is not a function`

请问如何获info的key呢？

## ENV

Platform: 

Node.js Version: 8.4.0

ThinkJS Version: 3.1.2

**Comment by lizheming** [comment]
same as https://github.com/thinkjs/thinkjs/issues/853
