### ISSUE TITLE
官网访问异常

### ISSUE THREAD

**Issue by KidLau** [thinkjs/thinkjs#857]
## DESC
访问官网文档，有时能看到3.0的文档，只能看到2.1的文档

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by lizheming** [comment]
英文文档目前没有 3.0 的，注意文档语言。

**Comment by KidLau** [comment]
请问如何切换中文文档呢？我系统是中文的

**Comment by lizheming** [comment]
清一下 cookie，或者英文文档底部有一个 Language 切换，又或者直接 http://thinkjs.org/zh-cn 都是可以的。

**Comment by KidLau** [comment]
好的，谢谢
