### ISSUE TITLE
RESTful API 失效

### ISSUE THREAD

**Issue by littledu** [thinkjs/thinkjs#861]
## DESC
之前在2.0版本下的 RESTful API 的各种action，如 getAction, postAction 等，目前在3.0下都失效了，如 getAction 改为 indexAction 则可以，感觉变成了普通 controller 了。
在3.0 下用 `thinkjs controller ooxx -r` 生成的也不行，求优先修复

## ENV

Platform: Mac OS

Node.js Version: 8.1.3

ThinkJS Version: 3.1.2

**Comment by lizheming** [comment]
和 2.x 不同，3.x RESTful 的路由需要额外定义一层自定义路由，详见文档：https://thinkjs.org/zh-cn/doc/3.0/rest.html#toc-6b0

**Comment by littledu** [comment]
@lizheming 感谢，文档有打开，但以为是`添加自定义的路由`，而我不需要自定义，就默认就行了，就没看下去，文档可以再优化优化嘿嘿。
