### ISSUE TITLE
session 如何存储在 db

### ISSUE THREAD

**Issue by littledu** [thinkjs/thinkjs#863]
## DESC
2.0 时候我是把 session 存储在 db 的，现在看了下貌似没有相关实现了？

## ENV

Platform:

Node.js Version:

ThinkJS Version:

**Comment by wurining** [comment]
这里是Thinkjs 3.0的[设计图](http://naotu.baidu.com/file/b0b782af210336178f793edb5f755f07?token=f10499e867adaacf)，右半部分有session模块，里面有对应的存储方法。你说的应该是存储在非内存数据库中，看起来新版本是还没有实现。

**Comment by lushijie** [comment]
session 存储在mysql  https://github.com/thinkjs/think-session-mysql

**Comment by littledu** [comment]
@lushijie https://github.com/thinkjs/think-awesome#session 这里怎么没有，看了你那个不是配置一下就能用？

**Comment by lushijie** [comment]
是的，需要按照 think-session-mysql 创建数据表，其他的和其他类型的session 使用一致

**Comment by littledu** [comment]
@lushijie 好的，感谢

**Comment by littledu** [comment]
@wurining 感谢
