### ISSUE TITLE
Any chance to make it more english centered?

### ISSUE THREAD

**Issue by pie6k** [thinkjs/thinkjs#864]
I'm not native english speaker, but I'm quite sure pushing this repo to use english as main language instead of chineese would make it (issues for example) more helpful for much more people.

Right now I'm not really able to quickly find anything useful inside issues section and potentially duplicate some issue etc.

**Comment by lizheming** [comment]
Thank you for your opinion. I'm agree with you so much, project can be benefit from beinternationalized community. First of all, we are all appreciate english issue. But we have to realize that Chinese developers are our main subscriber, most of them like use mandarin as default although I have remind them. Can you have other way to make it englishnized, I'm all ears.

By the way, I'll translate some useful issue to english manually like #713 , #832 ... and will more and more issue will be translated.

**Comment by zhanghengxin** [comment]
I LOVE CHINA AND WO就是喜欢中文，你咋咋滴

**Comment by vsme** [comment]
You can use Google translation, and I also use Google translation to translate English content, it is really very easy to use.

**Comment by pie6k** [comment]
@vsme I know and I do use it, but there are more than that. For example: If issues were in english, they could be found via github search or via google search and that could make big difference in traffic.

My opinion is that it can be a bit locking for this great project.

**Comment by lizheming** [comment]
@pie6k Yes, you are right! To search easily is why I translated those issue. I'll continue my translation working with your hope and call more people join it. 😋 Thank you very much again! 

At last, If you have some problem about ThinkJS using, you can post english issue directly. We will reply you using english quickly. I think this is another way to extend internationalized community.

**Comment by pie6k** [comment]
Another thing is project managers might be abit *scared* to let developers use this project when they will see most of the issues (and even main readme file) in Chinese.

Thats, I think, all I could say about it :) Thanks for great work here, guys!

**Comment by lizheming** [comment]
@pie6k yes, I'm agree with all your said. we will use both english and chinese to avoid scared two side people 😆
