### ISSUE TITLE
thinkjs3如何实现静态资源和json接口数据的gzip压缩？

### ISSUE THREAD

**Issue by dingyiming** [thinkjs/thinkjs#865]
## DESC

thinkjs3如何实现静态资源和json接口数据的gzip压缩？

### ENV

OS Platform: mac osx 11

Node.js Version: v8.5.0

ThinkJS Version: 3.1

### code
```js
const compress = require('koa-compress')

...
  {
    handle: compress,
    options: {
      filter: function (content_type) {  //配置过滤的压缩文件的类型
        return /text/i.test(content_type)
      },
      threshold: 2048,   //要压缩的最小响应字节
      flush: require('zlib').Z_SYNC_FLUSH  //同步的刷新缓冲区数据；
    }
  },
```

### error message

```
// no
```

### more description

配置了koa-compress,但似乎前端静态资源没有使用gzip

**Comment by lizheming** [comment]
线上环境的话静态资源都交给 Nginx 控制了，没走路由。另外建议 gzip 也全部交给 Nginx 来做比较好。

**Comment by welefen** [comment]
@dingyiming 线上推荐用 nginx，如果非要用框架处理静态资源请求的话。可以在 think-resource 里配置   https://github.com/thinkjs/think-resource#options

**Comment by dingyiming** [comment]
nginx这点是明白的，但是鉴于应用初期的情况，更希望做聚合，快速响应，简易迁移，所以希望直接将功能聚合到thinkjs3中完全支撑比较好

**Comment by lizheming** [comment]
https://github.com/thinkjs/think-resource#options 静态资源配置 `think-resource` 即可。

**Comment by dingyiming** [comment]
@lizheming 谢谢，搞定了

**Comment by hyingreborn** [comment]
@dingyiming @lizheming 我也配了gzip: true，可在chrome的network里看不到content-encoding: gzip，是没生效吗？
