### ISSUE TITLE
请求参为为数组的情况下怎么解析？

### ISSUE THREAD

**Issue by bing6** [thinkjs/thinkjs#866]
OS Platform:macOS

Node.js Version:7.7.2

ThinkJS Version:3.0

### code
```
{ action: 'create',
  'data[0][username]': '',
  'data[0][nickname]': '',
  'data[0][password]': '' }
```

### more description
因为前端用了jQuery Database插件,提交数据时是以数组形式的。但是默认的解析并没有对数组做处理，那么我该怎么办呢?

**Comment by lushijie** [comment]
你说的默认的解析指的是什么？ 对数组做处理指的是怎么处理？
如果是 get 提交 this.ctx.param() ，如果是 post 提交 this.ctx.post()，看一下你传给服务端的数据。

**Comment by bing6** [comment]
请求数据大概是这样的。
那么我在服务端只能通过this.post()或者this.ctx.post()获取到请求的参数.
结果大概是这样的。
{ action: 'create',
  'data[0][username]': '',
  'data[0][nickname]': '',
  'data[0][password]': '' }
我是希望能获取到{
action: 'create',
data[
{username:'', nickname:'', password:''}
]
这样的结果
}

**Comment by welefen** [comment]
@bing6 目前还不支持这种数据结构，你可以先自己处理下。我们这边讨论下这个 case

**Comment by bing6** [comment]
@welefen 
客户端提交的数据应该是这样的
action=create&data[0][username]=&data[0][nickname]=&data[0][password]=
URL编码后是
action=create&data%5B0%5D%5Busername%5D=&data%5B0%5D%5Bnickname%5D=&data%5B0%5D%5Bpassword%5D=

**Comment by welefen** [comment]
这种实际上并不是一种通用的格式，现在默认没有支持，框架支持 json 格式的数据。让客户端把数据 JSON.stringify 下发送，然后设置 Content-Type 为 application/json，这样拿到后就是你想要的数据了。

**Comment by bing6** [comment]
@welefen 
前端数据使用的是DataTables，一个jQuery插件。显示数据表格的，这个用的人应该还是挺多的。
而且插件本身还提供了编辑修改功能，这部分不是开源的。也没办法修改请求数据格式。

**Comment by lizheming** [comment]
@welefen 
- koa 默认使用 querystring 模块，所以不支持多数组形式的格式解析
- express 则比较复杂，支持简单的 `querystring` 也支持配置后使用 `qs` 模块高级解析，也可以自定义解析函数
 https://github.com/expressjs/express/blob/master/lib/utils.js#L196-L221
- eggjs 则比较另类，两种解析是并存的，`.query` 属性获取的是字符串解析，`.queries` 属性获取到的是数组解析，[源码](https://github.com/eggjs/egg/blob/master/app/extend/request.js#L144-L178)，具体的规则可参考苏千给 Koa 提的 issue [qs@koajs#5](https://github.com/koajs/qs/issues/5)。不过 Koa 的这个目前似乎还没有实现。

目前来看 express 的兼容会稍微柔和点。

**Comment by welefen** [comment]
@bing6  可以使用 https://github.com/thinkjs/think-qs 中间件，支持该数据结构。需要升级 `thinkjs@3.2.2`
