### ISSUE TITLE
3.0不支持google protobuf 数据？

### ISSUE THREAD

**Issue by brucecodezone** [thinkjs/thinkjs#867]
## DESC
由于业务需要，需要使用 protobuf 数据格式，但是发现无论是用this.post(),还是 this.ctx.request，等方法，均无法获取安卓客户端传递的 protobuf 数据？求解答。
### ENV

OS Platform:ubuntu 16.4

Node.js Version:8.0

ThinkJS Version:3.0

**Comment by brucecodezone** [comment]
@welefen

**Comment by welefen** [comment]
@brucecodezone  把传递的数据截图看下？

**Comment by welefen** [comment]
@brucecodezone ping

**Comment by xb594328980** [comment]
为啥不直接用grpc操作呢？

**Comment by brucecodezone** [comment]
@welefen 
抱歉,昨天有点忙~
写的测试代码
使用的protibuf库   "google-protobuf": "^3.4.0",

`const  superAgent = require('superagent');
const ReqPB = require('../src/protobuf/update_pb');

let reqPB = new ReqPB.Req();
reqPB.setAppkey('59a94a6');
reqPB.setUserid('dgdk123456781086581178');
reqPB.setAppver('1.0.4');
reqPB.setPlatform('Android');
reqPB.setPlatformver('4.4.1');
reqPB.setBrand('Xiaomi');
reqPB.setDevice('pro 6');
reqPB.setApiver('1.0')
let data = reqPB.serializeBinary();

console.log('序列化===',data.toString());


let deData = ReqPB.Req.deserializeBinary(data);
console.log('反序列化====',deData);
console.log('反序列化====',deData.getBrand());

//superagent http请求
superAgent
    .post(url)
    .type('application/x-protobuf')
    .send(data.toString())
    .end((err, res) => {
    if(err) console.log(err);
        console.log(res.res);
    });
`
`
console
➜  test git:(master) ✗ node testProbuf.js
序列化=== 10,24,53,57,97,57,52,97,54,51,56,48,54,51,100,56,50,102,50,51,57,98,51,52,49,100,18,22,100,103,100,107,49,50,51,52,53,54,55,56,49,48,56,54,53,56,49,49,55,56,26,5,49,46,48,46,52,34,7,65,110,100,1141,105,100,42,5,52,46,52,46,49,50,6,88,105,97,111,109,105,58,5,112,114,111,32,54,66,3,49,46,48
反序列化==== { wrappers_: null,
  messageId_: undefined,
  arrayIndexOffset_: -1,
  array: 
   [ '59a94a638063d82f239b341d',
     'dgdk123456781086581178',
     '1.0.4',
     'Android',
     '4.4.1',
     'Xiaomi',
     'pro 6',
     '1.0' ],
  pivot_: 1.7976931348623157e+308,
  convertedFloatingPointFields_: {} }
反序列化==== Xiaomi

`

**Comment by brucecodezone** [comment]
@xb594328980 服务端就是node了，业务不多，只是需要有些地方需要加密

**Comment by welefen** [comment]
type 为 `application/x-protobuf` 的数据目前 think-payload 是没有处理的，需要自己去处理。

**Comment by brucecodezone** [comment]
嗯，好的，谢谢～

**Comment by welefen** [comment]
@brucecodezone 你可以弄个 think-protobuf 中间件，用来解析这个数据，代码可以参考 https://github.com/thinkjs/think-payload 的实现。
