### ISSUE TITLE
3.0版本 Context对象的JsonP方法中的Content-Type有误

### ISSUE THREAD

**Issue by CNmarkhao** [thinkjs/thinkjs#868]
跨域访问，火狐能通过测试。Chrome中有误。报
its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.
查看了源码Context对象的确Content-Type 设置有误。

**Comment by CNmarkhao** [comment]
需要设置为 application/json-p 或者 text/json-p

**Comment by lizheming** [comment]
https://github.com/thinkjs/thinkjs/blob/2512359c88b41e61c172369d1a712f2141a11111/lib/extend/context.js#L86

jsonp 是一个 script 可执行脚本，的确不应该设置成 json 格式。 @welefen

**Comment by CNmarkhao** [comment]
原因是我使用了  koa-helmet  中间件导致的，可能启用了strict MIME type。
