### ISSUE TITLE
能否将404页面开放到view中？

### ISSUE THREAD

**Issue by hyingreborn** [thinkjs/thinkjs#870]
根据 #848 中的解决方案这样自定义后，只能使用自己的静态页模板，无法显示默认404页显示的错误信息，特别是开发阶段不太方便。能否把默认404页放到view目录中，方便直接修改？

**Comment by lizheming** [comment]
默认模板也是一个静态页模板，在模板中使用 `{{errMsg}}` 变量就可以显示错误信息了。

**Comment by hyingreborn** [comment]
@lizheming 感谢！
不过500页面只用这个{{errMsg}}，开发阶段就丢了详细的报错信息了。。。

**Comment by lizheming** [comment]
有一个 `{{error}}` 数组是堆栈信息，需要你自己去解析显示，具体自行参考默认模板吧。

**Comment by hyingreborn** [comment]
@lizheming 哦哦，好的，我就是没找到默认模板，方便告诉我下路径吗？

**Comment by lizheming** [comment]
https://github.com/thinkjs/think-trace/blob/master/template/500.html <https://github.com/thinkjs/think-trace/blob/master/template/500.html>

**Comment by hyingreborn** [comment]
@lizheming 非常感谢！
