### ISSUE TITLE
在base.js里面建一个方法，然后在继承base.js的控制器里面调用这个方法,里面的return 并不能阻止程序的执行。

### ISSUE THREAD

**Issue by arterli** [thinkjs/thinkjs#871]
## DESC
在base.js里面建一个方法如下：
```js
 async weblogin() {
    const islogin = await this.islogin();
    if (!islogin) {
      // 判断浏览客户端
      if (this.isMobile) {
        // 手机端直接跳转到登录页面
        return this.redirect('/center/public/login');
      } else {
        return this.redirect('/cmswing/error/login');
      }
    }
  }
```
然后在继承base.js的控制器里面调用这个方法
``` js
await this.weblogin();
```
 return this.redirect 并不能阻止程序的继续执行。
### ENV

Node.js Version: 8.5

ThinkJS Version: 3.2

**Comment by junmaqiang** [comment]
兄弟, 你是跳错了地方吧!  
用cmswing框架搭建的项目?  参考其他模块不就可以啦!

**Comment by arterli** [comment]
@junmaqiang 我就是 cmswing 的作者

**Comment by zhengqingxin** [comment]
@arterli 少写了`return`?     
`return await this.weblogin()`

**Comment by arterli** [comment]
@zhengqingxin `return await this.weblogin()` 这样是不是永远就不往下走了？

**Comment by zhengqingxin** [comment]
按照你现在`weblogin `的写法，是的

**Comment by arterli** [comment]
@zhengqingxin 2.2这样写时可以的，3.0就不行了。

**Comment by zhengqingxin** [comment]
先拥抱下变化吧，我们后续讨论下这个

**Comment by junmaqiang** [comment]
不错,要为作者点赞, @arterli

**Comment by 2681137811** [comment]
@arterli @welefen
是否是因为移除了 think.prevent 方法的原因
我也头大，用户请求 Action 就必须要再当前 Action 中 return 才能终止请求
如果使用 Action 调用其他方法无法再其他方法中终止后续执行

**Comment by welefen** [comment]
@arterli @2681137811  需要判断返回值是否为 false 来处理，如：

```js
const flag = this.xxx();
if(flag === false) return false;
```
2.x 版本中提供了 think.prevent 方法快速处理这种需求，但使用不当（没有 return 等）也会带来一个报错的问题，给开发者带来疑惑。如：https://github.com/thinkjs/thinkjs/issues/507

**Comment by lizheming** [comment]
You can add following code to your project, then ThinkJS 3.x `this.redirect()` behavior will same as 2.x. You can read more in https://zhuanlan.zhihu.com/p/34220232. 

```js
// src/common/extend/think.js
const preventMessage = 'PREVENT_NEXT_PROCESS';
module.exports = {
  prevent() {
    throw new Error(preventMessage);
  },
  isPrevent(err) {
    return think.isError(err) && err.message === preventMessage;
  }
};
```

```js
// src/common/extend/controller.js
module.exports = {
  redirect(...args) {
    this.ctx.redirect(...args);
    return think.prevent();
  },
  success(...args) {
    this.ctx.success(...args);
    return think.prevent();
  },
  fail(...args) {
    this.ctx.fail(...args);
    return think.prevent();
  }
};
```
