### ISSUE TITLE
thinkjs 3.x版本浏览器断点调试没效果。

### ISSUE THREAD

**Issue by zhobby** [thinkjs/thinkjs#872]
## DESC
已知3.0在vs code上的断点还存在问题。issue上关于这个问题有的网友说webstom和浏览器可行，但没有明确、总结的一个说法。下午自己试了下，发现没效果，请大家帮忙看看。以下是我尝试的具体步骤。
1.  按照官网指引新建一个demo项目
```
thinkjs new demo
cd demo
npm install
npm start
```

2. 全局安装 node-inspector

3. 启动 node-inspector 服务
![image](https://user-images.githubusercontent.com/17928085/30781649-a259ee08-a155-11e7-8242-422c23d3b284.png)

4. 启动 Node.js 服务
![image](https://user-images.githubusercontent.com/17928085/30781654-bffd0a80-a155-11e7-92b4-6e9a17563ee7.png)

5. 调试，打断点

6. 访问页面，完全没效果，经过断点哪里并没有停止，而是直接输出了

### ENV

OS Platform:
win 10

Node.js Version:
v6.9.2

ThinkJS Version:
3.2.1

Chrome Version:
版本 60.0.3112.113（正式版本） （64 位）

**Comment by zhobby** [comment]
### 补充下第5，6步的图片。
5. 调试，打断点
![image](https://user-images.githubusercontent.com/17928085/30781748-35a5729e-a157-11e7-865d-8b764e037c6e.png)



6. 访问页面，完全没效果，经过断点哪里并没有停止，而是直接输出了
![image](https://user-images.githubusercontent.com/17928085/30781735-1108c24c-a157-11e7-869e-2d9c76d84be2.png)

**Comment by junmaqiang** [comment]
我也一直都没有调试成功,  哈哈!  
thinkjs 如果解决这个问题, 其实对于我们开发者而言,体验是很赞的!

**Comment by welefen** [comment]
同 https://github.com/thinkjs/thinkjs/issues/756
