### ISSUE TITLE
部署正式机问题。

### ISSUE THREAD

**Issue by xlgosin** [thinkjs/thinkjs#874]
## DESC
项目部署本地访问正常，但是同样的配置部署上centos，上了测试服务器就出现302情况。
数据库数据加载不出来，而且页面加载比较慢。

后台返回的请求
[2017-09-25 01:52:26.352] [86524] [INFO] - GET /category/list 302 1ms

### ENV

OS Platform: centos 6.5

Node.js Version: v8.5.0

ThinkJS Version:think-cli@1.1.0

**Comment by junmaqiang** [comment]
环境问题还是坑最多的, 如果有条件的话, 用 docker 可以完全解决部署和运维时环境导致的问题!

**Comment by xlgosin** [comment]
我只是想快速部署起来测试机，看看效果。

**Comment by xlgosin** [comment]
已经解决。

**Comment by zhengqingxin** [comment]
什么原因呢？ @xlgosin

**Comment by xlgosin** [comment]
是我拿下来的代码的问题。不是thinkjs的问题。
