### ISSUE TITLE
多模块模式，模块的base控制器能不能继承自common下的自建的base控制器？

### ISSUE THREAD

**Issue by hyingreborn** [thinkjs/thinkjs#875]
## DESC
使用3.0的多模块模式后，存在admin/home两个模块，分别都有自己的base.js控制器，运行良好。
因为有些功能希望提供给所有模块使用，是否可以在src/common目录下自建一个全站级的base控制器，让每个模块的base.js继承它？

自己尝试了下，好像不行...求助...

### ENV

OS Platform: Win10

Node.js Version: 6.0x

ThinkJS Version: 3.2.0

### code
```
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by hyingreborn** [comment]
![image](https://user-images.githubusercontent.com/1283261/30799968-1a3e1d0c-a211-11e7-9d3a-5ab25819374f.png)

### 如图所示，希望可以通过http://localhost/ub 访问，渲染出view/common/upgradeBrowser.html页面

**Comment by junmaqiang** [comment]
这是很不错的需求!
记得PHP的Yii框架是可以这样子滴!  
thinkjs 我发现不可以!

**Comment by hyingreborn** [comment]
@junmaqiang 
我试了下，common/controller/ub.js是可以生效的。

不过那个base.js好像是不能被其他模块继承的，这样如果模块多了，想做一些全站级的控制就不太方便了

@lizheming  不知道是不是自己方法用做了？

**Comment by welefen** [comment]
@hyingreborn 可以继承的， require 的时候需要注意文件路径

**Comment by hyingreborn** [comment]
@welefen 感谢回复，我试了下路径应该是对的，不过顶级base.js的__before()方法好像没有执行，能看看是哪里出问题了吗？

#### 顶级base：/common/controller/base.js
```
module.exports = class extends think.Controller {
  __before() {
    return this.fail('common/controller/base.js')
  }
};
```
#### home模块base：/home/controller/base.js
```
const Base = require('../../common/controller/base.js');
module.exports = class extends Base {
  __before() {
    return this.fail('home/controller/base')
  }
};
```
#### home模块index：/home/controller/index.js
```
const Base = require('./base.js');
module.exports = class extends Base {
  __before() {
    return this.fail('home/controller/index')
  }
};
```

这样配置完后，访问localhost/home/index，返回的是：
```
{
"code": 1000,
"msg": "home/controller/base"
}
```
这是home模块base返回的内容，不是顶级base返回的内容

**Comment by welefen** [comment]
@hyingreborn 你这里在子类中把 `__before` 方法重写了，执行的时候当然不会执行父级对应的方法。如果想执行父级的方法，那么可以通过 `super.__before()` 调用，如：

```js
const Base = require('./base.js');
module.exports = class extends Base {
  async __before() {
    const flag = await super.__before();
    if(flag === false) return false;
    return this.fail('home/controller/index')
  }
};
```
`super.__before` 这是 ES 里的语法哦，建议你把 ES6 的特性系统性看看。

**Comment by hyingreborn** [comment]
@welefen 哦哦，好的，补习ES6去了  👍
