### ISSUE TITLE
thinkjs 3.0中没有使用ES6的import和export的语法，原因是什么？

### ISSUE THREAD

**Issue by KidLau** [thinkjs/thinkjs#879]
## DESC
在thinkjs 2.0中，用的是ES6的import和export语法
但在最新的thinkjs 3.0中，用的是commonJS的require和module.exports
请问是出于什么原因？是为了性能还是什么？求科普

**Comment by lizheming** [comment]
因为原生，这样能尽量不走 babel 编译。当然最新的 Node 已经支持 import 了，不过我们还是要考虑 LTS 的版本的。

**Comment by KidLau** [comment]
嗯，明白，谢谢！
