### ISSUE TITLE
I cant get any detail about the chain methods of model.

### ISSUE THREAD

**Issue by AkashiX** [thinkjs/thinkjs#881]
## DESC

// your detail description 
I just know there're how many the chain methods I can invoke, but how to invoke, and what params I need to pass,  I don't know...If there's a doc that show the usage in detail, plz tell me, thx!

**Comment by lizheming** [comment]
some condition add function like `where`, `group`, `order`, `uion`, `join`, `field`, `fieldReverse`, `page`, `limit`, `alias`, `having`, `group` you can chain, and other get result function you can't chain it.

**Comment by AkashiX** [comment]
I got, it's on API.
