### ISSUE TITLE
Debug with thinkjs

### ISSUE THREAD

**Issue by AkashiX** [thinkjs/thinkjs#882]
### ENV

OS Platform: Mac OSX

Node.js Version: v7.6.0

ThinkJS Version: 2.x

// your detail description 
What's the best way I can debug with thinkjs, like doing some break points that I can watch the params by using IDE such like vscode or webstorm. Can you give me some ideas?

**Comment by lizheming** [comment]
You can debug with vscode or webstorm as you like easily.

**Comment by AkashiX** [comment]
#756 Solution.
