### ISSUE TITLE
多级控制器的目录名如何获取?

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#883]
我项目是按照多级控制器方式部署的,下面是我的路径
`/src/controller/member/user.js  `

**问题:** 我在模板文件里通过命令 `ctx.controller` 获取的是 `member/user`
**目的:** 但我想获取的仅仅是目录名 'member' 而已,
**请问:** 咋样获取?  是否有相关命令?

**Comment by lizheming** [comment]
没有，自行处理把最后一个 controller 去掉就好了。

**Comment by junmaqiang** [comment]
好吧!
