### ISSUE TITLE
使用 thinkjs 3.x 做 app 接口，请问如何优化？

### ISSUE THREAD

**Issue by tumobi** [thinkjs/thinkjs#884]
最近项目使用 thinkjs 3.x 做 api ，不使用 session、cookie、view ，该如何删除相关的配置？

**Comment by lizheming** [comment]
直接去 `src/config/extend.js` 里删除相关配置即可。

**Comment by welefen** [comment]
cookie 操作只是一个方法，不会影响性能。

可以看 extend 和 middleware 配置，根据需要去掉不必要的部分

**Comment by tumobi** [comment]
@welefen @lizheming 谢谢
