### ISSUE TITLE
vscode 不支持 3.0 断点调试

### ISSUE THREAD

**Issue by lluck42** [thinkjs/thinkjs#885]
### ENV

OS Platform:win

Node.js Version:v6.11.3

ThinkJS Version:v3.0

### code

```js
// your code here
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "master+NPM",
            "type": "node",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "runtimeExecutable": "npm",
            "runtimeArgs": [
                "run-script",
                "debug"
            ],
            "port": 9876,
            "sourceMaps": true
        },
        {
            "name": "worker",
            "type": "node",
            "request": "attach",
            "port": 9877,
            "outFiles": [
                "${file}"
            ],
            "sourceMaps": true
        }
    ]
}
### error message
Debugging with legacy protocol because Node.js version could not be determined (Error: connect ECONNREFUSED 127.0.0.1:9877)
```
// your error message here
```
Debugging with legacy protocol because Node.js version could not be determined (Error: connect ECONNREFUSED 127.0.0.1:9877)
### more description

// your detail description 
thinkjs2.0 支持 刷新网页调试，express 支持 直接 F5 调试，thinkjs3.0，只支持调试入口文件。还是坐等出4.0吧 哈哈

**Comment by lizheming** [comment]
close with same #716 and #756
