### ISSUE TITLE
请问logic里面有两种类型的值如何验证

### ISSUE THREAD

**Issue by junmaqiang** [thinkjs/thinkjs#888]
**下面是我的代码**
```
   async indexAction() {
        //  只允许 get 请求类型
        this.allowMethods = 'get';
        // // 定义规则
        let rules = {
            city: {
                int: true, // 需要是 int 型
                int: { min: 1, max: 11000 }, //需要在 10 - 11000 之间
                aliasName: '城市'
            },
        };
        // // 校验规则
        let flag = this.validate(rules);
        // // 判断规则
        if (!flag) {
            // 通过 this.fail 把错误信息以 JSON 格式输出
            return this.fail('validate error', this.validateErrors);
            // 如果出错，返回
            // {"errno":1000,"errmsg":"validate error","data":{"username":"username can not be blank"}}
        }
    };
```

**问题**: 我的city 虽然都是数值类型, 但是还有一个all的情况,要如何写规则?

```
http://127.0.0.1:8360/adminis/user/index?city=1  访问这个没问题
http://127.0.0.1:8360/adminis/user/index?city=10  访问这个没问题
http://127.0.0.1:8360/adminis/user/index?city=100  访问这个没问题
http://127.0.0.1: 8360/adminis/user/index?city=all  访问这个就有问题
```

**目的**: 希望all 和 数值都可以访问

**Comment by lushijie** [comment]
像这种的话建议自己写一个检验规则，检验没有or的判断逻辑




发自网易邮箱大师
在2017年10月01日 12:24，sh_ajunker 写道：

下面是我的代码

   async indexAction() {
        //  只允许 get 请求类型
        this.allowMethods = 'get';
        // // 定义规则
        let rules = {
            city: {
                int: true, // 需要是 int 型
                int: { min: 1, max: 11000 }, //需要在 10 - 11000 之间
                aliasName: '城市'
            },
        };
        // // 校验规则
        let flag = this.validate(rules);
        // // 判断规则
        if (!flag) {
            // 通过 this.fail 把错误信息以 JSON 格式输出
            return this.fail('validate error', this.validateErrors);
            // 如果出错，返回
            // {"errno":1000,"errmsg":"validate error","data":{"username":"username can not be blank"}}
        }
    };


问题: 我的city 虽然都是数值类型, 但是还有一个all的情况,要如何写规则?

http://127.0.0.1:8360/adminis/user/index?city=1  访问这个没问题
http://127.0.0.1:8360/adminis/user/index?city=10  访问这个没问题
http://127.0.0.1:8360/adminis/user/index?city=100  访问这个没问题
http://127.0.0.1: 8360/adminis/user/index?city=all  访问这个就有问题

**Comment by junmaqiang** [comment]
问题解决了,我用的是正则表达式, 代码如下:
```
            city: {
                regexp: /all|\d{1,5}/g,
                aliasName: '城市'
            },
```
