### ISSUE TITLE
Logic层校验问题的一些疑惑和建议

### ISSUE THREAD

**Issue by stylehuan** [thinkjs/thinkjs#895]
### ENV

OS Platform:

Node.js Version:8.4.0

ThinkJS Version:3.0.0

### code

```js
this.allowMethods = 'post';
        // // 定义规则
        let rules = {
            userName: {
                aliasName: '用户名',
                string: true, // 字段类型为 String 类型
                required: true // 字段必填
            }
        };
```

### error message

```
// your error message here
```

### more description
- 上面的`allowMethods` 是无效的，必须要使用`this.rules`.
- 如果使用`this.rules`的话，当请求是不合法时 "msg": "METHOD_NOT_ALLOWED"，目前好像不能自定义。
- 所有`rule`里面多条验证规则的error都是一样的，统一返回`config`下`validateDefaultErrno`，如何进行细节区分？

**Comment by stylehuan** [comment]
目前的做法是在对应的`fail`中根据返回的`msg`重写.

**Comment by lizheming** [comment]
> 上面的 `allowMethods` 是无效的，必须要使用 `this.rules`。

这句实在是没看懂，`this.allowMethods` 是可以正常使用的，你是想说 `rules` 校验无效的话如果是不适用 `this.rules` 赋值的话需要自己手动调用 `this.validate(rules)`。

> 目前的做法是在对应的`fail`中根据返回的`msg`重写。

目前只有 `allowMethods` 的错误被写死了没办法重写，validate 相关的错误可以参考 [自定义错误信息](https://thinkjs.org/zh-cn/doc/3.0/logic.html#toc-212) 进行重写。

> 所有`rule`里面多条验证规则的`error`都是一样的，统一返回`config下validateDefaultErrno`，如何进行细节区分？

一般来说所有的校验错误都是应该是相同类型的，这样前端处理起来也比较方便。而且不知你以什么维度去区分错误号，如果是根据不同的校验规则不同的错误号的话，那多个校验规则报错你如何处理？当然如果萤是要区分的话可以自行调用 `this.validate(rules)` 方法后根据 `this.validateErrors` 的返回来做判断，然后自行调用 `this.fails(validateErrno, errMsg, this.validateErrors)` 返回结果。

**Comment by lushijie** [comment]
ping @stylehuan

**Comment by lushijie** [comment]
Close the issue for no responding.

**Comment by lushijie** [comment]
Close the issue for no responding.
