### ISSUE TITLE
公司业务需要基于thinkjs为后台开发微信小程序，有websocket的业务需求，求助作者

### ISSUE THREAD

**Issue by qq781548819** [thinkjs/thinkjs#897]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description 

thinkjs基于socket.io封装了的websocket无法使用微信小程序连接。

**Comment by lushijie** [comment]
Now, you can try [think-websocket-ws](https://github.com/thinkjs/think-websocket-ws) . This lib is now in alpha version.

**Comment by lushijie** [comment]
ping @qq781548819
