### ISSUE TITLE
controller和model都有子目录，modelInstance可能不是用子目录下的model实例化

### ISSUE THREAD

**Issue by yuanqu1208** [thinkjs/thinkjs#898]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by welefen** [comment]
@yuanqu1208  通过 URL 获取的只是资源名称，并没有层级结构。有子目录的情况可以手工在子类中重新指定下 modelInstance
