### ISSUE TITLE
服务端口生效早于think.beforeStartServer

### ISSUE THREAD

**Issue by libery** [thinkjs/thinkjs#900]
## DESC
thinkjs 配置信息放在zk中，在think.beforeStartServer中读取并设置到think.config，但是设置的端口不生效，通过日志发现使用服务端口要早于think.beforeStartServer执行完。

### ENV

OS Platform:
macos

Node.js Version:
v8.0.0
ThinkJS Version:
v3.2.1
### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lizheming** [comment]
https://github.com/thinkjs/thinkjs/blob/544106ca857b81acd2df61f6d12e01eabca6e8d7/lib/application.js#L131

因为需要设置 cluster 所以优先读取了。你这种需求直接自己在 production.js 执行实例化 Application 的时候写入到文件或者把配置写入到环境变量，内部通过读取环境变量来做比较好。

**Comment by welefen** [comment]
@libery  升级 `thinkjs@3.2.2`
