### ISSUE TITLE
think-mongo错误

### ISSUE THREAD

**Issue by brucecodezone** [thinkjs/thinkjs#901]
## DESC
服务压测时，接口已经挂掉，
但是日志显示一直是数据库连接操作

### ENV

OS Platform: win10

Node.js Version:8.1

ThinkJS Version:3.0

### code

```
pm2最后的日志，接口已经无法访问，但是pm2 显示服务还是运行，并且日志如下：
0|producti | [2017-10-10 17:12:43.952] [14947] [INFO] - mongodb://127.0.0.1:27017/gatedlaunch
0|producti | [2017-10-10 17:12:43.956] [14947] [INFO] - mongodb://127.0.0.1:27017/gatedlaunch
0|producti | [2017-10-10 17:13:10.458] [14948] [INFO] - mongodb://127.0.0.1:27017/gatedlaunch
0|producti | [2017-10-10 17:13:10.468] [14948] [INFO] - mongodb://127.0.0.1:27017/gatedlaunch
0|producti | [2017-10-10 17:13:10.472] [14948] [INFO] - mongodb://127.0.0.1:27017/gatedlaunch
0|producti | [2017-10-10 17:13:52.789] [14960] [INFO] - mongodb://127.0.0.1:27017/gatedlaunch
0|producti | [2017-10-10 17:13:52.847] [14948] [INFO] - mongodb://127.0.0.1:27017/gatedlaunch
0|producti | [2017-10-10 17:13:53.989] [14947] [INFO] - mongodb://127.0.0.1:27017/gatedlaunch
。。。。。。。
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by brucecodezone** [comment]
@welefen

**Comment by welefen** [comment]
接口已经挂掉 - 有具体的错误信息么？

**Comment by brucecodezone** [comment]
@welefen 查到原因了，有一个接口的逻辑比较复杂，中间进行了六七次的mongo数据库操作，压测时，io操作太多，cpu占内存特别高，错误信息哪里，pm2日志显示 mongo connection close。目前正在简化操作，并加入redis缓存，

**Comment by welefen** [comment]
@brucecodezone OK

**Comment by brucecodezone** [comment]
@welefen 经过排查，think-mongo插件，在压测和线上压力较大情况下，出现的问题：logic层仍然可以运行但,controller层出错，日志一直打印 mongod：//127.0.0.1/xxx连接信息，在用户层看，服务已经挂掉，但pm2显示服务online,服务器cpu占用慢慢升高,最终基本达到90%+；加入redis缓存后，情况缓解；

最终解决方法：使用think-mongoose，不使用redis,就可以稳定运行，每个进程服务器cpu占用基本不超过5%；

本人是一个nodejs新手，错误的具体信息，暂无法知道，希望大大们可以测试看看情况。

希望改进的建议：
1.redis连接无法打印连接日志，导致线上服务很难知道Redis连接不上的具体问题（希望日志插件改善）
2.development  production两个开发环境不能满足环境配置要求，一般都有开发、测试、预发、生产等环境，希望加入自定义环境配置
