### ISSUE TITLE
开启静态资源gzip无效

### ISSUE THREAD

**Issue by hyingreborn** [thinkjs/thinkjs#903]
## DESC
src/common/config/middleware.js中配置如下：
```js
{
    handle: 'resource',
    enable: true,
    options: {
      root: path.join(think.ROOT_PATH, 'www'),
      publicPath: /^\/(static|upload|html|favicon\.ico|robots\.txt|logo\.png)/,
      gzip: true
    }
  }
```
重启项目后，在chrome控制台的并没有看到gzip被开启，响应头中没有content-encoding: gzip 
### ENV

OS Platform: Win10/Mac OSX

Node.js Version: 6.x

ThinkJS Version: 3.2.2

**Comment by welefen** [comment]
目前 gzip 选项并不是直接支持 gzip 的功能，具体解释为：

`gzip: Try to serve the gzipped version of a file automatically when gzip is supported by a client and if the requested file with .gz extension exists. default is false.`

需要有对应的 .gz 文件配合

**Comment by welefen** [comment]
@hyingreborn 现在静态资源建议交给 nginx 来处理

**Comment by hyingreborn** [comment]
@welefen 了解了~感谢！
