### ISSUE TITLE
thinkjs3.0 断点调试时启动不了服务

### ISSUE THREAD

**Issue by andrewstz** [thinkjs/thinkjs#904]
## DESC
thinkjs3.0 断点调试时启动不了服务，更进不了controller。已经研究过 node_modules/thinkjs/lib/application.js、  node_modules/think-cluster/lib/master.js、 loader.js、bootstrap.js 。。。。等 代码。 但是就是搞不清楚为何 node development.js直接运行可以，调试模式下的 node --inspect-brk=16851 development.js 却不行。

### ENV

OS Platform: 
osx

Node.js Version: 
8.6.0

ThinkJS Version:
3.0

### code

```js
// your code here
```

### error message

```
没有报任何错误
```

### more description

// your detail description

**Comment by welefen** [comment]
https://github.com/thinkjs/thinkjs/issues/716#issuecomment-337449445
