### ISSUE TITLE
多模块下无法用命令行创建service

### ISSUE THREAD

**Issue by chj-damon** [thinkjs/thinkjs#905]
### ENV

OS Platform: window10 x64

Node.js Version: v8.7.0

ThinkJS Version: 3.2.2

### code

```js
thinkjs new demo --mode=module
cd demo
thinkjs module admin
thinkjs service token
```

### error message

```
current path is not thinkjs project
```

### more description
cd到模块目录下也是一样。
如果是非多模块项目，是可以执行的：
thinkjs new demo
thinkjs service token
结果如下：
```
create: src\service
create: src\service\token.js
```

**Comment by chj-damon** [comment]
补充：
多模块下controller, model, logic等命令都无效。报错都相同：
current path is not thinkjs project

**Comment by lizheming** [comment]
目前需要带上 `--mode=module` 执行命令才行

**Comment by denvey** [comment]
带上模块名是可以的
 thinkjs service admin/token

**Comment by chj-damon** [comment]
@lizheming thinkjs service admin/token --mode=module
是这样执行吗？
