### ISSUE TITLE
不用ES6/7是否能用thinkjs？

### ISSUE THREAD

**Issue by bi-kai** [thinkjs/thinkjs#906]
文档一开始就提及async/await  ts babel等ES6/7的技术，目前项目和个人计划等原因还没拍到这部分新特性，集成了前端全栈几乎全部新的技术和库，如果不会这些，是不是就不能用thinkjs？
我目前还是处在MEAN自己搭框架的阶段，感觉thinkjs技术门槛很高。

**Comment by welefen** [comment]
@bi-kai 可以不用 async/await 这些新的特性，但这样处理异步请求等情况时会麻烦很多。ES next 是标准规范，不是一些组件、库，建议你还是学习一下。并且现在招聘基本上也都是要求会这些了。
