### ISSUE TITLE
考虑支持下GraphQL不？

### ISSUE THREAD

**Issue by hyingreborn** [thinkjs/thinkjs#907]
刚看到GraphQL中文官网上线了~

git上搜了一个：
https://github.com/apollographql/apollo-server

**Comment by welefen** [comment]
@hyingreborn 暂时还没有考虑，你可以帮忙弄个模块

**Comment by lizheming** [comment]
It's very simple for add GraphQL support in ThinkJS 3, you can read more in this article: [《GraphQL in Action》](https://zhuanlan.zhihu.com/p/40348143)
