### ISSUE TITLE
thinkjs new demo -w -t 模式，npm start 启动不能生成app文件夹

### ISSUE THREAD

**Issue by c350156378** [thinkjs/thinkjs#910]
## DESC
thinkjs new demo -w -t 模式，npm start 启动不能自动生成app文件夹
手动执行tsc后没有问题了。

### ENV

OS Platform:
win7 64bit
Node.js Version:
8.6.0
ThinkJS Version:
3.2.2
### code

```js
// development.js
const Application = require('thinkjs');
const watcher = require('think-watcher');

const instance = new Application({
  ROOT_PATH: __dirname,
  watcher: watcher,
  env: 'development'
});

instance.run();


### error message

```
// your error message here
```

### more description

// your detail description

**Comment by welefen** [comment]
提供下 development.js 的内容

**Comment by welefen** [comment]
typescript 下不支持 -w 的模式，创建项目去掉 -w 再试下

**Comment by c350156378** [comment]
嗯，试了下。可以了。看到develepment.js的变化了， 之前只是想着去掉babel编译。
