### ISSUE TITLE
ThinkJS 是否支持转发 http 请求？

### ISSUE THREAD

**Issue by zheeeng** [thinkjs/thinkjs#911]
## DESC

有些请求要使用别人提供的服务，能否在 Controller 里把请求转发到其它服务器，Thinkjs 仅提供记录请求、CORS 服务。希望是 proxy 的方式。

### ENV

ThinkJS Version: 2.2

**Comment by welefen** [comment]
@zheeeng 可以自己弄个中间件处理下就可以了

**Comment by wurining** [comment]
[think-fetch](https://github.com/thinkjs/think-fetch)

**Comment by zheeeng** [comment]
@wurining Great job

**Comment by zheeeng** [comment]
此问题可以用 request + pipe 解决

const request = require('request')
xxxAction (req, res) => request('url').pipe(res)
