### ISSUE TITLE
没有类似Thinkphp中url生成的功能么？

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#914]
具体场景是这样的:比如微信登陆，需要传递一个回跳地址，所以需要一个完整的URL地址，现在的方法是用 ctx中的protocol host port path之类的自己拼接，有点麻烦
希望后续能增加这类功能。

**Comment by lizheming** [comment]
https://thinkjs.org/zh-cn/doc/3.0/context.html#toc-b28 这个？

**Comment by KuoKongQingYun** [comment]
@lizheming 不是获取当前的地址，是生成新的地址，比如说我在/home/index 的action里要生成 /user/index的URL地址，虽然正常情况下可以直接this.redirect('/user/index');
但是，如果需要完整地址的话（比如Oauth认证回跳），就得需要this.ctx.orgin+'/user/index'，如果还需要带参数的话，就得this.ctx.orgin+'/user/index'+'?xxx=xxx&xxxx=xxxx",感觉很冗长，而且可读性差，
Thinkphp有专门生成URL地址的工具函数，比如:
https://www.kancloud.cn/manual/thinkphp5/118041

**Comment by lizheming** [comment]
https://nodejs.org/dist/latest-v8.x/docs/api/url.html 我觉得你可能需要这个，看了下 ThinkPHP 的封装并没有觉得非常方便，不如直接用原生 API 比较好，语义化的同时减少了开发记忆接口的成本。
