### ISSUE TITLE
thinkjs3.0 如何支持HTTPS的呢

### ISSUE THREAD

**Issue by happyshrm** [thinkjs/thinkjs#917]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description 
您好!请问thinkjs3.0是如何支持https的呢？

**Comment by welefen** [comment]
https://thinkjs.org/zh-cn/doc/3.0/bootstrap.html#toc-dc4

不过 HTTPS 还是建议通过 nginx 来做

**Comment by happyshrm** [comment]
不支持pfx文件的吗

**Comment by happyshrm** [comment]
您好！刚刚报了这种错误,您能帮我排除一下吗？
TypeError: Cannot read property 'listen' of undefined

config.js的配置是如下：

const https = require('https');
const fs = require('fs');
const path = require('path');

let dir = path.join(__dirname+'/../..');
const options = {
    pfx: fs.readFileSync(dir+'/keys/server.pfx'),
    passphrase: '123456'
};

module.exports = {
    createServer: function (callback) {
        https.createServer(options, callback);
    },
    port: 9090
    
};

**Comment by welefen** [comment]
`https.createServer` 前面要加个 return，文档里漏写了。

**Comment by happyshrm** [comment]
sorry,那天用nginx实现完之后就忘记上来github看回复了。。。。

**Comment by happyshrm** [comment]
我再试试看

**Comment by happyshrm** [comment]
没有报错了，但是开启的服务不会响应，下面又是正常的
> thinkjs-application@1.0.0 start D:\company_project\tentacle-dc-service
> node development.js

[2017-10-27 09:17:48.782] [2472] [INFO] - Server running at http://127.0.0.1:9090
[2017-10-27 09:17:48.794] [2472] [INFO] - ThinkJS version: 3.2.2
[2017-10-27 09:17:48.795] [2472] [INFO] - Enviroment: development
[2017-10-27 09:17:48.798] [2472] [INFO] - Workers: 4

**Comment by happyshrm** [comment]
thinkjs3.0开启了四个工作进程之后，一旦修改某些文件，有些时候是没有实时更新的，虽然控制台已经显示已编译了，必须得通过重启服务才可以，这是问题是多个进程之间没有共享的内存导致的吗？

**Comment by welefen** [comment]
@happyshrm 1、用 Node 里原生的 https 模块创建服务看是否可以响应。 2、多等一会也不会生效么？

**Comment by happyshrm** [comment]
1，我估计得深入理解你们的源码架构才能解决了，不然可能真的没法解决
2，多等一会儿也是不生效的
关于nodejs，我也是刚接触不久，也是是我个人的原因导致的，后面我补好基础再看你们的源码吧！现在先用nginx来解决。多谢了！

**Comment by makeco** [comment]
@happyshrm 刚才在自己的腾讯云服务器上测试了, 目前仍可以访问https://www.makeco.cn

相关配置如下：
* OS Platform: ubuntu 16.04
* Node.js Version: 7.7.2
* ThinkJS Version: 3.2.3
* [ssl free](https://www.sslforfree.com)提供证书

代码如下：
```javascript

// default config
const https = require('https');
const fs = require('fs');
const path = require('path');

const options = {
  key: fs.readFileSync(path.join(think.ROOT_PATH, 'src/config/ssl/private.key')),
  cert: fs.readFileSync(path.join(think.ROOT_PATH, 'src/config/ssl/certificate.crt'))
};

module.exports = {
  port: 443,
  workers: 1,
  createServer: function(callback) {
    return https.createServer(options, callback);
  }
};
```
注意事项：
* 出现 bind eacces 异常，加sudo
* https默认使用443，确保没有被墙
