### ISSUE TITLE
动态设置配置后控制器中无法获取到数据?

### ISSUE THREAD

**Issue by mxh861001** [thinkjs/thinkjs#918]
### ENV

OS Platform: windows

Node.js Version:8.3

ThinkJS Version:3.2

### worker.js

```js
think.beforeStartServer( async() =>{
  const $config = {"name":"哈哈","name2":"呵呵"};
  think.config('sysConfig', $config);
  console.warn(think.config('sysConfig'))
});
```
### controller (返回undefined)

``` js 
  async indexAction() {
    console.warn(this.config('sysConfig'))
    return this.display();
  }
```

### html (为空)

``` js 
  {{config.sysConfig|dump}}
```

### 多模块的情况下
控制器中只能使用think.config获取到数据?模板中如何获取到数据?

**Comment by welefen** [comment]
@mxh861001 项目是单模块项目，还是多模块项目？

**Comment by mxh861001** [comment]
@welefen 多模块项目

**Comment by welefen** [comment]
@mxh861001 取不到是因为 2 个地方的模块名不一样。设置的时候指定模块名就可以了。

```js
think.config('sysConfig', $config, 'home')
```

**Comment by mxh861001** [comment]
@welefen 那如果我多个模块需要获取呢?这样不是很不方便了?

**Comment by 2681137811** [comment]
@welefen 顺便问一下默认模块一定要是 home 么，可否修改

**Comment by lushijie** [comment]
可以修改默认模块，在 think-router middlerware 配置中，具体配置可以查看 [think-router](https://github.com/thinkjs/think-router) @2681137811

**Comment by welefen** [comment]
@mxh861001 我们支持下可以批量设置模块配置的功能

**Comment by welefen** [comment]
@mxh861001 升级 `think-config@1.1.0`，已经支持批量设置配置：

```js
think.config('name', value, true); // 设置所有模块的配置，只在多模块下生效
think.config('name', value, 'home,admin'); //指定多个模块设置配置，只在多模块下生效
```

**Comment by hyingreborn** [comment]
https://thinkjs.org/zh-cn/doc/3.0/config.html#toc-b5b
@welefen 官方文档中是否能修改一下，明示一下think.config方法的第三个参数？或者默认不传第三个参数则默认为所有模块。最近碰到这个问题找了好久，才在这里找到了答案。

**Comment by lizheming** [comment]
@hyingreborn 你直接帮忙修改下文档不是更方便咩 😋
