### ISSUE TITLE
mongo的连接数越来越大。

### ISSUE THREAD

**Issue by houxiaozhao** [thinkjs/thinkjs#919]
## DESC
程序每查询一次mongo都会建立一个连接吗？
我开了个命令行监控Mongo的运行状态，发现当前打开的连接越来越多。
这样应该是不正常的吧，用不了多久就爆了！
连接会不会自动断开，还是可以配置最大连接数啊？？
### ENV

OS Platform:win10

Node.js Version:6.11.4

ThinkJS Version:3.2.3

### more description

当我退出程序的时候，连接就自动断开了。
![tim 20171026113702](https://user-images.githubusercontent.com/14978325/32033925-3165e7fa-ba42-11e7-87f7-7edd7e1b67f4.png)

**Comment by brucecodezone** [comment]
我也遇到相同的问题，官方的think-mongo有问题，使用think-mongoose吧，我的问题详情：https://github.com/thinkjs/thinkjs/issues/901

**Comment by welefen** [comment]
@houxiaozhao 已经找到原因，会尽快修复。

**Comment by welefen** [comment]
@houxiaozhao 升级 `think-mongo@1.0.3`

**Comment by houxiaozhao** [comment]
完美，谢谢你
