### ISSUE TITLE
think-mongo聚合操作支持开启allowDiskUse吗

### ISSUE THREAD

**Issue by shihuojian** [thinkjs/thinkjs#921]
目前使用聚餐操作大数据提示需要开启allowDiskUse，但是开启后还是一样？

**Comment by welefen** [comment]
@shihuojian 提供具体的代码

**Comment by shihuojian** [comment]
@welefen 如下，用Robomongo客户端去运行这段是可以的，但是线上确一直报错，提示需要开启allowDiskUse；

` let result =  await this.mongo('weChatFans').aggregate([
      { $match:{appId:{$in:['wxddb7ead93bcb766c','wx7899810b624ee9f4']}}},
      { $group: {
        _id: { nickname:"$nickname",sex:"$sex",city:"$city",province:"$province",country:"$country"},
        uniqueIds: { $addToSet: '$appId' },
        count: { $sum: 1 }
      }},{
        $match:{
          count: {$gt: 1},     //返回大于1的结果
        }
      }
    ],{ allowDiskUse: true });`

**Comment by shihuojian** [comment]
@welefen 我测试十几万的是正常的，大点就保存提示需要开启allowDiskUse:true,但是明明开启了还是那样

**Comment by welefen** [comment]
这个会调用 https://github.com/thinkjs/think-mongo/blob/master/src/query.js#L272，然后会调用 mongodb 模块里对应的 aggregate 方法，你可以调试下。

**Comment by shihuojian** [comment]
@welefen 问题解决了 我把think-mongo return中aggregate  return fn(options);改为return fn(options,{allowDiskUse: true});可以了，相应的模块是否能改下？

**Comment by welefen** [comment]
@shihuojian  已经修复，升级 `think-mongo@1.0.4`

**Comment by houxiaozhao** [comment]
大佬，更到1.0.4 使用聚合的时候出错了，1.0.3就没问题

**Comment by welefen** [comment]
@houxiaozhao 错误信息是什么？使用方式还是下面这样么？

```js
let result =  await this.mongo('weChatFans').aggregate([
      { $match:{appId:{$in:['wxddb7ead93bcb766c','wx7899810b624ee9f4']}}},
      { $group: {
        _id: { nickname:"$nickname",sex:"$sex",city:"$city",province:"$province",country:"$country"},
        uniqueIds: { $addToSet: '$appId' },
        count: { $sum: 1 }
      }},{
        $match:{
          count: {$gt: 1},     //返回大于1的结果
        }
      }
    ],{ allowDiskUse: true });
```

**Comment by houxiaozhao** [comment]
这个是错误信息
![tim 20171028091229](https://user-images.githubusercontent.com/14978325/32129902-7651385e-bbc0-11e7-9a3b-d3156ecc9967.png)
这个是我写的查数据库
```javascript
  async getFormById(form_instance_id) {
        return await this.model('form_instance').aggregate([{
            $match: {
                _id: new ObjectID(form_instance_id)
            }
        }, {
            $lookup: {
                from: 'form_list_instance',
                localField: '_id',
                foreignField: 'form_instance_id',
                as: 'lists'
            }
        }, {
            $lookup: {
                from: 'form_list_key_instance',
                localField: 'lists._id',
                foreignField: 'form_instance_list_id',
                as: 'keys'
            }
        }, {
            $lookup: {
                from: 'form_list_key_template',
                localField: 'keys.form_template_key_id',
                foreignField: '_id',
                as: 'templates'
            }
        }]);
    };
```

**Comment by welefen** [comment]
@houxiaozhao  升级 `think-mongo@1.0.5` 试下

**Comment by wurining** [comment]
看讨论笑死我了🤣，工程师们的日常，写新的Bug

**Comment by welefen** [comment]
@wurining 哈哈，越着急越容易出错

**Comment by welefen** [comment]
@shihuojian 问题解决了么？

**Comment by shihuojian** [comment]
在解决了，可以关闭

发自我的 iPhone

在 2017年11月2日，11:36，Welefen Lee <notifications@github.com<mailto:notifications@github.com>> 写道：


@shihuojian<https://github.com/shihuojian> 问题解决了么？
