### ISSUE TITLE
多模块下面，路由设置不生效

### ISSUE THREAD

**Issue by qipiaoyang** [thinkjs/thinkjs#922]
### ENV

OS Platform:  window10

Node.js Version:  8.0.0

ThinkJS Version: 3.0

### code

```js

//router.js
module.exports = [
    ['/','home/index/index']
];
```

### error message

```
NotFoundError: url `/` not found.
```

### more description

// your detail descripted
单模块下面没问题，多模块路由配置不生效，显示找不到

**Comment by Messilimeng** [comment]
同上

**Comment by qipiaoyang** [comment]
##因为thinkjs是先找的controller再去找的route，所以这边主要问题是controller里面没有index.js入口。

**Comment by qipiaoyang** [comment]
##     从thinkjs的运行来看是先找的controller，然后再执行route，个人感觉是controller里面少了个index.js

##     解决办法是
![image](https://user-images.githubusercontent.com/20981956/32094518-98ceb124-bb32-11e7-9b90-24557f7d1568.png)

```
module.exports = class extends think.Controller {
    async indexAction() {
      return this.redirect('/admin/index');
    }
  };
```

**Comment by welefen** [comment]
@qipiaoyang 这是默认对首页的地址做了优化，直接提前解析了。 https://github.com/thinkjs/think-router/blob/master/router.js#L255

不需要这个功能的话，可以在 `src/config/middleware.js` 里配置 router 中间件的 options: 

```js
{
    handle: 'router',
    options: {
        optimizeHomepageRouter: false
    }
}
```

**Comment by welefen** [comment]
@qipiaoyang 问题解决了么？

**Comment by qipiaoyang** [comment]
解决了，明白什么意思了
