### ISSUE TITLE
thinkjs new demo -w无效

### ISSUE THREAD

**Issue by yuu2lee4** [thinkjs/thinkjs#925]
## DESC
创建出来的代码里面还是有babel
### ENV

OS Platform: macos10.13

Node.js Version: 8.8.1
 
ThinkJS Version:3.2.3
![c3904328907e3829f2ae9944f832e473](https://user-images.githubusercontent.com/8046366/32130255-89e92294-bbc7-11e7-97a0-d795728a692f.jpg)

**Comment by wurining** [comment]
你用的think-cli版本应该是2.0.0吧，更新后貌似new命令只有-m;-c;-h这三个参数可以用了，文档在>>>[此](https://github.com/thinkjs/think-cli#new)
看新的readme文档，推测应该是想把不同的项目结构变成模板来下载，无babel转义这种应该一会变成一种模板，看[#930](https://github.com/thinkjs/thinkjs/issues/930)

**Comment by yuu2lee4** [comment]
@wurining   谢谢

**Comment by welefen** [comment]
@yuu2lee4 下周二会发布全新的 think-cli 版本

**Comment by lushijie** [comment]
请 npm install think-cli@latest --save-dev 替换旧 cli。 如遇到新问题请提 issue。
