### ISSUE TITLE
创建typescript项目错误

### ISSUE THREAD

**Issue by chigco** [thinkjs/thinkjs#928]
### ENV

OS Platform: 
mac
Node.js Version:
8.4
ThinkJS Version:
3.2
Ide:
VS Code
### code

controller/index.ts

```js
return this.display();
```

### error message

```
[ts] Property 'display' does not exist on the type 'default'.
```
同样的，添加 
```
thinkjs controller user -r
```
之后，controller/rest.ts

```js
modelInstance: Think.Model;
```

### error message

```
[ts] Namespace 'ThinkJS' has no exported member  'Model'
```

### more description

// your detail description

**Comment by SijieCai** [comment]
请更新 think-cli 到 2.0 版本，生成项目 thinkjs new project-name typescript.
在 2.0 对 TypeScript 更加优雅，并且和老版本实现方式完全不一样。
