### ISSUE TITLE
model没有提供加锁的操作么？希望在链式调用里加入加锁的方法

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#929]
我查了文档，里面貌似没有说怎么在事务里加锁，thinkphp对模型的链式调用里有个lock()就是加锁用的。
thinkjs只能执行原生的sql ，在查询语句里加入for update么？感觉有点不方便啊，用thinkjs的原因之一就是提供thinkphp一样的链式调用，自己写sql容易出现一些意料之外的问题。

**Comment by KuoKongQingYun** [comment]
找到了 在option里面，文档里貌似没写，我是从源码里找到的……

**Comment by KuoKongQingYun** [comment]
我是从php 、python转过来的
自己搜了一下相关信息，发现nodejs里数据库操作不能用锁，那么请问各位是如何处理数据完整性问题的呢？

**Comment by welefen** [comment]
@KuoKongQingYun 支持的，用 `this.lock(true)`。文档遗漏了，我们补充下。

**Comment by welefen** [comment]
https://thinkjs.org/zh-cn/doc/3.0/relation_model.html#toc-cee 文档加上
