### ISSUE TITLE
thinkjs-cli v2.0.0 无法创建TS项目&&如何创建多模块TS项目

### ISSUE THREAD

**Issue by wurining** [thinkjs/thinkjs#930]
## DESC
如图，按照文档创建ts项目不成功，没有在根目录创建`tsconfig.json`文件，当使用命令行增加新的Controller也没有出现对应的ts文件，另外`eslint`文件和`gitignore`文件名前面缺了‘.’, 插件加载不到这个文件。
![image](https://user-images.githubusercontent.com/26198634/32142523-d2865496-bc66-11e7-8676-48ad740216c9.png)

### ENV

OS Platform: MacOS 10.13
Node.js Version: v8.3.0
ThinkJS Version: lastest

**Comment by wurining** [comment]
已经解决>>>[点击查看](https://github.com/thinkjs/think-cli#new)
thinkjs new 命令第二个参数可以添加官方模板，文档未更新。
官方模板可以用thinkjs list查看。

**Comment by SijieCai** [comment]
eslint文件和gitignore文件名前面缺了‘.’ 的问题已经修复

**Comment by CloudnuY** [comment]
![image](https://user-images.githubusercontent.com/14636247/32647922-425034f8-c5b9-11e7-852f-d1446e1af1c1.png)

> eslint文件和gitignore文件名前面缺了‘.’ 的问题已经修复

最新的think-cli创建的项目里这个问题还存在

**Comment by wurining** [comment]
@CloudnuY 这个要不先自己加一下把。可以问问 @SijieCai
