### ISSUE TITLE
刚刚 cookie 赋值后 链接再次进来就获取不到了

### ISSUE THREAD

**Issue by Messilimeng** [thinkjs/thinkjs#934]
### ENV

OS Platform:
liunx 
Node.js Version:
8.X
ThinkJS Version:
3.2.3

cookie 赋值后 链接在此进来就获取不到了
![image](https://user-images.githubusercontent.com/12272166/32162041-8f356aa6-bd92-11e7-9ea7-777b23264141.png)

**Comment by lushijie** [comment]
可否发一下cookie adapter 的配置，这样不太好定位问题
