### ISSUE TITLE
scheme疑问

### ISSUE THREAD

**Issue by yuu2lee4** [thinkjs/thinkjs#935]
## DESC
按照官方例子报错了
### ENV

OS Platform: macos

Node.js Version: 8.8.1

ThinkJS Version: 3.2.3

### code

```js
module.exports = class extends think.Model {
  get schema() {
    return {
      type: { // 字段名称
        type: 'varchar(10)',
        default: 'small'
      },
      create_time: {
        type: 'datetime',
        default: () => think.datetime() // default 为一个函数
      },
      score: {
        type: 'int',
        default: data => { // data 为添加/更新时的数据
          return data.grade * 1.5;
        }
      }
    }
  }
}

const insertId = await model.add({
      type: 'test',
      grade: 20
 });
```

### error message
SQL: INSERT INTO `think_index` (`type`,`create_time`,`score`,`grade`) VALUES ('test','2017-10-30 21:54:57',NaN,20), Time: 5ms
{ Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'field list'
```
// your error message here
```

### more description

// your detail description 
这里score的值是个NAN

**Comment by welefen** [comment]
升级 `think-model-mysql@1.0.6`
