### ISSUE TITLE
getField第二个参数为true的时候一些不方便之处

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#937]
getField第二个参数为true的时候，根据文档是直接返回字段的单个值，
但我发现如果没有找到的情况下，返回的却是[ ]，个人认为这是个“很奇怪的设定”.
1. 从含义上来讲，既然是获取单个值，为什么在没找到的情况下返回的是个数组呢？
2. 这导致了一个困扰，接下来我该如何判断是否select到数据:
```js
let result = await xxxModel.where(……).getField('xxx',true);
if(result)
{
      //不行，因为[ ]是真值，所以无论如何都会进来
      deal(result);
}
else
{

}
```
```js
let result = await xxxModel.where(……).getField('xxx',true);
if(result != false) 
{
     //如果读取的值是null或者空字符串，本来应该进来的，但又进不来了
     deal(result);
}
else
{

}
```
```js
let result = await xxxModel.where(……).getField('xxx',true);
if(result == []) 
{
      //这里永远进不来了，因为[] = [] 为false
}
else
{
      deal(result);
}
```
……（其它的写法更奇怪了）
我建议是在第二个参数为true的情况下，如果没找到，就返回false或者null，null的话可能会和数据库里的null有点混淆，返回false应该是个不错的选择，因为很多数据库里没有 类型为bool的数据，就算有，也是数字形式（比如mysql）。
如果没读取到数据，返回的是false的话，
就能通过 result === false 来“肯定”没有select到数据了。

**Comment by makeco** [comment]
@KuoKongQingYun 推荐使用think.isEmpty方法，判断对象是否为空， undefined, null ,'', NaN, [], {}, 0, false 为 true，其他为 false。

**Comment by KuoKongQingYun** [comment]
@makeco 没注意有这个方法，谢谢提醒。
但问题的第一点还是很诡异，我看了一下对应的源码，应该是一处逻辑的疏忽

**Comment by welefen** [comment]
@KuoKongQingYun 多谢建议，取一个值如果没有的话应该返回 `undefined`

**Comment by welefen** [comment]
https://github.com/thinkjs/think-model/commit/d3d4c460ebcf8f8bd9fcdff9e434072070dd46d0
