### ISSUE TITLE
如何给production设置不同的数据库？

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#939]
目前我的做法是吧adapter.js里mysql相关的部分复制一份到config.production.js里，
还包含了
const mysql = require('think-model-mysql');
这样做合理么?

**Comment by KuoKongQingYun** [comment]
e额 知道了 adapter 可以支持 adapter.production.js

**Comment by welefen** [comment]
@KuoKongQingYun 可以把差异的配置在 `adapter.[env].js` 里，会自动跟 `adapter.js` 进行合并
