### ISSUE TITLE
typescript项目提示和实际对不上

### ISSUE THREAD

**Issue by chigco** [thinkjs/thinkjs#940]
### ENV

OS Platform:
Win7
Node.js Version:
v6.11
ThinkJS Version:
3.2.3
### code
在logic.ts中
```js
// your code here
return this.fail('validate error', this.validateErrors);
```

### error message

```
// your error message 
[ts] Property 'fail' does not exist on type 'default'.
anyhere
```

### more description
虽然报错了，但是运行却是没问题的。
类似的问题很多，提示错误，但是编译后可以跑。
// your detail description

**Comment by chigco** [comment]
```js
// your code here
think.config
```
也是如此。有些核心东西缺失的，我自己加上去了，
但是，比如，额外的fetch这个模块，查看模块没有附带相关的.d.ts，我自己增加一个新的Fetch.d.ts，那么，我放在哪里让ide识别比较好呢？和系统框架没有关系的，不想直接在thinkjs下的index.d.ts中增加

**Comment by chigco** [comment]
添加WebSocket支持后，在Controller中无任何对应方法的代码提示，也是需要自己来添加

**Comment by SijieCai** [comment]
你的 cli 版本是多少？

**Comment by SijieCai** [comment]
cli 1.1 生成的 TypeScript 方式是第一版，在 cli 2.0 后改进了的对 TypeScript 的支持。

用这个方式生成项目（cli 2.0） ：   thinkjs new project-name typescript

**Comment by SijieCai** [comment]
在新的TypeScript 项目结构下，每个extend 或者插件的 d.ts 在自己项目里定义，并用
declare module ‘thinkjs' {...}  合并接口。
在你自己的项目里，如果需要获得提示，需要在   src/index.ts 文件里面添加比如：
import 'think-websocket';
// import <other-think-module>;
这样相关的定义就会自动添加到对应的extend 对象里。

**Comment by SijieCai** [comment]
还有几个extend 的模块没有添加具体的 index.d.ts，会在近期加上

**Comment by chigco** [comment]
@SijieCai 是这样的。添加插件可以。
现在我增加了一个模型，那么，对应具体的xxx.d.ts也是需要我来增加是不是。
现在目录是这样
.\model\xxxx.ts
.\model\xxxx.d.ts

在xxxx.d.ts中：

declare module 'thinkjs' {
    export interface xxxx extends Model {
        addxxxx(): void;
    }
}

那么我应该如何加载这个d.ts来获得提示呢？
