### ISSUE TITLE
let http = require('http'); 

### ISSUE THREAD

**Issue by zhoutao1988** [thinkjs/thinkjs#941]
### ENV

OS Platform:10.12.1 (16B2555)

Node.js Version:v8.4.0

ThinkJS Version: v2.2.23

### code

```js
// your code here
```
var http = require('http');
indexAction(){
    console.log(http.url);
    console.log(http.method);
    console.log(http.pathname);
    return this.display();
  }
### error message

输出了三个undefined
```
// your error message here
```

### more description

// your detail description 
本人刚学习thinkjs
不知道是使用方法不对，还是有模块没有安装

**Comment by welefen** [comment]
action 里直接 `this.http.xxx`，另外建议用 ThinkJS 3.x 的版本

**Comment by zhoutao1988** [comment]
@welefen 
做前端好几年了，感觉一直是一个人在战斗

我自学路径从html>query>ExtJs>Angluarjs>微信小程序，最近打算用nodejs做中间件，学习了thinkjs

这是我离大神最近的一次了，能推荐几本关于前端的书籍，社区，或者您比较看好的前端技术吗

**Comment by lushijie** [comment]
- 针对学习教程可以去知乎搜一下里面好多推荐，还可以订阅一些定期更新的技术周刊（请关注我团周刊

 [奇舞周刊](https://weekly.75team.com/) ）。 

- 技术无所谓好坏，看什么适合你，什么适合业务，关键是自己能从中学到一些东西，既然存在就有诞生的理由，如果没落就一定有不好的东西值得我们去避免。基础一定要夯实！

- 你可以投简历，如果来了我司就可以和你心中的大神坐在一起撸代码了✧(≖ ◡ ≖✿)
