### ISSUE TITLE
多模块项目脚手架的问题

### ISSUE THREAD

**Issue by matinjugou** [thinkjs/thinkjs#949]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:3.0

### code

```js
// your code here
thinkJs new XXXX --mode=module
```

### error message

```
// your error message here
```

### more description

// your detail description 

3.0里已经去掉了多模块，但是在文档里留下了错误的搭建多模块项目脚手架的命令，下载下来之后不是多模块项目

**Comment by wurining** [comment]
参考[#930](https://github.com/thinkjs/thinkjs/issues/930)

**Comment by lushijie** [comment]
@matinjugou  3.0 并没有放弃支持多模块，只是不建议使用多模块了

**Comment by wurining** [comment]
@lushijie 可以回答是什么原因吗？

**Comment by lushijie** [comment]
之前发的一个版本有问题，后面修复啦😂




发自网易邮箱大师
在2017年11月06日 22:25，Wurining 写道：

@lushijie 可以回答是什么原因吗？

**Comment by wurining** [comment]
@lushijie 哈哈是这样😂
