### ISSUE TITLE
所有post方法请求超时

### ISSUE THREAD

**Issue by CHparis** [thinkjs/thinkjs#951]
## DESC
迁移了一次服务器，node版本是一样的，但是post请求不可以，get请求很通畅。liunx 服务器、Mac下开发环境也是这样。
更新了包，发现所有post方法请求超时
### ENV

OS Platform:
MAC OS

Node.js Version:
Node.js Version: v6.9.2
ThinkJS Version:

ThinkJS Version: 2.2.22

**Comment by CHparis** [comment]
[2017-11-08 11:15:38] [THINK] Server running at http://0.0.0.0:8360/
[2017-11-08 11:15:38] [THINK] ThinkJS Version: 2.2.24
[2017-11-08 11:15:38] [THINK] Cluster Status: closed
[2017-11-08 11:15:38] [THINK] WebSocket Status: closed
[2017-11-08 11:15:38] [THINK] File Auto Compile: true
[2017-11-08 11:15:38] [THINK] File Auto Reload: true
[2017-11-08 11:15:38] [THINK] App Enviroment: development

[2017-11-08 11:18:30] [HTTP] POST /uc/public/login 200 120044ms       【post请求超时】
[2017-11-08 11:19:53] [HTTP] GET /uc/public/login?password=123qwe&username=admin 200 31ms 【get请求正常】

**Comment by welefen** [comment]
@CHparis 我们这边未能复现。
写个最简单的 Action（里面直接 this.success 返回）看还能复现这个问题么？

**Comment by CHparis** [comment]
我新建了一个工程，测试了post是没问题的，我猜想应该是think JS 2.2.x与babel冲突了
下面是我的npm配置，请看一下
{
  "name": "CmsWing",
  "description": "application created by thinkjs",
  "version": "1.0.0",
  "scripts": {
    "start": "node www/development.js",
    "compile": "babel --presets es2015-loose,stage-1 --plugins transform-runtime src/ --out-dir app/ --source-maps",
    "watch-compile": "node -e \"console.log('<npm run watch-compile> no longer need, use <npm start> command direct.');console.log();\"",
    "watch": "npm run watch-compile"
  },
  "dependencies": {
    "babel-runtime": "6.x.x",
    "geetest": "latest",
    "node-crontab": "latest",
    "nunjucks": "^2.2.0",
    "pingpp": "latest",
    "source-map-support": "^0.4.0",
    "tar.gz": "^1.0.2",
    "think-pagination": "latest",
    "think-wechat": "latest",
    "thinkjs": "2.2.x",
    "lodash":"4.x.x",
    "wechat-api":"latest",
    "jimp":"latest",
    "qiniu":"latest",
    "urllib": ">=0.5.2",
    "moment": "latest",
    "superagent": "latest",
    "segment":"latest"
  },
  "devDependencies": {
    "babel-cli": "6.x.x",
    "babel-preset-es2015-loose": "6.x.x",
    "babel-preset-stage-1": "6.x.x",
    "babel-plugin-transform-runtime": "6.x.x",
    "babel-core": "6.x.x"
  },
  "repository": "",
  "license": "MIT"
}

**Comment by welefen** [comment]
@CHparis 配置没什么问题，可以把依赖都删除重新装下试试。

**Comment by lushijie** [comment]
ping @CHparis

**Comment by activePro** [comment]
我要也遇到了这样的问题，上述方法都试过了，不管用啊

**Comment by binonxia** [comment]
遇到同样的问题+1
