### ISSUE TITLE
logger日志等级，我不希望记录下INFO类型，只保留error warn,设置了等级无效果

### ISSUE THREAD

**Issue by fslit** [thinkjs/thinkjs#953]
## DESC
logger日志等级，我不希望记录下INFO类型，如何表达NODE运行中只保留error warn等级日志,设置了等级无效果
### ENV
development
OS Platform:
WIN8
Node.js Version:
NODE V8
ThinkJS Version:
thinkjs-application@1.0.0 D:\nodejs-web\iyaoma-api
+-- think-logger3@1.0.10
`-- thinkjs@3.2.3
  `-- think-logger3@1.0.10  deduped
### 配置信息
```js
dateFile: {
    handle: DateFile,
    level: 'error,warn',
    absolute: true,
    pattern: '-yyyy-MM-dd',
    alwaysIncludePattern: true,
    filename: path.join(think.ROOT_PATH, 'logs/app.log')
  }
```

**Comment by callmez** [comment]
日志配置 我也有个问题

如何按`level`记录日志,  有尝试按照log4js的配置来, 但是未成功.
``` 
ERROR:   logs/app.error.log
WARN:  logs/app.warn.log
INFO: log.app.log
```

**Comment by lizheming** [comment]
@callmez level 失效这个问题已确认，周末修一下。之前觉得 log4js 的配置非常的复杂，给新手使用日志功能带来了很大的概念负担。所以我是简化了它的配置，去除了 category, 多 appenders 等之类的配置，用户只需要配置下简单的参数就可以使用了。不过的确是不满足你们这些高级使用的需求，我再想想吧。

**Comment by callmez** [comment]
赞!!!

**Comment by lizheming** [comment]
@callmez 很好奇如果是 log4js 你会怎么配不同 level 不同文件？log4js 我现在只知道它的 level 配置是大于等于配置的 level 值生效，不能只针对一个 level 生效。

**Comment by lizheming** [comment]
@fslit 更新下 `think-logger3@1.1.0` 应该是没有问题了
@callmez 增加了说明如何传入 log4js 的配置，你更新到最新版试试看是否能满足你的需求，文档见：https://github.com/thinkjs/cn.thinkjs.org/blob/master/3.0/logger.md#高级配置

**Comment by callmez** [comment]
可以用, 非常感谢!!
