### ISSUE TITLE
多模块多层级路由解析不对

### ISSUE THREAD

**Issue by AspenLuoQiang** [thinkjs/thinkjs#954]
### ENV

OS Platform: mac

Node.js Version: 8.5

ThinkJS Version: 3.0.0

文件路径：src/api/v1/controller/post/list.js
path: /api/v1/post/list
log: 
`think-router RouterParser: path=/api/v1/post/list, module=api, controller=v1, action=post, query={} +0ms`

此解析貌似也文档介绍的不符。
![image](https://user-images.githubusercontent.com/12598256/32537061-040e7204-c49c-11e7-9e96-87bcb1239494.png)

**Comment by lushijie** [comment]
可否发一下 think-router 版本、路由配置、middleware配置以便定位问题？




--
发自我的网易邮箱手机智能版



在 2017-11-08 15:46:53，"罗强" <notifications@github.com> 写道：

DESC
ENV

OS Platform: mac

Node.js Version: 8.5

ThinkJS Version: 3.0.0

文件路径：src/api/v1/controller/post/list.js
path: /api/v1/post/list
log:
think-router RouterParser: path=/api/v1/post/list, module=api, controller=v1, action=post, query={} +0ms

此解析貌似也文档介绍的不符。

**Comment by lushijie** [comment]
可否发一下 think-router 版本、router 配置、middle 配置以便定位问题？

发自我的 iPhone

**Comment by welefen** [comment]
文件路径为啥是： src/api/v1/controller/post/list.js ？从路径上看是多模块项目，但多模块项目是不支持多级模块名的（这里是 api/v1）

**Comment by AspenLuoQiang** [comment]
@welefen 那应该是这个问题，我以为是可以支持多项目的多级模块的。那如果要使用这样多版本的（v1/v2）API模块有办法么？

**Comment by wurining** [comment]
@AspenLuoQiang 
* /api_v1/controller/post/list.js
* /api_v2/controller/post/list.js

**Comment by AspenLuoQiang** [comment]
@wurining 谢谢

**Comment by welefen** [comment]
@AspenLuoQiang 把 v1 目录移动到 controller 下就可以了，如： src/api/controller/v1/post/list.js
