### ISSUE TITLE
model.field(field) 对insert和update有效么？

### ISSUE THREAD

**Issue by KuoKongQingYun** [thinkjs/thinkjs#955]
因为有的字段 对象里有，但数据库里没有，每次我都要delete或者新建一个对象，然后再insert或者update，很不方便，
但我看文档field又只对select有效？

**Comment by welefen** [comment]
数据表中没有的字段，add 或者 update 的时候会自动过滤掉的。
对于数据表中有该字段但又不想更新，那么在 controller 中获取数据的时候可以通过指定有限的参数获取。

```js
const data1 = this.post(); // 获取所有的 post 数据
const data2 = this.post('title,content,email'); // 只获取指定的参数 post 数据
```

**Comment by KuoKongQingYun** [comment]
好的 那暂时先这样吧
