### ISSUE TITLE
thinkjs new出来的项目安装包后一直提示缺少think-logger3    运行不起来

### ISSUE THREAD

**Issue by liuhuanhui** [thinkjs/thinkjs#957]
thinkjs new出来的项目安装包后一直提示缺少think-logger3    运行不起来

**Comment by lizheming** [comment]
ThinkJS 的依赖里有标记要安装 `think-logger3` 诶，你 `npm install` 没有安装么？你的`think-cli`, `thinkjs` 和 `npm` 之类的版本分别是多少？

**Comment by liuhuanhui** [comment]
我两台电脑都不行
window:
nodejs：v8.4.0
npm：5.3.0
think-cli：@1.0.15
thinkjs：3.0

mac:
nodejs：v8.9
npm：5.5.1
think-cli：2.0.0
thinkjs：3.0

**Comment by liuhuanhui** [comment]
package和node_modules下面是有这个模块的

**Comment by liuhuanhui** [comment]
![image](https://user-images.githubusercontent.com/10370625/32695383-150ee998-c795-11e7-8817-dac592a0efaf.png)



npm安装出现这个错误 uuid

**Comment by lizheming** [comment]
是昨天发布的 think-logger3 有问题，你删除依赖重新安装下应该就正常了。

**Comment by liuhuanhui** [comment]
好吧............

**Comment by lizheming** [comment]
好的，感谢反馈。
