### ISSUE TITLE
socket配置，换一个action名称就报错

### ISSUE THREAD

**Issue by souljessi** [thinkjs/thinkjs#960]
### ENV

OS Platform:

Node.js Version: 8.9.0

ThinkJS Version: 3.2.2

### code

```js
// adapter.js
exports.websocket = {
    type: 'socketio',
    common: {
        // common config
    },
    socketio: {
        handle: socketio,
        allowOrigin: null,              // 默认情况下允许任何来源
        path: '/socket.io',             // 默认 '/socket.io'
        adapter: null,
        messages: [{
            open: '/tunnel/device/open',  
            close: '/tunnel/device/close',
            getDevice: '/tunnel/device/getDevice',//这里我key和action都改成getTunnelDevice就会报错
            getTunnelDevice: '/tunnel/device/getTunnelDevice'//用这个action就会报错
        }]
    }



device.js
export default class extends think.Controller {
   async getDeviceAction() {
//这个是正常的
}
async getTunnelDeviceAction(){
//这个action会报错，纯粹就是改了个命名
}
}
```
//客户端js
<script src="http://lib.baomitu.com/socket.io/2.0.1/socket.io.js"></script>
    <script type="text/javascript">
      var socket = io('http://172.16.187.83:8848');

//      socket.emit('getDevice', '31010/#');
         socket.emit('getTunnelDevice', '31010/#');
   

### error message
TypeError: this.ctx[queryMethod] is not a function

### more description
这里，换一个action名称就报TypeError: this.ctx[queryMethod] is not a function，就很迷。

**Comment by lushijie** [comment]
Update think-validator to 1.3.1.

**Comment by lushijie** [comment]
ping @souljessi
