### ISSUE TITLE
think-cli V2.1.0生成啊对项多模块项目的问题

### ISSUE THREAD

**Issue by jyh11111** [thinkjs/thinkjs#961]
##版本 think-cli V2.1.0 生成啊对项多模块项目的问题
### node 6.12.0 
OS Platform:
     Windows 7
Node.js Version:
      6.12.0         
ThinkJS Version: 
  3.2.4
### code
   1.在windows中用 thinkjs  new demo 没有反应
   2.用命令 thinkjs new demo -m生成的模板无module 
        若此时thinkjs module user添加模块时会覆盖先前文件！

**Comment by wurining** [comment]
@jyh11111 https://github.com/thinkjs/thinkjs/issues/930

**Comment by berwin** [comment]
@jyh11111 已经修复，更新 think-cli 版本到 2.1.1~就行啦
