### ISSUE TITLE
modify ctx.path in program

### ISSUE THREAD

**Issue by hvaexlove** [thinkjs/thinkjs#962]
请问怎么在thinkjs项目接口请求的path里加上一个一个前缀，类似于加上一个项目名一样的东西。

**Comment by lushijie** [comment]
第一种方案通过配置子域名的方式来解决，具体可以查看 Router 的文档。
第二种比较暴力的，写个middleware 直接修改 ctx.path， 具体可以查看 Middleware 的文档。

**Comment by hvaexlove** [comment]
@lushijie 我不是要子域名的形式  我是要在域名后面加上一个项目名 所有请求url全部带上这个项目名

**Comment by hvaexlove** [comment]
@lushijie 我是采用你说的第二种方式 在controller 的 base里面加入了一个 this.ctx.path = '/shop-server' + this.ctx.path;  但是 我访问 http://127.0.0.1:8360/shop-server 还是 404 访问 http://127.0.0.1:8360/ 是可以的

**Comment by lushijie** [comment]
那就自己写个最简单的middleware修改一下原始的ctx.path

发自我的 iPhone

**Comment by lushijie** [comment]
嗯，直接这样加上之后路由解析的时候也会把你加的这个算进去的，可以DEBUG=think-router npm start 查看路由解析情况。像你说的这种直接配置think-router prefix 就可以啦，其他的都不用啦。

发自我的 iPhone

**Comment by hvaexlove** [comment]
@lushijie  我最开始看官网的文档 配的prefix还是不行
![image](https://user-images.githubusercontent.com/17685971/32977341-467d5b26-cbf1-11e7-9602-996c6612b987.png)

**Comment by lushijie** [comment]
```js
{
  prefix: ['/shop-server'] 
}
```

**Comment by hvaexlove** [comment]
@lushijie 配了一下prefix: ['/shop-server']  发现还是不行 紧跟着看了一下prefix处理的源码 加上日志的打印 发现prefix是空的 请问大佬 这种情况问题可能会出现在哪里
![image](https://user-images.githubusercontent.com/17685971/32981689-7dbb4d9e-cc3e-11e7-80a8-bd39e36575bf.png)

**Comment by lushijie** [comment]
```js
// src/config/middleware.js
{
    handle: 'router',
    options: {
      prefix: ['/thinkjs'],
      suffix: ['.html'],
      subdomainOffset: 2,
      subdomain: {
        'lib2,lushijie': 'yyyyy'
      }
    }
 },
```
配置的是think-router ...

**Comment by hvaexlove** [comment]
@lushijie 终于好了 感谢大佬指导！
