### ISSUE TITLE
socket分发的action中，无法通过浏览器请求触发emit

### ISSUE THREAD

**Issue by sailengsi** [thinkjs/thinkjs#964]
## DESC
socket的action，通过前端的emit触发，可以正常调用emit分发。
但是，我想在浏览器访问这个action时调用emit分发，就报错了。

### ENV

OS Platform:Mac

Node.js Version:7.7.1

ThinkJS Version:3.xxx

### code

```js
testAction() {
       // client端，用socket.emit触发，这里是正常的
      // 但是，我想通过浏览器访问这个action时，也能触发，请问该怎么操作呢？
	this.emit('test',{
		msg:'test'
	})；
}
```

### error message

```
TypeError: Cannot read property 'emit' of undefined
```

### more description

意思就是：我通过浏览器访问一个操作，然后根据逻辑不同，去分发不同的事件，不知道该怎么操作。

**Comment by zhengqingxin** [comment]
直接从浏览器发一个非 websocket 请求是不行的，因为 nodejs request 里取不到 websocket 实例。简单来想，websocket建立连接的时候会给每个客户端分发一个唯一id，而如果直接通过 get 请求调用，服务器就是取不到这个 id 的。

实现你说的效果，客户端把 ajax 请求改成 socket.emit 方式应该就可以了。

**Comment by sailengsi** [comment]
@zhengqingxin 好吧，关键是我不是通过ajax操作的后台，是传统的跳转方式，看来只能改变一种方式了。
