### ISSUE TITLE
使用countSelect，表中没有id字段，生成的sql错误

### ISSUE THREAD

**Issue by liuhuanhui** [thinkjs/thinkjs#966]
使用countSelect，表中没有id字段，生成的sql错误
表中并没有user.id作为主键，使用wwid作为主键，导致出错 
![image](https://user-images.githubusercontent.com/10370625/32990881-c8706d3e-ccf6-11e7-8c15-c4a57383a625.png)

Error: ER_BAD_FIELD_ERROR: Unknown column 'user.id' in 'field list'

**Comment by lizheming** [comment]
```
get pk() {
  return 'wwid';
}
```

既然知道是主键的问题那就设置下主键呗😂，默认主键是 id 呀

**Comment by liuhuanhui** [comment]
好的 3Q~
