### ISSUE TITLE
middleware获取ctx.body

### ISSUE THREAD

**Issue by newsn** [thinkjs/thinkjs#968]
想通过middleware的方法，获取ctx.body的内容，并对ctx.body的内容进行加工处理（删除html空白字符串）。

但是新建立的middleware，通过src/config/middleware.js 进行加载的时候，只有放置于controller之后，并且controller的action必须return false，在自定义的middleware中，才能正常获取到ctx.body，加载到middleware.js列表中的其他的地方，ctx.body都是undefined。

在controller中，正常的return this.display()并不能走到自定义的middleware，只有return false才能继续流程。

提此issue。

**Comment by welefen** [comment]
可以弄个中间件，如：

```js
{
    handle: options => {
      return async (ctx, next) => {
        await next();
        let body = ctx.body;
        if (think.isString(body)) {
          // 替换内容
          body = body.replace(/\s+/g, ' ');
          ctx.body = body;
        }
      }
    }
  },
```
配置在 `src/config/middleware.js`，作为第一个。当然更建议把这个代码作为一个独立的文件放在 `src/middleware/` 中，然后配置对应的名称。

**Comment by newsn** [comment]
谢谢大佬回复。试试ing。嘿嘿。
