### ISSUE TITLE
payload上传多图兼容问题

### ISSUE THREAD

**Issue by LeeLovCY** [thinkjs/thinkjs#969]
multipart/form-data 表单同时上传多张图片的时候this.file()获取到的不是数组而是Object

**Comment by welefen** [comment]
```js
{
  handle: 'payload',
  options: {
    multiples: true
  }
}
```

**Comment by welefen** [comment]
https://github.com/thinkjs/think-payload/commit/f1be67cf259e9174eb4962c476d75e910e71a7aa

**Comment by LeeLovCY** [comment]
thank you
