### ISSUE TITLE
上传图片后名称不对有3.x上传的demo吗

### ISSUE THREAD

**Issue by lengyehan** [thinkjs/thinkjs#970]
### ENV
![image](https://user-images.githubusercontent.com/8751342/33115634-a6552fa2-cf9c-11e7-8a51-462cebbde876.png)

OS Platform:

Node.js Version:6.x

ThinkJS Version:3.x

### code

```js
// your code here
![image](https://user-images.githubusercontent.com/8751342/33115676-cc3ecd5e-cf9c-11e7-9f76-687db6186ff7.png)

```

### error message

```
// your error message here
```

### more description

// your detail description 
上传后文件重新命名后缀没了

**Comment by welefen** [comment]
中间件 payload 有参数配置(`src/config/middleware.js`)，如：

```js
{
  handle: 'payload',
  options: {
    keepExtensions: true
  }
}
```
更多配置参数见 https://github.com/thinkjs/think-payload
