### ISSUE TITLE
请问thinkjs怎样调用第三方webservice

### ISSUE THREAD

**Issue by bestliam** [thinkjs/thinkjs#973]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by zhengqingxin** [comment]
think-fetch

**Comment by KuoKongQingYun** [comment]
你用nodejs的request也行啊，又不是仅限于使用thinkjs内置的包

**Comment by bestliam** [comment]
用了soap包后
soap.createClient(url, function(err, client) {
      client.getmhrz(args, function(err, result) {
        var data = JSON.stringify(result);
      });
    });
thinkjs怎么包装呢？

**Comment by bestliam** [comment]
多谢各位，已用soap包解决
