### ISSUE TITLE
使用TypeScript，对Model添加方法，报错但可以运行。

### ISSUE THREAD

**Issue by wurining** [thinkjs/thinkjs#976]
## DESC
使用TypeScript，对Model添加方法，报错但可以运行。
### ENV
>OS Platform: lastest
>Node.js Version: v8.7.0
>ThinkJS Version: 3.2.4
### code
model代码
```js
import { think } from 'thinkjs';

export default class extends think.Model {

    /**
     * 通过Name字段获取
     * @param {string[]} params
     * @returns {any}
     */
    getByName (params?: string[]) {
        if (params == null || params.length == 0) {
            return this.select();
        }
        return this.where({
            name: ['IN', params]
        }).select();
    }
}

```
controller代码
```js
import Base from './base.js';
import OptionModel from '../model/option';

export default class extends Base {

    /**
     * 获取option
     */
    async indexAction () {
        let param: string              = this.get('param') || undefined;
        let params: string[]           = param ? param.split(',') : [];
        let modelInstance: OptionModel = this.model('option');
        let options                    = await modelInstance.getByName(params);
        return this.success(options);
    }
}
```
### error
<img width="639" alt="2017-11-28 5 28 38" src="https://user-images.githubusercontent.com/26198634/33312134-ec5e6cf6-d461-11e7-8dcf-918822d6f853.png">

**Comment by SijieCai** [comment]
this.model 返回类型不是 any，不能自动转换类型，使用 `as` 关键字:

let modelInstance = this.model('option') as OptionModel;

**Comment by wurining** [comment]
@SijieCai 谢谢回答，我是按照文档操作的，希望可以改正[文档](https://thinkjs.org/zh-cn/doc/3.0/typescript.html#toc-bd1)。

**Comment by SijieCai** [comment]
感谢 @wurining 反馈，文档已修改

**Comment by junmaqiang** [comment]
我代码是继承 rest 基类的, 因此model 实例化是挂给 this.modelInstance 的
那么用 这种写法可否?  this.modelInstance = this.model('option') as OptionModel;
@SijieCai

**Comment by SijieCai** [comment]
这样不行，使用泛型吧，修改 rest 基类，把 modelInstance 的类型定义成 T
`
// rest 基类
export default class <T extends Model> extends think.Controller {
  modelInstance: T;
  // ....
}

`

`
//你的 controller 类
import ControllerBase from '../rest';
import OptionModel from "../model/option";
export default class extends ControllerBase<OptionModel> {
   // ....
}
`

**Comment by SijieCai** [comment]
@junmaqiang
