### ISSUE TITLE
请问 cache 只能在controller中使用吗，在其他模块中如何使用

### ISSUE THREAD

**Issue by Evaim** [thinkjs/thinkjs#979]
### ENV

OS Platform:

Node.js Version:

ThinkJS Version:

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by lushijie** [comment]
cache 作为 extend 被注入到了 controller, context, think 上， 可以使用 think.cache，[代码](https://github.com/thinkjs/think-cache/blob/master/index.js)

**Comment by Evaim** [comment]
好的，谢谢
