### ISSUE TITLE
在bootstrap中拿不到Model，Controller等对象

### ISSUE THREAD

**Issue by hankexu** [thinkjs/thinkjs#987]
## DESC
我在启动时注册了一个监听事件，需要在事件被触发时使用model操作数据库，但是获取不到model实例
### ENV

OS Platform:
Windows 10，
Node.js Version:
8.7.0
ThinkJS Version:
3.2.4
### code

```js
think.app.on("appReady", () => {
  const server = think.app.server;
  console.log(server);
})
```

### error message

```
undefined
```

### more description

直接把文档中的代码复制到`master.js`中，结果也是undefined，但是群里有的朋友可以拿到，也有像我一样拿不到的。

**Comment by lushijie** [comment]
```js
think.app.on("appReady", async () => {
  // 使用 think.model 实例化 model
  console.log(await think.model('mysql/player').getAllPlayers());
});
```

**Comment by hankexu** [comment]
@lushijie 我的think.model 是 undefined

**Comment by lushijie** [comment]
那你是不是没有配置 model 的extend ?
```js
// src/config/extend.js
const model = require('think-model');
module.exports = [
  // 其他配置 ...
  model(think.app)
];

```

**Comment by hankexu** [comment]
配了，我在controller里用的好好的

**Comment by lushijie** [comment]
如果 think.model 这个方法没有，是 think-model 的问题。
如果 think.app.models 这个对象没有， 是 thinkjs/lib/loader.js loadData 的问题。
appReady 是在 thinkjs/lib/application.js 中触发的。

我没有复现你说的问题，你可以试着追一下这个问题的原因么？或者你有可以运行的 demo 代码么？

**Comment by chenyuncai** [comment]
我这边也试了下，这个事件在 worker.js 里是正常工作的，可以获取think.app.server的信息。

**Comment by lushijie** [comment]
```js
  loadAll(type, isCli) {
    this.initPath();
    think.loader = new Loader(think.APP_PATH, thinkPath);

    // write config to APP_PATH/runtime/config/[env].json file
    const config = think.loader.loadConfig(think.app.env);
    think.config = getConfigFn(config, think.loader.modules.length > 0);
    think.logger = new Logger(helper.parseAdapterConfig(think.config('logger')), true);

    if (type !== 'master') {
      this.writeConfig(config);
      this.loadExtend();
      this.loadData();
      this.loadMiddleware();
      if (!isCli) {
        this.loadCrontab();
      }
    }
    think.loader.loadBootstrap(type);
  }
```
@hankexu  你是在 worker.js 中写的吧？master.js 一些东西是没有的（源码如上)。

**Comment by xb594328980** [comment]
@hankexu 
@lushijie
在thinkjs的官方文档中有描述（https://thinkjs.org/zh-cn/doc/3.0/flow.html） 【系统服务启动】的描述，如果是Master 进程当加载master.js时还没有加载业务代码即所有的service、controller、model等，只有为worker进程时才会加载业务代码，所以在master.js中自然获取不到model实例；
按照作者的建议，建议把带有业务逻辑的代码放入worker.js中而不是master.就是中，如果需要只执行一次可以用：
// src/bootstrap/worker.js
think.messenger.on('consumeEvent', (data) => {
  // 该回调函数只会在一个进程下执行
});

**Comment by hankexu** [comment]
明白了，问题解决，谢谢
