### ISSUE TITLE
为什么npm上安装的think-cli后, thinkjs -V 总是显示 2.1.1 版本, 如何安装3.x 版本?

### ISSUE THREAD

**Issue by nicholaslai** [thinkjs/thinkjs#991]
## DESC
不管是 npm 还是 cnpm, 都是安装 2.1.1 版本
强制卸载也无法卸载, 卸载后 thinkjs -V 还是显示 2.1.1
请问如何安装 3.x 版本?
### ENV

OS Platform:windows 7

Node.js Version:8.9.1

ThinkJS Version:2.1.1

### code

```js
// your code here
```

### error message

```
// your error message here
```

### more description

// your detail description

**Comment by welefen** [comment]
thinkjs -v 显示的是 think-cli 的版本，-v 的时候不是有个提示文案么

**Comment by 15088134140** [comment]
3.x 版本指的是thinkjs的版本。
2.1.1 [版本指的是think-cli的版本，就目前think-cli的版本也才2.x。](https://github.com/thinkjs/think-cli)
thinkjs -V 显示的是think-cli的版本所以显示2.1.1是没有问题的。
当使用think-cli的命令`thinkjs new <project-name> <template-name>`得到的模板的package.json中的thinkjs为3.x
