### ISSUE TITLE
Validator  equels 的值取不到

### ISSUE THREAD

**Issue by callmez** [thinkjs/thinkjs#996]
https://github.com/thinkjs/think-validator/blob/9342e4e261a5635d79e8ca7a51d8fc055a1123a7/rules.js#L211

追了下代码: currentQuery 两次定义好像不需要, 取不到post的里的值

rule

```
let rule = {
      password: {
        byteLength: {min: 6, max: 20},
        string: true,
        required: true,
        trim: true,
        method: 'POST'
      },
      confirm: {
        equals: 'password',
        method: 'POST'
      }
}
```

返回: `confirm need equal undefined`  
@lushijie

**Comment by lushijie** [comment]
已修复，请更新 think-validator 到 1.3.2，感谢反馈

**Comment by callmez** [comment]
神速 给力
