### ISSUE TITLE
Controller的一些小问题

### ISSUE THREAD

**Issue by wurining** [thinkjs/thinkjs#997]
## DESC
1.使用TS，在Controller的Action中使用this.post函数时，对于user-agent为PostmanRuntime/6.4.1的请求无法获取post过来的value。

2.[点此查看 session文档#session-数据是怎么同步的](https://github.com/thinkjs/cn.thinkjs.org/blob/master/3.0/session.md#session-数据是怎么同步的)在使用ts时，此处的this.flush运行提示非函数，应该是this指向问题。可以改成：
```js
            this.ctx.res.once('finish', () => {
                console.log("flush");
                this.ctx.res.flush(); // 在请求时将 session flush 导存储容器中
            });
```
3.[点此查看 session文档#如何获取-session-对应-cookie-的值](https://github.com/thinkjs/cn.thinkjs.org/blob/master/3.0/session.md#如何获取-session-对应-cookie-的值)
使用ts时，此处的`this.cookie`在d.ts中没有添加，需要使用`this.ctx.cookie`获取该函数。
### ENV

OS Platform: Lastest

Node.js Version: Lastest

ThinkJS Version: 3.2.4

**Comment by welefen** [comment]
1、post 数据是根据 Content-Type 来解析的，现在支持的 Content-Type 为 https://github.com/thinkjs/think-payload/blob/master/index.js#L13-L39

2、flush 是 session 模块里的方法，这里的意思是在请求结束时刷新数据到存储容器中

3、d.ts 里有 cookie 的，https://github.com/thinkjs/thinkjs/blob/master/index.d.ts#L210

**Comment by SijieCai** [comment]
@wurining  cookie 方法的定义已经加上， ThinkJS version  3.2.5。

**Comment by wurining** [comment]
@welefen 
1. 1的问题我解决了，是我postman使用错误，post方法是对了，但是数据添加到了url中，没有添加到body中导致的post方法失效！
2. 2的问题我在session-mysql源码中看到了，这是内部方法。我上面提到的方法`this.ctx.res.flush()`，后来经过测试也是没有生效的。对于文档中提到的请求结束后会更新session，貌似是有概率的触发，执行请求后，查数据库表发现有时会没有变化。因为我想通过session识别用户，然后进行一些实时的信息同步，把相关数据xxx通过方法`this.session('xxx',xxx)`存到了session表中，当该客户端请求另一个action时可以通过`this.session('xxx')`获取xxx，因此是否有可以及时更新session的方法呢？
3. 非常感谢！

**Comment by welefen** [comment]
https://github.com/thinkjs/think-session-mysql/blob/master/index.js#L69 这里的 flush 方法没有执行？

**Comment by wurining** [comment]
@welefen 
    我昨晚又调试了一下，每次是可以触发flush方法的。但是有个没有解决的问题：我使用了session-mysql包作为session的持久化。我企图在A_action中用`this.session('key', val)`设置session的值，令其存储在表中，然后通过B_action中`this.session('key')`获取该val。此时若表中没有该sessionid的行，是可以正常工作的，如果出现过了并且过期了，这个过程会卡在A_action。我用了如下两种方法，第一种一直等待，第二种执行了，但是不会执行then里的语句，并且表也没有按照文档中说的请求结束后会更新数据。
``` typescript
    async getCaptchaAction () {
        console.log(this.cookie('fl_session_id'));
        let captcha = this.service('captcha').createNewMathExprCaptcha();
        if (!captcha) {
            return this.fail(88005);
        }
        let result: any;
        try {
            result = await this.session('captcha', captcha.text);
        } catch (err) {
            return this.fail(88005);
        }
        return this.success({
            'captcha': captcha.data
        })
    }
```
``` typescript
    async getCaptchaAction () {
        console.log(this.cookie('fl_session_id'));
        let captcha = this.service('captcha').createNewMathExprCaptcha();
        if (!captcha) {
            return this.fail(88005);
        }
        let result: any;
        try {
            this.session('captcha', captcha.text).then(function (val) {
                console.log(val + '   ' + captcha.text);
            }).catch(function (err) {
                console.log(err);
            });
            console.log('flush');
        } catch (err) {
            return this.fail(88005);
        }
        return this.success({
            'captcha': captcha.data
        })
    }
```

**Comment by wurining** [comment]
@welefen 
参照https://github.com/thinkjs/thinkjs/issues/889提了pr
https://github.com/thinkjs/think-session-mysql/compare/master...wurining:patch-1

**Comment by welefen** [comment]
@wurining think-session-mysql 已更新版本
