### ISSUE TITLE
think-sequelize  覆盖toJson

### ISSUE THREAD

**Issue by callmez** [thinkjs/thinkjs#998]
https://github.com/sequelize/sequelize/issues/1462

因为有个 Sequelize实例通过API 输出 数据的原因,  需要隐藏 例如 password, 等敏感的字段数据

Sequelize V4 已经有 instanceMethods的一个新的使用规则, 
https://github.com/sequelize/sequelize/blob/42638ff25d0460d3344066e580a60dc2699e908e/docs/upgrade-to-v4.md

但是该方式在think-sequelize方式下无法使用(think-sequelize 通过集成和extendClassMethods来合并两个类的属性和函数), 覆盖`toJSON`函数无法实现.  

所以想问下有没有更好的方式保留原生态的sequelize操作体验?

@lushijie

**Comment by callmez** [comment]
`const Model = think.sequel('user')` // 保留了预先定义的方法

`const User = Model.create({...})` // 创建对象之后却不能保留方法

是不是设计上有什么考虑... 如果是设计上刻意的,  那请问如何为`User`增加自定义方法. 

虽然可以借助`Sequelize`的一些预留机制上实现方法的扩展, 但是我觉得在定义上海市更方便.  

忘继续给力支持!!

**Comment by lushijie** [comment]
this.sequel 实际上是我们对sequelize 进行了一层封装，但是Model.create 返回的instance实际上是sequelize 默认的行为了，不再是我们所封装的实例了两个不太一致了。

**Comment by callmez** [comment]
对 我说的就是这个意思 . 现在就是想对 build后的instance 扩展方法

因为 sequelize 有对instance做 extend method 的设置, 但是 在think-sequelize中 我目前还没找到可以便捷扩展的方式.

**Comment by lushijie** [comment]
对，暂时还没有，关于这一块的设计限制我让李成银帮你解读一下吧 @welefen we

**Comment by lushijie** [comment]
think-sequelize@1.2.0 增加了对instance的扩展。欢迎使用！

```js
module.exports = class extends think.Sequel {
  constructor(...props) {
    super(...props);
  }

  get schema() {
    return {
      attributes: {
        id: {
          type: think.Sequel.Sequel.BIGINT,
          primaryKey: true
        },
        teamId: think.Sequel.Sequel.BIGINT, // belongsTo, 为当前模型添加外键
        name: think.Sequel.Sequel.STRING(255),
      },
      options: {
        timestamps: false,
        freezeTableName: true,
        tableName: 'think_player',
      }
    }
  }

  get instanceMethods() {
    return {
      test() {
        console.log(this.id);
      }
    }
  }
}
```

`instanceMethods` return an `object`,each object's item is a function. Arrow function is disabled.

If you just want add instance methods one by one in model, you can do like this:

```js
module.exports = class extends think.Sequel {
  constructor(...props) {
    super(...props);
    this.addInstanceMethod(function test() { // anonymous fn is disabled
      console.log(this.id);
    });
  }
}
```
These methods are added to `sequelize.define(*).prototype`!

**Comment by lushijie** [comment]
ping @callmez

**Comment by callmez** [comment]
这样好.    之前我都是借助Hook来扩展, 感谢!
